EE445M RTOS: lib/libdisplay/ST7735.c File Reference
ST7735.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include "ST7735.h"
#include "inc/tm4c123gh6pm.h"
Macros
#define ST7735_NOP 0x00
#define ST7735_SWRESET 0x01
#define ST7735_RDDID 0x04
#define ST7735_RDDST 0x09
#define ST7735_SLPIN 0x10
#define ST7735_SLPOUT 0x11
#define ST7735_PTLON 0x12
#define ST7735_NORON 0x13
#define ST7735_INVOFF 0x20
#define ST7735_INVON 0x21
#define ST7735_DISPOFF 0x28
#define ST7735_DISPON 0x29
#define ST7735_CASET 0x2A
#define ST7735_RASET 0x2B
#define ST7735_RAMWR 0x2C
#define ST7735_RAMRD 0x2E
#define ST7735_PTLAR 0x30
#define ST7735_COLMOD 0x3A
#define ST7735_MADCTL 0x36
#define ST7735_FRMCTR1 0xB1
#define ST7735_FRMCTR2 0xB2
#define ST7735_FRMCTR3 0xB3
#define ST7735_INVCTR 0xB4
#define ST7735_DISSET5 0xB6
#define ST7735_PWCTR1 0xC0
#define ST7735_PWCTR2 0xC1
#define ST7735_PWCTR3 0xC2
#define ST7735_PWCTR4 0xC3
#define ST7735_PWCTR5 0xC4
#define ST7735_VMCTR1 0xC5
#define ST7735_RDID1 0xDA
#define ST7735_RDID2 0xDB
#define ST7735_RDID3 0xDC
#define ST7735_RDID4 0xDD
#define ST7735_PWCTR6 0xFC
#define ST7735_GMCTRP1 0xE0
#define ST7735_GMCTRN1 0xE1
#define TFT_CS (*((volatile uint32_t *)0x40004020))
#define TFT_CS_LOW 0
#define TFT_CS_HIGH 0x08
#define DC (*((volatile uint32_t *)0x40004100))
#define DC_COMMAND 0
#define DC_DATA 0x40
#define RESET (*((volatile uint32_t *)0x40004200))
#define RESET_LOW 0
#define RESET_HIGH 0x80
#define SSI_CR0_SCR_M 0x0000FF00
#define SSI_CR0_SPH 0x00000080
#define SSI_CR0_SPO 0x00000040
#define SSI_CR0_FRF_M 0x00000030
#define SSI_CR0_FRF_MOTO 0x00000000
#define SSI_CR0_DSS_M 0x0000000F
#define SSI_CR0_DSS_8 0x00000007
#define SSI_CR1_MS 0x00000004
#define SSI_CR1_SSE 0x00000002
#define SSI_SR_BSY 0x00000010
#define SSI_SR_TNF 0x00000002
#define SSI_CPSR_CPSDVSR_M 0x000000FF
#define SSI_CC_CS_M 0x0000000F
#define SSI_CC_CS_SYSPLL 0x00000000
#define SYSCTL_RCGC1_SSI0 0x00000010
#define SYSCTL_RCGC2_GPIOA 0x00000001
#define ST7735_TFTWIDTH 128
#define ST7735_TFTHEIGHT 160
#define ST7735_NOP 0x00
#define ST7735_SWRESET 0x01
#define ST7735_RDDID 0x04
#define ST7735_RDDST 0x09
#define ST7735_SLPIN 0x10
#define ST7735_SLPOUT 0x11
#define ST7735_PTLON 0x12
#define ST7735_NORON 0x13
#define ST7735_INVOFF 0x20
#define ST7735_INVON 0x21
#define ST7735_DISPOFF 0x28
#define ST7735_DISPON 0x29
#define ST7735_CASET 0x2A
#define ST7735_RASET 0x2B
#define ST7735_RAMWR 0x2C
#define ST7735_RAMRD 0x2E
#define ST7735_PTLAR 0x30
#define ST7735_COLMOD 0x3A
#define ST7735_MADCTL 0x36
#define ST7735_FRMCTR1 0xB1
#define ST7735_FRMCTR2 0xB2
#define ST7735_FRMCTR3 0xB3
#define ST7735_INVCTR 0xB4
#define ST7735_DISSET5 0xB6
#define ST7735_PWCTR1 0xC0
#define ST7735_PWCTR2 0xC1
#define ST7735_PWCTR3 0xC2
#define ST7735_PWCTR4 0xC3
#define ST7735_PWCTR5 0xC4
#define ST7735_VMCTR1 0xC5
#define ST7735_RDID1 0xDA
#define ST7735_RDID2 0xDB
#define ST7735_RDID3 0xDC
#define ST7735_RDID4 0xDD
#define ST7735_PWCTR6 0xFC
#define ST7735_GMCTRP1 0xE0
#define ST7735_GMCTRN1 0xE1
#define DELAY 0x80
#define MADCTL_MY 0x80
#define MADCTL_MX 0x40
#define MADCTL_MV 0x20
#define MADCTL_ML 0x10
#define MADCTL_RGB 0x00
#define MADCTL_BGR 0x08
#define MADCTL_MH 0x04
Functions
static void writecommand (uint8_t c)
static void writedata (uint8_t c)
void Delay1ms (uint32_t n)
static void commandList (const uint8_t *addr)
static void commonInit (const uint8_t *cmdList)
void ST7735_InitB (void)
void ST7735_InitR (enum initRFlags option)
static void setAddrWindow (uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1)
static void pushColor (uint16_t color)
void ST7735_DrawPixel (int16_t x, int16_t y, uint16_t color)
void ST7735_DrawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
void ST7735_DrawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
void ST7735_FillScreen (uint16_t color)
void ST7735_FillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
uint16_t ST7735_Color565 (uint8_t r, uint8_t g, uint8_t b)
uint16_t ST7735_SwapColor (uint16_t x)
void ST7735_DrawBitmap (int16_t x, int16_t y, const uint16_t *image, int16_t w, int16_t h)
void ST7735_DrawCharS (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
void ST7735_DrawChar (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
uint32_t ST7735_DrawString (uint16_t x, uint16_t y, uint8_t *pt, int16_t textColor)
void fillmessage (uint32_t n)
void ST7735_SetCursor (uint32_t newX, uint32_t newY)
void ST7735_OutUDec (uint32_t n)
void ST7735_SetRotation (uint8_t m)
void ST7735_InvertDisplay (int i)
void ST7735_PlotClear (int32_t ymin, int32_t ymax)
void ST7735_PlotPoint (int32_t y)
void ST7735_PlotLine (int32_t y)
void ST7735_PlotPoints (int32_t y1, int32_t y2)
void ST7735_PlotBar (int32_t y)
void ST7735_PlotdBfs (int32_t y)
void ST7735_PlotNext (void)
void ST7735_PlotNextErase (void)
void ST7735_OutChar (uint8_t ch)
void ST7735_OutChar2 (uint8_t ch)
void ST7735_OutString (uint8_t *ptr)
void ST7735_OutString2 (uint8_t *ptr)
void ST7735_SetTextColor (uint16_t color)
int fputc (int ch, FILE *f)
int fgetc (FILE *f)
void Output_Init (void)
void Output_Clear (void)
void Output_Off (void)
void Output_On (void)
void Output_Color (uint32_t newColor)
Variables
uint32_t StX =0
uint32_t StY =0
uint32_t StX2 =0
uint32_t StY2 =10
uint16_t StTextColor = 0x07FF
static const uint8_t Font []
static uint8_t ColStart
static uint8_t RowStart
static uint8_t Rotation
static enum initRFlags TabColor
static int16_t _width = 128
static int16_t _height = 160
static const uint8_t Bcmd []
static const uint8_t Rcmd1 []
static const uint8_t Rcmd2green []
static const uint8_t Rcmd2red []
static const uint8_t Rcmd3 []
uint8_t Message [12]
uint32_t Messageindex
int32_t Ymax
int32_t Ymin
int32_t X
int32_t Yrange
int32_t lastj =0
uint8_t const dBfs [512]
Macro Definition Documentation
#define DC (*((volatile uint32_t *)0x40004100))
Definition at line 117 of file ST7735.c.
Referenced by writecommand(), and writedata().
#define DC_COMMAND 0
Definition at line 118 of file ST7735.c.
Referenced by writecommand().
#define DC_DATA 0x40
Definition at line 119 of file ST7735.c.
Referenced by writedata().
#define DELAY 0x80
Definition at line 511 of file ST7735.c.
Referenced by commandList().
#define MADCTL_BGR 0x08
Definition at line 1175 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define MADCTL_MH 0x04
Definition at line 1176 of file ST7735.c.
#define MADCTL_ML 0x10
Definition at line 1173 of file ST7735.c.
#define MADCTL_MV 0x20
Definition at line 1172 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define MADCTL_MX 0x40
Definition at line 1171 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define MADCTL_MY 0x80
Definition at line 1170 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define MADCTL_RGB 0x00
Definition at line 1174 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define RESET (*((volatile uint32_t *)0x40004200))
Definition at line 120 of file ST7735.c.
Referenced by commonInit().
#define RESET_HIGH 0x80
Definition at line 122 of file ST7735.c.
Referenced by commonInit().
#define RESET_LOW 0
Definition at line 121 of file ST7735.c.
Referenced by commonInit().
#define SSI_CC_CS_M 0x0000000F
Definition at line 137 of file ST7735.c.
Referenced by commonInit().
#define SSI_CC_CS_SYSPLL 0x00000000
Definition at line 138 of file ST7735.c.
Referenced by commonInit().
#define SSI_CPSR_CPSDVSR_M 0x000000FF
Definition at line 136 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_DSS_8 0x00000007
Definition at line 130 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_DSS_M 0x0000000F
Definition at line 129 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_FRF_M 0x00000030
Definition at line 127 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_FRF_MOTO 0x00000000
Definition at line 128 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_SCR_M 0x0000FF00
Definition at line 124 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_SPH 0x00000080
Definition at line 125 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR0_SPO 0x00000040
Definition at line 126 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR1_MS 0x00000004
Definition at line 131 of file ST7735.c.
Referenced by commonInit().
#define SSI_CR1_SSE 0x00000002
Definition at line 132 of file ST7735.c.
Referenced by commonInit().
#define SSI_SR_BSY 0x00000010
Definition at line 134 of file ST7735.c.
Referenced by writecommand().
#define SSI_SR_TNF 0x00000002
Definition at line 135 of file ST7735.c.
Referenced by writedata().
#define ST7735_CASET 0x2A
Definition at line 160 of file ST7735.c.
Referenced by setAddrWindow().
#define ST7735_CASET 0x2A
Definition at line 160 of file ST7735.c.
#define ST7735_COLMOD 0x3A
Definition at line 166 of file ST7735.c.
#define ST7735_COLMOD 0x3A
Definition at line 166 of file ST7735.c.
#define ST7735_DISPOFF 0x28
Definition at line 158 of file ST7735.c.
#define ST7735_DISPOFF 0x28
Definition at line 158 of file ST7735.c.
#define ST7735_DISPON 0x29
Definition at line 159 of file ST7735.c.
#define ST7735_DISPON 0x29
Definition at line 159 of file ST7735.c.
#define ST7735_DISSET5 0xB6
Definition at line 173 of file ST7735.c.
#define ST7735_DISSET5 0xB6
Definition at line 173 of file ST7735.c.
#define ST7735_FRMCTR1 0xB1
Definition at line 169 of file ST7735.c.
#define ST7735_FRMCTR1 0xB1
Definition at line 169 of file ST7735.c.
#define ST7735_FRMCTR2 0xB2
Definition at line 170 of file ST7735.c.
#define ST7735_FRMCTR2 0xB2
Definition at line 170 of file ST7735.c.
#define ST7735_FRMCTR3 0xB3
Definition at line 171 of file ST7735.c.
#define ST7735_FRMCTR3 0xB3
Definition at line 171 of file ST7735.c.
#define ST7735_GMCTRN1 0xE1
Definition at line 190 of file ST7735.c.
#define ST7735_GMCTRN1 0xE1
Definition at line 190 of file ST7735.c.
#define ST7735_GMCTRP1 0xE0
Definition at line 189 of file ST7735.c.
#define ST7735_GMCTRP1 0xE0
Definition at line 189 of file ST7735.c.
#define ST7735_INVCTR 0xB4
Definition at line 172 of file ST7735.c.
#define ST7735_INVCTR 0xB4
Definition at line 172 of file ST7735.c.
#define ST7735_INVOFF 0x20
Definition at line 156 of file ST7735.c.
Referenced by ST7735_InvertDisplay().
#define ST7735_INVOFF 0x20
Definition at line 156 of file ST7735.c.
#define ST7735_INVON 0x21
Definition at line 157 of file ST7735.c.
Referenced by ST7735_InvertDisplay().
#define ST7735_INVON 0x21
Definition at line 157 of file ST7735.c.
#define ST7735_MADCTL 0x36
Definition at line 167 of file ST7735.c.
Referenced by ST7735_InitR(), and ST7735_SetRotation().
#define ST7735_MADCTL 0x36
Definition at line 167 of file ST7735.c.
#define ST7735_NOP 0x00
Definition at line 146 of file ST7735.c.
#define ST7735_NOP 0x00
Definition at line 146 of file ST7735.c.
#define ST7735_NORON 0x13
Definition at line 154 of file ST7735.c.
#define ST7735_NORON 0x13
Definition at line 154 of file ST7735.c.
#define ST7735_PTLAR 0x30
Definition at line 165 of file ST7735.c.
#define ST7735_PTLAR 0x30
Definition at line 165 of file ST7735.c.
#define ST7735_PTLON 0x12
Definition at line 153 of file ST7735.c.
#define ST7735_PTLON 0x12
Definition at line 153 of file ST7735.c.
#define ST7735_PWCTR1 0xC0
Definition at line 175 of file ST7735.c.
#define ST7735_PWCTR1 0xC0
Definition at line 175 of file ST7735.c.
#define ST7735_PWCTR2 0xC1
Definition at line 176 of file ST7735.c.
#define ST7735_PWCTR2 0xC1
Definition at line 176 of file ST7735.c.
#define ST7735_PWCTR3 0xC2
Definition at line 177 of file ST7735.c.
#define ST7735_PWCTR3 0xC2
Definition at line 177 of file ST7735.c.
#define ST7735_PWCTR4 0xC3
Definition at line 178 of file ST7735.c.
#define ST7735_PWCTR4 0xC3
Definition at line 178 of file ST7735.c.
#define ST7735_PWCTR5 0xC4
Definition at line 179 of file ST7735.c.
#define ST7735_PWCTR5 0xC4
Definition at line 179 of file ST7735.c.
#define ST7735_PWCTR6 0xFC
Definition at line 187 of file ST7735.c.
#define ST7735_PWCTR6 0xFC
Definition at line 187 of file ST7735.c.
#define ST7735_RAMRD 0x2E
Definition at line 163 of file ST7735.c.
#define ST7735_RAMRD 0x2E
Definition at line 163 of file ST7735.c.
#define ST7735_RAMWR 0x2C
Definition at line 162 of file ST7735.c.
Referenced by setAddrWindow().
#define ST7735_RAMWR 0x2C
Definition at line 162 of file ST7735.c.
#define ST7735_RASET 0x2B
Definition at line 161 of file ST7735.c.
Referenced by setAddrWindow().
#define ST7735_RASET 0x2B
Definition at line 161 of file ST7735.c.
#define ST7735_RDDID 0x04
Definition at line 148 of file ST7735.c.
#define ST7735_RDDID 0x04
Definition at line 148 of file ST7735.c.
#define ST7735_RDDST 0x09
Definition at line 149 of file ST7735.c.
#define ST7735_RDDST 0x09
Definition at line 149 of file ST7735.c.
#define ST7735_RDID1 0xDA
Definition at line 182 of file ST7735.c.
#define ST7735_RDID1 0xDA
Definition at line 182 of file ST7735.c.
#define ST7735_RDID2 0xDB
Definition at line 183 of file ST7735.c.
#define ST7735_RDID2 0xDB
Definition at line 183 of file ST7735.c.
#define ST7735_RDID3 0xDC
Definition at line 184 of file ST7735.c.
#define ST7735_RDID3 0xDC
Definition at line 184 of file ST7735.c.
#define ST7735_RDID4 0xDD
Definition at line 185 of file ST7735.c.
#define ST7735_RDID4 0xDD
Definition at line 185 of file ST7735.c.
#define ST7735_SLPIN 0x10
Definition at line 151 of file ST7735.c.
#define ST7735_SLPIN 0x10
Definition at line 151 of file ST7735.c.
#define ST7735_SLPOUT 0x11
Definition at line 152 of file ST7735.c.
#define ST7735_SLPOUT 0x11
Definition at line 152 of file ST7735.c.
#define ST7735_SWRESET 0x01
Definition at line 147 of file ST7735.c.
#define ST7735_SWRESET 0x01
Definition at line 147 of file ST7735.c.
#define ST7735_TFTHEIGHT 160
Definition at line 144 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define ST7735_TFTWIDTH 128
Definition at line 143 of file ST7735.c.
Referenced by ST7735_SetRotation().
#define ST7735_VMCTR1 0xC5
Definition at line 180 of file ST7735.c.
#define ST7735_VMCTR1 0xC5
Definition at line 180 of file ST7735.c.
#define SYSCTL_RCGC1_SSI0 0x00000010
Definition at line 141 of file ST7735.c.
#define SYSCTL_RCGC2_GPIOA 0x00000001
Definition at line 142 of file ST7735.c.
#define TFT_CS (*((volatile uint32_t *)0x40004020))
Definition at line 114 of file ST7735.c.
Referenced by commonInit().
#define TFT_CS_HIGH 0x08
Definition at line 116 of file ST7735.c.
#define TFT_CS_LOW 0
Definition at line 115 of file ST7735.c.
Referenced by commonInit().
Function Documentation
static void commandList (const uint8_t * addr) static
Definition at line 647 of file ST7735.c.
References DELAY, Delay1ms(), writecommand(), and writedata().
Referenced by commonInit(), and ST7735_InitR().
{
   uint8_t numCommands, numArgs;
   uint16_t ms;
   numCommands = *(addr++);               // Number of commands to follow
   while(numCommands--) {                 // For each command...
     writecommand(*(addr++));             //   Read, issue command
     numArgs  = *(addr++);                //   Number of args to follow
     ms       = numArgs & DELAY;          //   If hibit set, delay follows args
     numArgs &= ~DELAY;                   //   Mask out delay bit
     while(numArgs--) {                   //   For each argument...
       writedata(*(addr++));              //     Read, issue argument
     }
     if(ms) {
       ms = *(addr++);             // Read post-command delay time (ms)
       if(ms == 255) ms = 500;     // If 255, delay for 500 ms
       Delay1ms(ms);
     }
   }
 }
static void commonInit (const uint8_t * cmdList) static
Definition at line 672 of file ST7735.c.
References ColStart, commandList(), Delay1ms(), GPIO_PORTA_AFSEL_R, GPIO_PORTA_AMSEL_R, GPIO_PORTA_DEN_R, GPIO_PORTA_DIR_R, GPIO_PORTA_PCTL_R, RESET, RESET_HIGH, RESET_LOW, RowStart, SSI0_CC_R, SSI0_CPSR_R, SSI0_CR0_R, SSI0_CR1_R, SSI_CC_CS_M, SSI_CC_CS_SYSPLL, SSI_CPSR_CPSDVSR_M, SSI_CR0_DSS_8, SSI_CR0_DSS_M, SSI_CR0_FRF_M, SSI_CR0_FRF_MOTO, SSI_CR0_SCR_M, SSI_CR0_SPH, SSI_CR0_SPO, SSI_CR1_MS, SSI_CR1_SSE, SYSCTL_PRGPIO_R, SYSCTL_RCGCGPIO_R, SYSCTL_RCGCSSI_R, TFT_CS, and TFT_CS_LOW.
Referenced by ST7735_InitB(), and ST7735_InitR().
{
   volatile uint32_t delay;
   ColStart  = RowStart = 0; // May be overridden in init func
   SYSCTL_RCGCSSI_R |= 0x01;  // activate SSI0
   SYSCTL_RCGCGPIO_R |= 0x01; // activate port A
   while((SYSCTL_PRGPIO_R&0x01)==0){}; // allow time for clock to start
   // toggle RST low to reset; CS low so it'll listen to us
   // SSI0Fss is temporarily used as GPIO
   GPIO_PORTA_DIR_R |= 0xC8;             // make PA3,6,7 out
   GPIO_PORTA_AFSEL_R &= ~0xC8;          // disable alt funct on PA3,6,7
   GPIO_PORTA_DEN_R |= 0xC8;             // enable digital I/O on PA3,6,7
                                         // configure PA3,6,7 as GPIO
   GPIO_PORTA_PCTL_R = (GPIO_PORTA_PCTL_R&0x00FF0FFF)+0x00000000;
   GPIO_PORTA_AMSEL_R &= ~0xC8;          // disable analog functionality on PA3,6,7
   TFT_CS = TFT_CS_LOW;
   RESET = RESET_HIGH;
   Delay1ms(500);
   RESET = RESET_LOW;
   Delay1ms(500);
   RESET = RESET_HIGH;
   Delay1ms(500);
   // initialize SSI0
   GPIO_PORTA_AFSEL_R |= 0x2C;           // enable alt funct on PA2,3,5
   GPIO_PORTA_DEN_R |= 0x2C;             // enable digital I/O on PA2,3,5
                                         // configure PA2,3,5 as SSI
   GPIO_PORTA_PCTL_R = (GPIO_PORTA_PCTL_R&0xFF0F00FF)+0x00202200;
   GPIO_PORTA_AMSEL_R &= ~0x2C;          // disable analog functionality on PA2,3,5
   SSI0_CR1_R &= ~SSI_CR1_SSE;           // disable SSI
   SSI0_CR1_R &= ~SSI_CR1_MS;            // master mode
                                         // configure for system clock/PLL baud clock source
   SSI0_CC_R = (SSI0_CC_R&~SSI_CC_CS_M)+SSI_CC_CS_SYSPLL;
 //                                        // clock divider for 3.125 MHz SSIClk (50 MHz PIOSC/16)
 //  SSI0_CPSR_R = (SSI0_CPSR_R&~SSI_CPSR_CPSDVSR_M)+16;
                                         // clock divider for 8 MHz SSIClk (80 MHz PLL/24)
                                         // SysClk/(CPSDVSR*(1+SCR))
                                         // 80/(10*(1+0)) = 8 MHz (slower than 4 MHz)
   SSI0_CPSR_R = (SSI0_CPSR_R&~SSI_CPSR_CPSDVSR_M)+10; // must be even number
   SSI0_CR0_R &= ~(SSI_CR0_SCR_M |       // SCR = 0 (8 Mbps data rate)
                   SSI_CR0_SPH |         // SPH = 0
                   SSI_CR0_SPO);         // SPO = 0
                                         // FRF = Freescale format
   SSI0_CR0_R = (SSI0_CR0_R&~SSI_CR0_FRF_M)+SSI_CR0_FRF_MOTO;
                                         // DSS = 8-bit data
   SSI0_CR0_R = (SSI0_CR0_R&~SSI_CR0_DSS_M)+SSI_CR0_DSS_8;
   SSI0_CR1_R |= SSI_CR1_SSE;            // enable SSI
   if(cmdList) commandList(cmdList);
 }
void Delay1ms (uint32_t n)
Definition at line 496 of file ST7735.c.
Referenced by commandList(), and commonInit().
                          {uint32_t volatile time;
   while(n){
     time = 72724*2/91;  // 1msec, tuned at 80 MHz
     while(time){
         time--;
     }
     n--;
   }
 }
int fgetc (FILE * f)
Definition at line 1564 of file ST7735.c.
                    {
   return 0;
 }
void fillmessage (uint32_t n)
Definition at line 1123 of file ST7735.c.
References Message, and Messageindex.
Referenced by ST7735_OutUDec().
{
 // This function uses recursion to convert decimal number
 //   of unspecified length as an ASCII string
   if(n >= 10){
     fillmessage(n/10);
     n = n%10;
   }
   Message[Messageindex] = (n+'0'); /* n is between 0 and 9 */
   if(Messageindex<11)Messageindex++;
 }
int fputc (int ch, FILE * f)
Definition at line 1559 of file ST7735.c.
References ST7735_OutChar().
{
   ST7735_OutChar(ch);
   return 1;
 }
void Output_Clear (void)
Definition at line 1586 of file ST7735.c.
References ST7735_FillScreen().
Referenced by Output_Off().
                        { // Clears the display
   ST7735_FillScreen(0);    // set screen to black
 }
void Output_Color (uint32_t newColor)
Definition at line 1601 of file ST7735.c.
References ST7735_SetTextColor().
                                     { // Set color of future output
   ST7735_SetTextColor(newColor);
 }
void Output_Init (void)
Definition at line 1580 of file ST7735.c.
References INITR_REDTAB, ST7735_FillScreen(), and ST7735_InitR().
Referenced by Output_On().
                       {
   ST7735_InitR(INITR_REDTAB);
   ST7735_FillScreen(0);                 // set screen to black
 }
void Output_Off (void)
Definition at line 1590 of file ST7735.c.
References Output_Clear().
                      {   // Turns off the display
   Output_Clear();  // not implemented
 }
void Output_On (void)
Definition at line 1594 of file ST7735.c.
References Output_Init().
                     { // Turns on the display
   Output_Init();      // reinitialize
 }
static void pushColor (uint16_t color) static
Definition at line 789 of file ST7735.c.
References writedata().
Referenced by ST7735_DrawChar(), and ST7735_DrawPixel().
{
   writedata((uint8_t)(color >> 8));
   writedata((uint8_t)color);
 }
static void setAddrWindow (uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1) static
Definition at line 769 of file ST7735.c.
References ColStart, RowStart, ST7735_CASET, ST7735_RAMWR, ST7735_RASET, writecommand(), and writedata().
Referenced by ST7735_DrawBitmap(), ST7735_DrawChar(), ST7735_DrawFastHLine(), ST7735_DrawFastVLine(), ST7735_DrawPixel(), and ST7735_FillRect().
{
   writecommand(ST7735_CASET); // Column addr set
   writedata(0x00);
   writedata(x0+ColStart);     // XSTART
   writedata(0x00);
   writedata(x1+ColStart);     // XEND
   writecommand(ST7735_RASET); // Row addr set
   writedata(0x00);
   writedata(y0+RowStart);     // YSTART
   writedata(0x00);
   writedata(y1+RowStart);     // YEND
   writecommand(ST7735_RAMWR); // write to RAM
 }
uint16_t ST7735_Color565 (uint8_t r, uint8_t g, uint8_t b)
Definition at line 908 of file ST7735.c.
Referenced by ST7735_PlotClear(), and ST7735_PlotNextErase().
{
   return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3);
 }
void ST7735_DrawBitmap (int16_t x, int16_t y, const uint16_t * image, int16_t w, int16_t h)
Definition at line 942 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
{
   int16_t skipC = 0;                      // non-zero if columns need to be skipped due to clipping
   int16_t originalWidth = w;              // save this value; even if not all columns fit on the screen, the image is still this width in ROM
   int i = w*(h - 1);
   if((x >= _width) || ((y - h + 1) >= _height) || ((x + w) <= 0) || (y < 0)){
     return;                             // image is totally off the screen, do nothing
   }
   if((w > _width) || (h > _height)){    // image is too wide for the screen, do nothing
     //***This isn't necessarily a fatal error, but it makes the
     //following logic much more complicated, since you can have
     //an image that exceeds multiple boundaries and needs to be
     //clipped on more than one side.
     return;
   }
   if((x + w - 1) >= _width){            // image exceeds right of screen
     skipC = (x + w) - _width;           // skip cut off columns
     w = _width - x;
   }
   if((y - h + 1) < 0){                  // image exceeds top of screen
     i = i - (h - y - 1)*originalWidth;  // skip the last cut off rows
     h = y + 1;
   }
   if(x < 0){                            // image exceeds left of screen
     w = w + x;
     skipC = -1*x;                       // skip cut off columns
     i = i - x;                          // skip the first cut off columns
     x = 0;
   }
   if(y >= _height){                     // image exceeds bottom of screen
     h = h - (y - _height + 1);
     y = _height - 1;
   }
   setAddrWindow(x, y-h+1, x+w-1, y);
   for(y=0; y<h; y=y+1){
     for(x=0; x<w; x=x+1){
                                         // send the top 8 bits
       writedata((uint8_t)(image[i] >> 8));
                                         // send the bottom 8 bits
       writedata((uint8_t)image[i]);
       i = i + 1;                        // go to the next pixel
     }
     i = i + skipC;
     i = i - 2*originalWidth;
   }
 }
void ST7735_DrawChar (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
Definition at line 1054 of file ST7735.c.
References _height, _width, Font, pushColor(), and setAddrWindow().
{
   uint8_t line; // horizontal row of pixels of character
   int32_t col, row, i, j;// loop indices
   if(((x + 5*size - 1) >= _width)  || // Clip right
      ((y + 8*size - 1) >= _height) || // Clip bottom
      ((x + 5*size - 1) < 0)        || // Clip left
      ((y + 8*size - 1) < 0)){         // Clip top
     return;
   }
   setAddrWindow(x, y, x+6*size-1, y+8*size-1);
   line = 0x01;        // print the top row first
   // print the rows, starting at the top
   for(row=0; row<8; row=row+1){
     for(i=0; i<size; i=i+1){
       // print the columns, starting on the left
       for(col=0; col<5; col=col+1){
         if(Font[(c*5)+col]&line){
           // bit is set in Font, print pixel(s) in text color
           for(j=0; j<size; j=j+1){
             pushColor(textColor);
           }
         } else{
           // bit is cleared in Font, print pixel(s) in background color
           for(j=0; j<size; j=j+1){
             pushColor(bgColor);
           }
         }
       }
       // print blank column(s) to the right of character
       for(j=0; j<size; j=j+1){
         pushColor(bgColor);
       }
     }
     line = line<<1;   // move up to the next row
   }
 }
void ST7735_DrawCharS (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
Definition at line 1007 of file ST7735.c.
References _height, _width, Font, ST7735_DrawPixel(), and ST7735_FillRect().
Referenced by ST7735_DrawString(), ST7735_OutChar(), ST7735_OutChar2(), and ST7735_OutUDec().
{
   uint8_t line; // vertical column of pixels of character in font
   int32_t i, j;
   if((x >= _width)            || // Clip right
      (y >= _height)           || // Clip bottom
      ((x + 5 * size - 1) < 0) || // Clip left
      ((y + 8 * size - 1) < 0))   // Clip top
     return;
   for (i=0; i<6; i++ ) {
     if (i == 5)
       line = 0x0;
     else
       line = Font[(c*5)+i];
     for (j = 0; j<8; j++) {
       if (line & 0x1) {
         if (size == 1) // default size
           ST7735_DrawPixel(x+i, y+j, textColor);
         else {  // big size
           ST7735_FillRect(x+(i*size), y+(j*size), size, size, textColor);
         }
       } else if (bgColor != textColor) {
         if (size == 1) // default size
           ST7735_DrawPixel(x+i, y+j, bgColor);
         else {  // big size
           ST7735_FillRect(x+i*size, y+j*size, size, size, bgColor);
         }
       }
       line >>= 1;
     }
   }
 }
void ST7735_DrawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Definition at line 849 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by main().
{
   uint8_t hi = color >> 8, lo = color;
   // Rudimentary clipping
   if((x >= _width) || (y >= _height)) return;
   if((x+w-1) >= _width)  w = _width-x;
   setAddrWindow(x, y, x+w-1, y);
   while (w--) {
     writedata(hi);
     writedata(lo);
   }
 }
void ST7735_DrawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
Definition at line 825 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by ST7735_PlotBar(), ST7735_PlotdBfs(), and ST7735_PlotNextErase().
{
   uint8_t hi = color >> 8, lo = color;
   // Rudimentary clipping
   if((x >= _width) || (y >= _height)) return;
   if((y+h-1) >= _height) h = _height-y;
   setAddrWindow(x, y, x, y+h-1);
   while (h--) {
     writedata(hi);
     writedata(lo);
   }
 }
void ST7735_DrawPixel (int16_t x, int16_t y, uint16_t color)
Definition at line 806 of file ST7735.c.
References _height, _width, pushColor(), and setAddrWindow().
Referenced by ST7735_DrawCharS(), ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().
{
   if((x < 0) || (x >= _width) || (y < 0) || (y >= _height)) return;
   setAddrWindow(x,y,x+1,y+1);
   pushColor(color);
 }
uint32_t ST7735_DrawString (uint16_t x, uint16_t y, uint8_t * pt, int16_t textColor)
Definition at line 1102 of file ST7735.c.
References ST7735_BLACK, and ST7735_DrawCharS().
Referenced by ST7735_OutChar(), ST7735_OutChar2(), and ST7735_OutUDec().
{
   uint32_t count = 0;
   if(y>15) return 0;
   while(*pt){
     ST7735_DrawCharS(x*6, y*10, *pt, textColor, ST7735_BLACK, 1);
     pt++;
     x = x+1;
     if(x>20) return count;  // number of characters printed
     count++;
   }
   return count;  // number of characters printed
 }
void ST7735_FillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 883 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by ST7735_DrawCharS(), ST7735_FillScreen(), and ST7735_PlotClear().
{
   uint8_t hi = color >> 8, lo = color;
   // rudimentary clipping (drawChar w/big text requires this)
   if((x >= _width) || (y >= _height)) return;
   if((x + w - 1) >= _width)  w = _width  - x;
   if((y + h - 1) >= _height) h = _height - y;
   setAddrWindow(x, y, x+w-1, y+h-1);
   for(y=h; y>0; y--) {
     for(x=w; x>0; x--) {
       writedata(hi);
       writedata(lo);
     }
   }
 }
void ST7735_FillScreen (uint16_t color)
Definition at line 869 of file ST7735.c.
References _height, _width, and ST7735_FillRect().
Referenced by Output_Clear(), Output_Init(), ST7735_InitB(), and ST7735_InitR().
{
   ST7735_FillRect(0, 0, _width, _height, color);
 }
void ST7735_InitB (void)
Definition at line 729 of file ST7735.c.
References Bcmd, commonInit(), ST7735_FillScreen(), ST7735_SetCursor(), ST7735_YELLOW, and StTextColor.
{
   commonInit(Bcmd);
   ST7735_SetCursor(0,0);
   StTextColor = ST7735_YELLOW;
   ST7735_FillScreen(0);                 // set screen to black
 }
void ST7735_InitR (enum initRFlags option)
Definition at line 741 of file ST7735.c.
References ColStart, commandList(), commonInit(), INITR_BLACKTAB, INITR_GREENTAB, Rcmd1, Rcmd2green, Rcmd2red, Rcmd3, RowStart, ST7735_FillScreen(), ST7735_MADCTL, ST7735_SetCursor(), ST7735_YELLOW, StTextColor, TabColor, writecommand(), and writedata().
Referenced by main(), and Output_Init().
{
   commonInit(Rcmd1);
   if(option == INITR_GREENTAB) {
     commandList(Rcmd2green);
     ColStart = 2;
     RowStart = 1;
   } else {
     // colstart, rowstart left at default '0' values
     commandList(Rcmd2red);
   }
   commandList(Rcmd3);
   // if black, change MADCTL color filter
   if (option == INITR_BLACKTAB) {
     writecommand(ST7735_MADCTL);
     writedata(0xC0);
   }
   TabColor = option;
   ST7735_SetCursor(0,0);
   StTextColor = ST7735_YELLOW;
   ST7735_FillScreen(0);                 // set screen to black
 }
void ST7735_InvertDisplay (int i)
Definition at line 1233 of file ST7735.c.
References ST7735_INVOFF, ST7735_INVON, and writecommand().
{
   if(i){
     writecommand(ST7735_INVON);
   } else{
     writecommand(ST7735_INVOFF);
   }
 }
void ST7735_OutChar (uint8_t ch)
Definition at line 1492 of file ST7735.c.
References ST7735_BLACK, ST7735_DrawCharS(), ST7735_DrawString(), ST7735_RED, ST7735_YELLOW, StTextColor, StX, and StY.
Referenced by fputc(), and ST7735_OutString().
{
   if((ch == 10) || (ch == 13) || (ch == 27)){
     StY++; StX=0;
     if(StY>15){
       StY = 0;
     }
     ST7735_DrawString(0,StY,"                     ",StTextColor);
     return;
   }
   ST7735_DrawCharS(StX*6,StY*10,ch,ST7735_YELLOW,ST7735_BLACK, 1);
   StX++;
   if(StX>20){
     StX = 20;
     ST7735_DrawCharS(StX*6,StY*10,'*',ST7735_RED,ST7735_BLACK, 1);
   }
   return;
 }
void ST7735_OutChar2 (uint8_t ch)
Definition at line 1510 of file ST7735.c.
References ST7735_BLACK, ST7735_DrawCharS(), ST7735_DrawString(), ST7735_RED, ST7735_YELLOW, StTextColor, StX2, and StY2.
Referenced by ST7735_OutString2().
{
   if((ch == 10) || (ch == 13) || (ch == 27)){
     StY2++; StX2=0;
     if(StY2>15){
       StY2 = 10;
     }
     ST7735_DrawString(0,StY2,"                     ",StTextColor);
     return;
   }
   ST7735_DrawCharS(StX2*6,StY2*10,ch,ST7735_YELLOW,ST7735_BLACK, 1);
   StX2++;
   if(StX2>20){
     StX2 = 20;
     ST7735_DrawCharS(StX2*6,StY2*10,'*',ST7735_RED,ST7735_BLACK, 1);
   }
   return;
 }
void ST7735_OutString (uint8_t * ptr)
Definition at line 1535 of file ST7735.c.
References ST7735_OutChar().
Referenced by main().
{
   while(*ptr){
     ST7735_OutChar(*ptr);
     ptr = ptr + 1;
   }
 }
void ST7735_OutString2 (uint8_t * ptr)
Definition at line 1542 of file ST7735.c.
References ST7735_OutChar2().
Referenced by main().
{
   while(*ptr){
     ST7735_OutChar2(*ptr);
     ptr = ptr + 1;
   }
 }
void ST7735_OutUDec (uint32_t n)
Definition at line 1154 of file ST7735.c.
References fillmessage(), Message, Messageindex, ST7735_BLACK, ST7735_DrawCharS(), ST7735_DrawString(), ST7735_RED, StTextColor, StX, and StY.
{
   Messageindex = 0;
   fillmessage(n);
   Message[Messageindex] = 0; // terminate
   ST7735_DrawString(StX,StY,Message,StTextColor);
   StX = StX+Messageindex;
   if(StX>20){
     StX = 20;
     ST7735_DrawCharS(StX*6,StY*10,'*',ST7735_RED,ST7735_BLACK, 1);
   }
 }
void ST7735_PlotBar (int32_t y)
Definition at line 1352 of file ST7735.c.
References ST7735_BLACK, ST7735_DrawFastVLine(), X, Ymax, Ymin, and Yrange.
{
 int32_t j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   ST7735_DrawFastVLine(X, j, 159-j, ST7735_BLACK);
 }
void ST7735_PlotClear (int32_t ymin, int32_t ymax)
Definition at line 1253 of file ST7735.c.
References ST7735_Color565(), ST7735_FillRect(), X, Ymax, Ymin, and Yrange.
{
   ST7735_FillRect(0, 32, 128, 128, ST7735_Color565(228,228,228)); // light grey
   if(ymax>ymin){
     Ymax = ymax;
     Ymin = ymin;
     Yrange = ymax-ymin;
   } else{
     Ymax = ymin;
     Ymin = ymax;
     Yrange = ymax-ymin;
   }
   //YrangeDiv2 = Yrange/2;
   X = 0;
 }
void ST7735_PlotdBfs (int32_t y)
Definition at line 1400 of file ST7735.c.
References dBfs, ST7735_BLACK, ST7735_DrawFastVLine(), and X.
{
 int32_t j;
   y = y/2; // 0 to 2047
   if(y<0) y=0;
   if(y>511) y=511;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=511 maps to j=32
   // y=0 maps to j=159
   j = dBfs[y];
   ST7735_DrawFastVLine(X, j, 159-j, ST7735_BLACK);
 }
void ST7735_PlotLine (int32_t y)
Definition at line 1294 of file ST7735.c.
References lastj, ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                {int32_t i,j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   if(j < 32) j = 32;
   if(j > 159) j = 159;
   if(lastj < 32) lastj = j;
   if(lastj > 159) lastj = j;
   if(lastj < j){
     for(i = lastj+1; i<=j ; i++){
       ST7735_DrawPixel(X,   i,   ST7735_BLUE) ;
       ST7735_DrawPixel(X+1, i,   ST7735_BLUE) ;
     }
   }else if(lastj > j){
     for(i = j; i<lastj ; i++){
       ST7735_DrawPixel(X,   i,   ST7735_BLUE) ;
       ST7735_DrawPixel(X+1, i,   ST7735_BLUE) ;
     }
   }else{
     ST7735_DrawPixel(X,   j,   ST7735_BLUE) ;
     ST7735_DrawPixel(X+1, j,   ST7735_BLUE) ;
   }
   lastj = j;
 }
void ST7735_PlotNext (void)
Definition at line 1420 of file ST7735.c.
References X.
{
   if(X==127){
     X = 0;
   } else{
     X++;
   }
 }
void ST7735_PlotNextErase (void)
Definition at line 1434 of file ST7735.c.
References ST7735_Color565(), ST7735_DrawFastVLine(), and X.
{
   if(X==127){
     X = 0;
   } else{
     X++;
   }
   ST7735_DrawFastVLine(X,32,128,ST7735_Color565(228,228,228));
 }
void ST7735_PlotPoint (int32_t y)
Definition at line 1273 of file ST7735.c.
References ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                 {int32_t j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X,   j,   ST7735_BLUE);
   ST7735_DrawPixel(X+1, j,   ST7735_BLUE);
   ST7735_DrawPixel(X,   j+1, ST7735_BLUE);
   ST7735_DrawPixel(X+1, j+1, ST7735_BLUE);
 }
void ST7735_PlotPoints (int32_t y1, int32_t y2)
Definition at line 1329 of file ST7735.c.
References ST7735_BLACK, ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                              {int32_t j;
   if(y1<Ymin) y1=Ymin;
   if(y1>Ymax) y1=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y1))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X, j, ST7735_BLUE);
   if(y2<Ymin) y2=Ymin;
   if(y2>Ymax) y2=Ymax;
   j = 32+(127*(Ymax-y2))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X, j, ST7735_BLACK);
 }
void ST7735_SetCursor (uint32_t newX, uint32_t newY)
Definition at line 1140 of file ST7735.c.
References StX, and StY.
Referenced by ST7735_InitB(), and ST7735_InitR().
{
   if((newX > 20) || (newY > 15)){       // bad input
     return;                             // do nothing
   }
   StX = newX;
   StY = newY;
 }
void ST7735_SetRotation (uint8_t m)
Definition at line 1183 of file ST7735.c.
References _height, _width, INITR_BLACKTAB, MADCTL_BGR, MADCTL_MV, MADCTL_MX, MADCTL_MY, MADCTL_RGB, Rotation, ST7735_MADCTL, ST7735_TFTHEIGHT, ST7735_TFTWIDTH, TabColor, writecommand(), and writedata().
{
   writecommand(ST7735_MADCTL);
   Rotation = m % 4; // can't be higher than 3
   switch (Rotation) {
    case 0:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MX | MADCTL_MY | MADCTL_RGB);
      } else {
        writedata(MADCTL_MX | MADCTL_MY | MADCTL_BGR);
      }
      _width  = ST7735_TFTWIDTH;
      _height = ST7735_TFTHEIGHT;
      break;
    case 1:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MY | MADCTL_MV | MADCTL_RGB);
      } else {
        writedata(MADCTL_MY | MADCTL_MV | MADCTL_BGR);
      }
      _width  = ST7735_TFTHEIGHT;
      _height = ST7735_TFTWIDTH;
      break;
   case 2:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_RGB);
      } else {
        writedata(MADCTL_BGR);
      }
      _width  = ST7735_TFTWIDTH;
      _height = ST7735_TFTHEIGHT;
     break;
    case 3:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MX | MADCTL_MV | MADCTL_RGB);
      } else {
        writedata(MADCTL_MX | MADCTL_MV | MADCTL_BGR);
      }
      _width  = ST7735_TFTHEIGHT;
      _height = ST7735_TFTWIDTH;
      break;
   }
 }
void ST7735_SetTextColor (uint16_t color)
Definition at line 1555 of file ST7735.c.
References StTextColor.
Referenced by Output_Color().
{
   StTextColor = color;
 }
uint16_t ST7735_SwapColor (uint16_t x)
Definition at line 918 of file ST7735.c.
{
   return (x << 11) | (x & 0x07E0) | (x >> 11);
 }
static void writecommand (uint8_t c) static
Definition at line 477 of file ST7735.c.
References DC, DC_COMMAND, SSI0_DR_R, SSI0_SR_R, and SSI_SR_BSY.
Referenced by commandList(), setAddrWindow(), ST7735_InitR(), ST7735_InvertDisplay(), and ST7735_SetRotation().
{
                                         // wait until SSI0 not busy/transmit FIFO empty
   while((SSI0_SR_R&SSI_SR_BSY)==SSI_SR_BSY){};
   DC = DC_COMMAND;
   SSI0_DR_R = c;                        // data out
                                         // wait until SSI0 not busy/transmit FIFO empty
   while((SSI0_SR_R&SSI_SR_BSY)==SSI_SR_BSY){};
 }
static void writedata (uint8_t c) static
Definition at line 487 of file ST7735.c.
References DC, DC_DATA, SSI0_DR_R, SSI0_SR_R, and SSI_SR_TNF.
Referenced by commandList(), pushColor(), setAddrWindow(), ST7735_DrawBitmap(), ST7735_DrawFastHLine(), ST7735_DrawFastVLine(), ST7735_FillRect(), ST7735_InitR(), and ST7735_SetRotation().
{
   while((SSI0_SR_R&SSI_SR_TNF)==0){};   // wait until transmit FIFO not full
   DC = DC_DATA;
   SSI0_DR_R = c;                        // data out
 }
Variable Documentation
int16_t _height = 160 static
Definition at line 457 of file ST7735.c.
Referenced by ST7735_DrawBitmap(), ST7735_DrawChar(), ST7735_DrawCharS(), ST7735_DrawFastHLine(), ST7735_DrawFastVLine(), ST7735_DrawPixel(), ST7735_FillRect(), ST7735_FillScreen(), and ST7735_SetRotation().
int16_t _width = 128 static
Definition at line 456 of file ST7735.c.
Referenced by ST7735_DrawBitmap(), ST7735_DrawChar(), ST7735_DrawCharS(), ST7735_DrawFastHLine(), ST7735_DrawFastVLine(), ST7735_DrawPixel(), ST7735_FillRect(), ST7735_FillScreen(), and ST7735_SetRotation().
const uint8_t Bcmd[] static
Definition at line 513 of file ST7735.c.
Referenced by ST7735_InitB().
uint8_t ColStart static
Definition at line 453 of file ST7735.c.
Referenced by commonInit(), setAddrWindow(), and ST7735_InitR().
uint8_t const dBfs[512]
Initial value:
={
159, 159, 145, 137, 131, 126, 123, 119, 117, 114, 112, 110, 108, 107, 105, 104, 103, 101,
  100, 99, 98, 97, 96, 95, 94, 93, 93, 92, 91, 90, 90, 89, 88, 88, 87, 87, 86, 85, 85, 84,
  84, 83, 83, 82, 82, 81, 81, 81, 80, 80, 79, 79, 79, 78, 78, 77, 77, 77, 76, 76, 76, 75,
  75, 75, 74, 74, 74, 73, 73, 73, 72, 72, 72, 72, 71, 71, 71, 71, 70, 70, 70, 70, 69, 69,
  69, 69, 68, 68, 68, 68, 67, 67, 67, 67, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 64, 64,
  64, 64, 64, 63, 63, 63, 63, 63, 63, 62, 62, 62, 62, 62, 62, 61, 61, 61, 61, 61, 61, 60,
  60, 60, 60, 60, 60, 59, 59, 59, 59, 59, 59, 59, 58, 58, 58, 58, 58, 58, 58, 57, 57, 57,
  57, 57, 57, 57, 56, 56, 56, 56, 56, 56, 56, 56, 55, 55, 55, 55, 55, 55, 55, 55, 54, 54,
  54, 54, 54, 54, 54, 54, 53, 53, 53, 53, 53, 53, 53, 53, 53, 52, 52, 52, 52, 52, 52, 52,
  52, 52, 52, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 50, 50, 50, 50, 50, 50, 50, 50, 50,
  50, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
  48, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 46, 46, 46, 46, 46, 46, 46, 46, 46,
  46, 46, 46, 46, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 44, 44, 44, 44, 44,
  44, 44, 44, 44, 44, 44, 44, 44, 44, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
  43, 43, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
  40, 40, 40, 40, 40, 40, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
  39, 39, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 37,
  37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 36, 36, 36, 36,
  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 35, 35, 35, 35, 35,
  35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 34, 34, 34, 34, 34, 34,
  34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 33, 33, 33, 33, 33,
  33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 32, 32, 32,
  32, 32, 32, 32, 32, 32, 32, 32, 32, 32
}
Definition at line 1367 of file ST7735.c.
Referenced by ST7735_PlotdBfs().
const uint8_t Font[] static
Definition at line 194 of file ST7735.c.
Referenced by ST7735_DrawChar(), and ST7735_DrawCharS().
int32_t lastj =0
Definition at line 1293 of file ST7735.c.
Referenced by ST7735_PlotLine().
uint8_t Message[12]
Definition at line 1120 of file ST7735.c.
Referenced by fillmessage(), and ST7735_OutUDec().
uint32_t Messageindex
Definition at line 1121 of file ST7735.c.
Referenced by fillmessage(), and ST7735_OutUDec().
const uint8_t Rcmd1[] static
Definition at line 572 of file ST7735.c.
Referenced by ST7735_InitR().
const uint8_t Rcmd2green[] static
Initial value:
= {
    2,
     0x2A   , 4      ,
      0x00, 0x02,
      0x00, 0x7F+0x02,
     0x2B   , 4      ,
      0x00, 0x01,
      0x00, 0x9F+0x01 }
Definition at line 609 of file ST7735.c.
Referenced by ST7735_InitR().
const uint8_t Rcmd2red[] static
Initial value:
= {
    2,
     0x2A   , 4      ,
      0x00, 0x00,
      0x00, 0x7F,
     0x2B   , 4      ,
      0x00, 0x00,
      0x00, 0x9F }
Definition at line 618 of file ST7735.c.
Referenced by ST7735_InitR().
const uint8_t Rcmd3[] static
Initial value:
= {
    4,
     0xE0 , 16      ,
      0x02, 0x1c, 0x07, 0x12,
      0x37, 0x32, 0x29, 0x2d,
      0x29, 0x25, 0x2B, 0x39,
      0x00, 0x01, 0x03, 0x10,
     0xE1 , 16      ,
      0x03, 0x1d, 0x07, 0x06,
      0x2E, 0x2C, 0x29, 0x2D,
      0x2E, 0x2E, 0x37, 0x3F,
      0x00, 0x00, 0x02, 0x10,
     0x13   ,     0x80 ,
      10,
     0x29  ,     0x80 ,
      100 }
Definition at line 627 of file ST7735.c.
Referenced by ST7735_InitR().
uint8_t Rotation static
Definition at line 454 of file ST7735.c.
Referenced by ST7735_SetRotation().
uint8_t RowStart static
Definition at line 453 of file ST7735.c.
Referenced by commonInit(), setAddrWindow(), and ST7735_InitR().
uint16_t StTextColor = 0x07FF
Definition at line 66 of file ST7735.c.
Referenced by ST7735_InitB(), ST7735_InitR(), ST7735_OutChar(), ST7735_OutChar2(), ST7735_OutUDec(), and ST7735_SetTextColor().
uint32_t StX =0
Definition at line 60 of file ST7735.c.
Referenced by ST7735_OutChar(), ST7735_OutUDec(), and ST7735_SetCursor().
uint32_t StX2 =0
Definition at line 63 of file ST7735.c.
Referenced by ST7735_OutChar2().
uint32_t StY =0
Definition at line 61 of file ST7735.c.
Referenced by ST7735_OutChar(), ST7735_OutUDec(), and ST7735_SetCursor().
uint32_t StY2 =10
Definition at line 64 of file ST7735.c.
Referenced by ST7735_OutChar2().
enum initRFlags TabColor static
Definition at line 455 of file ST7735.c.
Referenced by ST7735_InitR(), and ST7735_SetRotation().
int32_t X
Definition at line 1245 of file ST7735.c.
Referenced by ST7735_PlotBar(), ST7735_PlotClear(), ST7735_PlotdBfs(), ST7735_PlotLine(), ST7735_PlotNext(), ST7735_PlotNextErase(), ST7735_PlotPoint(), and ST7735_PlotPoints().
int32_t Ymax
Definition at line 1245 of file ST7735.c.
Referenced by ST7735_PlotBar(), ST7735_PlotClear(), ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().
int32_t Ymin
Definition at line 1245 of file ST7735.c.
Referenced by ST7735_PlotBar(), ST7735_PlotClear(), ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().
int32_t Yrange
Definition at line 1246 of file ST7735.c.
Referenced by ST7735_PlotBar(), ST7735_PlotClear(), ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().