EE445M RTOS: lib/libdisplay/ST7735.h File Reference
ST7735.h File Reference
Macros
#define ST7735_TFTWIDTH 128
#define ST7735_TFTHEIGHT 160
#define ST7735_BLACK 0x0000
#define ST7735_BLUE 0xF800
#define ST7735_RED 0x001F
#define ST7735_GREEN 0x07E0
#define ST7735_CYAN 0xFFE0
#define ST7735_MAGENTA 0xF81F
#define ST7735_YELLOW 0x07FF
#define ST7735_WHITE 0xFFFF
Enumerations
enum initRFlags { none, INITR_GREENTAB, INITR_REDTAB, INITR_BLACKTAB }
Functions
void ST7735_InitB (void)
void ST7735_InitR (enum initRFlags option)
void ST7735_DrawPixel (int16_t x, int16_t y, uint16_t color)
void ST7735_DrawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
void ST7735_DrawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
void ST7735_FillScreen (uint16_t color)
void ST7735_FillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
uint16_t ST7735_Color565 (uint8_t r, uint8_t g, uint8_t b)
uint16_t ST7735_SwapColor (uint16_t x)
void ST7735_DrawBitmap (int16_t x, int16_t y, const uint16_t *image, int16_t w, int16_t h)
void ST7735_DrawCharS (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
void ST7735_DrawChar (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
uint32_t ST7735_DrawString (uint16_t x, uint16_t y, uint8_t *pt, int16_t textColor)
void ST7735_SetCursor (uint32_t newX, uint32_t newY)
void ST7735_OutUDec (uint32_t n)
void ST7735_SetRotation (uint8_t m)
void ST7735_InvertDisplay (int i)
void ST7735_PlotClear (int32_t ymin, int32_t ymax)
void ST7735_PlotPoint (int32_t y)
void ST7735_PlotLine (int32_t y)
void ST7735_PlotPoints (int32_t y1, int32_t y2)
void ST7735_PlotBar (int32_t y)
void ST7735_PlotdBfs (int32_t y)
void ST7735_PlotNext (void)
void ST7735_PlotNextErase (void)
void ST7735_OutChar (uint8_t ch)
void ST7735_OutString (uint8_t *ptr)
void ST7735_SetTextColor (uint16_t color)
void Output_Init (void)
void Output_Clear (void)
void Output_Off (void)
void Output_On (void)
void Output_Color (uint32_t newColor)
Macro Definition Documentation
#define ST7735_BLACK 0x0000
Definition at line 69 of file ST7735.h.
Referenced by ST7735_DrawString(), ST7735_OutChar(), ST7735_OutChar2(), ST7735_OutUDec(), ST7735_PlotBar(), ST7735_PlotdBfs(), and ST7735_PlotPoints().
#define ST7735_BLUE 0xF800
Definition at line 70 of file ST7735.h.
Referenced by ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().
#define ST7735_CYAN 0xFFE0
Definition at line 73 of file ST7735.h.
#define ST7735_GREEN 0x07E0
Definition at line 72 of file ST7735.h.
#define ST7735_MAGENTA 0xF81F
Definition at line 74 of file ST7735.h.
#define ST7735_RED 0x001F
Definition at line 71 of file ST7735.h.
Referenced by ST7735_OutChar(), ST7735_OutChar2(), and ST7735_OutUDec().
#define ST7735_TFTHEIGHT 160
Definition at line 65 of file ST7735.h.
#define ST7735_TFTWIDTH 128
Definition at line 64 of file ST7735.h.
#define ST7735_WHITE 0xFFFF
Definition at line 76 of file ST7735.h.
#define ST7735_YELLOW 0x07FF
Definition at line 75 of file ST7735.h.
Referenced by main(), ST7735_InitB(), ST7735_InitR(), ST7735_OutChar(), and ST7735_OutChar2().
Enumeration Type Documentation
enum initRFlags
Enumerator
none
INITR_GREENTAB
INITR_REDTAB
INITR_BLACKTAB
Definition at line 57 of file ST7735.h.
                {
   none,
   INITR_GREENTAB,
   INITR_REDTAB,
   INITR_BLACKTAB
 };
Function Documentation
void Output_Clear (void)
Definition at line 1586 of file ST7735.c.
References ST7735_FillScreen().
Referenced by Output_Off().
                        { // Clears the display
   ST7735_FillScreen(0);    // set screen to black
 }
void Output_Color (uint32_t newColor)
Definition at line 1601 of file ST7735.c.
References ST7735_SetTextColor().
                                     { // Set color of future output
   ST7735_SetTextColor(newColor);
 }
void Output_Init (void)
Definition at line 1580 of file ST7735.c.
References INITR_REDTAB, ST7735_FillScreen(), and ST7735_InitR().
Referenced by Output_On().
                       {
   ST7735_InitR(INITR_REDTAB);
   ST7735_FillScreen(0);                 // set screen to black
 }
void Output_Off (void)
Definition at line 1590 of file ST7735.c.
References Output_Clear().
                      {   // Turns off the display
   Output_Clear();  // not implemented
 }
void Output_On (void)
Definition at line 1594 of file ST7735.c.
References Output_Init().
                     { // Turns on the display
   Output_Init();      // reinitialize
 }
uint16_t ST7735_Color565 (uint8_t r, uint8_t g, uint8_t b)
Definition at line 908 of file ST7735.c.
Referenced by ST7735_PlotClear(), and ST7735_PlotNextErase().
{
   return ((b & 0xF8) << 8) | ((g & 0xFC) << 3) | (r >> 3);
 }
void ST7735_DrawBitmap (int16_t x, int16_t y, const uint16_t * image, int16_t w, int16_t h)
Definition at line 942 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
{
   int16_t skipC = 0;                      // non-zero if columns need to be skipped due to clipping
   int16_t originalWidth = w;              // save this value; even if not all columns fit on the screen, the image is still this width in ROM
   int i = w*(h - 1);
   if((x >= _width) || ((y - h + 1) >= _height) || ((x + w) <= 0) || (y < 0)){
     return;                             // image is totally off the screen, do nothing
   }
   if((w > _width) || (h > _height)){    // image is too wide for the screen, do nothing
     //***This isn't necessarily a fatal error, but it makes the
     //following logic much more complicated, since you can have
     //an image that exceeds multiple boundaries and needs to be
     //clipped on more than one side.
     return;
   }
   if((x + w - 1) >= _width){            // image exceeds right of screen
     skipC = (x + w) - _width;           // skip cut off columns
     w = _width - x;
   }
   if((y - h + 1) < 0){                  // image exceeds top of screen
     i = i - (h - y - 1)*originalWidth;  // skip the last cut off rows
     h = y + 1;
   }
   if(x < 0){                            // image exceeds left of screen
     w = w + x;
     skipC = -1*x;                       // skip cut off columns
     i = i - x;                          // skip the first cut off columns
     x = 0;
   }
   if(y >= _height){                     // image exceeds bottom of screen
     h = h - (y - _height + 1);
     y = _height - 1;
   }
   setAddrWindow(x, y-h+1, x+w-1, y);
   for(y=0; y<h; y=y+1){
     for(x=0; x<w; x=x+1){
                                         // send the top 8 bits
       writedata((uint8_t)(image[i] >> 8));
                                         // send the bottom 8 bits
       writedata((uint8_t)image[i]);
       i = i + 1;                        // go to the next pixel
     }
     i = i + skipC;
     i = i - 2*originalWidth;
   }
 }
void ST7735_DrawChar (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
Definition at line 1054 of file ST7735.c.
References _height, _width, Font, pushColor(), and setAddrWindow().
{
   uint8_t line; // horizontal row of pixels of character
   int32_t col, row, i, j;// loop indices
   if(((x + 5*size - 1) >= _width)  || // Clip right
      ((y + 8*size - 1) >= _height) || // Clip bottom
      ((x + 5*size - 1) < 0)        || // Clip left
      ((y + 8*size - 1) < 0)){         // Clip top
     return;
   }
   setAddrWindow(x, y, x+6*size-1, y+8*size-1);
   line = 0x01;        // print the top row first
   // print the rows, starting at the top
   for(row=0; row<8; row=row+1){
     for(i=0; i<size; i=i+1){
       // print the columns, starting on the left
       for(col=0; col<5; col=col+1){
         if(Font[(c*5)+col]&line){
           // bit is set in Font, print pixel(s) in text color
           for(j=0; j<size; j=j+1){
             pushColor(textColor);
           }
         } else{
           // bit is cleared in Font, print pixel(s) in background color
           for(j=0; j<size; j=j+1){
             pushColor(bgColor);
           }
         }
       }
       // print blank column(s) to the right of character
       for(j=0; j<size; j=j+1){
         pushColor(bgColor);
       }
     }
     line = line<<1;   // move up to the next row
   }
 }
void ST7735_DrawCharS (int16_t x, int16_t y, uint8_t c, int16_t textColor, int16_t bgColor, uint8_t size)
Definition at line 1007 of file ST7735.c.
References _height, _width, Font, ST7735_DrawPixel(), and ST7735_FillRect().
Referenced by ST7735_DrawString(), ST7735_OutChar(), ST7735_OutChar2(), and ST7735_OutUDec().
{
   uint8_t line; // vertical column of pixels of character in font
   int32_t i, j;
   if((x >= _width)            || // Clip right
      (y >= _height)           || // Clip bottom
      ((x + 5 * size - 1) < 0) || // Clip left
      ((y + 8 * size - 1) < 0))   // Clip top
     return;
   for (i=0; i<6; i++ ) {
     if (i == 5)
       line = 0x0;
     else
       line = Font[(c*5)+i];
     for (j = 0; j<8; j++) {
       if (line & 0x1) {
         if (size == 1) // default size
           ST7735_DrawPixel(x+i, y+j, textColor);
         else {  // big size
           ST7735_FillRect(x+(i*size), y+(j*size), size, size, textColor);
         }
       } else if (bgColor != textColor) {
         if (size == 1) // default size
           ST7735_DrawPixel(x+i, y+j, bgColor);
         else {  // big size
           ST7735_FillRect(x+i*size, y+j*size, size, size, bgColor);
         }
       }
       line >>= 1;
     }
   }
 }
void ST7735_DrawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Definition at line 849 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by main().
{
   uint8_t hi = color >> 8, lo = color;
   // Rudimentary clipping
   if((x >= _width) || (y >= _height)) return;
   if((x+w-1) >= _width)  w = _width-x;
   setAddrWindow(x, y, x+w-1, y);
   while (w--) {
     writedata(hi);
     writedata(lo);
   }
 }
void ST7735_DrawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
Definition at line 825 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by ST7735_PlotBar(), ST7735_PlotdBfs(), and ST7735_PlotNextErase().
{
   uint8_t hi = color >> 8, lo = color;
   // Rudimentary clipping
   if((x >= _width) || (y >= _height)) return;
   if((y+h-1) >= _height) h = _height-y;
   setAddrWindow(x, y, x, y+h-1);
   while (h--) {
     writedata(hi);
     writedata(lo);
   }
 }
void ST7735_DrawPixel (int16_t x, int16_t y, uint16_t color)
Definition at line 806 of file ST7735.c.
References _height, _width, pushColor(), and setAddrWindow().
Referenced by ST7735_DrawCharS(), ST7735_PlotLine(), ST7735_PlotPoint(), and ST7735_PlotPoints().
{
   if((x < 0) || (x >= _width) || (y < 0) || (y >= _height)) return;
   setAddrWindow(x,y,x+1,y+1);
   pushColor(color);
 }
uint32_t ST7735_DrawString (uint16_t x, uint16_t y, uint8_t * pt, int16_t textColor)
Definition at line 1102 of file ST7735.c.
References ST7735_BLACK, and ST7735_DrawCharS().
Referenced by ST7735_OutChar(), ST7735_OutChar2(), and ST7735_OutUDec().
{
   uint32_t count = 0;
   if(y>15) return 0;
   while(*pt){
     ST7735_DrawCharS(x*6, y*10, *pt, textColor, ST7735_BLACK, 1);
     pt++;
     x = x+1;
     if(x>20) return count;  // number of characters printed
     count++;
   }
   return count;  // number of characters printed
 }
void ST7735_FillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 883 of file ST7735.c.
References _height, _width, setAddrWindow(), and writedata().
Referenced by ST7735_DrawCharS(), ST7735_FillScreen(), and ST7735_PlotClear().
{
   uint8_t hi = color >> 8, lo = color;
   // rudimentary clipping (drawChar w/big text requires this)
   if((x >= _width) || (y >= _height)) return;
   if((x + w - 1) >= _width)  w = _width  - x;
   if((y + h - 1) >= _height) h = _height - y;
   setAddrWindow(x, y, x+w-1, y+h-1);
   for(y=h; y>0; y--) {
     for(x=w; x>0; x--) {
       writedata(hi);
       writedata(lo);
     }
   }
 }
void ST7735_FillScreen (uint16_t color)
Definition at line 869 of file ST7735.c.
References _height, _width, and ST7735_FillRect().
Referenced by Output_Clear(), Output_Init(), ST7735_InitB(), and ST7735_InitR().
{
   ST7735_FillRect(0, 0, _width, _height, color);
 }
void ST7735_InitB (void)
Definition at line 729 of file ST7735.c.
References Bcmd, commonInit(), ST7735_FillScreen(), ST7735_SetCursor(), ST7735_YELLOW, and StTextColor.
{
   commonInit(Bcmd);
   ST7735_SetCursor(0,0);
   StTextColor = ST7735_YELLOW;
   ST7735_FillScreen(0);                 // set screen to black
 }
void ST7735_InitR (enum initRFlags option)
Definition at line 741 of file ST7735.c.
References ColStart, commandList(), commonInit(), INITR_BLACKTAB, INITR_GREENTAB, Rcmd1, Rcmd2green, Rcmd2red, Rcmd3, RowStart, ST7735_FillScreen(), ST7735_MADCTL, ST7735_SetCursor(), ST7735_YELLOW, StTextColor, TabColor, writecommand(), and writedata().
Referenced by main(), and Output_Init().
{
   commonInit(Rcmd1);
   if(option == INITR_GREENTAB) {
     commandList(Rcmd2green);
     ColStart = 2;
     RowStart = 1;
   } else {
     // colstart, rowstart left at default '0' values
     commandList(Rcmd2red);
   }
   commandList(Rcmd3);
   // if black, change MADCTL color filter
   if (option == INITR_BLACKTAB) {
     writecommand(ST7735_MADCTL);
     writedata(0xC0);
   }
   TabColor = option;
   ST7735_SetCursor(0,0);
   StTextColor = ST7735_YELLOW;
   ST7735_FillScreen(0);                 // set screen to black
 }
void ST7735_InvertDisplay (int i)
Definition at line 1233 of file ST7735.c.
References ST7735_INVOFF, ST7735_INVON, and writecommand().
{
   if(i){
     writecommand(ST7735_INVON);
   } else{
     writecommand(ST7735_INVOFF);
   }
 }
void ST7735_OutChar (uint8_t ch)
Definition at line 1492 of file ST7735.c.
References ST7735_BLACK, ST7735_DrawCharS(), ST7735_DrawString(), ST7735_RED, ST7735_YELLOW, StTextColor, StX, and StY.
Referenced by fputc(), and ST7735_OutString().
{
   if((ch == 10) || (ch == 13) || (ch == 27)){
     StY++; StX=0;
     if(StY>15){
       StY = 0;
     }
     ST7735_DrawString(0,StY,"                     ",StTextColor);
     return;
   }
   ST7735_DrawCharS(StX*6,StY*10,ch,ST7735_YELLOW,ST7735_BLACK, 1);
   StX++;
   if(StX>20){
     StX = 20;
     ST7735_DrawCharS(StX*6,StY*10,'*',ST7735_RED,ST7735_BLACK, 1);
   }
   return;
 }
void ST7735_OutString (uint8_t * ptr)
Definition at line 1535 of file ST7735.c.
References ST7735_OutChar().
Referenced by main().
{
   while(*ptr){
     ST7735_OutChar(*ptr);
     ptr = ptr + 1;
   }
 }
void ST7735_OutUDec (uint32_t n)
Definition at line 1154 of file ST7735.c.
References fillmessage(), Message, Messageindex, ST7735_BLACK, ST7735_DrawCharS(), ST7735_DrawString(), ST7735_RED, StTextColor, StX, and StY.
{
   Messageindex = 0;
   fillmessage(n);
   Message[Messageindex] = 0; // terminate
   ST7735_DrawString(StX,StY,Message,StTextColor);
   StX = StX+Messageindex;
   if(StX>20){
     StX = 20;
     ST7735_DrawCharS(StX*6,StY*10,'*',ST7735_RED,ST7735_BLACK, 1);
   }
 }
void ST7735_PlotBar (int32_t y)
Definition at line 1352 of file ST7735.c.
References ST7735_BLACK, ST7735_DrawFastVLine(), X, Ymax, Ymin, and Yrange.
{
 int32_t j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   ST7735_DrawFastVLine(X, j, 159-j, ST7735_BLACK);
 }
void ST7735_PlotClear (int32_t ymin, int32_t ymax)
Definition at line 1253 of file ST7735.c.
References ST7735_Color565(), ST7735_FillRect(), X, Ymax, Ymin, and Yrange.
{
   ST7735_FillRect(0, 32, 128, 128, ST7735_Color565(228,228,228)); // light grey
   if(ymax>ymin){
     Ymax = ymax;
     Ymin = ymin;
     Yrange = ymax-ymin;
   } else{
     Ymax = ymin;
     Ymin = ymax;
     Yrange = ymax-ymin;
   }
   //YrangeDiv2 = Yrange/2;
   X = 0;
 }
void ST7735_PlotdBfs (int32_t y)
Definition at line 1400 of file ST7735.c.
References dBfs, ST7735_BLACK, ST7735_DrawFastVLine(), and X.
{
 int32_t j;
   y = y/2; // 0 to 2047
   if(y<0) y=0;
   if(y>511) y=511;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=511 maps to j=32
   // y=0 maps to j=159
   j = dBfs[y];
   ST7735_DrawFastVLine(X, j, 159-j, ST7735_BLACK);
 }
void ST7735_PlotLine (int32_t y)
Definition at line 1294 of file ST7735.c.
References lastj, ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                {int32_t i,j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   if(j < 32) j = 32;
   if(j > 159) j = 159;
   if(lastj < 32) lastj = j;
   if(lastj > 159) lastj = j;
   if(lastj < j){
     for(i = lastj+1; i<=j ; i++){
       ST7735_DrawPixel(X,   i,   ST7735_BLUE) ;
       ST7735_DrawPixel(X+1, i,   ST7735_BLUE) ;
     }
   }else if(lastj > j){
     for(i = j; i<lastj ; i++){
       ST7735_DrawPixel(X,   i,   ST7735_BLUE) ;
       ST7735_DrawPixel(X+1, i,   ST7735_BLUE) ;
     }
   }else{
     ST7735_DrawPixel(X,   j,   ST7735_BLUE) ;
     ST7735_DrawPixel(X+1, j,   ST7735_BLUE) ;
   }
   lastj = j;
 }
void ST7735_PlotNext (void)
Definition at line 1420 of file ST7735.c.
References X.
{
   if(X==127){
     X = 0;
   } else{
     X++;
   }
 }
void ST7735_PlotNextErase (void)
Definition at line 1434 of file ST7735.c.
References ST7735_Color565(), ST7735_DrawFastVLine(), and X.
{
   if(X==127){
     X = 0;
   } else{
     X++;
   }
   ST7735_DrawFastVLine(X,32,128,ST7735_Color565(228,228,228));
 }
void ST7735_PlotPoint (int32_t y)
Definition at line 1273 of file ST7735.c.
References ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                 {int32_t j;
   if(y<Ymin) y=Ymin;
   if(y>Ymax) y=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X,   j,   ST7735_BLUE);
   ST7735_DrawPixel(X+1, j,   ST7735_BLUE);
   ST7735_DrawPixel(X,   j+1, ST7735_BLUE);
   ST7735_DrawPixel(X+1, j+1, ST7735_BLUE);
 }
void ST7735_PlotPoints (int32_t y1, int32_t y2)
Definition at line 1329 of file ST7735.c.
References ST7735_BLACK, ST7735_BLUE, ST7735_DrawPixel(), X, Ymax, Ymin, and Yrange.
                                              {int32_t j;
   if(y1<Ymin) y1=Ymin;
   if(y1>Ymax) y1=Ymax;
   // X goes from 0 to 127
   // j goes from 159 to 32
   // y=Ymax maps to j=32
   // y=Ymin maps to j=159
   j = 32+(127*(Ymax-y1))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X, j, ST7735_BLUE);
   if(y2<Ymin) y2=Ymin;
   if(y2>Ymax) y2=Ymax;
   j = 32+(127*(Ymax-y2))/Yrange;
   if(j<32) j = 32;
   if(j>159) j = 159;
   ST7735_DrawPixel(X, j, ST7735_BLACK);
 }
void ST7735_SetCursor (uint32_t newX, uint32_t newY)
Definition at line 1140 of file ST7735.c.
References StX, and StY.
Referenced by ST7735_InitB(), and ST7735_InitR().
{
   if((newX > 20) || (newY > 15)){       // bad input
     return;                             // do nothing
   }
   StX = newX;
   StY = newY;
 }
void ST7735_SetRotation (uint8_t m)
Definition at line 1183 of file ST7735.c.
References _height, _width, INITR_BLACKTAB, MADCTL_BGR, MADCTL_MV, MADCTL_MX, MADCTL_MY, MADCTL_RGB, Rotation, ST7735_MADCTL, ST7735_TFTHEIGHT, ST7735_TFTWIDTH, TabColor, writecommand(), and writedata().
{
   writecommand(ST7735_MADCTL);
   Rotation = m % 4; // can't be higher than 3
   switch (Rotation) {
    case 0:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MX | MADCTL_MY | MADCTL_RGB);
      } else {
        writedata(MADCTL_MX | MADCTL_MY | MADCTL_BGR);
      }
      _width  = ST7735_TFTWIDTH;
      _height = ST7735_TFTHEIGHT;
      break;
    case 1:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MY | MADCTL_MV | MADCTL_RGB);
      } else {
        writedata(MADCTL_MY | MADCTL_MV | MADCTL_BGR);
      }
      _width  = ST7735_TFTHEIGHT;
      _height = ST7735_TFTWIDTH;
      break;
   case 2:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_RGB);
      } else {
        writedata(MADCTL_BGR);
      }
      _width  = ST7735_TFTWIDTH;
      _height = ST7735_TFTHEIGHT;
     break;
    case 3:
      if (TabColor == INITR_BLACKTAB) {
        writedata(MADCTL_MX | MADCTL_MV | MADCTL_RGB);
      } else {
        writedata(MADCTL_MX | MADCTL_MV | MADCTL_BGR);
      }
      _width  = ST7735_TFTHEIGHT;
      _height = ST7735_TFTWIDTH;
      break;
   }
 }
void ST7735_SetTextColor (uint16_t color)
Definition at line 1555 of file ST7735.c.
References StTextColor.
Referenced by Output_Color().
{
   StTextColor = color;
 }
uint16_t ST7735_SwapColor (uint16_t x)
Definition at line 918 of file ST7735.c.
{
   return (x << 11) | (x & 0x07E0) | (x >> 11);
 }