EE445M RTOS: drive Class Reference
drive Class Reference
Drive
#include <drivepp.hpp>
Public Member Functions
drive ()
drive (motor *left, motor *right, percent_t speed=0, Direction direction=FORWARD)
void forward (percent_t speed)
void backward (percent_t speed)
void set (percent_t speed, Direction dir)
void stop (void)
void start (void)
void steer (uint32_t left_sens, uint32_t left_front_sens, uint32_t right_sens, uint32_t right_front_sens, uint32_t front_sens)
void reset_history ()
Private Attributes
motor * left
motor * right
int32_t integral_oblique_error
int32_t integral_side_error
int32_t last_counter
Static Private Attributes
static const int32_t kp_oblique_num = 10
static const int32_t kp_oblique_denom = 1
static const int32_t kp_side_num = 5
static const int32_t kp_side_denom = 2
static const int32_t ki_oblique_num = 1
static const int32_t ki_oblique_denom = 10000
static const int32_t ki_side_num = 1
static const int32_t ki_side_denom = 2000
Detailed Description
Definition at line 19 of file drivepp.hpp.
Constructor & Destructor Documentation
drive::drive ()
Definition at line 10 of file drivepp.cpp.
 {}
drive::drive (motor * left, motor * right, percent_t speed = 0, Direction direction = FORWARD)
Definition at line 12 of file drivepp.cpp.
References integral_oblique_error, left, right, and set().
{
     this->left = left;
     this->right = right;
     set(speed, direction);
     integral_oblique_error = 0;
 }
Member Function Documentation
void drive::backward (percent_t speed)
Move backward at some percent of full-speed.
Definition at line 38 of file drivepp.cpp.
References BACKWARD, left, right, and motor::set().
{
     left->set(speed, BACKWARD);
     right->set(speed, BACKWARD);
 }
void drive::forward (percent_t speed)
Move forward at some percent of full-speed.
Definition at line 32 of file drivepp.cpp.
References FORWARD, left, right, and motor::set().
{
     left->set(speed, FORWARD);
     right->set(speed, FORWARD);
 }
void drive::reset_history ()
Definition at line 122 of file drivepp.cpp.
References integral_oblique_error, and integral_side_error.
Referenced by switch_responder().
{
     integral_oblique_error = 0;
     integral_side_error = 0;
 }
void drive::set (percent_t speed, Direction dir)
Set motor vectors
Definition at line 44 of file drivepp.cpp.
References left, right, and motor::set().
Referenced by drive().
{
     left->set(speed, dir);
     right->set(speed, dir);
 }
void drive::start (void)
Re-enable all previoulsy stopped motors
Definition at line 26 of file drivepp.cpp.
References left, right, and motor::start().
Referenced by motor_control().
                   {
     left->start();
     right->start();
 }
void drive::steer (uint32_t left_sens, uint32_t left_front_sens, uint32_t right_sens, uint32_t right_front_sens, uint32_t front_sens)
Feed the autonomous driver sensor inputs.
Definition at line 50 of file drivepp.cpp.
References clamp(), FORWARD, integral_oblique_error, integral_side_error, kp_oblique_denom, kp_oblique_num, last_counter, left, motor::pwm_max_period, right, and motor::set().
Referenced by driver().
{
     /* todo: feed the lf/f, rf/r data here for porportional control of
      * the motors. the side with the larger coefficient slows more */
     Direction dir = FORWARD;
     left_sens = 0;
     right_sens = 0;
     front_sens = 0;
     /* if (last_counter >= steps_to_wait) { */
     /*     last_counter = 0; */
     /*     if (abs(last_left_sens - left_sens) > reset_thresh) { */
     /*         integral_oblique_error = 0; */
     /*         integral_side_error = 0; */
     /*         GPIOPinWrite(GPIO_PORTF_BASE, PIN_RED, PIN_RED ^ GPIOPinRead(GPIO_PORTF_BASE, PIN_RED)); */
     /*     } else if(abs(last_left_front_sens - left_front_sens) > reset_thresh) { */
     /*         integral_oblique_error = 0; */
     /*         integral_side_error = 0; */
     /*         GPIOPinWrite(GPIO_PORTF_BASE, PIN_RED, PIN_RED ^ GPIOPinRead(GPIO_PORTF_BASE, PIN_RED)); */
     /*     } else if(abs(last_right_sens - right_sens) > reset_thresh) { */
     /*         integral_oblique_error = 0; */
     /*         integral_side_error = 0; */
     /*         GPIOPinWrite(GPIO_PORTF_BASE, PIN_RED, PIN_RED ^ GPIOPinRead(GPIO_PORTF_BASE, PIN_RED)); */
     /*     } else if(abs(last_right_front_sens - right_front_sens) > reset_thresh) { */
     /*         integral_oblique_error = 0; */
     /*         integral_side_error = 0; */
     /*         GPIOPinWrite(GPIO_PORTF_BASE, PIN_RED, PIN_RED ^ GPIOPinRead(GPIO_PORTF_BASE, PIN_RED)); */
     /*     } */
     /*     last_left_sens = left_sens; */
     /*     last_left_front_sens = left_front_sens; */
     /*     last_right_sens = right_sens; */
     /*     last_right_front_sens = right_front_sens; */
     /* } */
     int32_t left_speed = left->pwm_max_period/2;
     int32_t right_speed = right->pwm_max_period/2;
     int32_t oblique_error = ((int32_t)left_front_sens - (int32_t)right_front_sens);
     integral_oblique_error = clamp(integral_oblique_error + oblique_error, -motor::pwm_max_period/4, motor::pwm_max_period/4);
     int32_t side_error = ((int32_t)left_sens - (int32_t)right_sens);
     integral_side_error = clamp(integral_side_error + side_error, -motor::pwm_max_period/8, motor::pwm_max_period/8);
     int32_t should_use_side_sensors = front_sens < 200;
     should_use_side_sensors = 0;
     int32_t should_slow_down = front_sens < 200;
     //int32_t delta = oblique_error*kp_oblique_num/kp_oblique_denom +
     //     (should_use_side_sensors * side_error * kp_side_num/kp_side_denom) +
                                                    //    (integral_oblique_error*ki_oblique_num/ki_oblique_denom) + (integral_side_error*ki_side_num/ki_side_denom);
     int32_t delta = oblique_error*kp_oblique_num/kp_oblique_denom;
     //+ (integral_oblique_error*ki_oblique_num/ki_oblique_denom);
     if (should_slow_down > 0) { delta /= 2; }
     left_speed +=  delta;
     right_speed -= delta;
     left->set(left_speed, dir);
     right->set(right_speed, dir);
     ++last_counter;
 }
void drive::stop (void)
Stop all motors
Definition at line 20 of file drivepp.cpp.
References left, right, and motor::stop().
Referenced by motor_control(), and Timer0A_Handler().
                  {
     left->stop();
     right->stop();
 }
Member Data Documentation
int32_t drive::integral_oblique_error private
Definition at line 23 of file drivepp.hpp.
Referenced by drive(), reset_history(), and steer().
int32_t drive::integral_side_error private
Definition at line 24 of file drivepp.hpp.
Referenced by reset_history(), and steer().
const int32_t drive::ki_oblique_denom = 10000 static private
Definition at line 33 of file drivepp.hpp.
const int32_t drive::ki_oblique_num = 1 static private
Definition at line 32 of file drivepp.hpp.
const int32_t drive::ki_side_denom = 2000 static private
Definition at line 36 of file drivepp.hpp.
const int32_t drive::ki_side_num = 1 static private
Definition at line 35 of file drivepp.hpp.
const int32_t drive::kp_oblique_denom = 1 static private
Definition at line 27 of file drivepp.hpp.
Referenced by steer().
const int32_t drive::kp_oblique_num = 10 static private
Definition at line 26 of file drivepp.hpp.
Referenced by steer().
const int32_t drive::kp_side_denom = 2 static private
Definition at line 30 of file drivepp.hpp.
const int32_t drive::kp_side_num = 5 static private
Definition at line 29 of file drivepp.hpp.
int32_t drive::last_counter private
Definition at line 38 of file drivepp.hpp.
Referenced by steer().
motor* drive::left private
Definition at line 21 of file drivepp.hpp.
Referenced by backward(), drive(), forward(), set(), start(), steer(), and stop().
motor* drive::right private
Definition at line 22 of file drivepp.hpp.
Referenced by backward(), drive(), forward(), set(), start(), steer(), and stop().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/drivepp.hpp
board-progs/autonomous-racer/common/drivepp.cpp