EE445M RTOS: timer Class Reference
timer Class Reference
#include <timerpp.hpp>
Public Member Functions
timer ()
timer (timer_t timer_id, subtimer_t timer_subtimer, uint32_t timer_configuration, reload_t timer_load_val, uint32_t timer_interrupt, bool timer_start=false)
virtual void start ()
virtual void stop ()
virtual uint32_t ack ()
virtual uint32_t get ()
const subtimer_t get_subtimer ()
const uint32_t get_base ()
void reload (void)
void load (uint32_t load_value)
Public Member Functions inherited from interruptable
interruptable ()
Private Attributes
timer_t id
uint32_t base
subtimer_t subtimer
reload_t reload_value
uint32_t configuration
uint32_t interrupt
Detailed Description
Definition at line 26 of file timerpp.hpp.
Constructor & Destructor Documentation
timer::timer ()
Definition at line 10 of file timerpp.cpp.
 {}
timer::timer (timer_t timer_id, subtimer_t timer_subtimer, uint32_t timer_configuration, reload_t timer_load_val, uint32_t timer_interrupt, bool timer_start = false)
Definition at line 12 of file timerpp.cpp.
References base, configuration, interrupt, reload(), reload_value, start(), and subtimer.
{
     id = timer_id;
     base = TIMER0_BASE + 0x1000 * timer_id;
     subtimer = timer_subtimer;
     reload_value = timer_load_val;
     configuration = timer_configuration;
     interrupt = timer_interrupt;
     SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0 + id);
     TimerConfigure(base, configuration);
     switch(subtimer) {
     case TIMER_A:
     case TIMER_BOTH:
         IntEnable(INT_TIMER0A + id*2);
         break;
     case TIMER_B:
         IntEnable(INT_TIMER0A + id*2 + 1);
         break;
     default:
         while (1) {}
     }
     reload();
     if (timer_start) { start(); }
 }
Member Function Documentation
uint32_t timer::ack (void) virtual
Acknowledge an interrupt. Clears the interrupt bits for this timer.
Implements interruptable.
Definition at line 74 of file timerpp.cpp.
References base, and subtimer.
Referenced by lswitch::end_debounce(), ping::handle_timer(), Timer0A_Handler(), Timer1A_Handler(), and Timer2A_Handler().
                     {
     switch(subtimer) {
     case TIMER_A:
     case TIMER_BOTH:
         TimerIntClear(base, INT_TIMER0A + id*2);
         break;
     case TIMER_B:
         TimerIntClear(base, INT_TIMER0A + id*2 + 1);
         break;
     default:
         while (1) {}
     }
     return 0xDEADBEEF;
 }
uint32_t timer::get (void) virtual
Definition at line 90 of file timerpp.cpp.
References base, and subtimer.
Referenced by ping::handle_gpio().
                     {
     switch(subtimer) {
     case TIMER_A:
     case TIMER_BOTH:
         TimerValueGet(base, TIMER_A);
         break;
     case TIMER_B:
         TimerValueGet(base, TIMER_B);
         break;
     default:
         while (1) {}
     }
 }
const uint32_t timer::get_base ()
Definition at line 109 of file timerpp.cpp.
References base.
Referenced by adc::configure_timer_interrupt().
{
     return base;
 }
const subtimer_t timer::get_subtimer ()
Definition at line 105 of file timerpp.cpp.
References subtimer.
Referenced by adc::configure_timer_interrupt().
{
     return subtimer;
 }
void timer::load (uint32_t load_value)
Definition at line 47 of file timerpp.cpp.
References base, and subtimer.
Referenced by ping::handle_gpio(), and reload().
{
     switch(subtimer) {
     case TIMER_A:
     case TIMER_BOTH:
         TimerLoadSet(base, TIMER_A, load_value);
         break;
     case TIMER_B:
         TimerLoadSet(base, TIMER_B, load_value);
         break;
     default:
         while (1) {}
     }
 }
void timer::reload (void)
Reload the timer with the initial reload value
Definition at line 42 of file timerpp.cpp.
References load(), and reload_value.
Referenced by ping::handle_gpio(), and timer().
                    {
     load(reload_value);
 }
void timer::start (void) virtual
Start a timer.
Implements interruptable.
Definition at line 62 of file timerpp.cpp.
References base, interrupt, and subtimer.
Referenced by lswitch::debounce(), ping::handle_gpio(), and timer().
                   {
     TimerIntEnable(base, interrupt);
     TimerEnable(base, subtimer);
 }
void timer::stop (void) virtual
Stop a timer.
Implements interruptable.
Definition at line 68 of file timerpp.cpp.
References base, interrupt, and subtimer.
                  {
     TimerIntDisable(base, interrupt);
     TimerDisable(base, subtimer);
 }
Member Data Documentation
uint32_t timer::base private
The base address of the specified timer
Definition at line 32 of file timerpp.hpp.
Referenced by ack(), get(), get_base(), load(), start(), stop(), and timer().
uint32_t timer::configuration private
The configuration bitset for the timer
Note
Reference timer.h for possible options (e.g. TIMER_CFG_PERIODIC)
Definition at line 42 of file timerpp.hpp.
Referenced by timer().
timer_t timer::id private
Defined between 0 to 4, where 0 indicates TIMER0
Definition at line 29 of file timerpp.hpp.
uint32_t timer::interrupt private
The timer interrupt to be acknowdeged, enabled, disabled
Note
Reference timer.h for possible options (e.g. TIMER_TIMA_TIMEOUT)
Definition at line 46 of file timerpp.hpp.
Referenced by start(), stop(), and timer().
reload_t timer::reload_value private
The reload value for the timer
Definition at line 38 of file timerpp.hpp.
Referenced by reload(), and timer().
subtimer_t timer::subtimer private
TIMER_A, TIMER_B, or TIMER_BOTH
Definition at line 35 of file timerpp.hpp.
Referenced by ack(), get(), get_subtimer(), load(), start(), stop(), and timer().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/timerpp.hpp
board-progs/autonomous-racer/common/timerpp.cpp