EE445M RTOS: circularbuffer< T, N > Class Template Reference
circularbuffer< T, N > Class Template Reference
Buffer
#include <circularbuffer.hpp>
Public Member Functions
circularbuffer ()
void increment_ptr (uint32_t *ptr, uint32_t increment, uint32_t wrap_len)
void add (const T ch)
T peek ()
T get (int32_t offset)
Public Member Functions inherited from buffer< T, N >
buffer ()
buffer (semaphore *sem)
void clear ()
void init ()
void notify (const T data)
bool add (const T data)
T peek ()
T get (bool &ok)
bool full ()
bool empty ()
uint32_t length ()
Additional Inherited Members
Public Attributes inherited from buffer< T, N >
uint32_t pos
uint32_t len
semaphore * sem
T buf [N]
uint32_t error_overflow
uint32_t error_underflow
Detailed Description
template<typename T, uint32_t N>
class circularbuffer< T, N >
Definition at line 13 of file circularbuffer.hpp.
Constructor & Destructor Documentation
template<typename T, uint32_t N> circularbuffer< T, N >::circularbuffer () inline
Definition at line 17 of file circularbuffer.hpp.
 : buffer<T, N>() { }
Member Function Documentation
template<typename T, uint32_t N> void circularbuffer< T, N >::add (const T ch) inline
Definition at line 24 of file circularbuffer.hpp.
Referenced by ping::handle_gpio(), and ir::sample().
{
         this->buf[this->pos] = ch;
         increment_ptr(&(this->pos), 1, this->len);
     }
template<typename T, uint32_t N> T circularbuffer< T, N >::get (int32_t offset) inline
Definition at line 33 of file circularbuffer.hpp.
{
         int32_t position_to_get = ((this->pos+offset) % this->len);
         if (position_to_get < 0) {
             return this->buf[position_to_get + this->len];
         }
         return this->buf[position_to_get];
     }
template<typename T, uint32_t N> void circularbuffer< T, N >::increment_ptr (uint32_t * ptr, uint32_t increment, uint32_t wrap_len) inline
Definition at line 19 of file circularbuffer.hpp.
Referenced by circularbuffer< int16_t, 32 >::add().
{
         *ptr = (*ptr + increment) % wrap_len;
     }
template<typename T, uint32_t N> T circularbuffer< T, N >::peek () inline
Definition at line 29 of file circularbuffer.hpp.
              {
         return this->buf(this->pos);
     }
The documentation for this class was generated from the following file:
board-progs/autonomous-racer/common/circularbuffer.hpp