EE445M RTOS: ir Class Reference
ir Class Reference
#include <ir.hpp>
Classes
struct calibration_data
Public Member Functions
ir ()
ir (uint8_t ir_adc_sequence_step, adc *ir_assoc_adc, int32_t ir_a=240333, int32_t ir_b=-314, int32_t ir_k=0)
void calibrate (int32_t a, int32_t b, int32_t k)
void sample (void)
int32_t average ()
int32_t distance ()
Static Public Attributes
static const int32_t max_distance = 500
static const int32_t min_distance = 0
Private Types
typedef struct ir::calibration_data calibration_data
Private Attributes
calibration_data calibration
circularbuffer< int16_t, 32 > buf
uint8_t adc_sequence_step
adc * assoc_adc
int32_t cached_average
Detailed Description
Definition at line 15 of file ir.hpp.
Member Typedef Documentation
typedef struct ir::calibration_data ir::calibration_data private
Constructor & Destructor Documentation
ir::ir ()
Definition at line 4 of file ir.cpp.
 {}
ir::ir (uint8_t ir_adc_sequence_step, adc * ir_assoc_adc, int32_t ir_a = 240333, int32_t ir_b = -314, int32_t ir_k = 0)
Definition at line 6 of file ir.cpp.
References adc_sequence_step, assoc_adc, buf, and calibrate().
{
     buf = circularbuffer<IR_BUFFER_TYPE, IR_BUFFER_LENGTH>();
     adc_sequence_step = ir_adc_sequence_step;
     assoc_adc = ir_assoc_adc;
     calibrate(ir_a, ir_b, ir_k);
 }
Member Function Documentation
int32_t ir::average ()
Definition at line 27 of file ir.cpp.
References buf, buffer< T, N >::buf, and buffer< T, N >::len.
Referenced by distance().
                     {
     int32_t i, value;
     value = 0;
     for (i=0; i<buf.len; ++i) {
         value += buf.buf[i];
     }
     value /= buf.len;
     return value;
 }
void ir::calibrate (int32_t a, int32_t b, int32_t k)
Definition at line 15 of file ir.cpp.
References ir::calibration_data::a, ir::calibration_data::b, calibration, and ir::calibration_data::k.
Referenced by ir().
{
     calibration.a = a;
     calibration.b = b;
     calibration.k = k;
 }
int32_t ir::distance ()
Converts the values of the IR distance sensor to centimeters
Returns
0 if the conversion did not succeed, data otherwise
Definition at line 40 of file ir.cpp.
References ir::calibration_data::a, average(), ir::calibration_data::b, cached_average, calibration, clamp(), ir::calibration_data::k, max_distance, and min_distance.
Referenced by can_transmitter().
                      {
     cached_average = average();
     if ((cached_average + calibration.b) <= 0) {
         return max_distance;
     }
     return clamp(calibration.a / (cached_average + calibration.b) - calibration.k,
                  min_distance, max_distance);
 }
void ir::sample (void)
Definition at line 22 of file ir.cpp.
References adc_sequence_step, circularbuffer< T, N >::add(), assoc_adc, buf, and adc::get_sample().
Referenced by ADC0Seq0_Handler().
                 {
     buf.add(assoc_adc->get_sample(adc_sequence_step));
     /* sem += adc_producer_index / (signal_length-1); */
 }
Member Data Documentation
uint8_t ir::adc_sequence_step private
Definition at line 52 of file ir.hpp.
Referenced by ir(), and sample().
adc* ir::assoc_adc private
Definition at line 53 of file ir.hpp.
Referenced by ir(), and sample().
circularbuffer< int16_t , 32 > ir::buf private
Definition at line 51 of file ir.hpp.
Referenced by average(), ir(), and sample().
int32_t ir::cached_average private
Definition at line 55 of file ir.hpp.
Referenced by distance().
calibration_data ir::calibration private
Definition at line 50 of file ir.hpp.
Referenced by calibrate(), and distance().
const int32_t ir::max_distance = 500 static
Definition at line 66 of file ir.hpp.
Referenced by distance().
const int32_t ir::min_distance = 0 static
Definition at line 67 of file ir.hpp.
Referenced by distance().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/ir.hpp
board-progs/autonomous-racer/common/ir.cpp