EE445M RTOS: motor Class Reference
motor Class Reference
Motor
#include <motorpp.hpp>
Public Member Functions
motor ()
motor (memory_address_t ctrl_base, memory_address_t ctrl_pin, memory_address_t pwm_base, memory_address_t pwm_gen, memory_address_t pwm_out, bool motor_installed_backwards=false)
void set_motor_installed_backwards (bool)
void stop (void)
void start (void)
void set (percent_t speed)
void set (percent_t percent_full_speed, Direction dir)
percent_t get (void)
void reverse (void)
Public Member Functions inherited from critical
uint32_t StartCritical (void)
void EndCritical (uint32_t primask)
Static Public Attributes
static const uint16_t pwm_max_period = 10000
Private Member Functions
void motor_init (void)
void pwm_init (void)
Direction adjusted_direction (void)
Private Attributes
blinker ctrl
blinker pwm
memory_address_t ctrl_base
memory_address_t ctrl_pin
memory_address_t pwm_base
memory_address_t pwm_pin
memory_address_t pwm_gen
memory_address_t pwm_out
bool motor_installed_backwards
uint32_t pwm_period
uint32_t duty_period
Direction direction
percent_t current_speed
bool enabled
Additional Inherited Members
Static Public Member Functions inherited from critical
static uint32_t static_StartCritical (void)
static void static_EndCritical (uint32_t primask)
Detailed Description
Definition at line 19 of file motorpp.hpp.
Constructor & Destructor Documentation
motor::motor ()
Definition at line 11 of file motorpp.cpp.
 {}
motor::motor (memory_address_t ctrl_base, memory_address_t ctrl_pin, memory_address_t pwm_base, memory_address_t pwm_gen, memory_address_t pwm_out, bool motor_installed_backwards = false)
Definition at line 13 of file motorpp.cpp.
References ctrl, ctrl_base, ctrl_pin, ctlsys::enable_periph(), enabled, motor_init(), motor_installed_backwards, pwm_base, pwm_gen, and pwm_out.
{
     this->ctrl = blinker(ctrl_base, ctrl_pin);
     this->ctrl_base = ctrl_base;
     this->ctrl_pin = ctrl_pin;
     this->pwm_base = pwm_base;
     this->pwm_gen = pwm_gen;
     this->pwm_out = pwm_out;
     ctlsys::enable_periph(ctrl_base);
     ctlsys::enable_periph(pwm_base);
     this->motor_installed_backwards = motor_installed_backwards;
     enabled = false;
     motor_init();
 }
Member Function Documentation
Direction motor::adjusted_direction (void) private
Return direction adjusted for motor position on the robot – Direction refers to the robot's orientation, not the motor's
Definition at line 39 of file motorpp.cpp.
References direction, motor_installed_backwards, and nav::opposite().
Referenced by set().
{
     return motor_installed_backwards ? nav::opposite(direction) :
         direction;
 }
percent_t motor::get (void)
Definition at line 141 of file motorpp.cpp.
References current_speed.
                      {
     return current_speed;
 }
void motor::motor_init (void) private
Initializes pins PE0-3 for output
Definition at line 89 of file motorpp.cpp.
References BACKWARD, direction, FORWARD, motor_installed_backwards, and pwm_init().
Referenced by motor().
{
     direction = motor_installed_backwards ? BACKWARD : FORWARD;
     pwm_init();
 }
void motor::pwm_init (void) private
Definition at line 102 of file motorpp.cpp.
References ctrl_base, DEFAULT_PWM_PERIOD, ctlsys::enable_periph(), critical::EndCritical(), FORWARD, pwm_base, pwm_gen, pwm_out, set(), start(), and critical::StartCritical().
Referenced by motor_init().
                      {
     uint32_t status = StartCritical();
     /* nucleo: abstract */
     ctlsys::enable_periph(GPIO_PORTB_BASE);
     ctlsys::enable_periph(ctrl_base);
     SysCtlPWMClockSet(SYSCTL_PWMDIV_1);
     PWMGenConfigure(pwm_base, pwm_gen, PWM_GEN_MODE_DOWN | PWM_GEN_MODE_NO_SYNC);
     PWMGenPeriodSet(pwm_base, pwm_gen, DEFAULT_PWM_PERIOD);
     PWMGenEnable(pwm_base, pwm_gen);
     switch(pwm_out) {
     case PWM_OUT_0:
         GPIOPinConfigure(GPIO_PB6_M0PWM0);
         GPIOPinTypePWM(GPIO_PORTB_BASE, GPIO_PIN_6);
         break;
     case PWM_OUT_1:
         GPIOPinConfigure(GPIO_PB7_M0PWM1);
         GPIOPinTypePWM(GPIO_PORTB_BASE, GPIO_PIN_7);
         break;
     default:
         while(1) {}
     }
     /* Enable the outputs. */
     PWMOutputState(pwm_base, (PWM_OUT_0_BIT | PWM_OUT_1_BIT), true);
     set(50, FORWARD);
     start();
     EndCritical(status);
 }
void motor::reverse (void)
Reverse motor direction.
note maintains current speed
Definition at line 136 of file motorpp.cpp.
References current_speed, direction, nav::opposite(), and set().
Referenced by switch_responder().
                     {
     set(current_speed, nav::opposite(direction));
 }
void motor::set (percent_t speed)
Set the motor speed.
Definition at line 67 of file motorpp.cpp.
References adjusted_direction(), BACKWARD, clamp(), current_speed, enabled, FORWARD, pwm_base, pwm_max_period, and pwm_out.
Referenced by drive::backward(), drive::forward(), pwm_init(), reverse(), drive::set(), set(), drive::steer(), and stop().
{
     speed = clamp(speed, 1, pwm_max_period);
     current_speed = speed;
     uint16_t adjusted_duty;
     switch(adjusted_direction()) {
     case FORWARD:
         adjusted_duty = speed;
         break;
     case BACKWARD:
         adjusted_duty = pwm_max_period - speed;
         break;
     default: while(1) {}
     }
     if (enabled == true) {
         PWMPulseWidthSet(pwm_base, pwm_out, speed);
     }
 }
void motor::set (percent_t percent_full_speed, Direction dir)
Set motor speed and direction.
Definition at line 56 of file motorpp.cpp.
References adjusted_direction(), BACKWARD, ctrl, ctrl_pin, direction, FORWARD, set(), blinker::turn_off(), and blinker::turn_on().
{
     this->direction = dir;
     switch(adjusted_direction()) {
     case FORWARD: ctrl.turn_off(ctrl_pin); break;
     case BACKWARD: ctrl.turn_on(ctrl_pin); break;
     default: while(1) {}
     }
     set(speed);
 }
void motor::set_motor_installed_backwards (bool backwards)
Denote that this motor is fastened to the robot in such a way that it requires reversed (directionally) control signals.
Definition at line 34 of file motorpp.cpp.
References motor_installed_backwards.
{
     this->motor_installed_backwards = backwards;
 }
void motor::start (void)
Enable power to the motor.
Definition at line 96 of file motorpp.cpp.
References enabled, pwm_base, and pwm_gen.
Referenced by pwm_init(), and drive::start().
                   {
     enabled = true;
     PWMGenEnable(pwm_base, pwm_gen);
 }
void motor::stop (void)
Cut all power to the motor.
Definition at line 45 of file motorpp.cpp.
References BACKWARD, direction, enabled, and set().
Referenced by drive::stop().
                  {
     if (direction == BACKWARD) {
         set(100);
     } else {
         set(0);
     }
     enabled = false;
     /* PWMGenDisable(pwm_base, pwm_gen); */
 }
Member Data Documentation
blinker motor::ctrl private
Definition at line 21 of file motorpp.hpp.
Referenced by motor(), and set().
memory_address_t motor::ctrl_base private
Definition at line 23 of file motorpp.hpp.
Referenced by motor(), and pwm_init().
memory_address_t motor::ctrl_pin private
Definition at line 24 of file motorpp.hpp.
Referenced by motor(), and set().
percent_t motor::current_speed private
Definition at line 34 of file motorpp.hpp.
Referenced by get(), reverse(), and set().
Direction motor::direction private
Definition at line 33 of file motorpp.hpp.
Referenced by adjusted_direction(), motor_init(), reverse(), set(), and stop().
uint32_t motor::duty_period private
Definition at line 32 of file motorpp.hpp.
bool motor::enabled private
Definition at line 45 of file motorpp.hpp.
Referenced by motor(), set(), start(), and stop().
bool motor::motor_installed_backwards private
Definition at line 29 of file motorpp.hpp.
Referenced by adjusted_direction(), motor(), motor_init(), and set_motor_installed_backwards().
blinker motor::pwm private
Definition at line 22 of file motorpp.hpp.
memory_address_t motor::pwm_base private
Definition at line 25 of file motorpp.hpp.
Referenced by motor(), pwm_init(), set(), and start().
memory_address_t motor::pwm_gen private
Definition at line 27 of file motorpp.hpp.
Referenced by motor(), pwm_init(), and start().
const uint16_t motor::pwm_max_period = 10000 static
Definition at line 75 of file motorpp.hpp.
Referenced by set(), and drive::steer().
memory_address_t motor::pwm_out private
Definition at line 28 of file motorpp.hpp.
Referenced by motor(), pwm_init(), and set().
uint32_t motor::pwm_period private
Definition at line 31 of file motorpp.hpp.
memory_address_t motor::pwm_pin private
Definition at line 26 of file motorpp.hpp.
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/motorpp.hpp
board-progs/autonomous-racer/common/motorpp.cpp