EE445M RTOS: lswitch Class Reference
lswitch Class Reference
#include <switchpp.hpp>
Public Member Functions
lswitch ()
lswitch (memory_address_t lswitch_base, memory_address_t lswitch_pin, semaphore *sem, timer_t timer_id, subtimer_t timer_subtimer, uint32_t switch_interrupt, uint32_t interrupt_mask=GPIO_BOTH_EDGES, bool start=false)
virtual void start (void)
virtual void stop (void)
virtual uint32_t ack (void)
void debounce (void)
uint32_t end_debounce (void)
uint32_t sample (void)
Public Member Functions inherited from interruptable
interruptable ()
Public Attributes
uint32_t debounced_data
Private Attributes
memory_address_t base
memory_address_t pin
semaphore * sem
timer tim
Detailed Description
Definition at line 16 of file switchpp.hpp.
Constructor & Destructor Documentation
lswitch::lswitch ()
Initialize lswitch.
Definition at line 15 of file switchpp.cpp.
References NULL, and sem.
                  {
     this->sem = NULL;
 }
lswitch::lswitch (memory_address_t lswitch_base, memory_address_t lswitch_pin, semaphore * sem, timer_t timer_id, subtimer_t timer_subtimer, uint32_t switch_interrupt, uint32_t interrupt_mask = GPIO_BOTH_EDGES, bool start = false)
Definition at line 20 of file switchpp.cpp.
References base, ctlsys::enable_periph(), pin, sem, start(), tim, and ctlsys::timer_timeout_from_subtimer().
{
     base = lswitch_base;
     pin = lswitch_pin;
     ctlsys::enable_periph(base);
     GPIOPinTypeGPIOInput(base, pin);
     GPIODirModeSet(base, pin, GPIO_DIR_MODE_IN);
     if ((base == GPIO_PORTF_BASE) && (pin & GPIO_PIN_0)) {
         HWREG(base + GPIO_O_LOCK) = GPIO_LOCK_KEY;
         HWREG(base + GPIO_O_CR) = 0x01;
         HWREG(base + GPIO_O_LOCK) = 0;
         GPIOPadConfigSet(base, pin, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
     }
     /* other solution: timer scoreboard */
     this->tim = timer(timer_id, timer_subtimer, TIMER_CFG_ONE_SHOT, SysCtlClockGet() / 50,
                       ctlsys::timer_timeout_from_subtimer(timer_subtimer));
     GPIOIntTypeSet(base, pin, switch_interrupt);
     IntEnable(interrupt_mask);
     this->sem = sem;
     *(this->sem) = semaphore();
     if (start) {
         this->start();
     }
 }
Member Function Documentation
uint32_t lswitch::ack (void) virtual
Implements interruptable.
Definition at line 83 of file switchpp.cpp.
References base, and pin.
Referenced by GPIOPortE_Handler().
                       {
     GPIOIntClear(base, pin);
 }
void lswitch::debounce (void)
Call this in the isr of the switch
Definition at line 65 of file switchpp.cpp.
References timer::start(), and tim.
Referenced by GPIOPortE_Handler().
{
     tim.start();
 }
uint32_t lswitch::end_debounce (void)
Call this in the isr of the switch's timer
Definition at line 74 of file switchpp.cpp.
References timer::ack(), NULL, semaphore::post(), sample(), sem, and tim.
Referenced by Timer1A_Handler().
{
     tim.ack();
     if(NULL != sem) {
         sem->post();
     }
     return sample();
 }
uint32_t lswitch::sample (void)
Return current value of the limit lswitch
Definition at line 88 of file switchpp.cpp.
References base, debounced_data, and pin.
Referenced by end_debounce().
{
     return debounced_data = GPIOPinRead(base, pin);
 }
void lswitch::start (void) virtual
Implements interruptable.
Definition at line 54 of file switchpp.cpp.
References base, and pin.
Referenced by lswitch().
                     {
     GPIOIntEnable(base, pin);
 }
void lswitch::stop (void) virtual
Implements interruptable.
Definition at line 59 of file switchpp.cpp.
References base, and pin.
                    {
     GPIOIntDisable(base, pin);
 }
Member Data Documentation
memory_address_t lswitch::base private
Definition at line 18 of file switchpp.hpp.
Referenced by ack(), lswitch(), sample(), start(), and stop().
uint32_t lswitch::debounced_data
Definition at line 40 of file switchpp.hpp.
Referenced by sample(), and switch_responder().
memory_address_t lswitch::pin private
Definition at line 19 of file switchpp.hpp.
Referenced by ack(), lswitch(), sample(), start(), and stop().
semaphore* lswitch::sem private
Definition at line 20 of file switchpp.hpp.
Referenced by end_debounce(), and lswitch().
timer lswitch::tim private
Definition at line 21 of file switchpp.hpp.
Referenced by debounce(), end_debounce(), and lswitch().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/switchpp.hpp
board-progs/autonomous-racer/common/switchpp.cpp