EE445M RTOS: critical Class Reference
critical Class Reference
#include <criticalpp.hpp>
Public Member Functions
uint32_t StartCritical (void)
void EndCritical (uint32_t primask)
Static Public Member Functions
static uint32_t static_StartCritical (void)
static void static_EndCritical (uint32_t primask)
Detailed Description
Definition at line 7 of file criticalpp.hpp.
Member Function Documentation
void critical::EndCritical (uint32_t primask) inline
Definition at line 14 of file criticalpp.hpp.
Referenced by uart::atomic_printf(), semaphore::guard(), semaphore::post(), motor::pwm_init(), semaphore::reset(), ping::sample(), semaphore::semaphore(), and semaphore::wait().
{
         asm("MSR    PRIMASK, R0\n");
     }
uint32_t critical::StartCritical (void) inline
Definition at line 9 of file criticalpp.hpp.
Referenced by uart::atomic_printf(), semaphore::guard(), semaphore::post(), motor::pwm_init(), semaphore::reset(), ping::sample(), semaphore::semaphore(), and semaphore::wait().
{
         asm("MRS    R0, PRIMASK  ;// save old status\n");
         asm("CPSID  I            ;// mask all (except faults)\n");
     }
static void critical::static_EndCritical (uint32_t primask) inline static
Definition at line 23 of file criticalpp.hpp.
Referenced by ctlsys::enable_periph().
{
         asm("MSR    PRIMASK, R0\n");
     }
static uint32_t critical::static_StartCritical (void) inline static
Definition at line 18 of file criticalpp.hpp.
Referenced by ctlsys::enable_periph().
{
         asm("MRS    R0, PRIMASK  ;// save old status\n");
         asm("CPSID  I            ;// mask all (except faults)\n");
     }
The documentation for this class was generated from the following file:
board-progs/autonomous-racer/common/criticalpp.hpp