EE445M RTOS: ping Class Reference
ping Class Reference
#include <pingpp.hpp>
Public Member Functions
ping ()
ping (memory_address_t port_base, memory_address_t port_pin, timer_t timer_id, subtimer_t timer_subtimer)
void sample (void)
virtual void start (void)
virtual void stop (void)
uint32_t handle_gpio (void)
uint32_t handle_timer (void)
semaphore * get_sem (void)
uint32_t notify (void)
int32_t average (void)
int32_t distance (void)
Public Member Functions inherited from critical
uint32_t StartCritical (void)
void EndCritical (uint32_t primask)
Public Attributes
circularbuffer< int32_t, 5 > buf
Private Attributes
semaphore sem
blinker sig
ping_status_t status
timer tim
uint32_t timer_interrupt
memory_address_t base
memory_address_t pin
uint32_t timer_signal_value
uint32_t timer_response_value
Additional Inherited Members
Static Public Member Functions inherited from critical
static uint32_t static_StartCritical (void)
static void static_EndCritical (uint32_t primask)
Detailed Description
Definition at line 28 of file pingpp.hpp.
Constructor & Destructor Documentation
ping::ping ()
Definition at line 11 of file pingpp.cpp.
 {}
ping::ping (memory_address_t port_base, memory_address_t port_pin, timer_t timer_id, subtimer_t timer_subtimer)
Definition at line 13 of file pingpp.cpp.
References base, buf, ctlsys::enable_periph(), pin, ping_not_active, sem, sig, status, tim, and timer_interrupt.
{
     status = ping_not_active;
     base = ping_base;
     pin = ping_pin;
     sig = blinker(base);
     sem = semaphore();
     buf = circularbuffer<PING_BUFFER_TYPE, PING_BUFFER_LENGTH>();
     switch(ping_timer_subtimer) {
     case TIMER_A:
     case TIMER_BOTH:
         timer_interrupt = TIMER_TIMA_TIMEOUT;
         break;
     case TIMER_B:
         timer_interrupt = TIMER_TIMB_TIMEOUT;
         break;
     default:
         while (1) {}
     }
     tim = timer(ping_timer_id, ping_timer_subtimer, TIMER_CFG_ONE_SHOT_UP, 0x0fffffe,
                 timer_interrupt);
     ctlsys::enable_periph(base);
 }
Member Function Documentation
int32_t ping::average (void)
Definition at line 135 of file pingpp.cpp.
References buf, buffer< T, N >::buf, and buffer< T, N >::len.
Referenced by distance(), and ping_handler().
                       {
     int32_t i, value;
     value = 0;
     for (i=0; i<buf.len; ++i) {
         value += buf.buf[i];
     }
     value /= buf.len;
     return value;
 }
int32_t ping::distance (void)
Definition at line 146 of file pingpp.cpp.
References average().
Referenced by can_transmitter().
{
     /* The speed of sound is 340 m/s or 29 microseconds per centimeter. */
     /* The ping travels out and back, so to find the distance of the */
     /* object we take half of the distance travelled. */
     /* bus clock is 25/2 ns */
     /* num bus clocks is in average() */
     /* time taken for round trip is average()*25/2 in ns */
     return (average() * 25) / (2492);
 }
semaphore * ping::get_sem (void)
The ping sensor's semaphore
Definition at line 130 of file pingpp.cpp.
References sem.
Referenced by main().
{
     return &sem;
 }
uint32_t ping::handle_gpio (void)
Acknowledge isr for sig.
Definition at line 107 of file pingpp.cpp.
References circularbuffer< T, N >::add(), base, buf, timer::get(), timer::load(), pin, ping_response, ping_sample_delay, ping_signal, timer::reload(), timer::start(), status, tim, timer_response_value, and timer_signal_value.
Referenced by GPIOPortD_Handler().
{
     GPIOIntClear(base, pin);
     status = ping_status_t(int(status) + 1);
     if (status == ping_signal) {
         tim.reload();
         timer_signal_value = tim.get();
         tim.start();
     } else if (status == ping_response) {
         timer_response_value = tim.get();
         buf.add(timer_response_value - timer_signal_value);
         status = ping_sample_delay;
         tim.load(SysCtlClockGet()/25);
         tim.start();
     } else {
         /* TODO: do something here? */
     }
     return 0xDEADBEEF;
 }
uint32_t ping::handle_timer (void)
Definition at line 85 of file pingpp.cpp.
References timer::ack(), ping_not_active, ping_response, ping_sample_delay, ping_signal, semaphore::post(), sem, status, and tim.
Referenced by Timer1A_Handler().
{
     tim.ack();
     if (status == ping_not_active) {
         /* TODO: remove when done debugging */
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_PIN_1);
     } else if (status == ping_signal) {
         /* TODO: remove when done debugging */
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2);
     } else if (status == ping_response) {
         /* TODO: remove when done debugging */
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, GPIO_PIN_3);
     } else if (status == ping_sample_delay) {
         status = ping_not_active;
     }
     /* either a timeout happened or the sensor delay period has been
        achieved */
     sem.post();
 }
uint32_t ping::notify (void)
Alert object that the isr watching both edges of sig has been triggered.
void ping::sample (void)
Warning
this device should not be sampled more than once every 200 micro-seconds
Definition at line 45 of file pingpp.cpp.
References base, delay::count(), critical::EndCritical(), ctlsys::gpio_int_disable(), ctlsys::gpio_int_enable(), ctlsys::periph_to_int(), pin, ping_not_active, sig, critical::StartCritical(), status, blinker::turn_off(), and blinker::turn_on().
Referenced by ping_handler().
                   {
     if (status == ping_not_active) {
         uint32_t intstatus = StartCritical();
         /* Disable interrupts in SIG */
         ctlsys::gpio_int_disable(base, pin);
         IntDisable(ctlsys::periph_to_int(base));
         /* Set Ping))) SIG to output */
         GPIOPinTypeGPIOOutput(base, pin);
         sig.turn_on(pin);
         /* Set SIG high for 5usec */
         delay::count(1);
         sig.turn_off(pin);
         /* Set Ping))) SIG to input */
         GPIOPinTypeGPIOInput(base, pin);
         GPIOIntTypeSet(base, pin, GPIO_BOTH_EDGES);
         delay::count(200);
         /* Enable interupts on SIG */
         ctlsys::gpio_int_enable(base, pin, true);
         IntEnable(ctlsys::periph_to_int(base));
         EndCritical(intstatus);
     }
 }
void ping::start (void) virtual
Start the timer monitoring sig.
Definition at line 74 of file pingpp.cpp.
References semaphore::post(), and sem.
Referenced by ping_handler().
                  {
     /* start the chain */
     sem.post();
 }
void ping::stop (void) virtual
Stop the timer monitoring sig.
Definition at line 80 of file pingpp.cpp.
References semaphore::reset(), and sem.
                 {
     sem.reset();
 }
Member Data Documentation
memory_address_t ping::base private
Definition at line 35 of file pingpp.hpp.
Referenced by handle_gpio(), ping(), and sample().
circularbuffer< int32_t , 5 > ping::buf
Definition at line 66 of file pingpp.hpp.
Referenced by average(), handle_gpio(), and ping().
memory_address_t ping::pin private
Definition at line 36 of file pingpp.hpp.
Referenced by handle_gpio(), ping(), and sample().
semaphore ping::sem private
Definition at line 30 of file pingpp.hpp.
Referenced by get_sem(), handle_timer(), ping(), start(), and stop().
blinker ping::sig private
Definition at line 31 of file pingpp.hpp.
Referenced by ping(), and sample().
ping_status_t ping::status private
Definition at line 32 of file pingpp.hpp.
Referenced by handle_gpio(), handle_timer(), ping(), and sample().
timer ping::tim private
Definition at line 33 of file pingpp.hpp.
Referenced by handle_gpio(), handle_timer(), and ping().
uint32_t ping::timer_interrupt private
Definition at line 34 of file pingpp.hpp.
Referenced by ping().
uint32_t ping::timer_response_value private
Definition at line 39 of file pingpp.hpp.
Referenced by handle_gpio().
uint32_t ping::timer_signal_value private
Definition at line 38 of file pingpp.hpp.
Referenced by handle_gpio().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/pingpp.hpp
board-progs/autonomous-racer/common/pingpp.cpp