EE445M RTOS: shell Class Reference
shell Class Reference
Shell
#include <shellpp.hpp>
Public Member Functions
shell ()
shell (uart *u)
shell (uart *u, semaphore *m_start, semaphore *m_stop)
void clear_buffer ()
void set_ps1 (char *new_ps1)
void print_ps1 ()
bool type (char ch)
void backspace (void)
void accept (char ch)
exit_status_t execute_command ()
Private Member Functions
int32_t ustrncmp (const char *, const char *, uint32_t)
void * memset (void *b, int c, int len)
uint32_t strlen (const char *)
void init_ps1 (void)
void init (void)
Static Private Member Functions
static exit_status_t help_info (const char *args)
static exit_status_t doctor (const char *args)
static exit_status_t witch (const char *args)
static exit_status_t jester (const char *args)
static exit_status_t motor_start (const char *args)
static exit_status_t motor_stop (const char *args)
static void ustrcpy (char *dest, const char *source)
Private Attributes
uart * uart0
buffer< char, 32 > buf
char ps1 [4+1]
Static Private Attributes
static char system_command_names [2][10]
static sys_cmd system_command_funcs [2]
static semaphore * m_start
static semaphore * m_stop
Detailed Description
Definition at line 31 of file shellpp.hpp.
Constructor & Destructor Documentation
shell::shell ()
Definition at line 81 of file shellpp.cpp.
References init().
              {
     init();
 }
shell::shell (uart * u)
Definition at line 86 of file shellpp.cpp.
References init(), and uart0.
                     {
     uart0 = u;
     init();
 }
shell::shell (uart * u, semaphore * m_start, semaphore * m_stop)
Definition at line 92 of file shellpp.cpp.
References init(), m_start, m_stop, and uart0.
{
     uart0 = u;
     m_start = m_start;
     m_stop = m_stop;
     init();
 }
Member Function Documentation
void shell::accept (char ch)
Accept a char, shell will call or appropriately.
Definition at line 174 of file shellpp.cpp.
References backspace(), execute_command(), and type().
Referenced by shell_handler().
{
     switch(ch) {
     case SC_CR:
         execute_command();
         break;
     case 127:
     case SC_BACKSPACE:
         backspace();
         break;
     default:
         type(ch);
         break;
     }
 }
void shell::backspace (void)
Remove a char from the shell buffer.
Definition at line 192 of file shellpp.cpp.
References uart::atomic_printf(), buf, buffer< T, N >::get(), and uart0.
Referenced by accept().
                       {
     bool ok;
     buf.get(ok);
     if (ok) {
         uart0->atomic_printf("\b \b");
     }
 }
void shell::clear_buffer ()
Clear the shell buffer.
Definition at line 142 of file shellpp.cpp.
References buf, and buffer< T, N >::clear().
{
     buf.clear();
 }
exit_status_t shell::doctor (const char * args) static private
Definition at line 21 of file shellpp.cpp.
References blink, EXIT_SUCCESS, PIN_RED, and blinker::toggle().
Referenced by execute_command().
{
     blinker blink = blinker(GPIO_PORTF_BASE);
     blink.toggle(PIN_RED);
     return EXIT_SUCCESS;
 }
exit_status_t shell::execute_command ()
Execute this command.
You know how I know this shell sucks? You can't even do this, because uart0 is a non-static context and this is a static context. eff this implementation of system
Definition at line 228 of file shellpp.cpp.
References uart::atomic_printf(), buf, buffer< T, N >::buf, doctor(), EXIT_SUCCESS, jester(), buffer< T, N >::length(), motor_start(), motor_stop(), print_ps1(), shell_command_is, uart0, and witch().
Referenced by accept().
{
     /* Null terminate to separate the cmd from the args */
     uint8_t len = buf.length();
     uint8_t idx = 0;
     while((idx < len) && (buf.buf[idx] != ' ')) {
         ++idx;
     }
     buf.buf[idx] = 0;
     /* Clear some space between the user input and this cmd output */
     uart0->atomic_printf("\r\n");
     exit_status_t exit_code = (exit_status_t) 0xDEADBEEF;
     const char* args = &buf.buf[idx+1];
     /* Waldo says this line requires the extra char to be a 0 */
     if(shell_command_is("doctor")) {
         exit_code = doctor(args);
     } else if(shell_command_is("witch")) {
         exit_code = witch(args);
     } else if(shell_command_is("jester")) {
         exit_code = jester(args);
         /* begin motor control commands */
     } else if(shell_command_is("start")) {
         exit_code = motor_start(args);
     } else if(shell_command_is("stop")) {
         exit_code = motor_stop(args);
     } else {
         uart0->atomic_printf("%s is not a recognized command.\n\r", buf.buf);
     }
 #ifdef SHELL_VERBOSE
     if (exit_code != EXIT_SUCCESS) {
         uart0->atomic_printf("\n\rnonzero exit code: %d", exit_code);
     }
 #endif
     /* Prepare for the next command */
     print_ps1();
     return exit_code;
 }
static exit_status_t shell::help_info (const char * args) static private
void shell::init (void) private
Common code between constructors
Definition at line 75 of file shellpp.cpp.
References buf, and init_ps1().
Referenced by shell().
                  {
     buf = buffer<char, SHELL_BUFFER_LENGTH>();
     init_ps1();
 }
void shell::init_ps1 (void) private
Definition at line 102 of file shellpp.cpp.
References print_ps1(), and ps1.
Referenced by init().
                      {
     /* KLUDGE: shitty way to set PS1 */
     ps1[0] = '>';
     ps1[1] = ' ';
     ps1[2] = ' ';
     ps1[3] = 0;
     print_ps1();
 }
exit_status_t shell::jester (const char * args) static private
Definition at line 35 of file shellpp.cpp.
References blink, EXIT_SUCCESS, PIN_BLUE, and blinker::toggle().
Referenced by execute_command().
{
     blinker blink = blinker(GPIO_PORTF_BASE);
     blink.toggle(PIN_BLUE);
     return EXIT_SUCCESS;
 }
void * shell::memset (void * b, int c, int len) private
Definition at line 113 of file shellpp.cpp.
{
     int i;
     unsigned char *p = (unsigned char *) b;
     i = 0;
     while(len > 0) {
         *p = c;
         ++p;
         --len;
     }
     return b;
 }
exit_status_t shell::motor_start (const char * args) static private
Definition at line 201 of file shellpp.cpp.
References EXIT_SUCCESS, and semaphore::post().
Referenced by execute_command().
{
     shell::m_start->post();
     return EXIT_SUCCESS;
 }
exit_status_t shell::motor_stop (const char * args) static private
Definition at line 207 of file shellpp.cpp.
References EXIT_SUCCESS, and semaphore::post().
Referenced by execute_command().
{
     shell::m_stop->post();
     return EXIT_SUCCESS;
 }
void shell::print_ps1 ()
Print the PS1.
Note
has the side effect of clearing the shell buffer
Definition at line 153 of file shellpp.cpp.
References uart::atomic_printf(), buf, buffer< T, N >::clear(), ps1, and uart0.
Referenced by execute_command(), and init_ps1().
                       {
     buf.clear();
     uart0->atomic_printf("\n\n\r%s", ps1);
 }
void shell::set_ps1 (char * new_ps1)
Set the PS1.
Definition at line 147 of file shellpp.cpp.
References ps1, strlen(), and umemcpy().
{
     umemcpy(ps1, new_ps1, strlen(new_ps1));
 }
uint32_t shell::strlen (const char * s) private
Return the length of a null-terminated string.
Definition at line 126 of file shellpp.cpp.
Referenced by set_ps1().
{
     uint32_t len = 0;
     while(s[len]) { ++len; }
     return(len);
 }
bool shell::type (char ch)
Add a char to the shell buffer.
Definition at line 159 of file shellpp.cpp.
References buffer< T, N >::add(), uart::atomic_printf(), buf, buffer< T, N >::full(), and uart0.
Referenced by accept().
{
     bool ret;
     if (buf.full()) {
         ret = false;
     } else {
         ret = true;
         buf.add((const char) ch);
     }
     if(ret) {
     uart0->atomic_printf("%c", ch);
     }
     return ret;
 }
void shell::ustrcpy (char * dest, const char * source) static private
Definition at line 66 of file shellpp.cpp.
{
     uint32_t i = 0;
     while (1) {
         dest[i] = source[i];
         if (source[i++] == '\0') { break; }
     }
 }
int32_t shell::ustrncmp (const char * s1, const char * s2, uint32_t n) private
Execute a system command.
Note
this implementation does not compare length, thus unique abbreviations are fair game (gdb style)
Definition at line 44 of file shellpp.cpp.
{
     /* Loop while there are more characters. */
     while(n) {
         /* If we reached a NULL in both strings, they must be equal so
          * we end the comparison and return 0 */
         if((!*s1 || (*s1 == ' ')) && (!*s2 || (*s2 == ' '))) {
             return(0);
         }
         if(*s2 < *s1) { return(1); }
         if(*s1 < *s2) { return(-1); }
         s1++;
         s2++;
         n--;
     }
     /* If we fall out, the strings must be equal for at least the
      * first n characters so return 0 to indicate this. */
     return 0;
 }
exit_status_t shell::witch (const char * args) static private
Definition at line 28 of file shellpp.cpp.
References blink, EXIT_SUCCESS, PIN_GREEN, and blinker::toggle().
Referenced by execute_command().
{
     blinker blink = blinker(GPIO_PORTF_BASE);
     blink.toggle(PIN_GREEN);
     return EXIT_SUCCESS;
 }
Member Data Documentation
buffer<char, 32 > shell::buf private
Definition at line 34 of file shellpp.hpp.
Referenced by backspace(), clear_buffer(), execute_command(), init(), print_ps1(), and type().
semaphore * shell::m_start static private
Definition at line 60 of file shellpp.hpp.
Referenced by shell().
semaphore * shell::m_stop static private
Definition at line 61 of file shellpp.hpp.
Referenced by shell().
char shell::ps1[4+1] private
Definition at line 36 of file shellpp.hpp.
Referenced by init_ps1(), print_ps1(), and set_ps1().
sys_cmd shell::system_command_funcs static private
Definition at line 54 of file shellpp.hpp.
char shell::system_command_names static private
Definition at line 53 of file shellpp.hpp.
uart* shell::uart0 private
Definition at line 33 of file shellpp.hpp.
Referenced by backspace(), execute_command(), print_ps1(), shell(), and type().
The documentation for this class was generated from the following files:
board-progs/autonomous-racer/common/shellpp.hpp
board-progs/autonomous-racer/common/shellpp.cpp