EE445M RTOS: lib/libclock/clock.c File Reference
clock.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "clock.h"
Functions
shape * CHToShape (clockhand *ch)
clockhand * CHCreateClockHand (point *center, ushort radius, uchar type)
void CHCalculateAngle (clockhand *ch, clocktime *tm)
void CHDestroyClockHand (clockhand *ch)
void CHDestroyClockHandShape (clockhand *ch)
clockface * CFCreateClockFace (ushort numHands, clockhand **chs, clocktime *th)
void CFDestroyClockFace (clockface *cf)
clockhand * CHDuplicateClockHand (clockhand *ch)
void CFUpdateTime (clockface *cf)
shape ** CFToShapes (clockface *cf)
void CFDestroyShapes (clockface *cf)
Function Documentation
clockface* CFCreateClockFace (ushort numHands, clockhand ** chs, clocktime * th)
Definition at line 91 of file clock.c.
References clockface::hands, clockface::numHands, and clockface::timehandle.
Referenced by demonstrateClock().
{
   ushort i;
   clockface* cf = (clockface*) calloc(1, sizeof(clockface));
   /* Moved to CFToShapes */
   /* cf->shapeBuffer = (shape**)malloc(numHands * sizeof(shape*)); */
   cf->numHands = numHands;
   /* Shallow copy of clockhands */
   cf->hands = (clockhand**) calloc(numHands, sizeof(clockhand*));
   for(i=0; i < numHands; ++i) {
       cf->hands[i] = chs[i];
   }
   /* Don't deep copy timehandle, we need it for the interrupt */
   cf->timehandle = th;
   return cf;
 }
void CFDestroyClockFace (clockface * cf)
Definition at line 112 of file clock.c.
References clockface::hands.
Referenced by demonstrateClock().
{
   free(cf->hands);
   free(cf);
 }
void CFDestroyShapes (clockface * cf)
Definition at line 146 of file clock.c.
References CHDestroyClockHandShape(), clockface::hands, clockface::numHands, and clockface::shapeBuffer.
Referenced by demonstrateClock().
{
   ushort i;
   for(i=0; i<cf->numHands; ++i) {
     /* free(cf->shapeBuffer[i]); */
     CHDestroyClockHandShape(cf->hands[i]);
   }
   free(cf->shapeBuffer);
 }
shape** CFToShapes (clockface * cf)
Definition at line 135 of file clock.c.
References CHToShape(), clockface::hands, clockface::numHands, and clockface::shapeBuffer.
Referenced by demonstrateClock().
{
   ushort i;
   cf->shapeBuffer = (shape**)malloc(cf->numHands * sizeof(shape*));
   for(i=0; i<cf->numHands; ++i) {
     cf->shapeBuffer[i] = CHToShape(cf->hands[i]);
   }
   return cf->shapeBuffer;
 }
void CFUpdateTime (clockface * cf)
Definition at line 128 of file clock.c.
References CHCalculateAngle(), clockface::hands, clockface::numHands, and clockface::timehandle.
Referenced by demonstrateClock().
{
   ushort i;
   for(i=0; i<cf->numHands; ++i) {
     CHCalculateAngle(cf->hands[i], cf->timehandle);
   }
 }
void CHCalculateAngle (clockhand * ch, clocktime * tm)
Definition at line 46 of file clock.c.
References clockhand::angle, CH_HOURS, CH_MINUTES, CH_MS, CH_SECONDS, clocktime::hours, clocktime::minutes, clocktime::ms, clocktime::seconds, and clockhand::type.
Referenced by CFUpdateTime().
{
   ushort tmpHours;
   switch(ch->type) {
   case CH_HOURS:
     tmpHours = tm->hours;
     while(tmpHours > 12) {
       tmpHours -= 12;
     }
     ch->angle = (short)(30*tmpHours + (tm->minutes)/2.0);
     break;
   case CH_MINUTES:
     ch->angle = (short)(6.0*tm->minutes + tm->seconds/10.0);
     break;
   case CH_SECONDS:
     ch->angle = 6*tm->seconds + 3.0/500*tm->ms;
     break;
   case CH_MS:
     ch->angle = (short)((9/25.0)*(tm->ms));
     break;
   }
   /* printf("--- ANGLE FOR %i: %i --- %i\n", ch->type, ch->angle, CH_SECONDS); */
 }
clockhand* CHCreateClockHand (point * center, ushort radius, uchar type)
Definition at line 32 of file clock.c.
References clockhand::angle, clockhand::center, clockhand::pointOnCircumference, clockhand::radius, shape_duplicate_point(), and clockhand::type.
Referenced by demonstrateClock().
{
   clockhand* ch = (clockhand*) calloc(1, sizeof(clockhand));
   ch->radius = radius;
   ch->center = shape_duplicate_point(center);
   ch->type = type;
   ch->angle = 0;
   ch->pointOnCircumference = shape_duplicate_point(center);
   return ch;
 }
void CHDestroyClockHand (clockhand * ch)
Definition at line 71 of file clock.c.
References clockhand::center, and clockhand::pointOnCircumference.
Referenced by demonstrateClock().
{
   /* SHDestroyShape(ch->shapeBuffer); */
   /* free(ch->shapeBuffer); */
   free(ch->pointOnCircumference);
   free(ch->center);
   free(ch);
 }
void CHDestroyClockHandShape (clockhand * ch)
Definition at line 80 of file clock.c.
References shape::points, and clockhand::shapeBuffer.
Referenced by CFDestroyShapes().
{
   /* point* p; */
   /* p = SHCreatePoint(p->x, p->y, p->shade); */
   /* SHDestroyShape(ch->shapeBuffer); */
   /* ch->center = p; */
   free(ch->shapeBuffer->points);
   free(ch->shapeBuffer);
 }
clockhand* CHDuplicateClockHand (clockhand * ch)
Definition at line 117 of file clock.c.
References clockhand::center, clockhand::pointOnCircumference, clockhand::radius, shape_duplicate_point(), shape_duplicate_shape(), clockhand::shapeBuffer, and clockhand::type.
{
     clockhand* dup = (clockhand*) calloc(1, sizeof(clockhand));
     dup->radius = ch->radius;
     dup->center = shape_duplicate_point(ch->center);
     dup->type = ch->type;
     dup->shapeBuffer = shape_duplicate_shape(ch->shapeBuffer);
     dup->pointOnCircumference = shape_duplicate_point(ch->pointOnCircumference);
     return dup;
 }
shape* CHToShape (clockhand * ch)
Definition at line 15 of file clock.c.
References clockhand::angle, clockhand::center, CH_ANGLE_OFFSET, PI_PI, clockhand::pointOnCircumference, clockhand::radius, shape_create(), clockhand::shapeBuffer, point::x, and point::y.
Referenced by CFToShapes().
{
   float x, y;
   x = cosf((ch->angle - CH_ANGLE_OFFSET) * PI_PI / 180) * ch->radius;
   y = sinf((ch->angle - CH_ANGLE_OFFSET) * PI_PI / 180) * ch->radius;
   /* avoid underflow (subtracting too much from an unsigned number) */
   if(-x > ch->center->x) {x = -ch->center->x;}
   if(-y > ch->center->y) {y = -ch->center->y;}
   ch->pointOnCircumference->x = ch->center->x+x;
   ch->pointOnCircumference->y = ch->center->y+y;
   ch->shapeBuffer = shape_create(2, ch->center, ch->pointOnCircumference);
   return ch->shapeBuffer;
 }