EE445M RTOS: lib/libconsole/console_framebuffer.h File Reference
console_framebuffer.h File Reference
Functions
void printFramebuffer (unsigned char *fb)
Function Documentation
void printFramebuffer (unsigned char * fb)
Definition at line 5 of file console_framebuffer.c.
References OLED_HEIGHT, OLED_WIDTH, RIT_FB_WIDTH, SHADE_0, SHADE_1, SHADE_2, and SHADE_3.
Referenced by demonstrateClock(), demonstrateDrawShapes(), demonstrateDrawString(), and main().
{
   unsigned char i, j, a, b;
   for(j=0; j<OLED_HEIGHT; ++j) {
     for(i=0; i<OLED_WIDTH; i+=2) {
       a = (fb[(i/2)+j*RIT_FB_WIDTH] >> 4);
       b = (fb[(i/2)+j*RIT_FB_WIDTH] & 0x0F);
       switch(a/4) {
       case 0: a=SHADE_0; break;
       case 1: a=SHADE_1; break;
       case 2: a=SHADE_2; break;
       case 3: a=SHADE_3; break;
       }
       switch(b/4) {
       case 0: b=SHADE_0; break;
       case 1: b=SHADE_1; break;
       case 2: b=SHADE_2; break;
       case 3: b=SHADE_3; break;
       }
       printf("%c%c", a, b);
     }
     printf("\n");
   }
 }