EE 445M: lib/libgraphics2d/framebuffer.h File Reference
lib/libgraphics2d/framebuffer.h File Reference
#include <stdarg.h>
#include "g2d_defines.h"
#include "shape.h"
Defines
#define max_pixel_width_of_long(x, y) (max_uc(_FBPixelWidthOfLong(x), _FBPixelWidthOfLong(y)))
#define max_pixel_height_of_long(x, y) (max_uc(_FBPixelHeightOfLong(x),_FBPixelHeightOfLong(y)))
Typedefs
typedef char ** framebuffer
Functions
unsigned char max_uc (unsigned char one, unsigned char two)
char * itoa (int i, char *buffer, uchar length)
framebuffer FBInit (void)
void FBDestroy (framebuffer fb)
void FBDrawString (framebuffer fb, point *top_left_corner, char *string)
void FBDrawStringAnonPt (framebuffer fb, point *top_left_corner, char *string)
void FBEraseString (framebuffer fb, point *top_left_corner, char *string)
void FBEraseStringAnonPt (framebuffer fb, point *top_left_corner, char *string)
void FBEraseChar (framebuffer, point *top_left_corner)
void _FBDrawString (framebuffer fb, point *top_left_corner, char *string)
void FBDrawShape (framebuffer fb, shape *sh)
void FBEraseShape (framebuffer fb, shape *sh)
void FBDrawMultipleShapes (framebuffer fb, ushort numShapes,...)
void FBDrawShapeArr (framebuffer fb, ushort numShapes, shape **shapeArr)
void FBEraseShapeArr (framebuffer fb, ushort numShapes, shape **shapeArr)
void _FBDrawShape (framebuffer fb, shape *sh, shade_t shade)
void FBSetPixel (framebuffer fb, uchar x, uchar y, shade_t shade)
void FBClearPixel (framebuffer fb, uchar x, uchar y)
void FBDrawLine (framebuffer fb, point *a, point *b, shade_t shade)
void FBDrawAnonLine (framebuffer fb, point *a, point *b, shade_t shade)
void FBEraseLine (framebuffer fb, point *pta, point *ptb)
void FBEraseAnonLine (framebuffer fb, point *a, point *b)
void _FBDrawLine (framebuffer fb, point *a, point *b, shade_t shade)
void FBDrawCircle (framebuffer fb, circle *c)
void FBDrawEllipse (framebuffer fb, point *center, ushort x_radius, ushort y_radius, shade_t shade)
void FBDrawEllipseFill (framebuffer fb, point *center, ushort x_radius, ushort y_radius, shade_t shade)
void _FBPlotFourEllipsePoints (framebuffer fb, point *center, ushort x, ushort y)
void _FBFillFourEllipsePoints (framebuffer fb, point *center, ushort x, ushort y)
pixel_t _FBPixelWidthOfLong (long l)
pixel_t _FBPixelHeightOfLong (long l)
pixel_t _FBPixelWidthOfString (char *str)
void FBPrintPointToConsole (point *p)
void FBPrintPointToConsoleWithoutNewline (point *p)
Variables
static const unsigned char valvanoFont [129][5]
Define Documentation
#define max_pixel_height_of_long (x, y) (max_uc(_FBPixelHeightOfLong(x),_FBPixelHeightOfLong(y)))
Definition at line 161 of file framebuffer.h.
Referenced by FBDrawGraph(), FBEraseGraph(), and FBEraseGraphData().
#define max_pixel_width_of_long (x, y) (max_uc(_FBPixelWidthOfLong(x), _FBPixelWidthOfLong(y)))
Definition at line 160 of file framebuffer.h.
Referenced by FBDrawGraph(), FBEraseGraph(), and FBEraseGraphData().
Typedef Documentation
typedef char** framebuffer
Definition at line 25 of file framebuffer.h.
Function Documentation
void _FBDrawLine (framebuffer fb, point * a, point * b, shade_t shade)
Definition at line 214 of file framebuffer.c.
References FBSetPixel(), SHDestroyPoint, SHDuplicatePoint, point::x, and point::y.
Referenced by FBDrawAnonLine(), FBDrawLine(), FBEraseAnonLine(), and FBEraseLine().
{
  point* a;
  point* b;
  int dx, dy, sx, sy, e2, err;
  a = SHDuplicatePoint(pta);
  b = SHDuplicatePoint(ptb);
  dx = abs(b->x-a->x); sx = (a->x < b->x) ? 1 : -1;
  dy = abs(b->y-a->y); sy = (a->y < b->y) ? 1 : -1;
  err = (dx>dy ? dx : -dy)/2;
  for(;;) {
    FBSetPixel(fb, a->x, a->y, shade);
    if (a->x == b->x && a->y == b->y) {break;}
    e2 = err;
    if (e2 >-dx) {err -= dy; a->x += sx;}
    if (e2 < dy) {err += dx; a->y += sy;}
  }
  SHDestroyPoint(a);
  SHDestroyPoint(b);
}
void _FBDrawShape (framebuffer fb, shape * sh, shade_t shade)
Definition at line 85 of file framebuffer.c.
References FBDrawLine(), FBSetPixel(), shape::numPoints, shape::points, point::x, and point::y.
Referenced by FBDrawShape(), and FBEraseShape().
{
  unsigned short p;
  for(p=0; p < sh->numPoints; ++p) {
    FBSetPixel(fb, sh->points[p]->x, sh->points[p]->y, shade);
    /* TODO: add gradient between points */
    if (p > 0) {
      FBDrawLine(fb, sh->points[p-1], sh->points[p], shade);
    }
  }
  /* Enclose the figure */
  if(p>1) {
    FBDrawLine(fb, sh->points[0], sh->points[p-1], shade);
  }
}
void _FBDrawString (framebuffer fb, point * top_left_corner, char * string)
Definition at line 452 of file framebuffer.c.
References FBSetPixel(), point::shade, SHDestroyPoint, SHDuplicatePoint, valvanoFont, point::x, and point::y.
Referenced by FBDrawString(), FBDrawStringAnonPt(), and FBEraseString().
{
  uchar active, col, row, mask;
  point* pen = SHDuplicatePoint(top_left_corner);
  while(*string != null) {
    for(col=0; col < VALVANO_FONT_WIDTH; ++col) {
      mask = 0x01;
      if (pen->x+col >= FB_WIDTH) {break;}
      for(row=0; row < VALVANO_FONT_HEIGHT; ++row) {
        if (pen->y+row >= FB_HEIGHT) {break;}
        active = mask & valvanoFont[*string][col];
        FBSetPixel(fb, pen->x + col, pen->y + row, active ? pen->shade : 0);
        mask = mask << 1;
      }
    }
    pen->x += VALVANO_FONT_WIDTH + VALVANO_FONT_KERNING;
    ++string;
  }
  SHDestroyPoint(pen);
}
void _FBFillFourEllipsePoints (framebuffer fb, point * center, ushort x, ushort y)
Definition at line 347 of file framebuffer.c.
References FBSetPixel(), point::shade, point::x, and point::y.
Referenced by FBDrawEllipseFill().
{
  int i;
  for(i = -x; i <= x; ++i) {
    FBSetPixel(fb, center->x + i, center->y + y, center->shade);
    FBSetPixel(fb, center->x + i, center->y - y, center->shade);
  }
}
pixel_t _FBPixelHeightOfLong (long l)
Definition at line 293 of file graph_framebuffer.c.
{
  // 2 pixels because we want one to pad the top and one on the bottom
  return VALVANO_FONT_LINE_SPACING + VALVANO_FONT_HEIGHT;
}
pixel_t _FBPixelWidthOfLong (long l)
Definition at line 283 of file graph_framebuffer.c.
{
  // 2 pixels because we want one to pad the front and one on the back
  return VALVANO_FONT_KERNING + (log(l) * VALVANO_FONT_WIDTH);
}
pixel_t _FBPixelWidthOfString (char * str)
Definition at line 274 of file graph_framebuffer.c.
{
  return VALVANO_FONT_KERNING + ((VALVANO_FONT_KERNING + VALVANO_FONT_WIDTH) * strlen(str));
}
void _FBPlotFourEllipsePoints (framebuffer fb, point * center, ushort x, ushort y)
Definition at line 329 of file framebuffer.c.
References FBSetPixel(), point::shade, point::x, and point::y.
Referenced by FBDrawEllipse().
{
  FBSetPixel(fb, center->x + x, center->y + y, center->shade);
  FBSetPixel(fb, center->x - x, center->y + y, center->shade);
  FBSetPixel(fb, center->x - x, center->y - y, center->shade);
  FBSetPixel(fb, center->x + x, center->y - y, center->shade);
}
void FBClearPixel (framebuffer fb, uchar x, uchar y)
Definition at line 177 of file framebuffer.c.
References FBSetPixel().
{
  FBSetPixel(fb, x, y, FB_COLOR_ERASE);
}
void FBDestroy (framebuffer fb)
Definition at line 37 of file framebuffer.c.
Referenced by demonstrateClock(), demonstrateDrawShapes(), and demonstrateDrawString().
{
  unsigned char i;
  for(i = 0; i < OLED_WIDTH; ++i) {
    free(fb[i]);
  }
  free(fb);
}
void FBDrawAnonLine (framebuffer fb, point * a, point * b, shade_t shade)
Definition at line 496 of file framebuffer.c.
References _FBDrawLine(), and SHDestroyPoint.
Referenced by _FBDrawGraphBounds(), and _FBDrawGraphData().
{
  _FBDrawLine(fb, a, b, shade);
  SHDestroyPoint(a);
  SHDestroyPoint(b);
}
void FBDrawCircle (framebuffer fb, circle * c)
Definition at line 244 of file framebuffer.c.
References circle::center, FBDrawEllipse(), circle::radius, and point::shade.
Referenced by demonstrateClock().
{
  FBDrawEllipse(fb, c->center, c->radius, c->radius, c->center->shade);
}
void FBDrawEllipse (framebuffer fb, point * center, ushort x_radius, ushort y_radius, shade_t shade)
Definition at line 258 of file framebuffer.c.
References _FBPlotFourEllipsePoints().
Referenced by FBDrawCircle().
{
  ushort x, y;
  int xx, yy, xx2, yy2, dx, dy, stop_x, stop_y, error;
  x = x_radius;
  y = 0;
  xx = x_radius * x_radius; // width^2
  yy = y_radius * y_radius; // height^2
  xx2 = xx*2;
  yy2 = yy*2;
  dx = yy * (1 - 2*x_radius);
  dy = xx;
  stop_x = yy*2*x_radius;
  stop_y = 0;
  error = 0;
  while (stop_x > stop_y) {
    _FBPlotFourEllipsePoints(fb, center, x, y);
    ++y;
    stop_y += xx2;
    error += dy;
    dy += xx2;
    if (2*error + dx > 0) {
      --x;
      stop_x -= yy2;
      error += dx;
      dx += yy2;
    }
  }
  /* First set of points is done, now plot the second set */
  x = 0;
  y = y_radius;
  dx = yy;
  dy = xx * (1 - 2*y_radius);
  error = 0;
  stop_x = 0;
  stop_y = xx2*y_radius;
  while (stop_x <= stop_y) {
    _FBPlotFourEllipsePoints(fb, center, x, y);
    x++;
    stop_x += yy2;
    error += dx;
    dx += yy2;
    if (2*error + dy > 0) {
      --y;
      stop_y -= xx2;
      error += dy;
      dy += xx2;
    }
  }
}
void FBDrawEllipseFill (framebuffer fb, point * center, ushort x_radius, ushort y_radius, shade_t shade)
Definition at line 364 of file framebuffer.c.
References _FBFillFourEllipsePoints(), FBSetPixel(), point::shade, point::x, and point::y.
Referenced by demonstrateDrawShapes().
{
  ushort x, y;
  int xx, yy, xx2, yy2, dx, dy, last_y_filled, stop_x, stop_y, error, i;
  xx = x_radius * x_radius; // width^2
  yy = y_radius * y_radius; // height^2
  xx2 = xx*2;
  yy2 = yy*2;
  error = 0;
  // fill the horizontal diameter
  for (i = -x_radius; i <= x_radius; ++i) {
    FBSetPixel(fb, center->x + i, center->y, center->shade);
  }
  /* First set of points is done, now plot the second set */
  x = 0;
  y = y_radius;
  dx = yy;
  dy = xx * (1 - 2*y_radius);
  stop_x = 0;
  stop_y = xx2*y_radius;
  // OPTIONAL OPTIMIZE: this loop
  last_y_filled = y;
  while (stop_x <= stop_y) {
    if (y != last_y_filled) {
      _FBFillFourEllipsePoints(fb, center, x, y);
      last_y_filled = y;
    }
    x++;
    stop_x += yy2;
    error += dx;
    dx += yy2;
    if (2*error + dy > 0) {
      --y;
      stop_y -= xx2;
      error += dy;
      dy += xx2;
    }
  }
}
void FBDrawLine (framebuffer fb, point * a, point * b, shade_t shade)
Definition at line 189 of file framebuffer.c.
References _FBDrawLine().
Referenced by _FBDrawShape(), and demonstrateDrawShapes().
{
  _FBDrawLine(fb, pta, ptb, shade);
}
void FBDrawMultipleShapes (framebuffer fb, ushort numShapes, ...)
Definition at line 109 of file framebuffer.c.
References FBDrawShape().
{
  unsigned char i;
  va_list args;
  va_start(args, numShapes);
  for(i=0; i < numShapes; ++i) {
    FBDrawShape(fb, va_arg(args, shape*));
  }
  va_end(args);                 /* clean up the list */
}
void FBDrawShape (framebuffer fb, shape * sh)
Definition at line 56 of file framebuffer.c.
References _FBDrawShape(), shape::points, and point::shade.
Referenced by FBDrawMultipleShapes(), and FBDrawShapeArr().
{
  when (sh->points[0] != null) {
    _FBDrawShape(fb, sh, sh->points[0]->shade);
  }
}
void FBDrawShapeArr (framebuffer fb, ushort numShapes, shape ** shapeArr)
Definition at line 128 of file framebuffer.c.
References FBDrawShape().
Referenced by demonstrateClock(), and demonstrateDrawShapes().
{
  unsigned char i;
  for(i=0; i < numShapes; ++i) {
    FBDrawShape(fb, shapeArr[i]);
  }
}
void FBDrawString (framebuffer fb, point * top_left_corner, char * string)
Definition at line 422 of file framebuffer.c.
References _FBDrawString().
Referenced by demonstrateClock(), and demonstrateDrawString().
{
  _FBDrawString(fb, top_left_corner, string);
}
void FBDrawStringAnonPt (framebuffer fb, point * top_left_corner, char * string)
Definition at line 410 of file framebuffer.c.
References _FBDrawString().
{
  _FBDrawString(fb, top_left_corner, string);
  free(top_left_corner);
}
void FBEraseAnonLine (framebuffer fb, point * a, point * b)
Definition at line 511 of file framebuffer.c.
References _FBDrawLine(), and SHDestroyPoint.
{
  _FBDrawLine(fb, a, b, FB_COLOR_ERASE);
  SHDestroyPoint(a);
  SHDestroyPoint(b);
}
void FBEraseChar (framebuffer , point * top_left_corner)
void FBEraseLine (framebuffer fb, point * pta, point * ptb)
Definition at line 200 of file framebuffer.c.
References _FBDrawLine().
{
  _FBDrawLine(fb, pta, ptb, FB_COLOR_ERASE);
}
void FBEraseShape (framebuffer fb, shape * sh)
Definition at line 72 of file framebuffer.c.
References _FBDrawShape().
Referenced by FBEraseShapeArr().
{
  _FBDrawShape(fb, sh, FB_COLOR_ERASE);
}
void FBEraseShapeArr (framebuffer fb, ushort numShapes, shape ** shapeArr)
Definition at line 143 of file framebuffer.c.
References FBEraseShape().
Referenced by demonstrateClock().
{
  unsigned char i;
  for(i=0; i < numShapes; ++i) {
    FBEraseShape(fb, shapeArr[i]);
  }
}
void FBEraseString (framebuffer fb, point * top_left_corner, char * string)
Definition at line 438 of file framebuffer.c.
References _FBDrawString(), point::shade, SHDestroyPoint, and SHDuplicatePoint.
Referenced by FBEraseStringAnonPt().
{
  point* pt = SHDuplicatePoint(top_left_corner);
  pt->shade = FB_COLOR_ERASE;
  _FBDrawString(fb, pt, string);
  SHDestroyPoint(pt);
}
void FBEraseStringAnonPt (framebuffer fb, point * top_left_corner, char * string)
Definition at line 426 of file framebuffer.c.
References FBEraseString().
{
  FBEraseString(fb, top_left_corner, string);
  free(top_left_corner);
}
framebuffer FBInit (void)
Definition at line 22 of file framebuffer.c.
Referenced by demonstrateClock(), demonstrateDrawShapes(), demonstrateDrawString(), and main().
                     {
  /* OPTIONAL TODO: bit-strap this struct */
  unsigned char i;
  unsigned char** fb = (unsigned char**) calloc(OLED_WIDTH, sizeof(unsigned char*));
  for(i = 0; i < OLED_WIDTH; ++i) {
    fb[i] = (unsigned char*) calloc(OLED_HEIGHT, sizeof(unsigned char));
  }
  return (framebuffer) fb;
}
void FBPrintPointToConsole (point * p)
Definition at line 529 of file framebuffer.c.
{
#ifdef __GNUC__
  printf("(%d,%d):%d\n", p->x, p->y, p->shade);
#endif
}
void FBPrintPointToConsoleWithoutNewline (point * p)
Definition at line 548 of file framebuffer.c.
References point::shade, point::x, and point::y.
{
#ifdef __GNUC__
  printf("(%d,%d):%d", p->x, p->y, p->shade);
#endif
}
void FBSetPixel (framebuffer fb, uchar x, uchar y, shade_t shade)
Definition at line 161 of file framebuffer.c.
Referenced by _FBDrawLine(), _FBDrawShape(), _FBDrawString(), _FBFillFourEllipsePoints(), _FBPlotFourEllipsePoints(), FBClearPixel(), and FBDrawEllipseFill().
{
  if (x < FB_WIDTH && y < FB_HEIGHT) {
    fb[x][y] = shade;
  }
}
char* itoa (int i, char * buffer, uchar length)
Definition at line 480 of file framebuffer.c.
{
  if (snprintf(buffer, length, "%02d", i) == -1)
    return ""; /* base case, or error */
  return buffer;
}
unsigned char max_uc (unsigned char one, unsigned char two)
Definition at line 255 of file graph_framebuffer.c.
{
  if (one > two) {return one;} else return two;
}
Variable Documentation
const unsigned char valvanoFont[129][5] [static]
Definition at line 28 of file framebuffer.h.
Referenced by _FBDrawString().