EE445M RTOS: lib/liboscope-grapher/graphlib.h File Reference
graphlib.h File Reference
#include "libstd/defines.h"
Data Structures
struct graph
Macros
#define GL_BLANK_STEPS_PRECEEDING_STALE_DATA 2
Typedefs
typedef struct graph graph
Functions
char * strdup (const char *str)
graph * GLCreateGraph (long x_min, long x_max, long y_min, long y_max, long x_steps)
void GLDestroyGraph (graph *graph)
char * GLSetTitle (graph *graph, char *title)
void GLLabelAxes (graph *graph, char *x_axis, char *y_axis)
void GLPushDataPoint (graph *graph, long y_val)
long GLOffScreenValue (graph *graph)
Macro Definition Documentation
#define GL_BLANK_STEPS_PRECEEDING_STALE_DATA 2
Definition at line 14 of file graphlib.h.
Referenced by _FBDrawGraphData().
Typedef Documentation
typedef struct graph graph
Function Documentation
graph* GLCreateGraph (long x_min, long x_max, long y_min, long y_max, long x_steps)
Definition at line 25 of file graphlib.c.
References graph::all_data_points_valid, graph::data, graph::x_index, graph::x_index_max, graph::x_max, graph::x_min, graph::y_max, and graph::y_min.
Referenced by main().
{
     graph* g = (graph*) calloc(1, sizeof(graph));
     g->x_min = x_min;
     g->x_max = x_max;
     g->y_min = y_min;
     g->y_max = y_max;
     g->data = (long*) calloc(x_steps, sizeof(long));
     g->x_index = 0;
     g->x_index_max = x_steps;
     g->all_data_points_valid = false;
     return (graph*) g;
 }
void GLDestroyGraph (graph * graph)
Definition at line 83 of file graphlib.c.
References graph::data, graph::title, graph::x_title, and graph::y_title.
{
     free(g->data);
     free(g->title);
     free(g->x_title);
     free(g->y_title);
     free(g);
 }
void GLLabelAxes (graph * graph, char * x_axis, char * y_axis)
Definition at line 48 of file graphlib.c.
References strdup(), graph::x_title, and graph::y_title.
Referenced by main().
{
     g->x_title = strdup(x_axis);
     g->y_title = strdup(y_axis);
 }
long GLOffScreenValue (graph * graph)
Definition at line 71 of file graphlib.c.
References graph::y_max, and graph::y_min.
{
     long off_screen_value = g->y_max + 1;
     if (off_screen_value < g->y_max) {
     off_screen_value = g->y_min - 1;
     } if (off_screen_value > g->y_min) {
     off_screen_value = LONG_MIN;
     }
     return off_screen_value;
 }
void GLPushDataPoint (graph * graph, long y_val)
Definition at line 56 of file graphlib.c.
References graph::all_data_points_valid, graph::data, graph::most_recent_data_point, graph::x_index, and graph::x_index_max.
Referenced by main().
{
     /* Procedure: push the y data point at the current x_position and
      * then increment the current x_position. */
     g->data[g->x_index] = y_val;
     g->most_recent_data_point = g->x_index++;
     if (g->x_index >= g->x_index_max) {
     g->x_index = 0;
     g->all_data_points_valid = true; // one-way toggle to true
     }
 }
char* GLSetTitle (graph * graph, char * title)
Definition at line 42 of file graphlib.c.
References strdup(), and graph::title.
Referenced by main().
{
     g->title = strdup(title);
     return g->title;
 }
char* strdup (const char * str)
Definition at line 15 of file graphlib.c.
References null.
Referenced by GLLabelAxes(), GLSetTitle(), and utarray_str_cpy().
{
   if (str != null) {
     char *copy = malloc(strlen(str) + 1);
     if (copy != null)
       return strcpy(copy, str);
   }
   return null;
 }