EE445M RTOS: lib/libgraphics2d/graphics2d.c File Reference
graphics2d.c File Reference
#include "graphics2d.h"
Macros
#define NDEBUG
Functions
unsigned char * G2ConvertFBToRITFormat (framebuffer fb)
void G2Draw (framebuffer fb)
Variables
unsigned char g_PackedDeviceBuffer [RIT_FB_WIDTH *RIT_FB_HEIGHT] = {0}
The One Buffer To Rule Them All (TM)
Macro Definition Documentation
#define NDEBUG
Definition at line 6 of file graphics2d.c.
Function Documentation
unsigned char* G2ConvertFBToRITFormat (framebuffer)
Unpack fb into in the format understood by RIT functions.
Parameters
fb Framebuffer to convert into a char*
Returns
fb in RITFormat (unpacked char* array)
Definition at line 23 of file graphics2d.c.
References g_PackedDeviceBuffer, OLED_HEIGHT, OLED_WIDTH, and RIT_FB_WIDTH.
Referenced by demonstrateClock(), demonstrateDrawShapes(), demonstrateDrawString(), G2Draw(), and main().
{
   /* i is x, j is y */
   unsigned char i, j;
   unsigned char a, b;
 #ifndef NDEBUG
   printf("%s Unpacking framebuffer...", __FUNCTION__);
 #endif
   for(j=0; j<OLED_HEIGHT; ++j) {
     for(i=0; i<OLED_WIDTH; i+=2) {
       a = fb[i][j];
       b = fb[i+1][j];
       g_PackedDeviceBuffer[(i/2)+j*RIT_FB_WIDTH] = (a<<4) | (b&0xF);
     }
   }
 #ifndef NDEBUG
   printf("%s Done unpacking framebuffer...", __FUNCTION__);
 #endif
   return g_PackedDeviceBuffer;
 }
void G2Draw (framebuffer)
Draw (unpacked) fb on the OLED.
Parameters
fb Framebuffer type (char**)
Returns
void
Definition at line 49 of file graphics2d.c.
References G2ConvertFBToRITFormat(), g_PackedDeviceBuffer, OLED_HEIGHT, and OLED_WIDTH.
{
   G2ConvertFBToRITFormat(fb);
 #ifndef __GNUC__
   RIT128x96x4ImageDraw(g_PackedDeviceBuffer, 0, 0, OLED_WIDTH, OLED_HEIGHT);
 #endif
 }
Variable Documentation
g_PackedDeviceBuffer = {0}
The One Buffer To Rule Them All (TM)
This buffer is what we will use to write to the display. It is created here so that it can be easily passed around to those who need it and it doesn't need to keep being malloc'd all the time.
Definition at line 21 of file graphics2d.c.
Referenced by G2ConvertFBToRITFormat(), and G2Draw().