EE445M Real Time Operating Systems: lib/libgraphics2d/graphics2d.h File Reference
lib/libgraphics2d/graphics2d.h File Reference
#include "g2d_defines.h"
#include "framebuffer.h"
Functions
void G2Draw (framebuffer fb)
unsigned char * G2ConvertFBToRITFormat (framebuffer fb)
Function Documentation
unsigned char* G2ConvertFBToRITFormat (framebuffer fb)
Definition at line 29 of file graphics2d.c.
References packedDeviceBuffer.
Referenced by demonstrateClock(), demonstrateDrawShapes(), demonstrateDrawString(), G2Draw(), and main().
{
  /* i is x, j is y */
  unsigned char i, j;
  unsigned char a, b;
  for(j=0; j<OLED_HEIGHT; ++j) {
    for(i=0; i<OLED_WIDTH; i+=2) {
      a = fb[i][j];
      b = fb[i+1][j];
      packedDeviceBuffer[(i/2)+j*RIT_FB_WIDTH] = (a<<4) | (b&0xF);
    }
  }
  return packedDeviceBuffer;
}
void G2Draw (framebuffer fb)
Definition at line 51 of file graphics2d.c.
References G2ConvertFBToRITFormat(), and packedDeviceBuffer.
{
  G2ConvertFBToRITFormat(fb);
#ifndef __GNUC__
  RIT128x96x4ImageDraw(packedDeviceBuffer, 0, 0, OLED_WIDTH, OLED_HEIGHT);
#endif
}