EE445M RTOS: lib/liboscope-grapher/graph_framebuffer.c File Reference
graph_framebuffer.c File Reference
#include "graph_framebuffer.h"
#include "shape.h"
#include <math.h>
#include <stdio.h>
#include <string.h>
Functions
void FBDrawFullscreenGraph (framebuffer fb, graph *g)
void FBEraseFullscreenGraph (framebuffer fb, graph *g)
void FBEraseFullscreenGraphData (framebuffer fb, graph *g)
void FBDrawGraph (framebuffer fb, graph *g, point *top_left_corner, pixel_t width, pixel_t height)
void FBEraseGraph (framebuffer fb, graph *g, point *top_left_corner, pixel_t width, pixel_t height)
void FBEraseGraphData (framebuffer fb, graph *g, point *top_left_corner, pixel_t width, pixel_t height)
private void _FBDrawGraphBounds (framebuffer fb, graph *g, pixel_t x_range_padding, pixel_t y_range_padding, point *top_left_corner, pixel_t width, pixel_t height, shade_t shade)
private void _FBDrawGraphData (framebuffer fb, graph *g, point *top_left_corner, shade_t shade)
private void _FBDrawGraphTitle (framebuffer fb, graph *g)
private void _FBDrawGraphAxesTitles (framebuffer fb, graph *g)
private void _FBDrawGraphAxesScale (framebuffer fb, graph *g)
unsigned char max_uc (unsigned char one, unsigned char two)
pixel_t _FBPixelHeightOfString (char *str)
private pixel_t _FBPixelWidthOfString (char *str)
private pixel_t _FBPixelWidthOfLong (long l)
private pixel_t _FBPixelHeightOfLong (long l)
Function Documentation
private void _FBDrawGraphAxesScale (framebuffer fb, graph * g)
Definition at line 245 of file graph_framebuffer.c.
Referenced by FBDrawGraph(), and FBEraseGraph().
{
 }
private void _FBDrawGraphAxesTitles (framebuffer fb, graph * g)
Definition at line 240 of file graph_framebuffer.c.
Referenced by FBDrawGraph(), and FBEraseGraph().
{
 }
private void _FBDrawGraphBounds (framebuffer fb, graph * g, pixel_t x_range_padding, pixel_t y_range_padding, point * top_left_corner, pixel_t width, pixel_t height, shade_t shade)
Definition at line 159 of file graph_framebuffer.c.
References shape_create_point(), point::x, and point::y.
Referenced by FBDrawGraph(), and FBEraseGraph().
{
   /* Draw X axis boundaries (aka vertical lines) */
   FBDrawAnonLine(fb,
                  shape_create_point(top_left_corner->x + x_range_padding,
                                top_left_corner->y,
                                shade),
                  shape_create_point(top_left_corner->x + x_range_padding,
                                top_left_corner->y + (height - y_range_padding),
                                shade),
                  shade);
   /* Draw Y axis boundaries (aka horizontal lines) */
   FBDrawAnonLine(fb,
                  shape_create_point(top_left_corner->x + x_range_padding,
                                top_left_corner->y + height - y_range_padding,
                                shade),
                  shape_create_point(top_left_corner->x + x_range_padding + width,
                                top_left_corner->y + height - y_range_padding,
                                shade),
                  shade);
 }
private void _FBDrawGraphData (framebuffer fb, graph * g, point * top_left_corner, shade_t shade)
Definition at line 198 of file graph_framebuffer.c.
References graph::all_data_points_valid, graph::data, GL_BLANK_STEPS_PRECEEDING_STALE_DATA, graph::most_recent_data_point, pixel_t, shape_create_point(), when, graph::x_max, graph::x_min, graph::x_pixel_end, graph::x_pixel_start, graph::y_max, graph::y_min, graph::y_pixel_end, and graph::y_pixel_start.
Referenced by FBDrawGraph(), FBEraseGraph(), and FBEraseGraphData().
{
   long idx = 0;
   /* Temporary variables reused in printfs */
   pixel_t x1, x2, y1, y2;
   /* Set this to true from lldb/gdb to see useful debugging information */
   bool debug = true;
   for(idx=0;
       (((g->all_data_points_valid == true) && (idx < g->x_index_max-1))) ||
         (g->all_data_points_valid == false && (idx < (g->most_recent_data_point - 1)));
       ++idx) {
     fprintf(stderr, "Printing index %ld\n", idx);
     if ((idx <= g->most_recent_data_point) &&
         (idx > g->most_recent_data_point + GL_BLANK_STEPS_PRECEEDING_STALE_DATA)) {
       /* Draw nothing */
       when (debug) {fprintf(stderr, "Not drawing this cycle [idx:%ld]\n", idx);}
     } else {
       x1 = g->x_pixel_start + ((idx)*(g->x_pixel_end-g->x_pixel_start)/(g->x_max-g->x_min));
       y1 = g->y_pixel_end   - ((g->data[idx]+g->y_min)*(g->y_pixel_end-g->y_pixel_start)/(g->y_max-g->y_min));
       x2 = g->x_pixel_start + ((idx+1)*(g->x_pixel_end-g->x_pixel_start)/(g->x_max-g->x_min));
       y2 = g->y_pixel_end   - ((g->data[idx+1]+g->y_min)*(g->y_pixel_end-g->y_pixel_start)/(g->y_max-g->y_min));
       FBDrawAnonLine(fb,
                      shape_create_point(x1, y1, shade),
                      shape_create_point(x2, y2, shade),
                      shade);
       when (debug) {fprintf(stderr, "Line from:\t(%u,\t%u) to (%u,\t%u)\n",x1,y1,x2,y2);}
     }
   }
 }
private void _FBDrawGraphTitle (framebuffer fb, graph * g)
Definition at line 235 of file graph_framebuffer.c.
Referenced by FBDrawGraph(), and FBEraseGraph().
{
 }
private pixel_t _FBPixelHeightOfLong (long l)
Definition at line 293 of file graph_framebuffer.c.
{
   // 2 pixels because we want one to pad the top and one on the bottom
   return VALVANO_FONT_LINE_SPACING + VALVANO_FONT_HEIGHT;
 }
pixel_t _FBPixelHeightOfString (char * str)
Definition at line 264 of file graph_framebuffer.c.
{
   /* TODO: consider line wrapping */
   return VALVANO_FONT_LINE_SPACING + VALVANO_FONT_HEIGHT;
 }
private pixel_t _FBPixelWidthOfLong (long l)
Definition at line 283 of file graph_framebuffer.c.
{
   // 2 pixels because we want one to pad the front and one on the back
   return VALVANO_FONT_KERNING + (log(l) * VALVANO_FONT_WIDTH);
 }
private pixel_t _FBPixelWidthOfString (char * str)
Definition at line 274 of file graph_framebuffer.c.
{
   return VALVANO_FONT_KERNING + ((VALVANO_FONT_KERNING + VALVANO_FONT_WIDTH) * strlen(str));
 }
void FBDrawFullscreenGraph (framebuffer fb, graph * g)
Definition at line 25 of file graph_framebuffer.c.
References FBDrawGraph(), OLED_HEIGHT, OLED_WIDTH, pixel_t, shade_t, and shape_create_point().
Referenced by main().
{
   point* origin = shape_create_point((pixel_t) 0, (pixel_t) 0, (shade_t) 15);
   FBDrawGraph(fb, g, origin, (pixel_t) OLED_WIDTH, (pixel_t) OLED_HEIGHT);
   SHDestroyPoint(origin);
 }
void FBDrawGraph (framebuffer fb, graph * g, point * top_left_corner, pixel_t width, pixel_t height)
Definition at line 73 of file graph_framebuffer.c.
References _FBDrawGraphAxesScale(), _FBDrawGraphAxesTitles(), _FBDrawGraphBounds(), _FBDrawGraphData(), _FBDrawGraphTitle(), pixel_t, point::shade, point::x, graph::x_max, graph::x_min, graph::x_pixel_end, graph::x_pixel_start, point::y, graph::y_max, graph::y_min, graph::y_pixel_end, and graph::y_pixel_start.
Referenced by FBDrawFullscreenGraph().
{
   /* Determine how many pixels to reserve for the scale numbers next
    * to the axes */
   pixel_t x_range_padding = max_pixel_width_of_long(g->y_min, g->y_max);
   pixel_t y_range_padding = max_pixel_height_of_long(g->x_min, g->x_max);
   /* {x,y}_pixel_{start,end} information in /resources/2014-04-07 10.07.01.jpg */
   g->x_pixel_start = top_left_corner->x + x_range_padding;
   g->x_pixel_end   = top_left_corner->x + width;
   g->y_pixel_start = top_left_corner->y;
   g->y_pixel_end   = top_left_corner->y + height - 2 - y_range_padding;
   _FBDrawGraphBounds(fb, g, x_range_padding, y_range_padding, top_left_corner, width, height, top_left_corner->shade);
   _FBDrawGraphData(fb, g, top_left_corner, top_left_corner->shade);
   _FBDrawGraphTitle(fb, g);
   _FBDrawGraphAxesTitles(fb, g);
   _FBDrawGraphAxesScale(fb, g);
 }
void FBEraseFullscreenGraph (framebuffer fb, graph * g)
Definition at line 38 of file graph_framebuffer.c.
References FB_COLOR_ERASE, FBEraseGraph(), OLED_HEIGHT, OLED_WIDTH, shade_t, shape_create_point(), x_pixel_t, and y_pixel_t.
Referenced by main().
{
   point* origin = shape_create_point((x_pixel_t) 0, (y_pixel_t) 0, (shade_t) FB_COLOR_ERASE);
   FBEraseGraph(fb, g, origin, (x_pixel_t) OLED_WIDTH, (y_pixel_t) OLED_HEIGHT);
   SHDestroyPoint(origin);
 }
void FBEraseFullscreenGraphData (framebuffer fb, graph * g)
Definition at line 51 of file graph_framebuffer.c.
References FB_COLOR_ERASE, FBEraseGraphData(), OLED_HEIGHT, OLED_WIDTH, shade_t, shape_create_point(), x_pixel_t, and y_pixel_t.
{
   point* origin = shape_create_point((x_pixel_t) 0, (y_pixel_t) 0, (shade_t) FB_COLOR_ERASE);
   FBEraseGraphData(fb, g, origin, (x_pixel_t) OLED_WIDTH, (y_pixel_t) OLED_HEIGHT);
   SHDestroyPoint(origin);
 }
void FBEraseGraph (framebuffer fb, graph * g, point * top_left_corner, pixel_t width, pixel_t height)
Definition at line 103 of file graph_framebuffer.c.
References _FBDrawGraphAxesScale(), _FBDrawGraphAxesTitles(), _FBDrawGraphBounds(), _FBDrawGraphData(), _FBDrawGraphTitle(), FB_SHADE_ERASE, pixel_t, point::x, graph::x_max, graph::x_min, graph::x_pixel_end, graph::x_pixel_start, point::y, graph::y_max, graph::y_min, graph::y_pixel_end, and graph::y_pixel_start.
Referenced by FBEraseFullscreenGraph().
{
   /* Determine how many pixels to reserve for the scale numbers next
    * to the axes */
   pixel_t x_range_padding = max_pixel_width_of_long(g->y_min, g->y_max);
   pixel_t y_range_padding = max_pixel_height_of_long(g->x_min, g->x_max);
   /* {x,y}_pixel_{start,end} information in /resources/2014-04-07 10.07.01.jpg */
   g->x_pixel_start = top_left_corner->x + x_range_padding;
   g->x_pixel_end   = top_left_corner->x + width;
   g->y_pixel_start = top_left_corner->y;
   g->y_pixel_end   = top_left_corner->y + height - 2 - y_range_padding;
   _FBDrawGraphBounds(fb, g, x_range_padding, y_range_padding, top_left_corner, width, height, FB_SHADE_ERASE);
   _FBDrawGraphData(fb, g, top_left_corner, FB_SHADE_ERASE);
   _FBDrawGraphTitle(fb, g);
   _FBDrawGraphAxesTitles(fb, g);
   _FBDrawGraphAxesScale(fb, g);
 }
void FBEraseGraphData (framebuffer fb, graph * g, point * top_left_corner, pixel_t width, pixel_t height)
Definition at line 133 of file graph_framebuffer.c.
References _FBDrawGraphData(), FB_SHADE_ERASE, pixel_t, point::x, graph::x_max, graph::x_min, graph::x_pixel_end, graph::x_pixel_start, point::y, graph::y_max, graph::y_min, graph::y_pixel_end, and graph::y_pixel_start.
Referenced by FBEraseFullscreenGraphData().
{
   /* Determine how many pixels to reserve for the scale numbers next
    * to the axes */
   pixel_t x_range_padding = max_pixel_width_of_long(g->y_min, g->y_max);
   pixel_t y_range_padding = max_pixel_height_of_long(g->x_min, g->x_max);
   /* {x,y}_pixel_{start,end} information in /resources/2014-04-07 10.07.01.jpg */
   g->x_pixel_start = top_left_corner->x + x_range_padding;
   g->x_pixel_end   = top_left_corner->x + width;
   g->y_pixel_start = top_left_corner->y;
   g->y_pixel_end   = top_left_corner->y + height - 2 - y_range_padding;
   _FBDrawGraphData(fb, g, top_left_corner, FB_SHADE_ERASE);
 }
unsigned char max_uc (unsigned char one, unsigned char two)
Definition at line 255 of file graph_framebuffer.c.
{
   if (one > two) {return one;} else return two;
 }