EE445M RTOS: Sw_crc_api
Sw_crc_api
Macros
#define CRC8_ITER(crc, data) g_pui8Crc8CCITT[(uint8_t)((crc) ^ (data))]
#define CRC16_ITER(crc, data)
#define CRC32_ITER(crc, data)
Functions
uint8_t Crc8CCITT (uint8_t ui8Crc, const uint8_t *pui8Data, uint32_t ui32Count)
uint16_t Crc16 (uint16_t ui16Crc, const uint8_t *pui8Data, uint32_t ui32Count)
uint16_t Crc16Array (uint32_t ui32WordLen, const uint32_t *pui32Data)
void Crc16Array3 (uint32_t ui32WordLen, const uint32_t *pui32Data, uint16_t *pui16Crc3)
uint32_t Crc32 (uint32_t ui32Crc, const uint8_t *pui8Data, uint32_t ui32Count)
Variables
static const uint8_t g_pui8Crc8CCITT [256]
static const uint16_t g_pui16Crc16 [256]
static const uint32_t g_pui32Crc32 []
Detailed Description
Macro Definition Documentation
#define CRC16_ITER (crc, data)
Value:
(((crc) >> 8) ^                               \
                                 g_pui16Crc16[(uint8_t)((crc) ^ (data))])
Definition at line 220 of file sw_crc.c.
Referenced by Crc16(), and Crc16Array3().
#define CRC32_ITER (crc, data)
Value:
(((crc) >> 8) ^                               \
                                 g_pui32Crc32[(uint8_t)((crc & 0xFF) ^        \
                                                        (data))])
Definition at line 228 of file sw_crc.c.
Referenced by Crc32().
#define CRC8_ITER (crc, data) g_pui8Crc8CCITT[(uint8_t)((crc) ^ (data))]
Definition at line 213 of file sw_crc.c.
Referenced by Crc8CCITT().
Function Documentation
uint16_t Crc16 (uint16_t ui16Crc, const uint8_t * pui8Data, uint32_t ui32Count)
Calculates the CRC-16 of an array of bytes.
Parameters
ui16Crc is the starting CRC-16 value.
pui8Data is a pointer to the data buffer.
ui32Count is the number of bytes in the data buffer.
This function is used to calculate the CRC-16 of the input buffer. The CRC-16 is computed in a running fashion, meaning that the entire data block that is to have its CRC-16 computed does not need to be supplied all at once. If the input buffer contains the entire block of data, then ui16Crc should be set to 0. If, however, the entire block of data is not available, then ui16Crc should be set to 0 for the first portion of the data, and then the returned value should be passed back in as ui16Crc for the next portion of the data.
For example, to compute the CRC-16 of a block that has been split into three pieces, use the following:
//!     ui16Crc = Crc16(0, pui8Data1, ui32Len1);
//!     ui16Crc = Crc16(ui16Crc, pui8Data2, ui32Len2);
//!     ui16Crc = Crc16(ui16Crc, pui8Data3, ui32Len3);
//!
Computing a CRC-16 in a running fashion is useful in cases where the data
is arriving via a serial link (for example) and is therefore not all
available at one time.
\return The CRC-16 of the input data.
Definition at line 411 of file sw_crc.c.
References CRC16_ITER.
Referenced by Crc16Array().
 {
     uint32_t ui32Temp;
     //
     // If the data buffer is not 16 bit-aligned, then perform a single step of
     // the CRC to make it 16 bit-aligned.
     //
     if((uint32_t)pui8Data & 1)
     {
         //
         // Perform the CRC on this input byte.
         //
         ui16Crc = CRC16_ITER(ui16Crc, *pui8Data);
         //
         // Skip this input byte.
         //
         pui8Data++;
         ui32Count--;
     }
     //
     // If the data buffer is not word-aligned and there are at least two bytes
     // of data left, then perform two steps of the CRC to make it word-aligned.
     //
     if(((uint32_t)pui8Data & 2) && (ui32Count > 1))
     {
         //
         // Read the next 16 bits.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // While there is at least a word remaining in the data buffer, perform
     // four steps of the CRC to consume a word.
     //
     while(ui32Count > 3)
     {
         //
         // Read the next word.
         //
         ui32Temp = *(uint32_t *)pui8Data;
         //
         // Perform the CRC on these four bytes.
         //
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 8);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 16);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 24);
         //
         // Skip these input bytes.
         //
         pui8Data += 4;
         ui32Count -= 4;
     }
     //
     // If there are two bytes left in the input buffer, then perform two steps
     // of the CRC.
     //
     if(ui32Count > 1)
     {
         //
         // Read the two bytes.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // If there is a final byte remaining in the input buffer, then perform a
     // single step of the CRC.
     //
     if(ui32Count != 0)
     {
         ui16Crc = CRC16_ITER(ui16Crc, *pui8Data);
     }
     //
     // Return the resulting CRC-16 value.
     //
     return(ui16Crc);
 }
uint16_t Crc16Array (uint32_t ui32WordLen, const uint32_t * pui32Data)
Calculates the CRC-16 of an array of words.
Parameters
ui32WordLen is the length of the array in words (the number of bytes divided by 4).
pui32Data is a pointer to the data buffer.
This function is a wrapper around the running CRC-16 function, providing the CRC-16 for a single block of data.
Returns
The CRC-16 of the input data.
Definition at line 537 of file sw_crc.c.
References Crc16().
 {
     //
     // Calculate and return the CRC-16 of this array of words.
     //
     return(Crc16(0, (const uint8_t *)pui32Data, ui32WordLen * 4));
 }
void Crc16Array3 (uint32_t ui32WordLen, const uint32_t * pui32Data, uint16_t * pui16Crc3)
Calculates three CRC-16s of an array of words.
Parameters
ui32WordLen is the length of the array in words (the number of bytes divided by 4).
pui32Data is a pointer to the data buffer.
pui16Crc3 is a pointer to an array in which to place the three CRC-16 values.
This function is used to calculate three CRC-16s of the input buffer; the first uses every byte from the array, the second uses only the even-index bytes from the array (in other words, bytes 0, 2, 4, etc.), and the third uses only the odd-index bytes from the array (in other words, bytes 1, 3, 5, etc.).
Returns
None
Definition at line 565 of file sw_crc.c.
References CRC16_ITER.
 {
     uint16_t ui16Crc, ui16Cri8Odd, ui16Cri8Even;
     uint32_t ui32Temp;
     //
     // Initialize the CRC values to zero.
     //
     ui16Crc = 0;
     ui16Cri8Odd = 0;
     ui16Cri8Even = 0;
     //
     // Loop while there are more words in the data buffer.
     //
     while(ui32WordLen--)
     {
         //
         // Read the next word.
         //
         ui32Temp = *pui32Data++;
         //
         // Perform the first CRC on all four data bytes.
         //
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 8);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 16);
         ui16Crc = CRC16_ITER(ui16Crc, ui32Temp >> 24);
         //
         // Perform the second CRC on only the even-index data bytes.
         //
         ui16Cri8Even = CRC16_ITER(ui16Cri8Even, ui32Temp);
         ui16Cri8Even = CRC16_ITER(ui16Cri8Even, ui32Temp >> 16);
         //
         // Perform the third CRC on only the odd-index data bytes.
         //
         ui16Cri8Odd = CRC16_ITER(ui16Cri8Odd, ui32Temp >> 8);
         ui16Cri8Odd = CRC16_ITER(ui16Cri8Odd, ui32Temp >> 24);
     }
     //
     // Return the resulting CRC-16 values.
     //
     pui16Crc3[0] = ui16Crc;
     pui16Crc3[1] = ui16Cri8Even;
     pui16Crc3[2] = ui16Cri8Odd;
 }
uint32_t Crc32 (uint32_t ui32Crc, const uint8_t * pui8Data, uint32_t ui32Count)
Calculates the CRC-32 of an array of bytes.
Parameters
ui32Crc is the starting CRC-32 value.
pui8Data is a pointer to the data buffer.
ui32Count is the number of bytes in the data buffer.
This function is used to calculate the CRC-32 of the input buffer. The CRC-32 is computed in a running fashion, meaning that the entire data block that is to have its CRC-32 computed does not need to be supplied all at once. If the input buffer contains the entire block of data, then ui32Crc should be set to 0xFFFFFFFF. If, however, the entire block of data is not available, then ui32Crc should be set to 0xFFFFFFFF for the first portion of the data, and then the returned value should be passed back in as ui32Crc for the next portion of the data. Once all data has been passed to the function, the final CRC-32 can be obtained by inverting the last returned value.
For example, to compute the CRC-32 of a block that has been split into three pieces, use the following:
//!     ui32Crc = Crc32(0xFFFFFFFF, pui8Data1, ui32Len1);
//!     ui32Crc = Crc32(ui32Crc, pui8Data2, ui32Len2);
//!     ui32Crc = Crc32(ui32Crc, pui8Data3, ui32Len3);
//!     ui32Crc ^= 0xFFFFFFFF;
//!
Computing a CRC-32 in a running fashion is useful in cases where the data
is arriving via a serial link (for example) and is therefore not all
available at one time.
\return The accumulated CRC-32 of the input data.
Definition at line 654 of file sw_crc.c.
References CRC32_ITER.
Referenced by EMACHashFilterBitCalculate(), and EMACVLANHashFilterBitCalculate().
 {
     uint32_t ui32Temp;
     //
     // If the data buffer is not 16 bit-aligned, then perform a single step
     // of the CRC to make it 16 bit-aligned.
     //
     if((uint32_t)pui8Data & 1)
     {
         //
         // Perform the CRC on this input byte.
         //
         ui32Crc = CRC32_ITER(ui32Crc, *pui8Data);
         //
         // Skip this input byte.
         //
         pui8Data++;
         ui32Count--;
     }
     //
     // If the data buffer is not word-aligned and there are at least two bytes
     // of data left, then perform two steps of the CRC to make it word-aligned.
     //
     if(((uint32_t)pui8Data & 2) && (ui32Count > 1))
     {
         //
         // Read the next int16_t.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp);
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // While there is at least a word remaining in the data buffer, perform
     // four steps of the CRC to consume a word.
     //
     while(ui32Count > 3)
     {
         //
         // Read the next word.
         //
         ui32Temp = *(uint32_t *)pui8Data;
         //
         // Perform the CRC on these four bytes.
         //
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp);
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp >> 8);
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp >> 16);
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp >> 24);
         //
         // Skip these input bytes.
         //
         pui8Data += 4;
         ui32Count -= 4;
     }
     //
     // If there are 16 bits left in the input buffer, then perform two steps of
     // the CRC.
     //
     if(ui32Count > 1)
     {
         //
         // Read the two bytes.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp);
         ui32Crc = CRC32_ITER(ui32Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // If there is a final byte remaining in the input buffer, then perform a
     // single step of the CRC.
     //
     if(ui32Count != 0)
     {
         ui32Crc = CRC32_ITER(ui32Crc, *pui8Data);
     }
     //
     // Return the resulting CRC-32 value.
     //
     return(ui32Crc);
 }
uint8_t Crc8CCITT (uint8_t ui8Crc, const uint8_t * pui8Data, uint32_t ui32Count)
Calculates the CRC-8-CCITT of an array of bytes.
Parameters
ui8Crc is the starting CRC-8-CCITT value.
pui8Data is a pointer to the data buffer.
ui32Count is the number of bytes in the data buffer.
This function is used to calculate the CRC-8-CCITT of the input buffer. The CRC-8-CCITT is computed in a running fashion, meaning that the entire data block that is to have its CRC-8-CCITT computed does not need to be supplied all at once. If the input buffer contains the entire block of data, then ui8Crc should be set to 0. If, however, the entire block of data is not available, then ui8Crc should be set to 0 for the first portion of the data, and then the returned value should be passed back in as ui8Crc for the next portion of the data.
For example, to compute the CRC-8-CCITT of a block that has been split into three pieces, use the following:
//!     ui8Crc = Crc8CCITT(0, pui8Data1, ui32Len1);
//!     ui8Crc = Crc8CCITT(ui8Crc, pui8Data2, ui32Len2);
//!     ui8Crc = Crc8CCITT(ui8Crc, pui8Data3, ui32Len3);
//!
Computing a CRC-8-CCITT in a running fashion is useful in cases where the
data is arriving via a serial link (for example) and is therefore not all
available at one time.
\return The CRC-8-CCITT of the input data.
Definition at line 266 of file sw_crc.c.
References CRC8_ITER.
 {
     uint32_t ui32Temp;
     //
     // If the data buffer is not 16 bit-aligned, then perform a single step of
     // the CRC to make it 16 bit-aligned.
     //
     if((uint32_t)pui8Data & 1)
     {
         //
         // Perform the CRC on this input byte.
         //
         ui8Crc = CRC8_ITER(ui8Crc, *pui8Data);
         //
         // Skip this input byte.
         //
         pui8Data++;
         ui32Count--;
     }
     //
     // If the data buffer is not word-aligned and there are at least two bytes
     // of data left, then perform two steps of the CRC to make it word-aligned.
     //
     if(((uint32_t)pui8Data & 2) && (ui32Count > 1))
     {
         //
         // Read the next 16 bits.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp);
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // While there is at least a word remaining in the data buffer, perform
     // four steps of the CRC to consume a word.
     //
     while(ui32Count > 3)
     {
         //
         // Read the next word.
         //
         ui32Temp = *(uint32_t *)pui8Data;
         //
         // Perform the CRC on these four bytes.
         //
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp);
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp >> 8);
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp >> 16);
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp >> 24);
         //
         // Skip these input bytes.
         //
         pui8Data += 4;
         ui32Count -= 4;
     }
     //
     // If there are 16 bits left in the input buffer, then perform two steps of
     // the CRC.
     //
     if(ui32Count > 1)
     {
         //
         // Read the 16 bits.
         //
         ui32Temp = *(uint16_t *)pui8Data;
         //
         // Perform the CRC on these two bytes.
         //
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp);
         ui8Crc = CRC8_ITER(ui8Crc, ui32Temp >> 8);
         //
         // Skip these input bytes.
         //
         pui8Data += 2;
         ui32Count -= 2;
     }
     //
     // If there is a final byte remaining in the input buffer, then perform a
     // single step of the CRC.
     //
     if(ui32Count != 0)
     {
         ui8Crc = CRC8_ITER(ui8Crc, *pui8Data);
     }
     //
     // Return the resulting CRC-8-CCITT value.
     //
     return(ui8Crc);
 }
Variable Documentation
const uint16_t g_pui16Crc16[256] static
Definition at line 97 of file sw_crc.c.
const uint32_t g_pui32Crc32[] static
Definition at line 140 of file sw_crc.c.
const uint8_t g_pui8Crc8CCITT[256] static
Definition at line 55 of file sw_crc.c.