EE445M RTOS: Framebuffer manipulation framework
Framebuffer manipulation framework
Frame bufer representation in memory.
Functions
framebuffer fb_init (void)
Create a framebuffer object and return the handle.
void fb_destroy (framebuffer)
Destroy a framebuffer object.
void fb_erase_string (framebuffer, point *, char *)
Erase string on fb starting at top_left_corner.
void fb_erase_string_anon (framebuffer fb, point *top_left_corner, char *string)
Erase string on fb starting at top_left_corner and free top_left_corner.
void fb_erase_char (framebuffer, point *, char)
Erase char on fb starting at top_left_corner.
void fb_erase_char_anon (framebuffer fb, point *top_left_corner, char c)
Call and free .
private void _fb_draw_string (framebuffer, point *, char *)
For internal use only.
void fb_draw_string (framebuffer fb, point *top_left_corner, char *string)
Draw string on fb starting at top_left_corner.
void fb_draw_string_anon_pt (framebuffer fb, point *top_left_corner, char *string)
Call fb_draw_string and destroy top_left_corner.
private void _fb_draw_char (framebuffer, point *, char)
For internal use only.
void fb_draw_shape (framebuffer, shape *)
Using as a canvas, draw .
void fb_draw_shapes (framebuffer, ushort,...)
void fb_draw_shape_arr (framebuffer, ushort, shape **)
void fb_erase_shape_arr (framebuffer, ushort, shape **)
private void _fb_draw_shape (framebuffer, shape *, shade_t)
For internal use only.
void fb_erase_shape (framebuffer fb, shape *sh)
Using as a canvas, draw .
void fb_set_pixel (framebuffer, uchar, uchar, shade_t)
In fb, set pixel (x,y) to .
void fb_clear_pixel (framebuffer fb, uchar x, uchar y)
Clear pixel (x,y) in .
void fb_erase_pixel (framebuffer fb, uchar x, uchar y)
Erase pixel (x,y) in .
private void _fb_draw_line (framebuffer, point *, point *, shade_t)
The heavy-lifter (pixel-setter) in line-segment-drawing.
void fb_erase_anon_line (framebuffer fb, point *point1, point *point2)
Erases a line connecting two points before destroys the two points.
void fb_erase_line (framebuffer fb, point *point1, point *point2)
Remove a line segment on from to .
void fb_draw_anon_line (framebuffer fb, point *point1, point *point2, shade_t shade)
Draws a line connecting two points before destroying the two points.
void fb_draw_line (framebuffer fb, point *point1, point *point2, shade_t shade)
Draw a line segment on from to of color .to of color .shade.
void fb_draw_line_gradient (framebuffer fb, point *point1, point *point2, shade_t shade)
Draw a line segment on from to .
void fb_draw_ellipse (framebuffer, point *, ushort, ushort, shade_t)
Draw an ellipse in fb at center with specified x- and y-radii of color shade.
void fb_draw_circle (framebuffer fb, circle *c)
Draw a circle in at with radius of color .
private void _fb_fill_four_ellipse_points (framebuffer, point *, ushort, ushort)
Fill an ellipse on fb.
void fb_draw_ellipse_fill (framebuffer, point *, ushort, ushort, shade_t)
Draw on fb a shaded ellipse described by center, x- and y-radii.
private void _fb_plot_four_ellipse_points (framebuffer, point *, ushort, ushort)
Plot on fb the four symmetric points on an ellipse described by a center and x- and y-offsets.
void fb_console_println_point (point *)
Print a point (ordered pair) to the console followed by a newline.
void fb_console_print_point (point *)
Print a point (ordered pair) to the console.
void fb_console_println_coordinate (uchar, uchar, shade_t)
Print a coordinate (ordered pair) to the console followed by a newline.
void fb_console_print_coordinate (uchar, uchar, shade_t)
Print a coordinate (ordered pair) to the console.
Detailed Description
Frame bufer representation in memory.
Represent and transform one frame's buffer in memory.
Author
Hershal Bhave
Eric Crosson
Version
0.1
Date
2014
Copyright
GNU Public License.
Note
Private functions (beginning with an underscore) are helper functions, not to be accessed outside the scope of this file. The purpose of these functions is to reduce duplicated code.
Bug:
This library is not modal (taking one framebuffer to act upon at a time).
Function Documentation
private void _fb_draw_char (framebuffer , point * , char)
For internal use only.
Peforms the base work of all framebuffer string drawing requests.
Peforms the base work of all framebuffer string drawing requests.
Parameters
fb Framebuffer to use as canvas
pen Coordinate of top left corner of char on fb
c Character to draw
Returns
void
Definition at line 283 of file framebuffer.c.
References FB_HEIGHT, fb_set_pixel(), FB_WIDTH, font_valvano, FONT_VALVANO_HEIGHT, FONT_VALVANO_WIDTH, point::shade, point::x, and point::y.
Referenced by _fb_draw_string(), and fb_erase_char().
{
     uchar active, col, row, mask;
     for(col=0; col < FONT_VALVANO_WIDTH; ++col) {
     mask = 0x01;
     if (pen->x+col >= FB_WIDTH) {
         /* We have exceeded the number of pixels on the screen */
 #ifndef NDEBUG
         printf("%s pen has gone offscreen. Ignoring rest of character...\n", __FUNCTION__);
 #endif
         break;
     }
     for(row=0; row < FONT_VALVANO_HEIGHT; ++row) {
         if (pen->y+row >= FB_HEIGHT) {break;}
         active = mask & font_valvano[c][col];
         fb_set_pixel(fb, pen->x + col, pen->y + row, active ? pen->shade : 0);
         mask = mask << 1;
     }
     }
 }
private void _fb_draw_line (framebuffer , point * , point * , shade_t)
The heavy-lifter (pixel-setter) in line-segment-drawing.
Parameters
fb The framebuffer to draw a line on
point1 The first endpoint of the line-segment to draw
point2 The final endpoint of the line-segment to draw
shade The shade of the line-segment to draw
Returns
void
Definition at line 105 of file framebuffer.c.
References fb_set_pixel(), shape_duplicate_point(), point::x, and point::y.
Referenced by fb_draw_anon_line(), fb_draw_line(), fb_erase_anon_line(), and fb_erase_line().
{
     point* a;
     point* b;
     int dx, dy, sx, sy, e2, err;
     a = shape_duplicate_point(point1);
     b = shape_duplicate_point(point2);
     dx = abs(b->x-a->x); sx = (a->x < b->x) ? 1 : -1;
     dy = abs(b->y-a->y); sy = (a->y < b->y) ? 1 : -1;
     err = (dx>dy ? dx : -dy)/2;
     for(;;) {
     fb_set_pixel(fb, a->x, a->y, shade);
     if ((a->x == b->x) && (a->y == b->y)) {break;}
     e2 = err;
     if (e2 >-dx) {err -= dy; a->x += sx;}
     if (e2 < dy) {err += dx; a->y += sy;}
     }
     SHDestroyPoint(a);
     SHDestroyPoint(b);
 }
private void _fb_draw_shape (framebuffer , shape * , shade_t)
For internal use only.
Helper function that performs the mechanics of drawing a shape.
Helper function that performs the mechanics of drawing a shape. The purpose of this function is to reduce duplicated code in memory.
Parameters
fb Framebuffer to use as canvas
sh Shape to draw
shade Color of shape
Returns
void
Definition at line 39 of file framebuffer.c.
References fb_draw_line_gradient(), shape::num_points, and shape::points.
Referenced by fb_draw_shape(), and fb_erase_shape().
{
     unsigned short p;
     for(p=0; p < sh->num_points; ++p) {
     /* TODO: determine if the below line is necessary */
     /* fb_set_pixel(fb, sh->points[p]->x, sh->points[p]->y, shade); */
     if (p > 0) {
         fb_draw_line_gradient(fb, sh->points[p-1], sh->points[p], shade);
     }
     }
     /* Enclose the figure */
     if(p>1) {
     fb_draw_line_gradient(fb, sh->points[0], sh->points[p-1], shade);
     }
 }
private void _fb_draw_string (framebuffer , point * , char *)
For internal use only.
Draw on the starting square against .
Draw a string on the framebuffer starting square against .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner of string on fb
string String to draw
Returns
void
Definition at line 269 of file framebuffer.c.
References _fb_draw_char(), FONT_VALVANO_KERNING, FONT_VALVANO_WIDTH, null, shape_duplicate_point(), and point::x.
Referenced by fb_draw_string(), fb_draw_string_anon_pt(), and fb_erase_string().
{
     point* pen = shape_duplicate_point(top_left_corner);
     while(*string != null) {
     _fb_draw_char(fb, pen, *(string++));
     pen->x += FONT_VALVANO_WIDTH + FONT_VALVANO_KERNING;
     }
     SHDestroyPoint(pen);
 }
private void _fb_fill_four_ellipse_points (framebuffer , point * , ushort , ushort)
Fill an ellipse on fb.
Fill an ellipse on fb.
Fill on fb from the four symmetric points on an ellipse described by a center and x- and y-offsets, to the axis of said ellipse.
Parameters
fb Framebuffer to use as canvas
center Geometric center of the ellipse
x X offset of point to plot
y Y offset of point to plot
Returns
void
Note
Points will be shaded with the value in center->shade.
Definition at line 138 of file framebuffer.c.
References fb_set_pixel(), point::shade, point::x, and point::y.
Referenced by fb_draw_ellipse_fill().
{
     int i;
     for(i = -x; i <= x; ++i) {
     fb_set_pixel(fb, center->x + i, center->y + y, center->shade);
     fb_set_pixel(fb, center->x + i, center->y - y, center->shade);
     }
 }
private void _fb_plot_four_ellipse_points (framebuffer , point * , ushort , ushort)
Plot on fb the four symmetric points on an ellipse described by a center and x- and y-offsets.
Plot on fb the four symmetric points on an ellipse.
Parameters
fb Framebuffer to use as canvas
center Geometric center of the ellipse
x X offset of point to plot
y Y offset of point to plot
Returns
void
Note
Points will be shaded with the value in ->shade.
Definition at line 129 of file framebuffer.c.
References fb_set_pixel(), point::shade, point::x, and point::y.
Referenced by fb_draw_ellipse().
{
     fb_set_pixel(fb, center->x + x, center->y + y, center->shade);
     fb_set_pixel(fb, center->x - x, center->y + y, center->shade);
     fb_set_pixel(fb, center->x - x, center->y - y, center->shade);
     fb_set_pixel(fb, center->x + x, center->y - y, center->shade);
 }
void fb_clear_pixel (framebuffer fb, uchar x, uchar y) inline
Clear pixel (x,y) in .
Clear pixel (x,y) in .
This is an alias for with a shade of zero.
Parameters
fb Framebuffer to use as canvas
x X coordinate
y Y coordinate
Returns
void Error behavior: when pixel (x,y) is not writeable (off screen) this function does nothing.
Definition at line 240 of file framebuffer.h.
References FB_COLOR_ERASE, and fb_set_pixel().
Referenced by fb_erase_pixel().
{
     fb_set_pixel(fb, x, y, FB_COLOR_ERASE);
 }
void fb_console_print_coordinate (uchar , uchar , shade_t)
Print a coordinate (ordered pair) to the console.
Print a coordinate (ordered pair) to the console.
Note
This function is only applicable on a computer (not for use on microcontrollers).
This function does not append a newline to the console after printing the ordered pair. To just print the ordered pair WITH a newline call function fb_console_println_coordinate instead.
Parameters
x X coordinate of the coordinate to print
y Y coordinate of the coordinate to print
shade Shade of the coodrinate to print
Returns
void
Definition at line 339 of file framebuffer.c.
{
 #ifdef __GNUC__
     printf("(%d,%d):%d", x, y, shade);
 #ifndef NDEBUG
     printf("%s This function was called in an inappropriate context.", __FUNCTION__);
     printf("Please consult the documentation.\n");
 #endif
 #endif
 }
void fb_console_print_point (point *)
Print a point (ordered pair) to the console.
Print a point (ordered pair) to the console.
Note
This function is only applicable on a computer (not for use on microcontrollers).
This function does not append a newline to the console after printing the ordered pair. To just print the ordered pair WITH a newline call function fb_console_println_point instead.
Parameters
p Point to printf to the console
Returns
void
Definition at line 316 of file framebuffer.c.
References point::shade, point::x, and point::y.
{
 #ifdef __GNUC__
     printf("(%d,%d):%d", p->x, p->y, p->shade);
 #ifndef NDEBUG
     printf("%s This function was called in an inappropriate context.\n", __FUNCTION__);
     printf("%s Please consult the documentation.\n", __FUNCTION__);
 #endif
 #endif
 }
void fb_console_println_coordinate (uchar , uchar , shade_t)
Print a coordinate (ordered pair) to the console followed by a newline.
Print a coordinate (ordered pair) to the console followed by a newline.
Note
This function is only applicable on a computer (not for use on microcontrollers).
This function appends a newline to the console after printing the ordered pair. To just print the ordered pair (sans newline) call function instead.
Parameters
x X coordinate of the coordinate to print
y Y coordinate of the coordinate to print
shade Shade of the coodrinate to print
Returns
void
Definition at line 327 of file framebuffer.c.
Referenced by fb_set_pixel().
{
 #ifdef __GNUC__
     printf("(%d,%d):%d\n", x, y, shade);
 #ifndef NDEBUG
     printf("%s This function was called in an inappropriate context.", __FUNCTION__);
     printf("Please consult the documentation.\n");
 #endif
 #endif
 }
void fb_console_println_point (point *)
Print a point (ordered pair) to the console followed by a newline.
Print a point (ordered pair) to the console followed by a newline.
Note
This function is only applicable on a computer (not for use on microcontrollers).
This function appends a newline to the console after printing the ordered pair. To just print the ordered pair (sans newline) call function instead.
Parameters
p Point to printf to the console
Returns
void
Definition at line 304 of file framebuffer.c.
References point::shade, point::x, and point::y.
{
 #ifdef __GNUC__
     printf("(%d,%d):%d\n", p->x, p->y, p->shade);
 #else
 #ifndef NDEBUG
     printf("%s This function was called in an inappropriate context.\n", __FUNCTION__);
     printf("%s Please consult the documentation.\n", __FUNCTION__);
 #endif
 #endif
 }
void fb_destroy (framebuffer)
Destroy a framebuffer object.
Destroy a framebuffer object.
Parameters
fb Framebuffer to destroy
Definition at line 22 of file framebuffer.c.
References OLED_WIDTH.
{
     unsigned char i;
     for(i = 0; i < OLED_WIDTH; ++i) {
     free(fb[i]);
     }
     free(fb);
 }
void fb_draw_anon_line (framebuffer fb, point * point1, point * point2, shade_t shade) inline
Draws a line connecting two points before destroying the two points.
Draws a line connecting two points before destroying the two points.
Parameters
fb Framebuffer to use as canvas
point1 One endpoint of the line to draw
point2 The other endpoint of the line to draw
shade Desired shade of the line on fb
Returns
void
Warning
This function destroys and .
Definition at line 315 of file framebuffer.h.
References _fb_draw_line().
{
     _fb_draw_line(fb, point1, point2, shade);
     SHDestroyPoint(point1);
     SHDestroyPoint(point2);
 }
void fb_draw_circle (framebuffer fb, circle * c) inline
Draw a circle in at with radius of color .
Draw a circle in at with radius of color .
Parameters
fb Framebuffer to use as canvas
center Center of circle to draw
radius Radius of circle to draw
shade Shade to draw circle with on fb
Returns
void
Definition at line 377 of file framebuffer.h.
References circle::center, fb_draw_ellipse(), circle::radius, and point::shade.
{
     fb_draw_ellipse(fb, c->center, c->radius, c->radius, c->center->shade);
 }
void fb_draw_ellipse (framebuffer , point * , ushort , ushort , shade_t)
Draw an ellipse in fb at center with specified x- and y-radii of color shade.
Draw an ellipse in fb at center with x- and y- radii of color shade.
Parameters
fb Framebuffer to use as canvas
center Center of ellipse to draw
x_radius X radius of specified ellipse
y_radius Y radius of specified ellipse
shade Shade to draw ellipse with on fb
Returns
void
Definition at line 147 of file framebuffer.c.
References _fb_plot_four_ellipse_points().
Referenced by fb_draw_circle().
{
     ushort x, y;
     int xx, yy, xx2, yy2, dx, dy, stop_x, stop_y, error;
     x = x_radius;
     y = 0;
     xx = x_radius * x_radius; // width^2
     yy = y_radius * y_radius; // height^2
     xx2 = xx*2;
     yy2 = yy*2;
     dx = yy * (1 - 2*x_radius);
     dy = xx;
     stop_x = yy*2*x_radius;
     stop_y = 0;
     error = 0;
     while (stop_x > stop_y) {
     _fb_plot_four_ellipse_points(fb, center, x, y);
     ++y;
     stop_y += xx2;
     error += dy;
     dy += xx2;
     if (2*error + dx > 0) {
         --x;
         stop_x -= yy2;
         error += dx;
         dx += yy2;
     }
     }
     /* First set of points is done, now plot the second set */
     x = 0;
     y = y_radius;
     dx = yy;
     dy = xx * (1 - 2*y_radius);
     error = 0;
     stop_x = 0;
     stop_y = xx2*y_radius;
     while (stop_x <= stop_y) {
     _fb_plot_four_ellipse_points(fb, center, x, y);
     x++;
     stop_x += yy2;
     error += dx;
     dx += yy2;
     if (2*error + dy > 0) {
         --y;
         stop_y -= xx2;
         error += dy;
         dy += xx2;
     }
     }
 }
void fb_draw_ellipse_fill (framebuffer , point * , ushort , ushort , shade_t)
Draw on fb a shaded ellipse described by center, x- and y-radii.
Draw on fb a shaded ellipse described by center, x- and y-radii.
Parameters
fb Framebuffer to use as canvas
center Gemoetric center of the ellipse
x_radius X radius of ellipse to plot
y_radius Y radius of ellipse to plot
shade Color to fill ellipse with
OPTIONAL: allow for different specified border color
Definition at line 211 of file framebuffer.c.
References _fb_fill_four_ellipse_points(), fb_set_pixel(), point::shade, point::x, and point::y.
{
     ushort x, y;
     int xx, yy, xx2, yy2, dx, dy, last_y_filled, stop_x, stop_y, error, i;
     xx = x_radius * x_radius; // width^2
     yy = y_radius * y_radius; // height^2
     xx2 = xx*2;
     yy2 = yy*2;
     error = 0;
     // fill the horizontal diameter
     for (i = -x_radius; i <= x_radius; ++i) {
     fb_set_pixel(fb, center->x + i, center->y, center->shade);
     }
     /* First set of points is done, now plot the second set */
     x = 0;
     y = y_radius;
     dx = yy;
     dy = xx * (1 - 2*y_radius);
     stop_x = 0;
     stop_y = xx2*y_radius;
     // OPTIONAL OPTIMIZE: this loop
     last_y_filled = y;
     while (stop_x <= stop_y) {
     if (y != last_y_filled) {
         _fb_fill_four_ellipse_points(fb, center, x, y);
         last_y_filled = y;
     }
     x++;
     stop_x += yy2;
     error += dx;
     dx += yy2;
     if (2*error + dy > 0) {
         --y;
         stop_y -= xx2;
         error += dy;
         dy += xx2;
     }
     }
 }
void fb_draw_line (framebuffer fb, point * point1, point * point2, shade_t shade) inline
Draw a line segment on from to of color .to of color .shade.
Draw a line segment on from to of color .
Parameters
fb Framebuffer to use as canvas
point1 Beginning of line segment
point2 End of line segment
shade Color of line segment
Returns
void
Definition at line 333 of file framebuffer.h.
References _fb_draw_line().
Referenced by fb_draw_line_gradient().
{
     _fb_draw_line(fb, point1, point2, shade);
 }
void fb_draw_line_gradient (framebuffer fb, point * point1, point * point2, shade_t shade) inline
Draw a line segment on from to .
Draw a line segment on from to .
Parameters
fb Framebuffer to use as canvas
point1 Beginning of line segment
point2 End of line segment
Returns
void
Bug:
This function is not implemented yet (pass-through).
Definition at line 347 of file framebuffer.h.
References fb_draw_line().
Referenced by _fb_draw_shape().
{
     fb_draw_line(fb, point1, point2, shade);
 }
void fb_draw_shape (framebuffer , shape *)
Using as a canvas, draw .
Using as a canvas, draw .
Parameters
fb Framebuffer to use as canvas
sh Shape to draw
Returns
void This function can also draw points and lines, i.e. a shape with only one or two points respectively.
Definition at line 31 of file framebuffer.c.
References _fb_draw_shape(), null, shape::points, and point::shade.
Referenced by fb_draw_shape_arr(), and fb_draw_shapes().
{
     if (sh->points[0] != null) {
     _fb_draw_shape(fb, sh, sh->points[0]->shade);
     }
 }
void fb_draw_shape_arr (framebuffer , ushort , shape **)
Method to draw an array of shapes on . Method to draw an array of shapes on .
Parameters
fb Framebuffer to use as canvas
numShapes Number of shapes to draw
shape_arr Array of shapes to draw
Returns
void
Definition at line 68 of file framebuffer.c.
References fb_draw_shape().
{
     unsigned char i;
     for(i=0; i < numShapes; ++i) {
     fb_draw_shape(fb, shape_arr[i]);
     }
 }
void fb_draw_shapes (framebuffer , ushort , ...)
Method to draw multiple shapes on . Method to draw multiple shapes on . Provide the number of shapes to draw for va_args.
Parameters
fb Framebuffer to use as canvas
numShapes Number of shapes to draw
Returns
void
Definition at line 56 of file framebuffer.c.
References fb_draw_shape().
{
     unsigned char i;
     va_list args;
     va_start(args, numShapes);
     for(i=0; i < numShapes; ++i) {
     fb_draw_shape(fb, va_arg(args, shape*));
     }
     va_end(args);                 /* clean up the list */
 }
void fb_draw_string (framebuffer fb, point * top_left_corner, char * string) inline
Draw string on fb starting at top_left_corner.
Draw string on starting at .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner of string on fb
string Character array to draw
Returns
void
Definition at line 115 of file framebuffer.h.
References _fb_draw_string().
{
     _fb_draw_string(fb, top_left_corner, string);
 }
void fb_draw_string_anon_pt (framebuffer fb, point * top_left_corner, char * string) inline
Call fb_draw_string and destroy top_left_corner.
Call and destroy .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner of string on fb. Will be destroyed.
string Character array to draw
Returns
void
Definition at line 130 of file framebuffer.h.
References _fb_draw_string().
{
     _fb_draw_string(fb, top_left_corner, string);
     free(top_left_corner);
 }
void fb_erase_anon_line (framebuffer fb, point * point1, point * point2) inline
Erases a line connecting two points before destroys the two points.
Erases a line connecting two points before destroys the two points.
Parameters
fb Framebuffer to use as canvas
point1 One endpoint of the line to draw
point2 The other endpoint of the line to draw
shade Desired shade of the line on fb
Returns
void
Warning
This function destroys and .
Definition at line 283 of file framebuffer.h.
References _fb_draw_line(), and FB_COLOR_ERASE.
{
     _fb_draw_line(fb, point1, point2, FB_COLOR_ERASE);
     SHDestroyPoint(point1);
     SHDestroyPoint(point2);
 }
void fb_erase_char (framebuffer , point * , char)
Erase char on fb starting at top_left_corner.
Erase char on starting at .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner on char on fb
c Char to erase from fb
Returns
void In order to erase a char successfully the fonts, char and coordinates must be identical. This will clear the values of the affected pixels; it is a destructive action and will not 'undo' changes to the canvas.
Definition at line 96 of file framebuffer.c.
References _fb_draw_char(), FB_COLOR_ERASE, point::shade, and shape_duplicate_point().
{
     point* pen = shape_duplicate_point(top_left_corner);
     pen->shade = FB_COLOR_ERASE;
     _fb_draw_char(fb, pen, c);
     SHDestroyPoint(pen);
 }
void fb_erase_char_anon (framebuffer fb, point * top_left_corner, char c) inline
Call and free .
Call and free .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of on char on . Will be destroyed.
c Char to erase from
Returns
void In order to erase a char successfully the fonts, char and coordinates must be identical. This will clear the values of the affected pixels; it is a destructive action and will not 'undo' changes to the canvas.
Definition at line 89 of file framebuffer.h.
{
     fb_erase_char_anon(fb, top_left_corner, c);
     free(top_left_corner);
 }
void fb_erase_line (framebuffer fb, point * point1, point * point2) inline
Remove a line segment on from to .
Remove a line segment on from to .
Parameters
fb Framebuffer to use as canvas
a Beginning of line segment
b End of line segment
Returns
void
Definition at line 299 of file framebuffer.h.
References _fb_draw_line(), and FB_COLOR_ERASE.
{
     _fb_draw_line(fb, point1, point2, FB_COLOR_ERASE);
 }
void fb_erase_pixel (framebuffer fb, uchar x, uchar y) inline
Erase pixel (x,y) in .
Erase pixel (x,y) in .
This is an alias for with a shade of zero.
Parameters
fb Framebuffer to use as canvas
x X coordinate
y Y coordinate
Returns
void Error behavior: when pixel (x,y) is not writeable (off screen) this function does nothing.
Definition at line 256 of file framebuffer.h.
References fb_clear_pixel().
{
     fb_clear_pixel(fb, x, y);
 }
void fb_erase_shape (framebuffer fb, shape * sh) inline
Using as a canvas, draw .
Using as a canvas, draw .
Parameters
fb Framebuffer to use as canvas
sh Shape to draw
Returns
void
Note
This function can also draw points and lines, i.e. a shape with only one or two points respectively.
Definition at line 211 of file framebuffer.h.
References _fb_draw_shape(), and FB_COLOR_ERASE.
Referenced by fb_erase_shape_arr().
{
     _fb_draw_shape(fb, sh, FB_COLOR_ERASE);
 }
void fb_erase_shape_arr (framebuffer , ushort , shape **)
Method to erase an array of shapes from . Method to erase an array of shapes from .
Parameters
fb Framebuffer to use as canvas
numShapes Number of shapes to erase
shape_arr Array containing shapes to erase
Returns
void
Definition at line 76 of file framebuffer.c.
References fb_erase_shape().
{
     unsigned char i;
     for(i=0; i < numShapes; ++i) {
     fb_erase_shape(fb, shape_arr[i]);
     }
 }
void fb_erase_string (framebuffer , point * , char *)
Erase string on fb starting at top_left_corner.
Erase on starting at .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner of string on fb
string String to erase from fb
Returns
void In order to erase a string successfully the fonts, char arrays and coordinates must be identical. This will clear the values of the affected pixels; it is a destructive action and will not 'undo' changes to the canvas.
Definition at line 260 of file framebuffer.c.
References _fb_draw_string(), FB_COLOR_ERASE, point::shade, and shape_duplicate_point().
Referenced by fb_erase_string_anon().
{
     point* pt = shape_duplicate_point(top_left_corner);
     pt->shade = FB_COLOR_ERASE;
     _fb_draw_string(fb, pt, string);
     SHDestroyPoint(pt);
 }
void fb_erase_string_anon (framebuffer fb, point * top_left_corner, char * string) inline
Erase string on fb starting at top_left_corner and free top_left_corner.
Call and free .
Parameters
fb Framebuffer to use as canvas
top_left_corner Coordinate of top left corner of string on fb
string String to erase from fb
Returns
void In order to erase a string successfully the fonts, char arrays and coordinates must be identical. This will clear the values of the affected pixels; it is a destructive action and will not 'undo' changes to the canvas.
Definition at line 55 of file framebuffer.h.
References fb_erase_string().
{
     fb_erase_string(fb, top_left_corner, string);
     free(top_left_corner);
 }
framebuffer fb_init (void)
Create a framebuffer object and return the handle.
Create a framebuffer object and return the handle.
Returns
framebuffer Newly malloc'd framebuffer
Definition at line 11 of file framebuffer.c.
References OLED_HEIGHT, and OLED_WIDTH.
                       {
     /* OPTIONAL OPTIMIZE: bit-strap this struct to reduce memory consumption */
     unsigned char i;
     unsigned char** fb = (unsigned char**) calloc(OLED_WIDTH, sizeof(unsigned char*));
     for(i = 0; i < OLED_WIDTH; ++i) {
     fb[i] = (unsigned char*) calloc(OLED_HEIGHT, sizeof(unsigned char));
     }
     return (framebuffer) fb;
 }
void fb_set_pixel (framebuffer , uchar , uchar , shade_t)
In fb, set pixel (x,y) to .
In , set pixel (x,y) to .
Parameters
fb Framebuffer to use as canvas
x X coordinate
y Y coordinate
shade Shade to set pixel
Returns
void Error behavior: when pixel (x,y) is not writeable (off screen) this function does nothing.
Definition at line 84 of file framebuffer.c.
References fb_console_println_coordinate(), FB_HEIGHT, and FB_WIDTH.
Referenced by _fb_draw_char(), _fb_draw_line(), _fb_fill_four_ellipse_points(), _fb_plot_four_ellipse_points(), fb_clear_pixel(), and fb_draw_ellipse_fill().
{
     if (x < FB_WIDTH && y < FB_HEIGHT) {
     fb[x][y] = shade;
     } else {
 #ifndef NDEBUG
     printf("%sPixel off screen: ", __FUNCTION__);
     fb_console_println_coordinate(x, y, shade);
 #endif
     }
 }