EE445M RTOS: Semaphore
Semaphore
Classes
class semaphore
Functions
semaphore::semaphore ()
semaphore::semaphore (int16_t initial_value)
void semaphore::init (void)
void semaphore::post (void)
void semaphore::wait (void)
void semaphore::take (void)
bool semaphore::guard (void)
bool semaphore::blocked (void)
void semaphore::reset (void)
Variables
int16_t semaphore::value
uint32_t semaphore::total_posts
Detailed Description
Function Documentation
bool semaphore::blocked (void)
True if the semaphore is blocked.
Definition at line 68 of file semaphorepp.cpp.
References value.
Referenced by wait().
{
     return value <= 0;
 }
bool semaphore::guard (void)
without the waiting – take if ready, leave if not.
Warning
this decrements the semaphore if the return value is true.
Definition at line 57 of file semaphorepp.cpp.
References critical::EndCritical(), critical::StartCritical(), and value.
Referenced by can_handler(), motor_control(), ping_handler(), shell_handler(), switch_responder(), thread_blink_blue(), thread_blink_green(), and thread_blink_red().
                       {
     uint32_t status = StartCritical();
     bool ret = value > 0;
     if (ret) {
         --value;
     }
     EndCritical(status);
     return ret;
 }
void semaphore::init (void)
Definition at line 21 of file semaphorepp.cpp.
References total_posts.
Referenced by semaphore().
                      {
 #if TEST_SEMAPHORE == 1
     total_posts = 0;
 #endif
 }
void semaphore::post (void)
Increment the semaphore.
Definition at line 45 of file semaphorepp.cpp.
References critical::EndCritical(), critical::StartCritical(), total_posts, and value.
Referenced by CAN0_Handler(), lswitch::end_debounce(), ping::handle_timer(), shell::motor_start(), shell::motor_stop(), buffer< int32_t, N >::notify(), and ping::start().
                      {
     int32_t status = StartCritical();
     ++value;
 #if TEST_SEMAPHORE == 1
     ++total_posts;
 #endif
     EndCritical(status);
 }
void semaphore::reset (void)
Reset the semaphore.
Definition at line 28 of file semaphorepp.cpp.
References critical::EndCritical(), critical::StartCritical(), and value.
Referenced by semaphore(), and ping::stop().
                       {
     int32_t status = StartCritical();
     value = 0;
     EndCritical(status);
 }
semaphore::semaphore ()
Definition at line 7 of file semaphorepp.cpp.
References init(), and reset().
                      {
     init();
     reset();
 }
semaphore::semaphore (int16_t initial_value)
Definition at line 13 of file semaphorepp.cpp.
References critical::EndCritical(), init(), critical::StartCritical(), and value.
{
     int32_t status = StartCritical();
     value = initial_value;
     EndCritical(status);
     init();
 }
void semaphore::take (void)
Take the semaphore
void semaphore::wait (void)
Wait on a semaphore.
Definition at line 35 of file semaphorepp.cpp.
References blocked(), critical::EndCritical(), critical::StartCritical(), and value.
                      {
     while(blocked()) {
         os_surrender_context();
     }
     int32_t status = StartCritical();
     --value;
     EndCritical(status);
 }
Variable Documentation
uint32_t semaphore::total_posts private
Definition at line 21 of file semaphorepp.hpp.
Referenced by init(), and post().
int16_t semaphore::value private
Definition at line 19 of file semaphorepp.hpp.
Referenced by blocked(), guard(), post(), reset(), semaphore(), and wait().