EE445M RTOS: Button I/O library
Button I/O library
Macros
#define button_metadata_init_(_name, _base, _pin, _interrupt)
#define button_metadata_init(_base, _pin, _interrupt) button_metadata_init_(button_metadata, _base, _pin, _interrupt)
#define BUTTON_LEFT GPIO_PIN_4
#define BUTTON_RIGHT GPIO_PIN_0
#define BUTTONS_BOTH (BUTTON_LEFT | BUTTON_RIGHT)
Functions
void button_init (hw_metadata)
void button_set_interrupt (hw_metadata)
Detailed Description
Macro Definition Documentation
#define BUTTON_LEFT GPIO_PIN_4
Definition at line 26 of file button.h.
Referenced by postpone_suicide(), and update_pid().
#define button_metadata_init (_base, _pin, _interrupt) button_metadata_init_(button_metadata, _base, _pin, _interrupt)
Create a hardware_metadata struct named `button_metadata'
Definition at line 23 of file button.h.
Referenced by GPIOPortF_Handler(), and main().
#define button_metadata_init_ (_name, _base, _pin, _interrupt)
Value:
hw_metadata _name;                      \
    _name.button = (hw_button_metadata) {           \
    .base     = (memory_address_t) _base,           \
    .pin      = (memory_address_t) _pin,            \
    .interrupt = (uint32_t) _interrupt          \
    }
Create a struct named _name.
Definition at line 13 of file button.h.
#define BUTTON_RIGHT GPIO_PIN_0
Definition at line 27 of file button.h.
Referenced by postpone_suicide(), and update_pid().
#define BUTTONS_BOTH (BUTTON_LEFT | BUTTON_RIGHT)
Definition at line 28 of file button.h.
Referenced by button_debounce_end(), button_debounce_start(), GPIOPortF_Handler(), and main().
Function Documentation
void button_init (hw_metadata)
Initialize buttons for use as input.
Note
Currently only supports on-board peripherals.
Definition at line 22 of file button.c.
References hw_metadata::button, GPIO_DIR_MODE_IN, GPIO_LOCK_KEY, GPIO_O_CR, GPIO_O_LOCK, GPIO_PIN_TYPE_STD_WPU, GPIO_PORTF_BASE, GPIO_STRENGTH_2MA, GPIODirModeSet(), GPIOIntEnable(), GPIOPadConfigSet(), HWREG, and hw_button_metadata::pin.
Referenced by hw_driver_init().
{
     GPIODirModeSet(GPIO_PORTF_BASE, metadata.button.pin, GPIO_DIR_MODE_IN);
     HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
     HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x01;
     HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = 0;
     GPIOPadConfigSet(GPIO_PORTF_BASE, metadata.button.pin,
                      GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
     GPIOIntEnable(GPIO_PORTF_BASE, metadata.button.pin);
 }
void button_set_interrupt (hw_metadata)
Subscribe to a hardware interrupt.
Parameters
Hardware target to subscribe to and isr to invoke upon interrupt
Definition at line 35 of file button.c.
References hw_button_metadata::base, hw_metadata::button, GPIOIntTypeSet(), INT_GPIOF_TM4C123, IntDisable(), IntEnable(), hw_button_metadata::interrupt, and hw_button_metadata::pin.
Referenced by hw_channel_init().
{
     if (metadata.button.interrupt) {
         GPIOIntTypeSet(metadata.button.base,
                        metadata.button.pin,
                        metadata.button.interrupt);
         IntEnable(INT_GPIOF_TM4C123);
     } else {
         IntDisable(INT_GPIOF_TM4C123);
     }
 }