EE445M RTOS: Uartstdio_api
Uartstdio_api
Functions
void UARTStdioConfig (uint32_t ui32PortNum, uint32_t ui32Baud, uint32_t ui32SrcClock)
int UARTwrite (const char *pcBuf, uint32_t ui32Len)
int UARTgets (char *pcBuf, uint32_t ui32Len)
unsigned char UARTgetc (void)
void UARTvprintf (const char *pcString, va_list vaArgP)
void UARTprintf (const char *pcString,...)
Variables
static uint32_t g_ui32Base = 0
static const char *const g_pcHex = "0123456789abcdef"
static const uint32_t g_ui32UARTBase [3]
static const uint32_t g_ui32UARTPeriph [3]
Detailed Description
Function Documentation
unsigned char UARTgetc (void)
Read a single character from the UART, blocking if necessary.
This function will receive a single character from the UART and store it at the supplied address.
In both buffered and unbuffered modes, this function will block until a character is received. If non-blocking operation is required in buffered mode, a call to UARTRxAvail() may be made to determine whether any characters are currently available for reading.
Returns
Returns the character read.
Definition at line 786 of file uartstdio.c.
References g_ui32Base, and MAP_UARTCharGet.
 {
 #ifdef UART_BUFFERED
     unsigned char cChar;
     //
     // Wait for a character to be received.
     //
     while(RX_BUFFER_EMPTY)
     {
         //
         // Block waiting for a character to be received (if the buffer is
         // currently empty).
         //
     }
     //
     // Read a character from the buffer.
     //
     cChar = g_pcUARTRxBuffer[g_ui32UARTRxReadIndex];
     ADVANCE_RX_BUFFER_INDEX(g_ui32UARTRxReadIndex);
     //
     // Return the character to the caller.
     //
     return(cChar);
 #else
     //
     // Block until a character is received by the UART then return it to
     // the caller.
     //
     return(MAP_UARTCharGet(g_ui32Base));
 #endif
 }
int UARTgets (char * pcBuf, uint32_t ui32Len)
A simple UART based get string function, with some line processing.
Parameters
pcBuf points to a buffer for the incoming string from the UART.
ui32Len is the length of the buffer for storage of the string, including the trailing 0.
This function will receive a string from the UART input and store the characters in the buffer pointed to by pcBuf. The characters will continue to be stored until a termination character is received. The termination characters are CR, LF, or ESC. A CRLF pair is treated as a single termination character. The termination characters are not stored in the string. The string will be terminated with a 0 and the function will return.
In both buffered and unbuffered modes, this function will block until a termination character is received. If non-blocking operation is required in buffered mode, a call to UARTPeek() may be made to determine whether a termination character already exists in the receive buffer prior to calling UARTgets().
Since the string will be null terminated, the user must ensure that the buffer is sized to allow for the additional null character.
Returns
Returns the count of characters that were stored, not including the trailing 0.
Definition at line 569 of file uartstdio.c.
References ASSERT, g_ui32Base, MAP_UARTCharGet, MAP_UARTCharPut, and UARTwrite().
 {
 #ifdef UART_BUFFERED
     uint32_t ui32Count = 0;
     int8_t cChar;
     //
     // Check the arguments.
     //
     ASSERT(pcBuf != 0);
     ASSERT(ui32Len != 0);
     ASSERT(g_ui32Base != 0);
     //
     // Adjust the length back by 1 to leave space for the trailing
     // null terminator.
     //
     ui32Len--;
     //
     // Process characters until a newline is received.
     //
     while(1)
     {
         //
         // Read the next character from the receive buffer.
         //
         if(!RX_BUFFER_EMPTY)
         {
             cChar = g_pcUARTRxBuffer[g_ui32UARTRxReadIndex];
             ADVANCE_RX_BUFFER_INDEX(g_ui32UARTRxReadIndex);
             //
             // See if a newline or escape character was received.
             //
             if((cChar == '\r') || (cChar == '\n') || (cChar == 0x1b))
             {
                 //
                 // Stop processing the input and end the line.
                 //
                 break;
             }
             //
             // Process the received character as long as we are not at the end
             // of the buffer.  If the end of the buffer has been reached then
             // all additional characters are ignored until a newline is
             // received.
             //
             if(ui32Count < ui32Len)
             {
                 //
                 // Store the character in the caller supplied buffer.
                 //
                 pcBuf[ui32Count] = cChar;
                 //
                 // Increment the count of characters received.
                 //
                 ui32Count++;
             }
         }
     }
     //
     // Add a null termination to the string.
     //
     pcBuf[ui32Count] = 0;
     //
     // Return the count of int8_ts in the buffer, not counting the trailing 0.
     //
     return(ui32Count);
 #else
     uint32_t ui32Count = 0;
     int8_t cChar;
     static int8_t bLastWasCR = 0;
     //
     // Check the arguments.
     //
     ASSERT(pcBuf != 0);
     ASSERT(ui32Len != 0);
     ASSERT(g_ui32Base != 0);
     //
     // Adjust the length back by 1 to leave space for the trailing
     // null terminator.
     //
     ui32Len--;
     //
     // Process characters until a newline is received.
     //
     while(1)
     {
         //
         // Read the next character from the console.
         //
         cChar = MAP_UARTCharGet(g_ui32Base);
         //
         // See if the backspace key was pressed.
         //
         if(cChar == '\b')
         {
             //
             // If there are any characters already in the buffer, then delete
             // the last.
             //
             if(ui32Count)
             {
                 //
                 // Rub out the previous character.
                 //
                 UARTwrite("\b \b", 3);
                 //
                 // Decrement the number of characters in the buffer.
                 //
                 ui32Count--;
             }
             //
             // Skip ahead to read the next character.
             //
             continue;
         }
         //
         // If this character is LF and last was CR, then just gobble up the
         // character because the EOL processing was taken care of with the CR.
         //
         if((cChar == '\n') && bLastWasCR)
         {
             bLastWasCR = 0;
             continue;
         }
         //
         // See if a newline or escape character was received.
         //
         if((cChar == '\r') || (cChar == '\n') || (cChar == 0x1b))
         {
             //
             // If the character is a CR, then it may be followed by a LF which
             // should be paired with the CR.  So remember that a CR was
             // received.
             //
             if(cChar == '\r')
             {
                 bLastWasCR = 1;
             }
             //
             // Stop processing the input and end the line.
             //
             break;
         }
         //
         // Process the received character as long as we are not at the end of
         // the buffer.  If the end of the buffer has been reached then all
         // additional characters are ignored until a newline is received.
         //
         if(ui32Count < ui32Len)
         {
             //
             // Store the character in the caller supplied buffer.
             //
             pcBuf[ui32Count] = cChar;
             //
             // Increment the count of characters received.
             //
             ui32Count++;
             //
             // Reflect the character back to the user.
             //
             MAP_UARTCharPut(g_ui32Base, cChar);
         }
     }
     //
     // Add a null termination to the string.
     //
     pcBuf[ui32Count] = 0;
     //
     // Send a CRLF pair to the terminal to end the line.
     //
     UARTwrite("\r\n", 2);
     //
     // Return the count of int8_ts in the buffer, not counting the trailing 0.
     //
     return(ui32Count);
 #endif
 }
void UARTprintf (const char * pcString, ...)
A simple UART based printf function supporting %c, %d, %p, %s, %u, %x, and %X.
Parameters
pcString is the format string.
... are the optional arguments, which depend on the contents of the format string.
This function is very similar to the C library fprintf() function. All of its output will be sent to the UART. Only the following formatting characters are supported:
%c to print a character
%d or %i to print a decimal value
%s to print a string
%u to print an unsigned decimal value
%x to print a hexadecimal value using lower case letters
%X to print a hexadecimal value using lower case letters (not upper case letters as would typically be used)
%p to print a pointer as a hexadecimal value
%% to print out a % character
For %s, %d, %i, %u, %p, %x, and %X, an optional number may reside between the % and the format character, which specifies the minimum number of characters to use for that value; if preceded by a 0 then the extra characters will be filled with zeros instead of spaces. For example, \%8d'' will use eight characters to print the decimal value with spaces added to reach eight;%08d'' will use eight characters as well but will add zeroes instead of spaces.
The type of the arguments after pcString must match the requirements of the format string. For example, if an integer was passed where a string was expected, an error of some kind will most likely occur.
Returns
None.
Definition at line 1292 of file uartstdio.c.
References UARTvprintf().
 {
     va_list vaArgP;
     //
     // Start the varargs processing.
     //
     va_start(vaArgP, pcString);
     UARTvprintf(pcString, vaArgP);
     //
     // We're finished with the varargs now.
     //
     va_end(vaArgP);
 }
void UARTStdioConfig (uint32_t ui32PortNum, uint32_t ui32Baud, uint32_t ui32SrcClock)
Determines whether the ring buffer whose pointers and size are provided is full or not.
Parameters
pui32Read points to the read index for the buffer.
pui32Write points to the write index for the buffer.
ui32Size is the size of the buffer in bytes.
This function is used to determine whether or not a given ring buffer is full. The structure of the code is specifically to ensure that we do not see warnings from the compiler related to the order of volatile accesses being undefined.
Returns
Returns true if the buffer is full or false otherwise. Determines whether the ring buffer whose pointers and size are provided is empty or not.
Parameters
pui32Read points to the read index for the buffer.
pui32Write points to the write index for the buffer.
This function is used to determine whether or not a given ring buffer is empty. The structure of the code is specifically to ensure that we do not see warnings from the compiler related to the order of volatile accesses being undefined.
Returns
Returns true if the buffer is empty or false otherwise. Determines the number of bytes of data contained in a ring buffer.
Parameters
pui32Read points to the read index for the buffer.
pui32Write points to the write index for the buffer.
ui32Size is the size of the buffer in bytes.
This function is used to determine how many bytes of data a given ring buffer currently contains. The structure of the code is specifically to ensure that we do not see warnings from the compiler related to the order of volatile accesses being undefined.
Returns
Returns the number of bytes of data currently in the buffer. Configures the UART console.
Parameters
ui32PortNum is the number of UART port to use for the serial console (0-2)
ui32Baud is the bit rate that the UART is to be configured to use.
ui32SrcClock is the frequency of the source clock for the UART module.
This function will configure the specified serial port to be used as a serial console. The serial parameters are set to the baud rate specified by the ui32Baud parameter and use 8 bit, no parity, and 1 stop bit.
This function must be called prior to using any of the other UART console functions: UARTprintf() or UARTgets(). This function assumes that the caller has previously configured the relevant UART pins for operation as a UART rather than as GPIOs.
Returns
None.
Definition at line 334 of file uartstdio.c.
References ASSERT, g_ui32Base, g_ui32UARTBase, g_ui32UARTPeriph, MAP_IntEnable, MAP_SysCtlPeripheralEnable, MAP_SysCtlPeripheralPresent, MAP_UARTConfigSetExpClk, MAP_UARTEnable, MAP_UARTFIFOLevelSet, MAP_UARTIntDisable, MAP_UARTIntEnable, UART_CONFIG_PAR_NONE, UART_CONFIG_STOP_ONE, UART_CONFIG_WLEN_8, UART_FIFO_RX1_8, UART_FIFO_TX1_8, UART_INT_RT, and UART_INT_RX.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32PortNum == 0) || (ui32PortNum == 1) ||
            (ui32PortNum == 2));
 #ifdef UART_BUFFERED
     //
     // In buffered mode, we only allow a single instance to be opened.
     //
     ASSERT(g_ui32Base == 0);
 #endif
     //
     // Check to make sure the UART peripheral is present.
     //
     if(!MAP_SysCtlPeripheralPresent(g_ui32UARTPeriph[ui32PortNum]))
     {
         return;
     }
     //
     // Select the base address of the UART.
     //
     g_ui32Base = g_ui32UARTBase[ui32PortNum];
     //
     // Enable the UART peripheral for use.
     //
     MAP_SysCtlPeripheralEnable(g_ui32UARTPeriph[ui32PortNum]);
     //
     // Configure the UART for 115200, n, 8, 1
     //
     MAP_UARTConfigSetExpClk(g_ui32Base, ui32SrcClock, ui32Baud,
                             (UART_CONFIG_PAR_NONE | UART_CONFIG_STOP_ONE |
                              UART_CONFIG_WLEN_8));
 #ifdef UART_BUFFERED
     //
     // Set the UART to interrupt whenever the TX FIFO is almost empty or
     // when any character is received.
     //
     MAP_UARTFIFOLevelSet(g_ui32Base, UART_FIFO_TX1_8, UART_FIFO_RX1_8);
     //
     // Flush both the buffers.
     //
     UARTFlushRx();
     UARTFlushTx(true);
     //
     // Remember which interrupt we are dealing with.
     //
     g_ui32PortNum = ui32PortNum;
     //
     // We are configured for buffered output so enable the master interrupt
     // for this UART and the receive interrupts.  We don't actually enable the
     // transmit interrupt in the UART itself until some data has been placed
     // in the transmit buffer.
     //
     MAP_UARTIntDisable(g_ui32Base, 0xFFFFFFFF);
     MAP_UARTIntEnable(g_ui32Base, UART_INT_RX | UART_INT_RT);
     MAP_IntEnable(g_ui32UARTInt[ui32PortNum]);
 #endif
     //
     // Enable the UART operation.
     //
     MAP_UARTEnable(g_ui32Base);
 }
void UARTvprintf (const char * pcString, va_list vaArgP)
A simple UART based vprintf function supporting %c, %d, %p, %s, %u, %x, and %X.
Parameters
pcString is the format string.
vaArgP is a variable argument list pointer whose content will depend upon the format string passed in pcString.
This function is very similar to the C library vprintf() function. All of its output will be sent to the UART. Only the following formatting characters are supported:
%c to print a character
%d or %i to print a decimal value
%s to print a string
%u to print an unsigned decimal value
%x to print a hexadecimal value using lower case letters
%X to print a hexadecimal value using lower case letters (not upper case letters as would typically be used)
%p to print a pointer as a hexadecimal value
%% to print out a % character
For %s, %d, %i, %u, %p, %x, and %X, an optional number may reside between the % and the format character, which specifies the minimum number of characters to use for that value; if preceded by a 0 then the extra characters will be filled with zeros instead of spaces. For example, \%8d'' will use eight characters to print the decimal value with spaces added to reach eight;%08d'' will use eight characters as well but will add zeroes instead of spaces.
The type of the arguments in the variable arguments list must match the requirements of the format string. For example, if an integer was passed where a string was expected, an error of some kind will most likely occur.
Returns
None.
Definition at line 860 of file uartstdio.c.
References ASSERT, g_pcHex, and UARTwrite().
Referenced by UARTprintf().
 {
     uint32_t ui32Idx, ui32Value, ui32Pos, ui32Count, ui32Base, ui32Neg;
     char *pcStr, pcBuf[16], cFill;
     //
     // Check the arguments.
     //
     ASSERT(pcString != 0);
     //
     // Loop while there are more characters in the string.
     //
     while(*pcString)
     {
         //
         // Find the first non-% character, or the end of the string.
         //
         for(ui32Idx = 0;
             (pcString[ui32Idx] != '%') && (pcString[ui32Idx] != '\0');
             ui32Idx++)
         {
         }
         //
         // Write this portion of the string.
         //
         UARTwrite(pcString, ui32Idx);
         //
         // Skip the portion of the string that was written.
         //
         pcString += ui32Idx;
         //
         // See if the next character is a %.
         //
         if(*pcString == '%')
         {
             //
             // Skip the %.
             //
             pcString++;
             //
             // Set the digit count to zero, and the fill character to space
             // (in other words, to the defaults).
             //
             ui32Count = 0;
             cFill = ' ';
             //
             // It may be necessary to get back here to process more characters.
             // Goto's aren't pretty, but effective.  I feel extremely dirty for
             // using not one but two of the beasts.
             //
 again:
             //
             // Determine how to handle the next character.
             //
             switch(*pcString++)
             {
                 //
                 // Handle the digit characters.
                 //
                 case '0':
                 case '1':
                 case '2':
                 case '3':
                 case '4':
                 case '5':
                 case '6':
                 case '7':
                 case '8':
                 case '9':
                 {
                     //
                     // If this is a zero, and it is the first digit, then the
                     // fill character is a zero instead of a space.
                     //
                     if((pcString[-1] == '0') && (ui32Count == 0))
                     {
                         cFill = '0';
                     }
                     //
                     // Update the digit count.
                     //
                     ui32Count *= 10;
                     ui32Count += pcString[-1] - '0';
                     //
                     // Get the next character.
                     //
                     goto again;
                 }
                 //
                 // Handle the %c command.
                 //
                 case 'c':
                 {
                     //
                     // Get the value from the varargs.
                     //
                     ui32Value = va_arg(vaArgP, uint32_t);
                     //
                     // Print out the character.
                     //
                     UARTwrite((char *)&ui32Value, 1);
                     //
                     // This command has been handled.
                     //
                     break;
                 }
                 //
                 // Handle the %d and %i commands.
                 //
                 case 'd':
                 case 'i':
                 {
                     //
                     // Get the value from the varargs.
                     //
                     ui32Value = va_arg(vaArgP, uint32_t);
                     //
                     // Reset the buffer position.
                     //
                     ui32Pos = 0;
                     //
                     // If the value is negative, make it positive and indicate
                     // that a minus sign is needed.
                     //
                     if((int32_t)ui32Value < 0)
                     {
                         //
                         // Make the value positive.
                         //
                         ui32Value = -(int32_t)ui32Value;
                         //
                         // Indicate that the value is negative.
                         //
                         ui32Neg = 1;
                     }
                     else
                     {
                         //
                         // Indicate that the value is positive so that a minus
                         // sign isn't inserted.
                         //
                         ui32Neg = 0;
                     }
                     //
                     // Set the base to 10.
                     //
                     ui32Base = 10;
                     //
                     // Convert the value to ASCII.
                     //
                     goto convert;
                 }
                 //
                 // Handle the %s command.
                 //
                 case 's':
                 {
                     //
                     // Get the string pointer from the varargs.
                     //
                     pcStr = va_arg(vaArgP, char *);
                     //
                     // Determine the length of the string.
                     //
                     for(ui32Idx = 0; pcStr[ui32Idx] != '\0'; ui32Idx++)
                     {
                     }
                     //
                     // Write the string.
                     //
                     UARTwrite(pcStr, ui32Idx);
                     //
                     // Write any required padding spaces
                     //
                     if(ui32Count > ui32Idx)
                     {
                         ui32Count -= ui32Idx;
                         while(ui32Count--)
{
                             UARTwrite(" ", 1);
                         }
                     }
                     //
                     // This command has been handled.
                     //
                     break;
                 }
                 //
                 // Handle the %u command.
                 //
                 case 'u':
                 {
                     //
                     // Get the value from the varargs.
                     //
                     ui32Value = va_arg(vaArgP, uint32_t);
                     //
                     // Reset the buffer position.
                     //
                     ui32Pos = 0;
                     //
                     // Set the base to 10.
                     //
                     ui32Base = 10;
                     //
                     // Indicate that the value is positive so that a minus sign
                     // isn't inserted.
                     //
                     ui32Neg = 0;
                     //
                     // Convert the value to ASCII.
                     //
                     goto convert;
                 }
                 //
                 // Handle the %x and %X commands.  Note that they are treated
                 // identically; in other words, %X will use lower case letters
                 // for a-f instead of the upper case letters it should use.  We
                 // also alias %p to %x.
                 //
                 case 'x':
                 case 'X':
                 case 'p':
                 {
                     //
                     // Get the value from the varargs.
                     //
                     ui32Value = va_arg(vaArgP, uint32_t);
                     //
                     // Reset the buffer position.
                     //
                     ui32Pos = 0;
                     //
                     // Set the base to 16.
                     //
                     ui32Base = 16;
                     //
                     // Indicate that the value is positive so that a minus sign
                     // isn't inserted.
                     //
                     ui32Neg = 0;
                     //
                     // Determine the number of digits in the string version of
                     // the value.
                     //
 convert:
                     for(ui32Idx = 1;
                         (((ui32Idx * ui32Base) <= ui32Value) &&
                          (((ui32Idx * ui32Base) / ui32Base) == ui32Idx));
                         ui32Idx *= ui32Base, ui32Count--)
                     {
                     }
                     //
                     // If the value is negative, reduce the count of padding
                     // characters needed.
                     //
                     if(ui32Neg)
                     {
                         ui32Count--;
                     }
                     //
                     // If the value is negative and the value is padded with
                     // zeros, then place the minus sign before the padding.
                     //
                     if(ui32Neg && (cFill == '0'))
                     {
                         //
                         // Place the minus sign in the output buffer.
                         //
                         pcBuf[ui32Pos++] = '-';
                         //
                         // The minus sign has been placed, so turn off the
                         // negative flag.
                         //
                         ui32Neg = 0;
                     }
                     //
                     // Provide additional padding at the beginning of the
                     // string conversion if needed.
                     //
                     if((ui32Count > 1) && (ui32Count < 16))
                     {
                         for(ui32Count--; ui32Count; ui32Count--)
{
                             pcBuf[ui32Pos++] = cFill;
                         }
                     }
                     //
                     // If the value is negative, then place the minus sign
                     // before the number.
                     //
                     if(ui32Neg)
                     {
                         //
                         // Place the minus sign in the output buffer.
                         //
                         pcBuf[ui32Pos++] = '-';
                     }
                     //
                     // Convert the value into a string.
                     //
                     for(; ui32Idx; ui32Idx /= ui32Base)
                     {
                         pcBuf[ui32Pos++] =
                             g_pcHex[(ui32Value / ui32Idx) % ui32Base];
                     }
                     //
                     // Write the string.
                     //
                     UARTwrite(pcBuf, ui32Pos);
                     //
                     // This command has been handled.
                     //
                     break;
                 }
                 //
                 // Handle the %% command.
                 //
                 case '%':
                 {
                     //
                     // Simply write a single %.
                     //
                     UARTwrite(pcString - 1, 1);
                     //
                     // This command has been handled.
                     //
                     break;
                 }
                 //
                 // Handle all other commands.
                 //
                 default:
                 {
                     //
                     // Indicate an error.
                     //
                     UARTwrite("ERROR", 5);
                     //
                     // This command has been handled.
                     //
                     break;
                 }
             }
         }
     }
 }
int UARTwrite (const char * pcBuf, uint32_t ui32Len)
Writes a string of characters to the UART output.
Parameters
pcBuf points to a buffer containing the string to transmit.
ui32Len is the length of the string to transmit.
This function will transmit the string to the UART output. The number of characters transmitted is determined by the ui32Len parameter. This function does no interpretation or translation of any characters. Since the output is sent to a UART, any LF (/n) characters encountered will be replaced with a CRLF pair.
Besides using the ui32Len parameter to stop transmitting the string, if a null character (0) is encountered, then no more characters will be transmitted and the function will return.
In non-buffered mode, this function is blocking and will not return until all the characters have been written to the output FIFO. In buffered mode, the characters are written to the UART transmit buffer and the call returns immediately. If insufficient space remains in the transmit buffer, additional characters are discarded.
Returns
Returns the count of characters written.
Definition at line 436 of file uartstdio.c.
References ASSERT, g_ui32Base, MAP_UARTCharPut, MAP_UARTIntEnable, and UART_INT_TX.
Referenced by UARTgets(), and UARTvprintf().
 {
 #ifdef UART_BUFFERED
     unsigned int uIdx;
     //
     // Check for valid arguments.
     //
     ASSERT(pcBuf != 0);
     ASSERT(g_ui32Base != 0);
     //
     // Send the characters
     //
     for(uIdx = 0; uIdx < ui32Len; uIdx++)
     {
         //
         // If the character to the UART is \n, then add a \r before it so that
         // \n is translated to \n\r in the output.
         //
         if(pcBuf[uIdx] == '\n')
         {
             if(!TX_BUFFER_FULL)
             {
                 g_pcUARTTxBuffer[g_ui32UARTTxWriteIndex] = '\r';
                 ADVANCE_TX_BUFFER_INDEX(g_ui32UARTTxWriteIndex);
             }
             else
             {
                 //
                 // Buffer is full - discard remaining characters and return.
                 //
                 break;
             }
         }
         //
         // Send the character to the UART output.
         //
         if(!TX_BUFFER_FULL)
         {
             g_pcUARTTxBuffer[g_ui32UARTTxWriteIndex] = pcBuf[uIdx];
             ADVANCE_TX_BUFFER_INDEX(g_ui32UARTTxWriteIndex);
         }
         else
         {
             //
             // Buffer is full - discard remaining characters and return.
             //
             break;
         }
     }
     //
     // If we have anything in the buffer, make sure that the UART is set
     // up to transmit it.
     //
     if(!TX_BUFFER_EMPTY)
     {
         UARTPrimeTransmit(g_ui32Base);
         MAP_UARTIntEnable(g_ui32Base, UART_INT_TX);
     }
     //
     // Return the number of characters written.
     //
     return(uIdx);
 #else
     unsigned int uIdx;
     //
     // Check for valid UART base address, and valid arguments.
     //
     ASSERT(g_ui32Base != 0);
     ASSERT(pcBuf != 0);
     //
     // Send the characters
     //
     for(uIdx = 0; uIdx < ui32Len; uIdx++)
     {
         //
         // If the character to the UART is \n, then add a \r before it so that
         // \n is translated to \n\r in the output.
         //
         if(pcBuf[uIdx] == '\n')
         {
             MAP_UARTCharPut(g_ui32Base, '\r');
         }
         //
         // Send the character to the UART output.
         //
         MAP_UARTCharPut(g_ui32Base, pcBuf[uIdx]);
     }
     //
     // Return the number of characters written.
     //
     return(uIdx);
 #endif
 }
Variable Documentation
const char* const g_pcHex = "0123456789abcdef" static
Definition at line 134 of file uartstdio.c.
Referenced by UARTvprintf().
uint32_t g_ui32Base = 0 static
Definition at line 126 of file uartstdio.c.
Referenced by UARTgetc(), UARTgets(), UARTStdioConfig(), and UARTwrite().
const uint32_t g_ui32UARTBase[3] static
Initial value:
=
{
    UART0_BASE, UART1_BASE, UART2_BASE
}
Definition at line 141 of file uartstdio.c.
Referenced by UARTStdioConfig().
const uint32_t g_ui32UARTPeriph[3] static
Initial value:
=
{
    SYSCTL_PERIPH_UART0, SYSCTL_PERIPH_UART1, SYSCTL_PERIPH_UART2
}
Definition at line 170 of file uartstdio.c.
Referenced by UARTStdioConfig().