EE445M RTOS: System-interaction calls
System-interaction calls
Invoke system calls.
Data Structures
struct system_command
Macros
#define SYSTEM_MAX_COMMAND_NAME_LENGTH 16
#define SYSTEM_MAX_COMMANDS 16
Typedefs
typedef uint8_t system_iterator
typedef uint8_t exit_status_t
typedef struct system_command system_command
Functions
void system_init ()
bool system_register_command (const char *, int(*)())
bool system_deregister_command (const char *)
exit_status_t system_exec (const char *, const char **)
system_command * _system_command_from_name (const char *command_name)
Detailed Description
Invoke system calls.
Every language offers a 'system' call – pass it a string and the system interprets it. This is that library for this RTOS.
Author
Eric Crosson
Version
0.1
Date
2014
Precondition
None
Copyright
GNU Public License
Macro Definition Documentation
#define SYSTEM_MAX_COMMAND_NAME_LENGTH 16
Maximum length of a callable command.
Definition at line 14 of file system.h.
#define SYSTEM_MAX_COMMANDS 16
Maximum number of commands supported by the system.
Definition at line 17 of file system.h.
Referenced by _system_command_from_name(), system_init(), and system_register_command().
Typedef Documentation
typedef uint8_t exit_status_t
Type definition of an exit code.
Definition at line 24 of file system.h.
typedef struct system_command system_command
typedef uint8_t system_iterator
Iterator optimized for size that is guaranteed to be able to iterate over .
Definition at line 21 of file system.h.
Function Documentation
system_command* _system_command_from_name (const char * command_name)
For internal use only. This function returns a pointer to the registered to the command name .
Definition at line 58 of file system.c.
References strcmp(), and SYSTEM_MAX_COMMANDS.
Referenced by system_deregister_command(), and system_exec().
{
     system_iterator i=0;
     while(i<SYSTEM_MAX_COMMANDS &&
           0 != strcmp(SYSTEM_COMMANDS[i].name, command_name)) {
         ++i;
     }
     return &SYSTEM_COMMANDS[i];
 }
bool system_deregister_command (const char *)
Remove a command from the index of executable system commands.
Returns
True if command was successfully deregistered.
Definition at line 45 of file system.c.
References _system_command_from_name(), CDL_DELETE, CDL_PREPEND, and system_command::valid.
{
     /* Grab the structure of the command to deregister and invaldiate
      * the metadata. Move it from the registered to the unregistered
      * pile. */
     system_command* command = _system_command_from_name(command_name);
     command->valid = false;
     CDL_DELETE(registered_commands, command);
     CDL_PREPEND(unregistered_commands, command);
     return true;
 }
exit_status_t system_exec (const char * , const char **)
Execute a system command.
Returns
The exit code of the executed command.
Bug:
Currently argument passing is not supported.
Definition at line 69 of file system.c.
References _system_command_from_name(), system_command::command, postpone_death, and system_command::valid.
Referenced by shell_execute_command().
{
     system_command* sys_command = _system_command_from_name(command);
     if (sys_command->valid) {
     return sys_command->command(/*arguments*/);
     } else {
     /* TODO: determine what to do here */
     postpone_death();       /* plan a */
     return EXIT_FAILURE;    /* plan b */
     }
 }
void system_init ()
Initialize internal data structures.
Note
Ensure this method is called before any commands are registered.
Definition at line 19 of file system.c.
References CDL_PREPEND, and SYSTEM_MAX_COMMANDS.
Referenced by main().
                    {
     system_iterator i;
     /* All commands begin in the unregistered state */
     for(i=0; i<SYSTEM_MAX_COMMANDS; ++i) {
     CDL_PREPEND(unregistered_commands, &SYSTEM_COMMANDS[i]);
     }
 }
bool system_register_command (const char * , int(*)())
Register a command for later execution.
Returns
True if command was successfully registered.
Definition at line 29 of file system.c.
References CDL_DELETE, CDL_PREPEND, system_command::command, memset(), system_command::name, SYSTEM_MAX_COMMANDS, unregistered_commands, ustrcpy(), and system_command::valid.
Referenced by main().
{
     /* Grab the first free command, move it from the unregisted to the
      * registered pile, and populate it with this function's
      * arguments */
     system_command* sys_command = unregistered_commands;
     CDL_DELETE(unregistered_commands, sys_command);
     CDL_PREPEND(registered_commands, sys_command);
     sys_command->valid = true;
     memset(sys_command->name, 0, SYSTEM_MAX_COMMANDS);
     ustrcpy(sys_command->name, command_name);
     sys_command->command = command;
     return true;
 }