EE445M RTOS: Test of cpp functionality
Test of cpp functionality
Classes
class blinker
class ctlsys
Functions
blinker::blinker ()
blinker::blinker (port_t port_base)
blinker::blinker (port_t port_base, port_t output_pins)
virtual void blinker::set_base (port_t port)
virtual void blinker::turn_on (pin_t pin)
virtual void blinker::turn_off (pin_t pin)
virtual void blinker::toggle (pin_t pin)
virtual void blinker::blink (pin_t pin)
static void ctlsys::enable_periph (uint32_t sys_periph)
static uint32_t ctlsys::timer_timeout_from_subtimer (uint32_t subtimer)
static uint32_t ctlsys::gpio_pin_to_int (uint32_t pin)
static uint32_t ctlsys::periph_to_int (uint32_t periph)
static void ctlsys::gpio_int_clear (uint32_t base, uint32_t pin)
static void ctlsys::gpio_int_disable (uint32_t base, uint32_t pin)
static void ctlsys::gpio_int_enable (uint32_t base, uint32_t pin, bool clear_int=false)
static void ctlsys::set_clock (void)
Variables
const pin_t PIN_RED = GPIO_PIN_1
const pin_t PIN_GREEN = GPIO_PIN_3
const pin_t PIN_BLUE = GPIO_PIN_2
uint32_t blinker::port_base
Detailed Description
Function Documentation
void blinker::blink (pin_t pin) virtual
Implements gpio_twiddler.
Definition at line 38 of file blinker.cpp.
References blinker::port_base.
Referenced by UART0_Handler().
{
     GPIOPinWrite(port_base, pin, pin ^ GPIOPinRead(port_base, pin));
     GPIOPinWrite(port_base, pin, pin ^ GPIOPinRead(port_base, pin));
 }
blinker::blinker ()
Definition at line 8 of file blinker.cpp.
 { }
blinker::blinker (port_t port_base)
Definition at line 10 of file blinker.cpp.
References blinker::set_base().
{
     set_base(port_base);
 }
blinker::blinker (port_t port_base, port_t output_pins)
Initialize at outputs
Definition at line 14 of file blinker.cpp.
References ctlsys::enable_periph(), and blinker::set_base().
{
     set_base(port_base);
     ctlsys::enable_periph(port_base);
     GPIOPinTypeGPIOOutput(port_base, output_pins);
 }
static void ctlsys::enable_periph (uint32_t sys_periph) inline static
Enable peripherals based on a GPIO_PORTx_BASE.
Definition at line 24 of file ctlsysctl.hpp.
References critical::static_EndCritical(), and critical::static_StartCritical().
Referenced by blinker::blinker(), can::init(), lswitch::lswitch(), motor::motor(), ping::ping(), and motor::pwm_init().
{
         uint32_t periph_base = 0xDEADBEEF;
         switch(sys_periph) {
         case GPIO_PORTA_BASE: periph_base = SYSCTL_PERIPH_GPIOA; break;
         case GPIO_PORTB_BASE: periph_base = SYSCTL_PERIPH_GPIOB; break;
         case GPIO_PORTC_BASE: periph_base = SYSCTL_PERIPH_GPIOC; break;
         case GPIO_PORTD_BASE: periph_base = SYSCTL_PERIPH_GPIOD; break;
         case GPIO_PORTE_BASE: periph_base = SYSCTL_PERIPH_GPIOE; break;
         case GPIO_PORTF_BASE: periph_base = SYSCTL_PERIPH_GPIOF; break;
         case GPIO_PORTG_BASE: periph_base = SYSCTL_PERIPH_GPIOG; break;
         case GPIO_PORTH_BASE: periph_base = SYSCTL_PERIPH_GPIOH; break;
         case GPIO_PORTJ_BASE: periph_base = SYSCTL_PERIPH_GPIOJ; break;
         case PWM0_BASE:       periph_base = SYSCTL_PERIPH_PWM0; break;
         case PWM1_BASE:       periph_base = SYSCTL_PERIPH_PWM1; break;
         case CAN0_BASE:       periph_base = SYSCTL_PERIPH_CAN0; break;
         case CAN1_BASE:       periph_base = SYSCTL_PERIPH_CAN1; break;
         default: while(1) {}
         }
         uint32_t ui32Status = static_StartCritical();
         SysCtlPeripheralEnable(periph_base);
         static_EndCritical(ui32Status);
     }
static void ctlsys::gpio_int_clear (uint32_t base, uint32_t pin) inline static
Definition at line 88 of file ctlsysctl.hpp.
References ctlsys::gpio_pin_to_int().
Referenced by ctlsys::gpio_int_enable().
{
         uint32_t interrupt = gpio_pin_to_int(pin);
         GPIOIntClear(base, interrupt);
     }
static void ctlsys::gpio_int_disable (uint32_t base, uint32_t pin) inline static
Definition at line 93 of file ctlsysctl.hpp.
References ctlsys::gpio_pin_to_int().
Referenced by ping::sample().
{
         uint32_t interrupt = gpio_pin_to_int(pin);
         GPIOIntDisable(base, interrupt);
     }
static void ctlsys::gpio_int_enable (uint32_t base, uint32_t pin, bool clear_int = false) inline static
Definition at line 99 of file ctlsysctl.hpp.
References ctlsys::gpio_int_clear(), and ctlsys::gpio_pin_to_int().
Referenced by ping::sample().
{
         uint32_t interrupt = gpio_pin_to_int(pin);
         if (clear_int) {
             gpio_int_clear(base, interrupt);
         }
         GPIOIntEnable(base, interrupt);
     }
static uint32_t ctlsys::gpio_pin_to_int (uint32_t pin) inline static
Definition at line 59 of file ctlsysctl.hpp.
Referenced by ctlsys::gpio_int_clear(), ctlsys::gpio_int_disable(), and ctlsys::gpio_int_enable().
{
         switch(pin) {
         case GPIO_PIN_0: return GPIO_INT_PIN_0;
         case GPIO_PIN_1: return GPIO_INT_PIN_1;
         case GPIO_PIN_2: return GPIO_INT_PIN_2;
         case GPIO_PIN_3: return GPIO_INT_PIN_3;
         case GPIO_PIN_4: return GPIO_INT_PIN_4;
         case GPIO_PIN_5: return GPIO_INT_PIN_5;
         case GPIO_PIN_6: return GPIO_INT_PIN_6;
         case GPIO_PIN_7: return GPIO_INT_PIN_7;
         default: while(1) {}
         }
     }
static uint32_t ctlsys::periph_to_int (uint32_t periph) inline static
Definition at line 73 of file ctlsysctl.hpp.
Referenced by ping::sample().
{
         switch(periph) {
         case GPIO_PORTA_BASE: return INT_GPIOA_TM4C123;
         case GPIO_PORTB_BASE: return INT_GPIOB_TM4C123;
         case GPIO_PORTC_BASE: return INT_GPIOC_TM4C123;
         case GPIO_PORTD_BASE: return INT_GPIOD_TM4C123;
         case GPIO_PORTE_BASE: return INT_GPIOE_TM4C123;
         case GPIO_PORTF_BASE: return INT_GPIOF_TM4C123;
         case GPIO_PORTG_BASE: return INT_GPIOG_TM4C123;
         case GPIO_PORTH_BASE: return INT_GPIOH_TM4C123;
         case CAN0_BASE:       return INT_CAN0_TM4C123;
         default: while(1) {}
         }
     }
void blinker::set_base (port_t port) virtual
Implements gpio_twiddler.
Definition at line 22 of file blinker.cpp.
References blinker::port_base.
Referenced by blinker::blinker().
{
     this->port_base = port_base;
 }
static void ctlsys::set_clock (void) inline static
Set the clock as used in our labs.
Definition at line 109 of file ctlsysctl.hpp.
Referenced by main().
{
         SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                        SYSCTL_XTAL_16MHZ);
     }
static uint32_t ctlsys::timer_timeout_from_subtimer (uint32_t subtimer) inline static
Definition at line 47 of file ctlsysctl.hpp.
Referenced by lswitch::lswitch().
{
         uint32_t timeout =  0x0;
         switch(subtimer) {
         case TIMER_BOTH:
         case TIMER_A: timeout = TIMER_TIMA_TIMEOUT; break;
         case TIMER_B: timeout = TIMER_TIMB_TIMEOUT; break;
         default: while(1) {}
         }
         return timeout;
     }
void blinker::toggle (pin_t pin) virtual
Implements gpio_twiddler.
Definition at line 34 of file blinker.cpp.
References blinker::port_base.
Referenced by can_handler(), can_transmitter(), shell::doctor(), shell::jester(), thread_blink_blue(), thread_blink_green(), thread_blink_red(), Timer1A_Handler(), Timer2A_Handler(), and shell::witch().
{
     GPIOPinWrite(port_base, pin, pin ^ GPIOPinRead(port_base, pin));
 }
void blinker::turn_off (pin_t pin) virtual
Implements gpio_twiddler.
Definition at line 30 of file blinker.cpp.
References blinker::port_base.
Referenced by ping::sample(), and motor::set().
{
     GPIOPinWrite(port_base, pin, 0);
 }
void blinker::turn_on (pin_t pin) virtual
Implements gpio_twiddler.
Definition at line 26 of file blinker.cpp.
References blinker::port_base.
Referenced by ping::sample(), and motor::set().
{
     GPIOPinWrite(port_base, pin, pin);
 }
Variable Documentation
const pin_t PIN_BLUE = GPIO_PIN_2
Definition at line 20 of file blinker.hpp.
Referenced by can_handler(), can_transmitter(), shell::jester(), and thread_blink_blue().
const pin_t PIN_GREEN = GPIO_PIN_3
Definition at line 19 of file blinker.hpp.
Referenced by thread_blink_green(), Timer1A_Handler(), and shell::witch().
const pin_t PIN_RED = GPIO_PIN_1
Definition at line 18 of file blinker.hpp.
Referenced by shell::doctor(), thread_blink_red(), Timer2A_Handler(), and UART0_Handler().
uint32_t blinker::port_base private
Definition at line 34 of file blinker.hpp.
Referenced by blinker::blink(), blinker::set_base(), blinker::toggle(), blinker::turn_off(), and blinker::turn_on().