EE445M RTOS: Scheduler_api
Scheduler_api
Data Structures
struct tSchedulerTask
Typedefs
typedef void(* tSchedulerFunction) (void *pvParam)
Functions
void SchedulerSysTickIntHandler (void)
void SchedulerInit (uint32_t ui32TicksPerSecond)
void SchedulerRun (void)
void SchedulerTaskEnable (uint32_t ui32Index, bool bRunNow)
void SchedulerTaskDisable (uint32_t ui32Index)
uint32_t SchedulerTickCountGet (void)
uint32_t SchedulerElapsedTicksGet (uint32_t ui32TickCount)
uint32_t SchedulerElapsedTicksCalc (uint32_t ui32TickStart, uint32_t ui32TickEnd)
Variables
static volatile uint32_t g_ui32SchedulerTickCount
tSchedulerTask g_psSchedulerTable []
uint32_t g_ui32SchedulerNumTasks
Detailed Description
Typedef Documentation
typedef void(* tSchedulerFunction) (void *pvParam)
Definition at line 50 of file scheduler.h.
Function Documentation
uint32_t SchedulerElapsedTicksCalc (uint32_t ui32TickStart, uint32_t ui32TickEnd)
Returns the number of ticks elapsed between two times.
Parameters
ui32TickStart is the system tick count for the start of the period.
ui32TickEnd is the system tick count for the end of the period.
This function may be called by a client to determine the number of ticks which have elapsed between provided starting and ending tick counts. The function takes into account wrapping cases where the end tick count is lower than the starting count assuming that the ending tick count always represents a later time than the starting count.
Returns
The number of ticks elapsed between the provided start and end counts.
Definition at line 299 of file scheduler.c.
Referenced by SchedulerElapsedTicksGet().
 {
     return((ui32TickEnd > ui32TickStart) ? (ui32TickEnd - ui32TickStart) :
            ((0xFFFFFFFF - ui32TickStart) + ui32TickEnd + 1));
 }
uint32_t SchedulerElapsedTicksGet (uint32_t ui32TickCount)
Returns the number of ticks elapsed since the provided tick count.
Parameters
ui32TickCount is the tick count from which to determine the elapsed time.
This function may be called by a client to determine how much time has passed since a particular tick count provided in the ui32TickCount parameter. This function takes into account wrapping of the global tick counter and assumes that the provided tick count always represents a time in the past. The returned value will, of course, be wrong if the tick counter has wrapped more than once since the passed ui32TickCount. As a result, please do not use this function if you are dealing with timeouts of 497 days or longer (assuming you use a 10mS tick period).
Returns
The number of ticks elapsed since the provided tick count.
Definition at line 272 of file scheduler.c.
References g_ui32SchedulerTickCount, and SchedulerElapsedTicksCalc().
Referenced by SchedulerRun().
 {
     //
     // Determine the calculation based upon whether the global tick count has
     // wrapped since the passed ui32TickCount.
     //
     return(SchedulerElapsedTicksCalc(ui32TickCount, g_ui32SchedulerTickCount));
 }
void SchedulerInit (uint32_t ui32TicksPerSecond)
Initializes the task scheduler.
Parameters
ui32TicksPerSecond sets the basic frequency of the SysTick interrupt used by the scheduler to determine when to run the various task functions.
This function must be called during application startup to configure the SysTick timer. This is used by the scheduler module to determine when each of the functions provided in the g_psSchedulerTable array is called.
The caller is responsible for ensuring that SchedulerSysTickIntHandler() has previously been installed in the SYSTICK vector in the vector table and must also ensure that interrupts are enabled at the CPU level.
Note that this call does not start the scheduler calling the configured functions. All function calls are made in the context of later calls to SchedulerRun(). This call merely configures the SysTick interrupt that is used by the scheduler to determine what the current system time is.
Returns
None.
Definition at line 84 of file scheduler.c.
References ASSERT, SysCtlClockGet(), SysTickEnable(), SysTickIntEnable(), and SysTickPeriodSet().
 {
     ASSERT(ui32TicksPerSecond);
     //
     // Configure SysTick for a periodic interrupt.
     //
     SysTickPeriodSet(SysCtlClockGet() / ui32TicksPerSecond);
     SysTickEnable();
     SysTickIntEnable();
 }
void SchedulerRun (void)
Instructs the scheduler to update its task table and make calls to functions needing called.
This function must be called periodically by the client to allow the scheduler to make calls to any configured task functions if it is their time to be called. The call must be made at least as frequently as the most frequent task configured in the g_psSchedulerTable array.
Although the scheduler makes use of the SysTick interrupt, all calls to functions configured in g_psSchedulerTable are made in the context of SchedulerRun().
Returns
None.
Definition at line 114 of file scheduler.c.
References tSchedulerTask::bActive, g_psSchedulerTable, g_ui32SchedulerNumTasks, g_ui32SchedulerTickCount, tSchedulerTask::pfnFunction, tSchedulerTask::pvParam, SchedulerElapsedTicksGet(), tSchedulerTask::ui32FrequencyTicks, and tSchedulerTask::ui32LastCall.
 {
     uint32_t ui32Loop;
     tSchedulerTask *pi16Task;
     //
     // Loop through each task in the task table.
     //
     for(ui32Loop = 0; ui32Loop < g_ui32SchedulerNumTasks; ui32Loop++)
     {
         //
         // Get a pointer to the task information.
         //
         pi16Task = &g_psSchedulerTable[ui32Loop];
         //
         // Is this task active and, if so, is it time to call it's function?
         //
         if(pi16Task->bActive &&
            (SchedulerElapsedTicksGet(pi16Task->ui32LastCall) >=
             pi16Task->ui32FrequencyTicks))
         {
             //
             // Remember the timestamp at which we make the function call.
             //
             pi16Task->ui32LastCall = g_ui32SchedulerTickCount;
             //
             // Call the task function, passing the provided parameter.
             //
             pi16Task->pfnFunction(pi16Task->pvParam);
         }
     }
 }
void SchedulerSysTickIntHandler (void)
Handles the SysTick interrupt on behalf of the scheduler module.
Applications using the scheduler module must ensure that this function is hooked to the SysTick interrupt vector.
Returns
None.
Definition at line 55 of file scheduler.c.
References g_ui32SchedulerTickCount.
 {
     g_ui32SchedulerTickCount++;
 }
void SchedulerTaskDisable (uint32_t ui32Index)
Disables a task and prevents the scheduler from calling it.
Parameters
ui32Index is the index of the task which is to be disabled in the global g_psSchedulerTable array.
This function marks one of the configured tasks as inactive and prevents SchedulerRun() from calling it. The task may be reenabled by calling SchedulerTaskEnable().
Returns
None.
Definition at line 221 of file scheduler.c.
References tSchedulerTask::bActive, g_psSchedulerTable, and g_ui32SchedulerNumTasks.
 {
     //
     // Is the task index passed valid?
     //
     if(ui32Index < g_ui32SchedulerNumTasks)
     {
         //
         // Yes - mark the task as inactive.
         //
         g_psSchedulerTable[ui32Index].bActive = false;
     }
 }
void SchedulerTaskEnable (uint32_t ui32Index, bool bRunNow)
Enables a task and allows the scheduler to call it periodically.
Parameters
ui32Index is the index of the task which is to be enabled in the global g_psSchedulerTable array.
bRunNow is true if the task is to be run on the next call to SchedulerRun() or false if one whole period is to elapse before the task is run.
This function marks one of the configured tasks as enabled and causes SchedulerRun() to call that task periodically. The caller may choose to have the enabled task run for the first time on the next call to SchedulerRun() or to wait one full task period before making the first call.
Returns
None.
Definition at line 169 of file scheduler.c.
References tSchedulerTask::bActive, g_psSchedulerTable, g_ui32SchedulerNumTasks, g_ui32SchedulerTickCount, tSchedulerTask::ui32FrequencyTicks, and tSchedulerTask::ui32LastCall.
 {
     //
     // Is the task index passed valid?
     //
     if(ui32Index < g_ui32SchedulerNumTasks)
     {
         //
         // Yes - mark the task as active.
         //
         g_psSchedulerTable[ui32Index].bActive = true;
         //
         // Set the last call time to ensure that the function is called either
         // next time the scheduler is run or after the desired number of ticks
         // depending upon the value of the bRunNow parameter.
         //
         if(bRunNow)
         {
             //
             // Cause the task to run on the next call to SchedulerRun().
             //
             g_psSchedulerTable[ui32Index].ui32LastCall =
                 (g_ui32SchedulerTickCount -
                  g_psSchedulerTable[ui32Index].ui32FrequencyTicks);
         }
         else
         {
             //
             // Cause the task to run after one full time period.
             //
             g_psSchedulerTable[ui32Index].ui32LastCall =
                 g_ui32SchedulerTickCount;
         }
     }
 }
uint32_t SchedulerTickCountGet (void)
Returns the current system time in ticks since power on.
This function may be called by a client to retrieve the current system time. The value returned is a count of ticks elapsed since the system last booted.
Returns
Tick count since last boot.
Definition at line 247 of file scheduler.c.
References g_ui32SchedulerTickCount.
 {
     return(g_ui32SchedulerTickCount);
 }
Variable Documentation
tSchedulerTask g_psSchedulerTable[]
This global table must be populated by the client and contains information on each function that the scheduler is to call.
Referenced by SchedulerRun(), SchedulerTaskDisable(), and SchedulerTaskEnable().
uint32_t g_ui32SchedulerNumTasks
This global variable must be exported by the client. It must contain the number of entries in the g_psSchedulerTable array.
Referenced by SchedulerRun(), SchedulerTaskDisable(), and SchedulerTaskEnable().
volatile uint32_t g_ui32SchedulerTickCount static
Definition at line 42 of file scheduler.c.
Referenced by SchedulerElapsedTicksGet(), SchedulerRun(), SchedulerSysTickIntHandler(), SchedulerTaskEnable(), and SchedulerTickCountGet().