EE445M RTOS: Math
Math
Functions
int32_t clamp (int32_t value, int32_t min, int32_t max)
int32_t floor (int32_t value, int32_t scaling)
int32_t ceil (int32_t value, int32_t scaling)
int32_t max (int32_t v1, int32_t v2)
int32_t abs (int32_t val)
Detailed Description
Function Documentation
int32_t abs (int32_t val)
Definition at line 28 of file math.cpp.
{
     if (val > 0) {
         return val;
     }
     return -val;
 }
int32_t ceil (int32_t value, int32_t scaling)
Definition at line 19 of file math.cpp.
{
     return (value + scaling)/scaling*scaling;
 }
int32_t clamp (int32_t value, int32_t min, int32_t max)
Definition at line 5 of file math.cpp.
References max().
Referenced by ir::distance(), motor::set(), and drive::steer().
{
     if (value > max) {
         return max;
     } else if (value < min) {
         return min;
     } else {
         return value;
     }
 }
int32_t floor (int32_t value, int32_t scaling)
Definition at line 15 of file math.cpp.
{
     return value/scaling*scaling;
 }
int32_t max (int32_t v1, int32_t v2)
Definition at line 23 of file math.cpp.
Referenced by clamp().
{
     if (v1 > v2) return v1;
     return v2;
 }