EE445M RTOS: Geometric modeling
Geometric modeling
Spatial and geometric modeling library.
Data Structures
struct point
Representation of an ordered pair with a shade.
struct shape
Representation of a shape.
struct circle
Representation of a circle.
Functions
void shape_destroy_point (point *p)
void shape_destroy_circle (circle *cir)
point * shape_create_point (ushort, ushort, shade_t)
point * shape_duplicate_point (point *p)
shape * shape_create (ushort,...)
shape * shape_duplicate_shape (shape *)
void shape_destroy_shape (shape *)
circle * shape_create_circle (ushort, point *)
shape * shape_create_triangle (point *, point *, point *)
shape * shape_create_quad (point *, uchar, uchar)
Detailed Description
Spatial and geometric modeling library.
Graphics framework for describing 2D systems.
Author
Hershal Bhave
Eric Crosson
Version
0.1
Date
2014
Note
Destroy whatever you create.
Copyright
GNU Public License.
Function Documentation
shape* shape_create (ushort , ...)
Return a pointer to a shape with numPoints points.
Parameters
numpoints Number of vertices in this polygon
points... Comma separated point-defined polygon
Returns
point* Pointer to the described polygon
Note
va_args requires a preceeding argument (size va_args).
Definition at line 31 of file shape.c.
References shape::num_points, and shape::points.
Referenced by CHToShape(), shape_create_quad(), and shape_create_triangle().
{
   unsigned char i;
   shape* sh = (shape*) calloc(1, sizeof(shape));
   point** pts = (point**) calloc(num_points, sizeof(point*));
   va_list args;
   va_start(args, num_points);
   for(i=0; i < num_points; ++i) {
     pts[i] = va_arg(args, point*);
   }
   va_end(args);         /* clean up the list */
   sh->num_points = num_points;
   sh->points = pts;
   return sh;
 }
circle* shape_create_circle (ushort , point *)
Return a pointer to a circle in memory described by center and radius.
Parameters
center Point describing the center of the circle
radius Length of the radius in units
Returns
shape* to newly described circle
Definition at line 58 of file shape.c.
References circle::center, and circle::radius.
{
     circle* cir = (circle*) calloc(1, sizeof(circle));
     cir->center = center;
     cir->radius = radius;
     return cir;
 }
point* shape_create_point (ushort , ushort , shade_t)
Return a point that describes the given arguments.
Parameters
x x coordinate
y y coordinate
shade shading of this point
Returns
point* The newly created point
Definition at line 6 of file shape.c.
References point::shade, point::x, and point::y.
Referenced by _FBDrawGraphBounds(), _FBDrawGraphData(), FBDrawFullscreenGraph(), FBEraseFullscreenGraph(), FBEraseFullscreenGraphData(), shape_create_quad(), and shape_duplicate_point().
{
     point* p = malloc(sizeof(point));
     p->x = x;
     p->y = y;
     p->shade = shade;
     return p;
 }
shape* shape_create_quad (point * , uchar , uchar)
A handy function to create a general quadrilateral.
Parameters
top_left_corner Coordinates of the top left corner of the quadrilateral
width Width of the quadrilateral
p2 height Height of the quadrilateral
Returns
shape* to newly described quadrilateral
Definition at line 19 of file shape.c.
References point::shade, shade_t, shape_create(), shape_create_point(), point::x, and point::y.
{
     ushort x = top_left_corner->x;
     ushort y = top_left_corner->y;
     shade_t shade = top_left_corner->shade;
     return shape_create(4,
             top_left_corner,
             shape_create_point(x+width, y,        shade),
             shape_create_point(x+width, y+height, shade),
             shape_create_point(x,       y+height, shade));
 }
shape* shape_create_triangle (point * , point * , point *)
A handy function to create a triangle.
Parameters
p0 Vertex a
p1 Vertex b
p2 Vertex c
Returns
shape* to newly described triangle
Definition at line 14 of file shape.c.
References shape_create().
{
   return shape_create(3, p0, p1, p2);
 }
void shape_destroy_circle (circle * cir) inline
Destroys a circle described by center and radius.
Parameters
cir Circle to destroy
Definition at line 57 of file shape.h.
{
     free(cir);
 }
void shape_destroy_point (point * p) inline
Destroys a point described by x and y coordinates.
Parameters
p Point to destroy
Definition at line 48 of file shape.h.
{
     free(p);
 }
void shape_destroy_shape (shape *)
Destroy a shape object.
Parameters
sh Shape object to destroy
Returns
void
Definition at line 49 of file shape.c.
References shape::num_points, and shape::points.
{
   ushort i;
   for(i=0; i<sh->num_points; ++i) {
     free(sh->points[i]);
   }
   free(sh->points);
 }
point* shape_duplicate_point (point * p) inline
Duplicate a point
Parameters
p Point to duplicate
Returns
point* Duplicated point
Warning
Don't forget to destroy each duplicated (created) point.
Definition at line 77 of file shape.h.
References point::shade, shape_create_point(), point::x, and point::y.
Referenced by _fb_draw_line(), _fb_draw_string(), CHCreateClockHand(), CHDuplicateClockHand(), fb_erase_char(), and fb_erase_string().
{
     return shape_create_point(p->x, p->y, p->shade);
 }
shape* shape_duplicate_shape (shape *)
Duplicate a shape object.
Parameters
shape The shape to duplicate
Returns
shape A duplicate of the given shape
Definition at line 66 of file shape.c.
References shape::num_points, and shape::points.
Referenced by CHDuplicateClockHand().
{
     ushort i;
     shape* dup = (shape*) calloc(1, sizeof(shape));
     dup->num_points = s->num_points;
     dup->points = (point**) calloc(dup->num_points, sizeof(point*));
     for(i=0; i < dup->num_points; ++i) {
     dup->points[i] = s->points[i];
     }
     return dup;
 }