EE445M RTOS: Softssi_api
Softssi_api
Data Structures
struct tSoftSSI
This structure contains the state of a single instance of a SoftSSI module.
Macros
#define SOFTSSI_STATE_IDLE 0
#define SOFTSSI_STATE_START 1
#define SOFTSSI_STATE_IN 2
#define SOFTSSI_STATE_OUT 3
#define SOFTSSI_STATE_STOP1 4
#define SOFTSSI_STATE_STOP2 5
#define SOFTSSI_FLAG_ENABLE 0x80
#define SOFTSSI_FLAG_SPH 0x02
#define SOFTSSI_FLAG_SPO 0x01
Functions
void SoftSSIConfigSet (tSoftSSI *psSSI, uint8_t ui8Protocol, uint8_t ui8Bits)
static void SoftSSITxInt (tSoftSSI *psSSI)
static void SoftSSIRxInt (tSoftSSI *psSSI)
void SoftSSITimerTick (tSoftSSI *psSSI)
void SoftSSIEnable (tSoftSSI *psSSI)
void SoftSSIDisable (tSoftSSI *psSSI)
void SoftSSIIntEnable (tSoftSSI *psSSI, uint32_t ui32IntFlags)
void SoftSSIIntDisable (tSoftSSI *psSSI, uint32_t ui32IntFlags)
uint32_t SoftSSIIntStatus (tSoftSSI *psSSI, bool bMasked)
void SoftSSIIntClear (tSoftSSI *psSSI, uint32_t ui32IntFlags)
bool SoftSSIDataAvail (tSoftSSI *psSSI)
bool SoftSSISpaceAvail (tSoftSSI *psSSI)
void SoftSSIDataPut (tSoftSSI *psSSI, uint32_t ui32Data)
int32_t SoftSSIDataPutNonBlocking (tSoftSSI *psSSI, uint32_t ui32Data)
void SoftSSIDataGet (tSoftSSI *psSSI, uint32_t *pui32Data)
int32_t SoftSSIDataGetNonBlocking (tSoftSSI *psSSI, uint32_t *pui32Data)
bool SoftSSIBusy (tSoftSSI *psSSI)
void SoftSSICallbackSet (tSoftSSI *psSSI, void(*pfnCallback)(void))
void SoftSSIFssGPIOSet (tSoftSSI *psSSI, uint32_t ui32Base, uint8_t ui8Pin)
void SoftSSIClkGPIOSet (tSoftSSI *psSSI, uint32_t ui32Base, uint8_t ui8Pin)
void SoftSSITxGPIOSet (tSoftSSI *psSSI, uint32_t ui32Base, uint8_t ui8Pin)
void SoftSSIRxGPIOSet (tSoftSSI *psSSI, uint32_t ui32Base, uint8_t ui8Pin)
void SoftSSITxBufferSet (tSoftSSI *psSSI, uint16_t *pui16TxBuffer, uint16_t ui16Len)
void SoftSSIRxBufferSet (tSoftSSI *psSSI, uint16_t *pui16RxBuffer, uint16_t ui16Len)
Detailed Description
Macro Definition Documentation
#define SOFTSSI_FLAG_ENABLE 0x80
Definition at line 57 of file softssi.c.
Referenced by SoftSSIBusy(), SoftSSIConfigSet(), SoftSSIDisable(), SoftSSIEnable(), and SoftSSITimerTick().
#define SOFTSSI_FLAG_SPH 0x02
Definition at line 58 of file softssi.c.
Referenced by SoftSSITimerTick().
#define SOFTSSI_FLAG_SPO 0x01
Definition at line 59 of file softssi.c.
Referenced by SoftSSIConfigSet().
#define SOFTSSI_STATE_IDLE 0
Definition at line 45 of file softssi.c.
Referenced by SoftSSIBusy(), SoftSSIConfigSet(), and SoftSSITimerTick().
#define SOFTSSI_STATE_IN 2
Definition at line 47 of file softssi.c.
Referenced by SoftSSITimerTick().
#define SOFTSSI_STATE_OUT 3
Definition at line 48 of file softssi.c.
Referenced by SoftSSITimerTick().
#define SOFTSSI_STATE_START 1
Definition at line 46 of file softssi.c.
Referenced by SoftSSITimerTick().
#define SOFTSSI_STATE_STOP1 4
Definition at line 49 of file softssi.c.
Referenced by SoftSSITimerTick().
#define SOFTSSI_STATE_STOP2 5
Definition at line 50 of file softssi.c.
Referenced by SoftSSITimerTick().
Function Documentation
bool SoftSSIBusy (tSoftSSI * psSSI)
Determines whether the SoftSSI transmitter is busy or not.
Parameters
psSSI specifies the SoftSSI data structure.
Allows the caller to determine whether all transmitted bytes have cleared the transmitter. If false is returned, then the transmit FIFO is empty and all bits of the last transmitted word have left the shift register.
Returns
Returns true if the SoftSSI is transmitting or false if all transmissions are complete.
Definition at line 1072 of file softssi.c.
References SOFTSSI_FLAG_ENABLE, SOFTSSI_STATE_IDLE, tSoftSSI::ui16TxBufferRead, tSoftSSI::ui16TxBufferWrite, tSoftSSI::ui8Flags, and tSoftSSI::ui8State.
 {
     //
     // Determine if the SSI is busy.
     //
     return(((psSSI->ui8State == SOFTSSI_STATE_IDLE) &&
             (((psSSI->ui8Flags & SOFTSSI_FLAG_ENABLE) == 0) ||
              (psSSI->ui16TxBufferRead == psSSI->ui16TxBufferWrite))) ? false :
            true);
 }
void SoftSSICallbackSet (tSoftSSI * psSSI, void(*)(void) pfnCallback)
Sets the callback used by the SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
pfnCallback is a pointer to the callback function.
This function sets the address of the callback function that is called when there is an ``interrupt'' produced by the SoftSSI module.
Returns
None.
Definition at line 1097 of file softssi.c.
References tSoftSSI::pfnIntCallback.
 {
     //
     // Save the callback function address.
     //
     psSSI->pfnIntCallback = pfnCallback;
 }
void SoftSSIClkGPIOSet (tSoftSSI * psSSI, uint32_t ui32Base, uint8_t ui8Pin)
Sets the GPIO pin to be used as the SoftSSI Clk signal.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Base is the base address of the GPIO module.
ui8Pin is the bit-packed representation of the pin to use.
This function sets the GPIO pin that is used for the SoftSSI Clk signal.
The pin is specified using a bit-packed byte, where bit 0 of the byte represents GPIO port pin 0, bit 1 represents GPIO port pin 1, and so on.
Returns
None.
Definition at line 1157 of file softssi.c.
References tSoftSSI::ui32ClkGPIO.
 {
     //
     // Save the base address and pin for the Clk signal.
     //
     psSSI->ui32ClkGPIO = ui32Base + (ui8Pin << 2);
 }
void SoftSSIConfigSet (tSoftSSI * psSSI, uint8_t ui8Protocol, uint8_t ui8Bits)
Sets the configuration of a SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
ui8Protocol specifes the data transfer protocol.
ui8Bits specifies the number of bits transferred per frame.
This function configures the data format of a SoftSSI module. The ui8Protocol parameter can be one of the following values: SOFTSSI_FRF_MOTO_MODE_0, SOFTSSI_FRF_MOTO_MODE_1, SOFTSSI_FRF_MOTO_MODE_2, or SOFTSSI_FRF_MOTO_MODE_3. These frame formats imply the following polarity and phase configurations:
Polarity Phase         Mode
  0       0   SOFTSSI_FRF_MOTO_MODE_0
  0       1   SOFTSSI_FRF_MOTO_MODE_1
  1       0   SOFTSSI_FRF_MOTO_MODE_2
  1       1   SOFTSSI_FRF_MOTO_MODE_3
The ui8Bits parameter defines the width of the data transfers, and can be a value between 4 and 16, inclusive.
Returns
None.
Definition at line 90 of file softssi.c.
References HWREG, MAP_GPIOPinTypeGPIOInput, MAP_GPIOPinTypeGPIOOutput, SOFTSSI_FLAG_ENABLE, SOFTSSI_FLAG_SPO, SOFTSSI_STATE_IDLE, SOFTSSI_TXFF, tSoftSSI::ui16RxBufferRead, tSoftSSI::ui16RxBufferWrite, tSoftSSI::ui16TxBufferRead, tSoftSSI::ui16TxBufferWrite, tSoftSSI::ui32ClkGPIO, tSoftSSI::ui32FssGPIO, tSoftSSI::ui32RxGPIO, tSoftSSI::ui32TxGPIO, tSoftSSI::ui8Bits, tSoftSSI::ui8Flags, tSoftSSI::ui8IdleCount, tSoftSSI::ui8IntStatus, and tSoftSSI::ui8State.
 {
     //
     // See if a GPIO pin has been set for Fss.
     //
     if(psSSI->ui32FssGPIO != 0)
     {
         //
         // Configure the Fss pin.
         //
         MAP_GPIOPinTypeGPIOOutput(psSSI->ui32FssGPIO & 0xfffff000,
                                   (psSSI->ui32FssGPIO & 0x00000fff) >> 2);
         //
         // Set the Fss pin high.
         //
         HWREG(psSSI->ui32FssGPIO) = 255;
     }
     //
     // Configure the Clk pin.
     //
     MAP_GPIOPinTypeGPIOOutput(psSSI->ui32ClkGPIO & 0xfffff000,
                               (psSSI->ui32ClkGPIO & 0x00000fff) >> 2);
     //
     // Set the Clk pin high or low based on the configured clock polarity.
     //
     if((ui8Protocol & SOFTSSI_FLAG_SPO) == 0)
     {
         HWREG(psSSI->ui32ClkGPIO) = 0;
     }
     else
     {
         HWREG(psSSI->ui32ClkGPIO) = 255;
     }
     //
     // Configure the Tx pin and set it low.
     //
     MAP_GPIOPinTypeGPIOOutput(psSSI->ui32TxGPIO & 0xfffff000,
                               (psSSI->ui32TxGPIO & 0x00000fff) >> 2);
     HWREG(psSSI->ui32TxGPIO) = 0;
     //
     // See if a GPIO pin has been set for Rx.
     //
     if(psSSI->ui32RxGPIO != 0)
     {
         //
         // Configure the Rx pin.
         //
         MAP_GPIOPinTypeGPIOInput(psSSI->ui32RxGPIO & 0xfffff000,
                                  (psSSI->ui32RxGPIO & 0x00000fff) >> 2);
     }
     //
     // Make sure that the transmit and receive FIFOs are empty.
     //
     psSSI->ui16TxBufferRead = 0;
     psSSI->ui16TxBufferWrite = 0;
     psSSI->ui16RxBufferRead = 0;
     psSSI->ui16RxBufferWrite = 0;
     //
     // Save the frame protocol.
     //
     psSSI->ui8Flags = ui8Protocol;
     //
     // Save the number of data bits.
     //
     psSSI->ui8Bits = ui8Bits;
     //
     // Since the FIFOs are empty, the transmit FIFO "interrupt" is asserted.
     //
     psSSI->ui8IntStatus = SOFTSSI_TXFF;
     //
     // Reset the idle counter.
     //
     psSSI->ui8IdleCount = 0;
     //
     // Disable the SoftSSI module.
     //
     psSSI->ui8Flags &= ~(SOFTSSI_FLAG_ENABLE);
     //
     // Start the SoftSSI state machine in the idle state.
     //
     psSSI->ui8State = SOFTSSI_STATE_IDLE;
 }
bool SoftSSIDataAvail (tSoftSSI * psSSI)
Determines if there is any data in the receive FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
This function determines if there is any data available to be read from the receive FIFO.
Returns
Returns true if there is data in the receive FIFO or false if there is no data in the receive FIFO.
Definition at line 829 of file softssi.c.
References tSoftSSI::ui16RxBufferRead, and tSoftSSI::ui16RxBufferWrite.
 {
     //
     // Return the availability of data.
     //
     return((psSSI->ui16RxBufferRead == psSSI->ui16RxBufferWrite) ? false :
            true);
 }
void SoftSSIDataGet (tSoftSSI * psSSI, uint32_t * pui32Data)
Gets a data element from the SoftSSI receive FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
pui32Data is a pointer to a storage location for data that was received over the SoftSSI interface.
This function gets received data from the receive FIFO of the specified SoftSSI module and places that data into the location specified by the pui32Data parameter.
Note
Only the lower N bits of the value written to pui32Data contain valid data, where N is the data width as configured by SoftSSIConfigSet(). For example, if the interface is configured for 8-bit data width, only the lower 8 bits of the value written to pui32Data contain valid data.
Returns
None.
Definition at line 987 of file softssi.c.
References tSoftSSI::pui16RxBuffer, SoftSSIRxInt(), tSoftSSI::ui16RxBufferLen, tSoftSSI::ui16RxBufferRead, and tSoftSSI::ui16RxBufferWrite.
 {
     //
     // Wait until there is data to be read.
     //
     while(psSSI->ui16RxBufferRead ==
           *(volatile uint16_t *)(&(psSSI->ui16RxBufferWrite)))
     {
     }
     //
     // Read data from SoftSSI.
     //
     *pui32Data = psSSI->pui16RxBuffer[psSSI->ui16RxBufferRead];
     psSSI->ui16RxBufferRead++;
     if(psSSI->ui16RxBufferRead == psSSI->ui16RxBufferLen)
     {
         psSSI->ui16RxBufferRead = 0;
     }
     //
     // See if a receive FIFO "interrupt" needs to be cleared.
     //
     SoftSSIRxInt(psSSI);
 }
int32_t SoftSSIDataGetNonBlocking (tSoftSSI * psSSI, uint32_t * pui32Data)
Gets a data element from the SoftSSI receive FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
pui32Data is a pointer to a storage location for data that was received over the SoftSSI interface.
This function gets received data from the receive FIFO of the specified SoftSSI module and places that data into the location specified by the ui32Data parameter. If there is no data in the FIFO, then this function returns a zero.
Note
Only the lower N bits of the value written to pui32Data contain valid data, where N is the data width as configured by SoftSSIConfigSet(). For example, if the interface is configured for 8-bit data width, only the lower 8 bits of the value written to pui32Data contain valid data.
Returns
Returns the number of elements read from the SoftSSI receive FIFO.
Definition at line 1035 of file softssi.c.
References tSoftSSI::pui16RxBuffer, SoftSSIRxInt(), tSoftSSI::ui16RxBufferLen, tSoftSSI::ui16RxBufferRead, and tSoftSSI::ui16RxBufferWrite.
 {
     //
     // Check for data to read.
     //
     if(psSSI->ui16RxBufferRead != psSSI->ui16RxBufferWrite)
     {
         *pui32Data = psSSI->pui16RxBuffer[psSSI->ui16RxBufferRead];
         psSSI->ui16RxBufferRead++;
         if(psSSI->ui16RxBufferRead == psSSI->ui16RxBufferLen)
         {
             psSSI->ui16RxBufferRead = 0;
         }
         SoftSSIRxInt(psSSI);
         return(1);
     }
     else
     {
         return(0);
     }
 }
void SoftSSIDataPut (tSoftSSI * psSSI, uint32_t ui32Data)
Puts a data element into the SoftSSI transmit FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Data is the data to be transmitted over the SoftSSI interface.
This function places the supplied data into the transmit FIFO of the specified SoftSSI module.
Note
The upper 32 - N bits of the ui32Data are discarded, where N is the data width as configured by SoftSSIConfigSet(). For example, if the interface is configured for 8-bit data width, the upper 24 bits of ui32Data are discarded.
Returns
None.
Definition at line 889 of file softssi.c.
References tSoftSSI::pui16TxBuffer, SoftSSITxInt(), tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, and tSoftSSI::ui16TxBufferWrite.
 {
     uint16_t ui16Temp;
     //
     // Wait until there is space.
     //
     ui16Temp = psSSI->ui16TxBufferWrite + 1;
     if(ui16Temp == psSSI->ui16TxBufferLen)
     {
         ui16Temp = 0;
     }
     while(ui16Temp == *(volatile uint16_t *)(&(psSSI->ui16TxBufferRead)))
     {
     }
     //
     // Write the data to the SoftSSI.
     //
     psSSI->pui16TxBuffer[psSSI->ui16TxBufferWrite] = ui32Data;
     psSSI->ui16TxBufferWrite = ui16Temp;
     //
     // See if a transmit FIFO "interrupt" needs to be cleared.
     //
     SoftSSITxInt(psSSI);
 }
int32_t SoftSSIDataPutNonBlocking (tSoftSSI * psSSI, uint32_t ui32Data)
Puts a data element into the SoftSSI transmit FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Data is the data to be transmitted over the SoftSSI interface.
This function places the supplied data into the transmit FIFO of the specified SoftSSI module. If there is no space in the FIFO, then this function returns a zero.
Note
The upper 32 - N bits of the ui32Data are discarded, where N is the data width as configured by SoftSSIConfigSet(). For example, if the interface is configured for 8-bit data width, the upper 24 bits of ui32Data are discarded.
Returns
Returns the number of elements written to the SSI transmit FIFO.
Definition at line 937 of file softssi.c.
References tSoftSSI::pui16TxBuffer, SoftSSITxInt(), tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, and tSoftSSI::ui16TxBufferWrite.
 {
     uint16_t ui16Temp;
     //
     // Determine the values of the write pointer once incremented.
     //
     ui16Temp = psSSI->ui16TxBufferWrite + 1;
     if(ui16Temp == psSSI->ui16TxBufferLen)
     {
         ui16Temp = 0;
     }
     //
     // Check for space to write.
     //
     if(ui16Temp != psSSI->ui16TxBufferRead)
     {
         psSSI->pui16TxBuffer[psSSI->ui16TxBufferWrite] = ui32Data;
         psSSI->ui16TxBufferWrite = ui16Temp;
         SoftSSITxInt(psSSI);
         return(1);
     }
     else
     {
         return(0);
     }
 }
void SoftSSIDisable (tSoftSSI * psSSI)
Disables the SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
This function disables operation of the SoftSSI module. If a data transfer is in progress, it is finished before the module is fully disabled.
Returns
None.
Definition at line 697 of file softssi.c.
References SOFTSSI_FLAG_ENABLE, and tSoftSSI::ui8Flags.
 {
     //
     // Disable the SoftSSI module.
     //
     psSSI->ui8Flags &= ~(SOFTSSI_FLAG_ENABLE);
 }
void SoftSSIEnable (tSoftSSI * psSSI)
Enables the SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
This function enables operation of the SoftSSI module. The SoftSSI module must be configured before it is enabled.
Returns
None.
Definition at line 676 of file softssi.c.
References SOFTSSI_FLAG_ENABLE, and tSoftSSI::ui8Flags.
 {
     //
     // Enable the SoftSSI module.
     //
     psSSI->ui8Flags |= SOFTSSI_FLAG_ENABLE;
 }
void SoftSSIFssGPIOSet (tSoftSSI * psSSI, uint32_t ui32Base, uint8_t ui8Pin)
Sets the GPIO pin to be used as the SoftSSI Fss signal.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Base is the base address of the GPIO module.
ui8Pin is the bit-packed representation of the pin to use.
This function sets the GPIO pin that is used for the SoftSSI Fss signal. If there is not a GPIO pin allocated for Fss, the SoftSSI module does not assert/deassert the Fss signal, leaving it to the application either to do manually or to not do at all if the slave device has Fss tied to ground.
The pin is specified using a bit-packed byte, where bit 0 of the byte represents GPIO port pin 0, bit 1 represents GPIO port pin 1, and so on.
Returns
None.
Definition at line 1125 of file softssi.c.
References tSoftSSI::ui32FssGPIO.
 {
     //
     // Save the base address and pin for the Fss signal.
     //
     if(ui32Base == 0)
     {
         psSSI->ui32FssGPIO = 0;
     }
     else
     {
         psSSI->ui32FssGPIO = ui32Base + (ui8Pin << 2);
     }
 }
void SoftSSIIntClear (tSoftSSI * psSSI, uint32_t ui32IntFlags)
Clears SoftSSI ``interrupt'' sources.
Parameters
psSSI specifies the SoftSSI data structure.
ui32IntFlags is a bit mask of the ``interrupt'' sources to be cleared.
The specified SoftSSI interrupt'' sources are cleared so that they no longer assert. This function must be called in theinterrupt'' handler to keep the ``interrupt'' from being recognized again immediately upon exit. The ui32IntFlags parameter is the logical OR of any of the SOFTSSI_TXEOT, SOFTSSI_RXTO, and SOFTSSI_RXOR values.
Returns
None.
Definition at line 807 of file softssi.c.
References SOFTSSI_RXFF, SOFTSSI_TXFF, and tSoftSSI::ui8IntStatus.
 {
     //
     // Clear the requested "interrupt" sources.
     //
     psSSI->ui8IntStatus &= ~(ui32IntFlags) | SOFTSSI_TXFF | SOFTSSI_RXFF;
 }
void SoftSSIIntDisable (tSoftSSI * psSSI, uint32_t ui32IntFlags)
Disables individual SoftSSI ``interrupt'' sources.
Parameters
psSSI specifies the SoftSSI data structure.
ui32IntFlags is a bit mask of the ``interrupt'' sources to be disabled.
Disables the indicated SoftSSI ``interrupt'' sources. The ui32IntFlags parameter can be any of the SOFTSSI_TXEOT, SOFTSSI_TXFF, SOFTSSI_RXFF, SOFTSSI_RXTO, or SOFTSSI_RXOR values.
Returns
None.
Definition at line 747 of file softssi.c.
References tSoftSSI::ui8IntMask.
 {
     //
     // Disable the specified "interrupts".
     //
     psSSI->ui8IntMask &= ~(ui32IntFlags);
 }
void SoftSSIIntEnable (tSoftSSI * psSSI, uint32_t ui32IntFlags)
Enables individual SoftSSI ``interrupt'' sources.
Parameters
psSSI specifies the SoftSSI data structure.
ui32IntFlags is a bit mask of the ``interrupt'' sources to be enabled.
Enables the indicated SoftSSI ``interrupt'' sources. Only the sources that are enabled can be reflected to the callback function; disabled sources do not result in a callback. The ui32IntFlags parameter can be any of the SOFTSSI_TXEOT, SOFTSSI_TXFF, SOFTSSI_RXFF, SOFTSSI_RXTO, or SOFTSSI_RXOR values.
Returns
None.
Definition at line 723 of file softssi.c.
References tSoftSSI::ui8IntMask.
 {
     //
     // Enable the specified "interrupts".
     //
     psSSI->ui8IntMask |= ui32IntFlags;
 }
uint32_t SoftSSIIntStatus (tSoftSSI * psSSI, bool bMasked)
Gets the current ``interrupt'' status.
Parameters
psSSI specifies the SoftSSI data structure.
bMasked is false if the raw interrupt'' status is required or \b true if the maskedinterrupt'' status is required.
This function returns the interrupt'' status for the SoftSSI module. Either the rawinterrupt'' status or the status of ``interrupts'' that are allowed to reflect to the callback can be returned.
Returns
The current ``interrupt'' status, enumerated as a bit field of SOFTSSI_TXEOT, SOFTSSI_TXFF, SOFTSSI_RXFF, SOFTSSI_RXTO, and SOFTSSI_RXOR.
Definition at line 773 of file softssi.c.
References tSoftSSI::ui8IntMask, and tSoftSSI::ui8IntStatus.
 {
     //
     // Return either the "interrupt" status or the raw "interrupt" status as
     // requested.
     //
     if(bMasked)
     {
         return(psSSI->ui8IntStatus & psSSI->ui8IntMask);
     }
     else
     {
         return(psSSI->ui8IntStatus);
     }
 }
void SoftSSIRxBufferSet (tSoftSSI * psSSI, uint16_t * pui16RxBuffer, uint16_t ui16Len)
Sets the receive FIFO buffer for a SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
pui16RxBuffer is the address of the receive FIFO buffer.
ui16Len is the size, in 16-bit half-words, of the receive FIFO buffer.
This function sets the address and size of the receive FIFO buffer and also resets the read and write pointers, marking the receive FIFO as empty. When the buffer pointer and length are configured as zero, all data received from the slave device is discarded. This capability is useful when there is no GPIO pin allocated for the Rx signal.
Returns
None.
Definition at line 1276 of file softssi.c.
References tSoftSSI::pui16RxBuffer, tSoftSSI::ui16RxBufferLen, tSoftSSI::ui16RxBufferRead, and tSoftSSI::ui16RxBufferWrite.
 {
     //
     // Save the receive FIFO buffer address and length.
     //
     psSSI->pui16RxBuffer = pui16RxBuffer;
     psSSI->ui16RxBufferLen = ui16Len;
     //
     // Reset the receive FIFO read and write pointers.
     //
     psSSI->ui16RxBufferRead = 0;
     psSSI->ui16RxBufferWrite = 0;
 }
void SoftSSIRxGPIOSet (tSoftSSI * psSSI, uint32_t ui32Base, uint8_t ui8Pin)
Sets the GPIO pin to be used as the SoftSSI Rx signal.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Base is the base address of the GPIO module.
ui8Pin is the bit-packed representation of the pin to use.
This function sets the GPIO pin that is used for the SoftSSI Rx signal. If there is not a GPIO pin allocated for Rx, the SoftSSI module does not read data from the slave device.
The pin is specified using a bit-packed byte, where bit 0 of the byte represents GPIO port pin 0, bit 1 represents GPIO port pin 1, and so on.
Returns
None.
Definition at line 1209 of file softssi.c.
References tSoftSSI::ui32RxGPIO.
 {
     //
     // Save the base address and pin for the Rx signal.
     //
     if(ui32Base == 0)
     {
         psSSI->ui32RxGPIO = 0;
     }
     else
     {
         psSSI->ui32RxGPIO = ui32Base + (ui8Pin << 2);
     }
 }
static void SoftSSIRxInt (tSoftSSI * psSSI) static
Handles the assertion/deassertion of the receive FIFO ``interrupt''.
Parameters
psSSI specifies the SoftSSI data structure.
This function is used to determine when to assert or deassert the receive FIFO ``interrupt''.
Returns
None.
Definition at line 243 of file softssi.c.
References SOFTSSI_RXFF, tSoftSSI::ui16RxBufferLen, tSoftSSI::ui16RxBufferRead, tSoftSSI::ui16RxBufferWrite, and tSoftSSI::ui8IntStatus.
Referenced by SoftSSIDataGet(), SoftSSIDataGetNonBlocking(), and SoftSSITimerTick().
 {
     uint16_t ui16Temp;
     //
     // Determine the number of words in the receive FIFO.
     //
     if(psSSI->ui16RxBufferRead > psSSI->ui16RxBufferWrite)
     {
         ui16Temp = (psSSI->ui16RxBufferLen + psSSI->ui16RxBufferWrite -
                     psSSI->ui16RxBufferRead);
     }
     else
     {
         ui16Temp = psSSI->ui16RxBufferWrite - psSSI->ui16RxBufferRead;
     }
     //
     // If the receive FIFO is now half full or more, generate a receive FIFO
     // "interrupt".  Otherwise, clear the receive FIFO "interrupt".
     //
     if(ui16Temp >= (psSSI->ui16RxBufferLen / 2))
     {
         psSSI->ui8IntStatus |= SOFTSSI_RXFF;
     }
     else
     {
         psSSI->ui8IntStatus &= ~(SOFTSSI_RXFF);
     }
 }
bool SoftSSISpaceAvail (tSoftSSI * psSSI)
Determines if there is any space in the transmit FIFO.
Parameters
psSSI specifies the SoftSSI data structure.
This function determines if there is space available in the transmit FIFO.
Returns
Returns true if there is space available in the transmit FIFO or false if there is no space available in the transmit FIFO.
Definition at line 851 of file softssi.c.
References tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, and tSoftSSI::ui16TxBufferWrite.
 {
     uint16_t ui16Temp;
     //
     // Determine the values of the write pointer once incremented.
     //
     ui16Temp = psSSI->ui16TxBufferWrite + 1;
     if(ui16Temp == psSSI->ui16TxBufferLen)
     {
         ui16Temp = 0;
     }
     //
     // Return the availability of space.
     //
     return((psSSI->ui16TxBufferRead == ui16Temp) ? false : true);
 }
void SoftSSITimerTick (tSoftSSI * psSSI)
Performs the periodic update of the SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
This function performs the periodic, time-based updates to the SoftSSI module. The transmission and reception of data over the SoftSSI link is performed by the state machine in this function.
This function must be called at twice the desired SoftSSI clock rate. For example, to run the SoftSSI clock at 10 KHz, this function must be called at a 20 KHz rate.
Returns
None.
Definition at line 292 of file softssi.c.
References HWREG, tSoftSSI::pfnIntCallback, tSoftSSI::pui16RxBuffer, tSoftSSI::pui16TxBuffer, SOFTSSI_FLAG_ENABLE, SOFTSSI_FLAG_SPH, SOFTSSI_RXOR, SOFTSSI_RXTO, SOFTSSI_STATE_IDLE, SOFTSSI_STATE_IN, SOFTSSI_STATE_OUT, SOFTSSI_STATE_START, SOFTSSI_STATE_STOP1, SOFTSSI_STATE_STOP2, SOFTSSI_TXEOT, SoftSSIRxInt(), SoftSSITxInt(), tSoftSSI::ui16RxBufferLen, tSoftSSI::ui16RxBufferRead, tSoftSSI::ui16RxBufferWrite, tSoftSSI::ui16RxData, tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, tSoftSSI::ui16TxBufferWrite, tSoftSSI::ui16TxData, tSoftSSI::ui32ClkGPIO, tSoftSSI::ui32FssGPIO, tSoftSSI::ui32RxGPIO, tSoftSSI::ui32TxGPIO, tSoftSSI::ui8Bits, tSoftSSI::ui8CurrentBit, tSoftSSI::ui8Flags, tSoftSSI::ui8IdleCount, tSoftSSI::ui8IntMask, tSoftSSI::ui8IntStatus, and tSoftSSI::ui8State.
 {
     uint16_t ui16Temp;
     //
     // Determine the current state of the state machine.
     //
     switch(psSSI->ui8State)
     {
         //
         // The state machine is idle.
         //
         case SOFTSSI_STATE_IDLE:
         {
             //
             // See if the SoftSSI module is enabled and there is data in the
             // transmit FIFO.
             //
             if(((psSSI->ui8Flags & SOFTSSI_FLAG_ENABLE) != 0) &&
                (psSSI->ui16TxBufferRead != psSSI->ui16TxBufferWrite))
             {
                 //
                 // Assert the Fss signal if it is configured.
                 //
                 if(psSSI->ui32FssGPIO != 0)
                 {
                     HWREG(psSSI->ui32FssGPIO) = 0;
                 }
                 //
                 // Move to the start state.
                 //
                 psSSI->ui8State = SOFTSSI_STATE_START;
             }
             //
             // Otherwise, see if there is data in the receive FIFO.
             //
             else if((psSSI->ui16RxBufferRead != psSSI->ui16RxBufferWrite) &&
                     (psSSI->ui8IdleCount != 64))
             {
                 //
                 // Increment the idle counter.
                 //
                 psSSI->ui8IdleCount++;
                 //
                 // See if the idle counter has become large enough to trigger
                 // a timeout "interrupt".
                 //
                 if(psSSI->ui8IdleCount == 64)
                 {
                     //
                     // Trigger the receive timeout "interrupt".
                     //
                     psSSI->ui8IntStatus |= SOFTSSI_RXTO;
                 }
             }
             //
             // This state has been handled.
             //
             break;
         }
         //
         // The start machine is in the transfer start state.
         //
         case SOFTSSI_STATE_START:
         {
             //
             // Get the next word to transfer from the transmit FIFO.
             //
             psSSI->ui16TxData =
                 (psSSI->pui16TxBuffer[psSSI->ui16TxBufferRead] <<
                  (16 - psSSI->ui8Bits));
             //
             // Initialize the receive buffer to zero.
             //
             psSSI->ui16RxData = 0;
             //
             // Initialize the count of bits tranferred.
             //
             psSSI->ui8CurrentBit = 0;
             //
             // Write the first bit of the transmit word to the Tx pin.
             //
             HWREG(psSSI->ui32TxGPIO) =
                 (psSSI->ui16TxData & 0x8000) ? 255 : 0;
             //
             // Shift to the next bit of the transmit word.
             //
             psSSI->ui16TxData <<= 1;
             //
             // If in SPI mode 1 or 3, then the Clk signal needs to be toggled.
             //
             if((psSSI->ui8Flags & SOFTSSI_FLAG_SPH) != 0)
             {
                 HWREG(psSSI->ui32ClkGPIO) ^= 255;
             }
             //
             // Move to the data input state.
             //
             psSSI->ui8State = SOFTSSI_STATE_IN;
             //
             // This state has been handled.
             //
             break;
         }
         //
         // The state machine is in the data input state.
         //
         case SOFTSSI_STATE_IN:
         {
             //
             // Read the next bit from the Rx signal if it is configured.
             //
             if(psSSI->ui32RxGPIO != 0)
             {
                 psSSI->ui16RxData = ((psSSI->ui16RxData << 1) |
                                      (HWREG(psSSI->ui32RxGPIO) ? 1 : 0));
             }
             //
             // Toggle the Clk signal.
             //
             HWREG(psSSI->ui32ClkGPIO) ^= 255;
             //
             // Increment the number of bits transferred.
             //
             psSSI->ui8CurrentBit++;
             //
             // See if the entire word has been transferred.
             //
             if(psSSI->ui8CurrentBit != psSSI->ui8Bits)
             {
                 //
                 // There are more bits to transfer, so move to the data output
                 // state.
                 //
                 psSSI->ui8State = SOFTSSI_STATE_OUT;
             }
             else
             {
                 //
                 // Increment the transmit read pointer, removing the word that
                 // was just transferred from the transmit FIFO.
                 //
                 psSSI->ui16TxBufferRead++;
                 if(psSSI->ui16TxBufferRead == psSSI->ui16TxBufferLen)
                 {
                     psSSI->ui16TxBufferRead = 0;
                 }
                 //
                 // See if a transmit FIFO "interrupt" needs to be asserted.
                 //
                 SoftSSITxInt(psSSI);
                 //
                 // Determine the new value for the receive FIFO write pointer.
                 //
                 ui16Temp = psSSI->ui16RxBufferWrite + 1;
                 if(ui16Temp >= psSSI->ui16RxBufferLen)
                 {
                     ui16Temp = 0;
                 }
                 //
                 // See if there is space in the receive FIFO for the word that
                 // was just received.
                 //
                 if(ui16Temp == psSSI->ui16RxBufferRead)
                 {
                     //
                     // The receive FIFO is full, so generate a receive FIFO
                     // overrun "interrupt".
                     //
                     psSSI->ui8IntStatus |= SOFTSSI_RXOR;
                 }
                 else
                 {
                     //
                     // Store the new word into the receive FIFO.
                     //
                     psSSI->pui16RxBuffer[psSSI->ui16RxBufferWrite] =
                         psSSI->ui16RxData;
                     //
                     // Save the new receive FIFO write pointer.
                     //
                     psSSI->ui16RxBufferWrite = ui16Temp;
                     //
                     // See if a receive FIFO "interrupt" needs to be asserted.
                     //
                     SoftSSIRxInt(psSSI);
                 }
                 //
                 // See if the next word should be transmitted immediately.
                 // This will occur when there is data in the transmit FIFO, the
                 // SoftSSI module is enabled, and the SoftSSI module is in SPI
                 // mode 1 or 3.
                 //
                 if(((psSSI->ui8Flags & SOFTSSI_FLAG_ENABLE) != 0) &&
                    ((psSSI->ui8Flags & SOFTSSI_FLAG_SPH) != 0) &&
                    (psSSI->ui16TxBufferRead != psSSI->ui16TxBufferWrite))
                 {
                     //
                     // Get the next word to transfer from the transmit FIFO.
                     //
                     psSSI->ui16TxData =
                         (psSSI->pui16TxBuffer[psSSI->ui16TxBufferRead] <<
                          (16 - psSSI->ui8Bits));
                     //
                     // Initialize the receive buffer to zero.
                     //
                     psSSI->ui16RxData = 0;
                     //
                     // Initialize the count of bits tranferred.
                     //
                     psSSI->ui8CurrentBit = 0;
                     //
                     // Move to the data output state.
                     //
                     psSSI->ui8State = SOFTSSI_STATE_OUT;
                 }
                 else
                 {
                     //
                     // The next word should not be transmitted immediately, so
                     // move to the first step of the stop state.
                     //
                     psSSI->ui8State = SOFTSSI_STATE_STOP1;
                 }
             }
             //
             // This state has been handled.
             //
             break;
         }
         //
         // The state machine is in the data output state.
         //
         case SOFTSSI_STATE_OUT:
         {
             //
             // Write the next bit of the transmit word to the Tx pin.
             //
             HWREG(psSSI->ui32TxGPIO) = (psSSI->ui16TxData & 0x8000) ? 255 : 0;
             //
             // Toggle the Clk signal.
             //
             HWREG(psSSI->ui32ClkGPIO) ^= 255;
             //
             // Shift to the next bit of the transmit word.
             //
             psSSI->ui16TxData <<= 1;
             //
             // Move to the data input state.
             //
             psSSI->ui8State = SOFTSSI_STATE_IN;
             //
             // This state has been handled.
             //
             break;
         }
         //
         // The state machine is in the first step of the stop state.
         //
         case SOFTSSI_STATE_STOP1:
         {
             //
             // Set the Tx pin low.
             //
             HWREG(psSSI->ui32TxGPIO) = 0;
             //
             // If in SPI mode 1 or 3, then the Clk signal needs to be toggled.
             //
             if((psSSI->ui8Flags & SOFTSSI_FLAG_SPH) == 0)
             {
                 HWREG(psSSI->ui32ClkGPIO) ^= 255;
             }
             //
             // Move to the second step of the stop state.
             //
             psSSI->ui8State = SOFTSSI_STATE_STOP2;
             //
             // This state has been handled.
             //
             break;
         }
         //
         // The state machine is in the second step of the stop state.
         //
         case SOFTSSI_STATE_STOP2:
         {
             //
             // Deassert the Fss signal if it is configured.
             //
             if(psSSI->ui32FssGPIO != 0)
             {
                 HWREG(psSSI->ui32FssGPIO) = 255;
             }
             //
             // Move to the idle state.
             //
             psSSI->ui8State = SOFTSSI_STATE_IDLE;
             //
             // Reset the idle counter.
             //
             psSSI->ui8IdleCount = 0;
             //
             // See if the end of transfer "interrupt" should be generated.
             //
             if(psSSI->ui16TxBufferRead == psSSI->ui16TxBufferWrite)
             {
                 psSSI->ui8IntStatus |= SOFTSSI_TXEOT;
             }
             //
             // This state has been handled.
             //
             break;
         }
     }
     //
     // Call the "interrupt" callback while there are enabled "interrupts"
     // asserted.  By calling in a loop until the "interrupts" are no longer
     // asserted, this mimics the behavior of a real hardware implementation of
     // the SSI peripheral.
     //
     while(((psSSI->ui8IntStatus & psSSI->ui8IntMask) != 0) &&
           (psSSI->pfnIntCallback != 0))
     {
         //
         // Call the callback function.
         //
         psSSI->pfnIntCallback();
     }
 }
void SoftSSITxBufferSet (tSoftSSI * psSSI, uint16_t * pui16TxBuffer, uint16_t ui16Len)
Sets the transmit FIFO buffer for a SoftSSI module.
Parameters
psSSI specifies the SoftSSI data structure.
pui16TxBuffer is the address of the transmit FIFO buffer.
ui16Len is the size, in 16-bit half-words, of the transmit FIFO buffer.
This function sets the address and size of the transmit FIFO buffer and also resets the read and write pointers, marking the transmit FIFO as empty.
Returns
None.
Definition at line 1241 of file softssi.c.
References tSoftSSI::pui16TxBuffer, tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, and tSoftSSI::ui16TxBufferWrite.
 {
     //
     // Save the transmit FIFO buffer address and length.
     //
     psSSI->pui16TxBuffer = pui16TxBuffer;
     psSSI->ui16TxBufferLen = ui16Len;
     //
     // Reset the transmit FIFO read and write pointers.
     //
     psSSI->ui16TxBufferRead = 0;
     psSSI->ui16TxBufferWrite = 0;
 }
void SoftSSITxGPIOSet (tSoftSSI * psSSI, uint32_t ui32Base, uint8_t ui8Pin)
Sets the GPIO pin to be used as the SoftSSI Tx signal.
Parameters
psSSI specifies the SoftSSI data structure.
ui32Base is the base address of the GPIO module.
ui8Pin is the bit-packed representation of the pin to use.
This function sets the GPIO pin that is used for the SoftSSI Tx signal.
The pin is specified using a bit-packed byte, where bit 0 of the byte represents GPIO port pin 0, bit 1 represents GPIO port pin 1, and so on.
Returns
None.
Definition at line 1182 of file softssi.c.
References tSoftSSI::ui32TxGPIO.
 {
     //
     // Save the base address and pin for the Tx signal.
     //
     psSSI->ui32TxGPIO = ui32Base + (ui8Pin << 2);
 }
static void SoftSSITxInt (tSoftSSI * psSSI) static
Handles the assertion/deassertion of the transmit FIFO ``interrupt''.
Parameters
psSSI specifies the SoftSSI data structure.
This function is used to determine when to assert or deassert the transmit FIFO ``interrupt''.
Returns
None.
Definition at line 199 of file softssi.c.
References SOFTSSI_TXFF, tSoftSSI::ui16TxBufferLen, tSoftSSI::ui16TxBufferRead, tSoftSSI::ui16TxBufferWrite, and tSoftSSI::ui8IntStatus.
Referenced by SoftSSIDataPut(), SoftSSIDataPutNonBlocking(), and SoftSSITimerTick().
 {
     uint16_t ui16Temp;
     //
     // Determine the number of words left in the transmit FIFO.
     //
     if(psSSI->ui16TxBufferRead > psSSI->ui16TxBufferWrite)
     {
         ui16Temp = (psSSI->ui16TxBufferLen + psSSI->ui16TxBufferWrite -
                     psSSI->ui16TxBufferRead);
     }
     else
     {
         ui16Temp = psSSI->ui16TxBufferWrite - psSSI->ui16TxBufferRead;
     }
     //
     // If the transmit FIFO is now half full or less, generate a transmit FIFO
     // "interrupt".  Otherwise, clear the transmit FIFO "interrupt".
     //
     if(ui16Temp <= (psSSI->ui16TxBufferLen / 2))
     {
         psSSI->ui8IntStatus |= SOFTSSI_TXFF;
     }
     else
     {
         psSSI->ui8IntStatus &= ~(SOFTSSI_TXFF);
     }
 }