EE445M RTOS: Adc_api
Adc_api
Macros
#define ADC_SEQ (ADC_O_SSMUX0)
#define ADC_SEQ_STEP (ADC_O_SSMUX1 - ADC_O_SSMUX0)
#define ADC_SSMUX (ADC_O_SSMUX0 - ADC_O_SSMUX0)
#define ADC_SSEMUX (ADC_O_SSEMUX0 - ADC_O_SSMUX0)
#define ADC_SSCTL (ADC_O_SSCTL0 - ADC_O_SSMUX0)
#define ADC_SSFIFO (ADC_O_SSFIFO0 - ADC_O_SSMUX0)
#define ADC_SSFSTAT (ADC_O_SSFSTAT0 - ADC_O_SSMUX0)
#define ADC_SSOP (ADC_O_SSOP0 - ADC_O_SSMUX0)
#define ADC_SSDC (ADC_O_SSDC0 - ADC_O_SSMUX0)
#define ADC_SSTSH (ADC_O_SSTSH0 - ADC_O_SSMUX0)
Functions
static uint_fast8_t _ADCIntNumberGet (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCIntRegister (uint32_t ui32Base, uint32_t ui32SequenceNum, void(*pfnHandler)(void))
void ADCIntUnregister (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCIntDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCIntEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
uint32_t ADCIntStatus (uint32_t ui32Base, uint32_t ui32SequenceNum, bool bMasked)
void ADCIntClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Trigger, uint32_t ui32Priority)
void ADCSequenceStepConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Step, uint32_t ui32Config)
int32_t ADCSequenceOverflow (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceOverflowClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
int32_t ADCSequenceUnderflow (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceUnderflowClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
int32_t ADCSequenceDataGet (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t *pui32Buffer)
void ADCProcessorTrigger (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSoftwareOversampleConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Factor)
void ADCSoftwareOversampleStepConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Step, uint32_t ui32Config)
void ADCSoftwareOversampleDataGet (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t *pui32Buffer, uint32_t ui32Count)
void ADCHardwareOversampleConfigure (uint32_t ui32Base, uint32_t ui32Factor)
void ADCComparatorConfigure (uint32_t ui32Base, uint32_t ui32Comp, uint32_t ui32Config)
void ADCComparatorRegionSet (uint32_t ui32Base, uint32_t ui32Comp, uint32_t ui32LowRef, uint32_t ui32HighRef)
void ADCComparatorReset (uint32_t ui32Base, uint32_t ui32Comp, bool bTrigger, bool bInterrupt)
void ADCComparatorIntDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCComparatorIntEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
uint32_t ADCComparatorIntStatus (uint32_t ui32Base)
void ADCComparatorIntClear (uint32_t ui32Base, uint32_t ui32Status)
void ADCIntDisableEx (uint32_t ui32Base, uint32_t ui32IntFlags)
void ADCIntEnableEx (uint32_t ui32Base, uint32_t ui32IntFlags)
uint32_t ADCIntStatusEx (uint32_t ui32Base, bool bMasked)
void ADCIntClearEx (uint32_t ui32Base, uint32_t ui32IntFlags)
void ADCReferenceSet (uint32_t ui32Base, uint32_t ui32Ref)
uint32_t ADCReferenceGet (uint32_t ui32Base)
void ADCPhaseDelaySet (uint32_t ui32Base, uint32_t ui32Phase)
uint32_t ADCPhaseDelayGet (uint32_t ui32Base)
void ADCSequenceDMAEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
void ADCSequenceDMADisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
bool ADCBusy (uint32_t ui32Base)
void ADCClockConfigSet (uint32_t ui32Base, uint32_t ui32Config, uint32_t ui32ClockDiv)
uint32_t ADCClockConfigGet (uint32_t ui32Base, uint32_t *pui32ClockDiv)
Variables
static uint8_t g_pui8OversampleFactor [3]
Detailed Description
Macro Definition Documentation
#define ADC_SEQ (ADC_O_SSMUX0)
Definition at line 64 of file adc.c.
Referenced by ADCSequenceDataGet(), ADCSequenceStepConfigure(), ADCSoftwareOversampleDataGet(), and ADCSoftwareOversampleStepConfigure().
#define ADC_SEQ_STEP (ADC_O_SSMUX1 - ADC_O_SSMUX0)
Definition at line 65 of file adc.c.
Referenced by ADCSequenceDataGet(), ADCSequenceStepConfigure(), ADCSoftwareOversampleDataGet(), and ADCSoftwareOversampleStepConfigure().
#define ADC_SSCTL (ADC_O_SSCTL0 - ADC_O_SSMUX0)
Definition at line 68 of file adc.c.
Referenced by ADCSequenceStepConfigure(), and ADCSoftwareOversampleStepConfigure().
#define ADC_SSDC (ADC_O_SSDC0 - ADC_O_SSMUX0)
Definition at line 72 of file adc.c.
Referenced by ADCSequenceStepConfigure().
#define ADC_SSEMUX (ADC_O_SSEMUX0 - ADC_O_SSMUX0)
Definition at line 67 of file adc.c.
Referenced by ADCSequenceStepConfigure(), and ADCSoftwareOversampleStepConfigure().
#define ADC_SSFIFO (ADC_O_SSFIFO0 - ADC_O_SSMUX0)
Definition at line 69 of file adc.c.
Referenced by ADCSequenceDataGet(), and ADCSoftwareOversampleDataGet().
#define ADC_SSFSTAT (ADC_O_SSFSTAT0 - ADC_O_SSMUX0)
Definition at line 70 of file adc.c.
Referenced by ADCSequenceDataGet().
#define ADC_SSMUX (ADC_O_SSMUX0 - ADC_O_SSMUX0)
Definition at line 66 of file adc.c.
Referenced by ADCSequenceStepConfigure(), and ADCSoftwareOversampleStepConfigure().
#define ADC_SSOP (ADC_O_SSOP0 - ADC_O_SSMUX0)
Definition at line 71 of file adc.c.
Referenced by ADCSequenceStepConfigure().
#define ADC_SSTSH (ADC_O_SSTSH0 - ADC_O_SSMUX0)
Definition at line 73 of file adc.c.
Referenced by ADCSequenceStepConfigure().
Function Documentation
static uint_fast8_t _ADCIntNumberGet (uint32_t ui32Base, uint32_t ui32SequenceNum) static
Returns the interrupt number for a given ADC base address and sequence number.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function returns the interrupt number for the ADC module and sequence number provided in the ui32Base and ui32SequenceNum parameters.
Returns
Returns the ADC sequence interrupt number or 0 if the interrupt does not exist.
Definition at line 99 of file adc.c.
References ADC0_BASE, CLASS_IS_TM4C123, CLASS_IS_TM4C129, INT_ADC0SS0_TM4C123, INT_ADC0SS0_TM4C129, and INT_ADC1SS0_TM4C129.
Referenced by ADCIntRegister(), and ADCIntUnregister().
 {
     uint_fast8_t ui8Int;
     //
     // Determine the interrupt to register based on the sequence number.
     //
     if(CLASS_IS_TM4C123)
     {
         ui8Int = ((ui32Base == ADC0_BASE) ?
                   (INT_ADC0SS0_TM4C123 + ui32SequenceNum) :
                   (INT_ADC0SS0_TM4C123 + ui32SequenceNum));
     }
     else if(CLASS_IS_TM4C129)
     {
         ui8Int = ((ui32Base == ADC0_BASE) ?
                   (INT_ADC0SS0_TM4C129 + ui32SequenceNum) :
                   (INT_ADC1SS0_TM4C129 + ui32SequenceNum));
     }
     else
     {
         ui8Int = 0;
     }
     return(ui8Int);
 }
bool ADCBusy (uint32_t ui32Base)
Determines whether the ADC is busy or not.
Parameters
ui32Base is the base address of the ADC.
This function allows the caller to determine whether or not the ADC is currently sampling . If false is returned, then the ADC is not sampling data.
Use this function to detect that the ADC is finished sampling data before putting the device into deep sleep. Before using this function, it is highly recommended that the event trigger is changed to ADC_TRIGGER_NEVER on all enabled sequencers to prevent the ADC from starting after checking the busy status.
Returns
Returns true if the ADC is sampling or false if all samples are complete.
Definition at line 1834 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_ACTSS_BUSY, ADC_O_ACTSS, ASSERT, and HWREG.
 {
     //
     // Check the argument.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Determine if the ADC is busy.
     //
     return((HWREG(ui32Base + ADC_O_ACTSS) & ADC_ACTSS_BUSY) ? true : false);
 }
uint32_t ADCClockConfigGet (uint32_t ui32Base, uint32_t * pui32ClockDiv)
Returns the clock configuration for the ADC.
Parameters
ui32Base is the base address of the ADC to configure, which must always be ADC0_BASE.
pui32ClockDiv is a pointer to the input clock divider for the clock selected by the ADC_CLOCK_SRC in use by the ADCs.
This function returns the ADC clock configuration and the clock divider for the ADCs.
Example: Read the current ADC clock configuration.
//! uint32_t ui32Config, ui32ClockDiv;
//!
//! //
//! // Read the current ADC clock configuration.
//! //
//! ui32Config = ADCClockConfigGet(ADC0_BASE, &ui32ClockDiv);
//!
\return The current clock configuration of the ADC defined as a combination
of one of \b ADC_CLOCK_SRC_PLL, \b ADC_CLOCK_SRC_PIOSC,
\b ADC_CLOCK_SRC_MOSC, or \b ADC_CLOCK_SRC_ALTCLK logical ORed with one of
\b ADC_CLOCK_RATE_FULL, \b ADC_CLOCK_RATE_HALF, \b ADC_CLOCK_RATE_QUARTER,
or \b ADC_CLOCK_RATE_EIGHTH.  See ADCClockConfigSet() for more information
on these values.
Definition at line 1978 of file adc.c.
References ADC0_BASE, ADC_CC_CLKDIV_M, ADC_CC_CLKDIV_S, ADC_O_CC, ADC_O_PC, ADC_PC_SR_M, ASSERT, and HWREG.
 {
     uint32_t ui32Config;
     //
     // Check the argument.
     //
     ASSERT(ui32Base == ADC0_BASE);
     //
     // Read the current configuration.
     //
     ui32Config = HWREG(ui32Base + ADC_O_CC);
     //
     // If the clock divider was requested provide the current value.
     //
     if(pui32ClockDiv)
     {
         *pui32ClockDiv =
                     ((ui32Config & ADC_CC_CLKDIV_M) >> ADC_CC_CLKDIV_S) + 1;
     }
     //
     // Clear out the divider bits.
     //
     ui32Config &= ~ADC_CC_CLKDIV_M;
     //
     // Add in the sample interval to the configuration.
     //
     ui32Config = (HWREG(ui32Base + ADC_O_PC) & ADC_PC_SR_M) << 4;
     return(ui32Config);
 }
void ADCClockConfigSet (uint32_t ui32Base, uint32_t ui32Config, uint32_t ui32ClockDiv)
Sets the clock configuration for the ADC.
Parameters
ui32Base is the base address of the ADC to configure, which must always be ADC0_BASE.
ui32Config is a combination of the ADC_CLOCK_SRC_ and ADC_CLOCK_RATE_* values used to configure the ADC clock input.
ui32ClockDiv is the input clock divider for the clock selected by the ADC_CLOCK_SRC value.
This function is used to configure the input clock to the ADC modules. The clock configuration is shared across ADC units so ui32Base must always be ADC0_BASE. The ui32Config value is logical OR of one of the ADC_CLOCK_RATE_ and one of the ADC_CLOCK_SRC_ values defined below. The ADC_CLOCK_SRC_* values determine the input clock for the ADC. Not all values are available on all devices so check the device data sheet to determine value configuration options. Regardless of the source, the final frequency for TM4C123x devices must be 16 MHz and for TM4C129x parts after dividing must be between 16 and 32 MHz.
Note
For TM4C123x devices, if the PLL is enabled, the PLL/25 is used as the ADC clock unless ADC_CLOCK_SRC_PIOSC is specified. If the PLL is disabled, the MOSC is used as the clock source unless ADC_CLOCK_SRC_PIOSC is specified.
ADC_CLOCK_SRC_PLL - The main PLL output (TM4x129 class only).
ADC_CLOCK_SRC_PIOSC - The internal PIOSC at 16 MHz.
ADC_CLOCK_SRC_ALTCLK - The output of the ALTCLK in the system control module (TM4x129 class only).
ADC_CLOCK_SRC_MOSC - The external MOSC (TM4x129 class only).
ADC_CLOCK_RATE values control how often samples are provided back to the application. The values are the following:
ADC_CLOCK_RATE_FULL - All samples.
ADC_CLOCK_RATE_HALF - Every other sample.
ADC_CLOCK_RATE_QUARTER - Every fourth sample.
ADC_CLOCK_RATE_EIGHTH - Every either sample.
The ui32ClockDiv parameter allows for dividing a higher frequency down into the valid range for the ADCs. This parameter is typically only used ADC_CLOCK_SRC_PLL option because it is the only clock value that can be with the in the correct range to use the divider. The actual value ranges from 1 to 64.
Example: ADC Clock Configurations
//!
//! //
//! // Configure the ADC to use PIOSC divided by one (16 MHz) and sample at
//! // half the rate.
//! //
//! ADCClockConfigSet(ADC0_BASE, ADC_CLOCK_SRC_PIOSC | ADC_CLOCK_RATE_HALF, 1);
//!
//! ...
//!
//! //
//! // Configure the ADC to use PLL at 480 MHz divided by 24 to get an ADC
//! // clock of 20 MHz.
//! //
//! ADCClockConfigSet(ADC0_BASE, ADC_CLOCK_SRC_PLL | ADC_CLOCK_RATE_FULL, 24);
//!
\return None.
Definition at line 1916 of file adc.c.
References ADC0_BASE, ADC_CC_CLKDIV_M, ADC_CC_CLKDIV_S, ADC_CC_CS_M, ADC_CLOCK_RATE_FULL, ADC_O_CC, ADC_O_PC, ADC_PC_SR_M, ASSERT, and HWREG.
 {
     //
     // Check the argument.
     //
     ASSERT(ui32Base == ADC0_BASE);
     //
     // A rate must be supplied.
     //
     ASSERT((ui32Config & ADC_CLOCK_RATE_FULL) != 0);
     //
     // Clock must be valid divider.
     //
     ASSERT(((ui32ClockDiv - 1) & ~ADC_CC_CLKDIV_M) == 0);
     //
     // Write the sample conversion rate.
     //
     HWREG(ui32Base + ADC_O_PC) = (ui32Config >> 4) & ADC_PC_SR_M;
     //
     // Write the clock select and divider.
     //
     HWREG(ui32Base + ADC_O_CC) = (ui32Config & ADC_CC_CS_M) |
                                  (((ui32ClockDiv - 1) << ADC_CC_CLKDIV_S)) ;
 }
void ADCComparatorConfigure (uint32_t ui32Base, uint32_t ui32Comp, uint32_t ui32Config)
Configures an ADC digital comparator.
Parameters
ui32Base is the base address of the ADC module.
ui32Comp is the index of the comparator to configure.
ui32Config is the configuration of the comparator.
This function configures a comparator. The ui32Config parameter is the result of a logical OR operation between the ADC_COMP_TRIG_xxx, and ADC_COMP_INT_xxx values.
The ADC_COMP_TRIG_xxx term can take on the following values:
ADC_COMP_TRIG_NONE to never trigger PWM fault condition.
ADC_COMP_TRIG_LOW_ALWAYS to always trigger PWM fault condition when ADC output is in the low-band.
ADC_COMP_TRIG_LOW_ONCE to trigger PWM fault condition once when ADC output transitions into the low-band.
ADC_COMP_TRIG_LOW_HALWAYS to always trigger PWM fault condition when ADC output is in the low-band only if ADC output has been in the high-band since the last trigger output.
ADC_COMP_TRIG_LOW_HONCE to trigger PWM fault condition once when ADC output transitions into low-band only if ADC output has been in the high-band since the last trigger output.
ADC_COMP_TRIG_MID_ALWAYS to always trigger PWM fault condition when ADC output is in the mid-band.
ADC_COMP_TRIG_MID_ONCE to trigger PWM fault condition once when ADC output transitions into the mid-band.
ADC_COMP_TRIG_HIGH_ALWAYS to always trigger PWM fault condition when ADC output is in the high-band.
ADC_COMP_TRIG_HIGH_ONCE to trigger PWM fault condition once when ADC output transitions into the high-band.
ADC_COMP_TRIG_HIGH_HALWAYS to always trigger PWM fault condition when ADC output is in the high-band only if ADC output has been in the low-band since the last trigger output.
ADC_COMP_TRIG_HIGH_HONCE to trigger PWM fault condition once when ADC output transitions into high-band only if ADC output has been in the low-band since the last trigger output.
The ADC_COMP_INT_xxx term can take on the following values:
ADC_COMP_INT_NONE to never generate ADC interrupt.
ADC_COMP_INT_LOW_ALWAYS to always generate ADC interrupt when ADC output is in the low-band.
ADC_COMP_INT_LOW_ONCE to generate ADC interrupt once when ADC output transitions into the low-band.
ADC_COMP_INT_LOW_HALWAYS to always generate ADC interrupt when ADC output is in the low-band only if ADC output has been in the high-band since the last trigger output.
ADC_COMP_INT_LOW_HONCE to generate ADC interrupt once when ADC output transitions into low-band only if ADC output has been in the high-band since the last trigger output.
ADC_COMP_INT_MID_ALWAYS to always generate ADC interrupt when ADC output is in the mid-band.
ADC_COMP_INT_MID_ONCE to generate ADC interrupt once when ADC output transitions into the mid-band.
ADC_COMP_INT_HIGH_ALWAYS to always generate ADC interrupt when ADC output is in the high-band.
ADC_COMP_INT_HIGH_ONCE to generate ADC interrupt once when ADC output transitions into the high-band.
ADC_COMP_INT_HIGH_HALWAYS to always generate ADC interrupt when ADC output is in the high-band only if ADC output has been in the low-band since the last trigger output.
ADC_COMP_INT_HIGH_HONCE to generate ADC interrupt once when ADC output transitions into high-band only if ADC output has been in the low-band since the last trigger output.
Returns
None.
Definition at line 1222 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_DCCTL0, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32Comp < 8);
     //
     // Save the new setting.
     //
     HWREG(ui32Base + ADC_O_DCCTL0 + (ui32Comp * 4)) = ui32Config;
 }
void ADCComparatorIntClear (uint32_t ui32Base, uint32_t ui32Status)
Clears sample sequence comparator interrupt source.
Parameters
ui32Base is the base address of the ADC module.
ui32Status is the bit-mapped interrupts status to clear.
The specified interrupt status is cleared.
Returns
None.
Definition at line 1414 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_DCISC, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Clear the interrupt.
     //
     HWREG(ui32Base + ADC_O_DCISC) = ui32Status;
 }
void ADCComparatorIntDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Disables a sample sequence comparator interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function disables the requested sample sequence comparator interrupt.
Returns
None.
Definition at line 1334 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Disable this sample sequence comparator interrupt.
     //
     HWREG(ui32Base + ADC_O_IM) &= ~(0x10000 << ui32SequenceNum);
 }
void ADCComparatorIntEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Enables a sample sequence comparator interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function enables the requested sample sequence comparator interrupt.
Returns
None.
Definition at line 1361 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Enable this sample sequence interrupt.
     //
     HWREG(ui32Base + ADC_O_IM) |= 0x10000 << ui32SequenceNum;
 }
uint32_t ADCComparatorIntStatus (uint32_t ui32Base)
Gets the current comparator interrupt status.
Parameters
ui32Base is the base address of the ADC module.
This function returns the digital comparator interrupt status bits. This status is sequence agnostic.
Returns
The current comparator interrupt status.
Definition at line 1388 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_DCISC, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Return the digital comparator interrupt status.
     //
     return(HWREG(ui32Base + ADC_O_DCISC));
 }
void ADCComparatorRegionSet (uint32_t ui32Base, uint32_t ui32Comp, uint32_t ui32LowRef, uint32_t ui32HighRef)
Defines the ADC digital comparator regions.
Parameters
ui32Base is the base address of the ADC module.
ui32Comp is the index of the comparator to configure.
ui32LowRef is the reference point for the low/mid band threshold.
ui32HighRef is the reference point for the mid/high band threshold.
The ADC digital comparator operation is based on three ADC value regions:
low-band is defined as any ADC value less than or equal to the ui32LowRef value.
mid-band is defined as any ADC value greater than the ui32LowRef value but less than or equal to the ui32HighRef value.
high-band is defined as any ADC value greater than the ui32HighRef value.
Returns
None.
Definition at line 1258 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_DCCMP0, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32Comp < 8);
     ASSERT((ui32LowRef < 4096) && (ui32LowRef <= ui32HighRef));
     ASSERT(ui32HighRef < 4096);
     //
     // Save the new region settings.
     //
     HWREG(ui32Base + ADC_O_DCCMP0 + (ui32Comp * 4)) = ((ui32HighRef << 16) |
                                                        ui32LowRef);
 }
void ADCComparatorReset (uint32_t ui32Base, uint32_t ui32Comp, bool bTrigger, bool bInterrupt)
Resets the current ADC digital comparator conditions.
Parameters
ui32Base is the base address of the ADC module.
ui32Comp is the index of the comparator.
bTrigger is the flag to indicate reset of Trigger conditions.
bInterrupt is the flag to indicate reset of Interrupt conditions.
Because the digital comparator uses current and previous ADC values, this function allows the comparator to be reset to its initial value to prevent stale data from being used when a sequence is enabled.
Returns
None.
Definition at line 1293 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_DCRIC, ASSERT, and HWREG.
 {
     uint32_t ui32Temp;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32Comp < 8);
     //
     // Set the appropriate bits to reset the trigger and/or interrupt
     // comparator conditions.
     //
     ui32Temp = 0;
     if(bTrigger)
     {
         ui32Temp |= (1 << (16 + ui32Comp));
     }
     if(bInterrupt)
     {
         ui32Temp |= (1 << ui32Comp);
     }
     HWREG(ui32Base + ADC_O_DCRIC) = ui32Temp;
 }
void ADCHardwareOversampleConfigure (uint32_t ui32Base, uint32_t ui32Factor)
Configures the hardware oversampling factor of the ADC.
Parameters
ui32Base is the base address of the ADC module.
ui32Factor is the number of samples to be averaged.
This function configures the hardware oversampling for the ADC, which can be used to provide better resolution on the sampled data. Oversampling is accomplished by averaging multiple samples from the same analog input. Six different oversampling rates are supported; 2x, 4x, 8x, 16x, 32x, and 64x. Specifying an oversampling factor of zero disables hardware oversampling.
Hardware oversampling applies uniformly to all sample sequencers. It does not reduce the depth of the sample sequencers like the software oversampling APIs; each sample written into the sample sequencer FIFO is a fully oversampled analog input reading.
Enabling hardware averaging increases the precision of the ADC at the cost of throughput. For example, enabling 4x oversampling reduces the throughput of a 250 k samples/second ADC to 62.5 k samples/second.
Returns
None.
Definition at line 1124 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_SAC, ASSERT, and HWREG.
 {
     uint32_t ui32Value;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(((ui32Factor == 0) || (ui32Factor == 2) || (ui32Factor == 4) ||
             (ui32Factor == 8) || (ui32Factor == 16) || (ui32Factor == 32) ||
             (ui32Factor == 64)));
     //
     // Convert the oversampling factor to a shift factor.
     //
     for(ui32Value = 0, ui32Factor >>= 1; ui32Factor;
         ui32Value++, ui32Factor >>= 1)
     {
     }
     //
     // Write the shift factor to the ADC to configure the hardware oversampler.
     //
     HWREG(ui32Base + ADC_O_SAC) = ui32Value;
 }
void ADCIntClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
Clears sample sequence interrupt source.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
The specified sample sequence interrupt is cleared, so that it no longer asserts. This function must be called in the interrupt handler to keep the interrupt from being triggered again immediately upon exit.
Note
Because there is a write buffer in the Cortex-M processor, it may take several clock cycles before the interrupt source is actually cleared. Therefore, it is recommended that the interrupt source be cleared early in the interrupt handler (as opposed to the very last action) to avoid returning from the interrupt handler before the interrupt source is actually cleared. Failure to do so may result in the interrupt handler being immediately reentered (because the interrupt controller still sees the interrupt source asserted).
Returns
None.
Definition at line 363 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ISC, ASSERT, and HWREG.
Referenced by ADC0Seq0_Handler(), adc_open(), and do_adc_func().
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Clear the interrupt.
     //
     HWREG(ui32Base + ADC_O_ISC) = 1 << ui32SequenceNum;
 }
void ADCIntClearEx (uint32_t ui32Base, uint32_t ui32IntFlags)
Clears the specified ADC interrupt sources.
Parameters
ui32Base is the base address of the ADC port.
ui32IntFlags is the bit mask of the interrupt sources to disable.
Clears the interrupt for the specified interrupt source(s).
The ui32IntFlags parameter is the logical OR of the ADC_INT_* values. See the ADCIntEnableEx() function for the list of possible ADC_INT* values.
Note
Because there is a write buffer in the Cortex-M processor, it may take several clock cycles before the interrupt source is actually cleared. Therefore, it is recommended that the interrupt source be cleared early in the interrupt handler (as opposed to the very last action) to avoid returning from the interrupt handler before the interrupt source is actually cleared. Failure to do so may result in the interrupt handler being immediately reentered (because the interrupt controller still sees the interrupt source asserted).
Returns
None.
Definition at line 1606 of file adc.c.
References ADC_O_ISC, and HWREG.
 {
     HWREG(ui32Base + ADC_O_ISC) |= ui32IntFlags;
 }
void ADCIntDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Disables a sample sequence interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function disables the requested sample sequence interrupt.
Returns
None.
Definition at line 234 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Disable this sample sequence interrupt.
     //
     HWREG(ui32Base + ADC_O_IM) &= ~(1 << ui32SequenceNum);
 }
void ADCIntDisableEx (uint32_t ui32Base, uint32_t ui32IntFlags)
Disables ADC interrupt sources.
Parameters
ui32Base is the base address of the ADC module.
ui32IntFlags is the bit mask of the interrupt sources to disable.
This function disables the indicated ADC interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The ui32IntFlags parameter is the logical OR of any of the following:
ADC_INT_SS0 - interrupt due to ADC sample sequence 0.
ADC_INT_SS1 - interrupt due to ADC sample sequence 1.
ADC_INT_SS2 - interrupt due to ADC sample sequence 2.
ADC_INT_SS3 - interrupt due to ADC sample sequence 3.
ADC_INT_DMA_SS0 - interrupt due to DMA on ADC sample sequence 0.
ADC_INT_DMA_SS1 - interrupt due to DMA on ADC sample sequence 1.
ADC_INT_DMA_SS2 - interrupt due to DMA on ADC sample sequence 2.
ADC_INT_DMA_SS3 - interrupt due to DMA on ADC sample sequence 3.
ADC_INT_DCON_SS0 - interrupt due to digital comparator on ADC sample sequence 0.
ADC_INT_DCON_SS1 - interrupt due to digital comparator on ADC sample sequence 1.
ADC_INT_DCON_SS2 - interrupt due to digital comparator on ADC sample sequence 2.
ADC_INT_DCON_SS3 - interrupt due to digital comparator on ADC sample sequence 3.
Returns
None.
Definition at line 1461 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Disable the requested interrupts.
     //
     HWREG(ui32Base + ADC_O_IM) &= ~ui32IntFlags;
 }
void ADCIntEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Enables a sample sequence interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function enables the requested sample sequence interrupt. Any outstanding interrupts are cleared before enabling the sample sequence interrupt.
Returns
None.
Definition at line 263 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ADC_O_ISC, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Clear any outstanding interrupts on this sample sequence.
     //
     HWREG(ui32Base + ADC_O_ISC) = 1 << ui32SequenceNum;
     //
     // Enable this sample sequence interrupt.
     //
     HWREG(ui32Base + ADC_O_IM) |= 1 << ui32SequenceNum;
 }
void ADCIntEnableEx (uint32_t ui32Base, uint32_t ui32IntFlags)
Enables ADC interrupt sources.
Parameters
ui32Base is the base address of the ADC module.
ui32IntFlags is the bit mask of the interrupt sources to disable.
This function enables the indicated ADC interrupt sources. Only the sources that are enabled can be reflected to the processor interrupt; disabled sources have no effect on the processor.
The ui32IntFlags parameter is the logical OR of any of the following:
ADC_INT_SS0 - interrupt due to ADC sample sequence 0.
ADC_INT_SS1 - interrupt due to ADC sample sequence 1.
ADC_INT_SS2 - interrupt due to ADC sample sequence 2.
ADC_INT_SS3 - interrupt due to ADC sample sequence 3.
ADC_INT_DMA_SS0 - interrupt due to DMA on ADC sample sequence 0.
ADC_INT_DMA_SS1 - interrupt due to DMA on ADC sample sequence 1.
ADC_INT_DMA_SS2 - interrupt due to DMA on ADC sample sequence 2.
ADC_INT_DMA_SS3 - interrupt due to DMA on ADC sample sequence 3.
ADC_INT_DCON_SS0 - interrupt due to digital comparator on ADC sample sequence 0.
ADC_INT_DCON_SS1 - interrupt due to digital comparator on ADC sample sequence 1.
ADC_INT_DCON_SS2 - interrupt due to digital comparator on ADC sample sequence 2.
ADC_INT_DCON_SS3 - interrupt due to digital comparator on ADC sample sequence 3.
Returns
None.
Definition at line 1508 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_IM, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Enable the requested interrupts.
     //
     HWREG(ui32Base + ADC_O_IM) |= ui32IntFlags;
 }
void ADCIntRegister (uint32_t ui32Base, uint32_t ui32SequenceNum, void(*)(void) pfnHandler)
Registers an interrupt handler for an ADC interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
pfnHandler is a pointer to the function to be called when the ADC sample sequence interrupt occurs.
This function sets the handler to be called when a sample sequence interrupt occurs. This function enables the global interrupt in the interrupt controller; the sequence interrupt must be enabled with ADCIntEnable(). It is the interrupt handler's responsibility to clear the interrupt source via ADCIntClear().
See also
IntRegister() for important information about registering interrupt handlers.
Returns
None.
Definition at line 148 of file adc.c.
References _ADCIntNumberGet(), ADC0_BASE, ADC1_BASE, ASSERT, IntEnable(), and IntRegister().
 {
     uint_fast8_t ui8Int;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Determine the interrupt to register based on the sequence number.
     //
     ui8Int = _ADCIntNumberGet(ui32Base, ui32SequenceNum);
     ASSERT(ui8Int != 0);
     //
     // Register the interrupt handler.
     //
     IntRegister(ui8Int, pfnHandler);
     //
     // Enable the timer interrupt.
     //
     IntEnable(ui8Int);
 }
uint32_t ADCIntStatus (uint32_t ui32Base, uint32_t ui32SequenceNum, bool bMasked)
Gets the current interrupt status.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
bMasked is false if the raw interrupt status is required and true if the masked interrupt status is required.
This function returns the interrupt status for the specified sample sequence. Either the raw interrupt status or the status of interrupts that are allowed to reflect to the processor can be returned.
Returns
The current raw or masked interrupt status.
Definition at line 299 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ISC, ADC_O_RIS, ASSERT, and HWREG.
Referenced by do_adc_func().
 {
     uint32_t ui32Temp;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Return either the interrupt status or the raw interrupt status as
     // requested.
     //
     if(bMasked)
     {
         ui32Temp = HWREG(ui32Base + ADC_O_ISC) & (0x10001 << ui32SequenceNum);
     }
     else
     {
         ui32Temp = (HWREG(ui32Base + ADC_O_RIS) &
                     (0x10000 | (1 << ui32SequenceNum)));
         //
         // If the digital comparator status bit is set, reflect it to the
         // appropriate sequence bit.
         //
         if(ui32Temp & 0x10000)
         {
             ui32Temp |= 0xF0000;
             ui32Temp &= ~(0x10000 << ui32SequenceNum);
         }
     }
     //
     // Return the interrupt status
     //
     return(ui32Temp);
 }
uint32_t ADCIntStatusEx (uint32_t ui32Base, bool bMasked)
Gets interrupt status for the specified ADC module.
Parameters
ui32Base is the base address of the ADC module.
bMasked specifies whether masked or raw interrupt status is returned.
If bMasked is set as true, then the masked interrupt status is returned; otherwise, the raw interrupt status is returned.
Returns
Returns the current interrupt status for the specified ADC module. The value returned is the logical OR of the ADC_INT_* values that are currently active.
Definition at line 1538 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_INT_DCON_SS0, ADC_INT_DCON_SS1, ADC_INT_DCON_SS2, ADC_INT_DCON_SS3, ADC_O_ISC, ADC_O_RIS, ADC_RIS_INRDC, ASSERT, and HWREG.
 {
     uint32_t ui32Temp;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Return either the masked interrupt status or the raw interrupt status as
     // requested.
     //
     if(bMasked)
     {
         ui32Temp = HWREG(ui32Base + ADC_O_ISC);
     }
     else
     {
         //
         // Read the Raw interrupt status to see if a digital comparator
         // interrupt is active.
         //
         ui32Temp = HWREG(ui32Base + ADC_O_RIS);
         //
         // Since, the raw interrupt status only indicates that any one of the
         // digital comparators caused an interrupt, if the raw interrupt status
         // is set then the return value is modified to indicate that all sample
         // sequences have a pending digital comparator interrupt.
         // This is exactly how the hardware works so the return code is
         // modified to match this behavior.
         //
         if(ui32Temp & ADC_RIS_INRDC)
         {
             ui32Temp |= (ADC_INT_DCON_SS3 | ADC_INT_DCON_SS2 |
                          ADC_INT_DCON_SS1 | ADC_INT_DCON_SS0);
         }
     }
     return(ui32Temp);
 }
void ADCIntUnregister (uint32_t ui32Base, uint32_t ui32SequenceNum)
Unregisters the interrupt handler for an ADC interrupt.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function unregisters the interrupt handler. This function disables the global interrupt in the interrupt controller; the sequence interrupt must be disabled via ADCIntDisable().
See also
IntRegister() for important information about registering interrupt handlers.
Returns
None.
Definition at line 194 of file adc.c.
References _ADCIntNumberGet(), ADC0_BASE, ADC1_BASE, ASSERT, IntDisable(), and IntUnregister().
 {
     uint_fast8_t ui8Int;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Determine the interrupt to unregister based on the sequence number.
     //
     ui8Int = _ADCIntNumberGet(ui32Base, ui32SequenceNum);
     ASSERT(ui8Int != 0);
     //
     // Disable the interrupt.
     //
     IntDisable(ui8Int);
     //
     // Unregister the interrupt handler.
     //
     IntUnregister(ui8Int);
 }
uint32_t ADCPhaseDelayGet (uint32_t ui32Base)
Gets the phase delay between a trigger and the start of a sequence.
Parameters
ui32Base is the base address of the ADC module.
This function gets the current phase delay between the detection of an ADC trigger event and the start of the sample sequence.
Returns
Returns the phase delay, specified as one of ADC_PHASE_0, ADC_PHASE_22_5, ADC_PHASE_45, ADC_PHASE_67_5, ADC_PHASE_90, ADC_PHASE_112_5, ADC_PHASE_135, ADC_PHASE_157_5, ADC_PHASE_180, ADC_PHASE_202_5, ADC_PHASE_225, ADC_PHASE_247_5, ADC_PHASE_270, ADC_PHASE_292_5, ADC_PHASE_315, or ADC_PHASE_337_5.
Definition at line 1745 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_SPC, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Return the phase delay.
     //
     return(HWREG(ui32Base + ADC_O_SPC));
 }
void ADCPhaseDelaySet (uint32_t ui32Base, uint32_t ui32Phase)
Sets the phase delay between a trigger and the start of a sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32Phase is the phase delay, specified as one of ADC_PHASE_0, ADC_PHASE_22_5, ADC_PHASE_45, ADC_PHASE_67_5, ADC_PHASE_90, ADC_PHASE_112_5, ADC_PHASE_135, ADC_PHASE_157_5, ADC_PHASE_180, ADC_PHASE_202_5, ADC_PHASE_225, ADC_PHASE_247_5, ADC_PHASE_270, ADC_PHASE_292_5, ADC_PHASE_315, or ADC_PHASE_337_5.
This function sets the phase delay between the detection of an ADC trigger event and the start of the sample sequence. By selecting a different phase delay for a pair of ADC modules (such as ADC_PHASE_0 and ADC_PHASE_180) and having each ADC module sample the same analog input, it is possible to increase the sampling rate of the analog input (with samples N, N+2, N+4, and so on, coming from the first ADC and samples N+1, N+3, N+5, and so on, coming from the second ADC). The ADC module has a single phase delay that is applied to all sample sequences within that module.
Note
This capability is not available on all parts.
Returns
None.
Definition at line 1707 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_SPC, ADC_PHASE_0, ADC_PHASE_112_5, ADC_PHASE_135, ADC_PHASE_157_5, ADC_PHASE_180, ADC_PHASE_202_5, ADC_PHASE_225, ADC_PHASE_22_5, ADC_PHASE_247_5, ADC_PHASE_270, ADC_PHASE_292_5, ADC_PHASE_315, ADC_PHASE_337_5, ADC_PHASE_45, ADC_PHASE_67_5, ADC_PHASE_90, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT((ui32Phase == ADC_PHASE_0) || (ui32Phase == ADC_PHASE_22_5) ||
            (ui32Phase == ADC_PHASE_45) || (ui32Phase == ADC_PHASE_67_5) ||
            (ui32Phase == ADC_PHASE_90) || (ui32Phase == ADC_PHASE_112_5) ||
            (ui32Phase == ADC_PHASE_135) || (ui32Phase == ADC_PHASE_157_5) ||
            (ui32Phase == ADC_PHASE_180) || (ui32Phase == ADC_PHASE_202_5) ||
            (ui32Phase == ADC_PHASE_225) || (ui32Phase == ADC_PHASE_247_5) ||
            (ui32Phase == ADC_PHASE_270) || (ui32Phase == ADC_PHASE_292_5) ||
            (ui32Phase == ADC_PHASE_315) || (ui32Phase == ADC_PHASE_337_5));
     //
     // Set the phase delay.
     //
     HWREG(ui32Base + ADC_O_SPC) = ui32Phase;
 }
void ADCProcessorTrigger (uint32_t ui32Base, uint32_t ui32SequenceNum)
Causes a processor trigger for a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number, with ADC_TRIGGER_WAIT or ADC_TRIGGER_SIGNAL optionally ORed into it.
This function triggers a processor-initiated sample sequence if the sample sequence trigger is configured to ADC_TRIGGER_PROCESSOR. If ADC_TRIGGER_WAIT is ORed into the sequence number, the processor-initiated trigger is delayed until a later processor-initiated trigger to a different ADC module that specifies ADC_TRIGGER_SIGNAL, allowing multiple ADCs to start from a processor-initiated trigger in a synchronous manner.
Returns
None.
Definition at line 884 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_PSSI, ASSERT, and HWREG.
Referenced by do_adc_func(), and main().
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Generate a processor trigger for this sample sequence.
     //
     HWREG(ui32Base + ADC_O_PSSI) |= ((ui32SequenceNum & 0xffff0000) |
                                      (1 << (ui32SequenceNum & 0xf)));
 }
uint32_t ADCReferenceGet (uint32_t ui32Base)
Returns the current setting of the ADC reference.
Parameters
ui32Base is the base address of the ADC module.
Returns the value of the ADC reference setting. The returned value is one of ADC_REF_INT, ADC_REF_EXT_3V, or ADC_REF_EXT_1V.
Note
The value returned by this function is only meaningful if used on a part that is capable of using an external reference. Consult the data sheet for your part to determine if it has an external reference input.
Returns
The current setting of the ADC reference.
Definition at line 1667 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_CTL_VREF_M, ADC_O_CTL, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     //
     // Return the value of the reference.
     //
     return(HWREG(ui32Base + ADC_O_CTL) & ADC_CTL_VREF_M);
 }
void ADCReferenceSet (uint32_t ui32Base, uint32_t ui32Ref)
Selects the ADC reference.
Parameters
ui32Base is the base address of the ADC module.
ui32Ref is the reference to use.
The ADC reference is set as specified by ui32Ref. It must be one of ADC_REF_INT, ADC_REF_EXT_3V, or ADC_REF_EXT_1V for internal or external reference. If ADC_REF_INT is chosen, then an internal 3V reference is used and no external reference is needed. If ADC_REF_EXT_3V is chosen, then a 3V reference must be supplied to the AVREF pin. If ADC_REF_EXT_1V is chosen, then a 1V external reference must be supplied to the AVREF pin.
Note
The ADC reference can only be selected on parts that have an external reference. Consult the data sheet for your part to determine if there is an external reference.
Returns
None.
Definition at line 1634 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_CTL_VREF_M, ADC_O_CTL, ADC_REF_EXT_1V, ADC_REF_EXT_3V, ADC_REF_INT, ASSERT, and HWREG.
Referenced by adc_init().
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT((ui32Ref == ADC_REF_INT) || (ui32Ref == ADC_REF_EXT_3V) ||
            (ui32Ref == ADC_REF_EXT_1V));
     //
     // Set the reference.
     //
     HWREG(ui32Base + ADC_O_CTL) =
         (HWREG(ui32Base + ADC_O_CTL) & ~ADC_CTL_VREF_M) | ui32Ref;
 }
void ADCSequenceConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Trigger, uint32_t ui32Priority)
Configures the trigger source and priority of a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
ui32Trigger is the trigger source that initiates the sample sequence; must be one of the ADC_TRIGGER_* values.
ui32Priority is the relative priority of the sample sequence with respect to the other sample sequences.
This function configures the initiation criteria for a sample sequence. Valid sample sequencers range from zero to three; sequencer zero captures up to eight samples, sequencers one and two capture up to four samples, and sequencer three captures a single sample. The trigger condition and priority (with respect to other sample sequencer execution) are set.
The ui32Trigger parameter can take on the following values:
ADC_TRIGGER_PROCESSOR - A trigger generated by the processor, via the ADCProcessorTrigger() function.
ADC_TRIGGER_COMP0 - A trigger generated by the first analog comparator; configured with ComparatorConfigure().
ADC_TRIGGER_COMP1 - A trigger generated by the second analog comparator; configured with ComparatorConfigure().
ADC_TRIGGER_COMP2 - A trigger generated by the third analog comparator; configured with ComparatorConfigure().
ADC_TRIGGER_EXTERNAL - A trigger generated by an input from the Port B4 pin. Note that some microcontrollers can select from any GPIO using the GPIOADCTriggerEnable() function.
ADC_TRIGGER_TIMER - A trigger generated by a timer; configured with TimerControlTrigger().
ADC_TRIGGER_PWM0 - A trigger generated by the first PWM generator; configured with PWMGenIntTrigEnable().
ADC_TRIGGER_PWM1 - A trigger generated by the second PWM generator; configured with PWMGenIntTrigEnable().
ADC_TRIGGER_PWM2 - A trigger generated by the third PWM generator; configured with PWMGenIntTrigEnable().
ADC_TRIGGER_PWM3 - A trigger generated by the fourth PWM generator; configured with PWMGenIntTrigEnable().
ADC_TRIGGER_ALWAYS - A trigger that is always asserted, causing the sample sequence to capture repeatedly (so long as there is not a higher priority source active).
When ADC_TRIGGER_PWM0, ADC_TRIGGER_PWM1, ADC_TRIGGER_PWM2 or ADC_TRIGGER_PWM3 is specified, one of the following should be ORed into ui32Trigger to select the PWM module from which the triggers will be routed for this sequence:
ADC_TRIGGER_PWM_MOD0 - Selects PWM module 0 as the source of the PWM0 to PWM3 triggers for this sequence.
ADC_TRIGGER_PWM_MOD1 - Selects PWM module 1 as the source of the PWM0 to PWM3 triggers for this sequence.
Note that not all trigger sources are available on all Tiva family members; consult the data sheet for the device in question to determine the availability of triggers.
The ui32Priority parameter is a value between 0 and 3, where 0 represents the highest priority and 3 the lowest. Note that when programming the priority among a set of sample sequences, each must have unique priority; it is up to the caller to guarantee the uniqueness of the priorities.
Returns
None.
Definition at line 502 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_EMUX, ADC_O_SSPRI, ADC_O_TSSEL, ADC_TRIGGER_ALWAYS, ADC_TRIGGER_COMP0, ADC_TRIGGER_COMP1, ADC_TRIGGER_COMP2, ADC_TRIGGER_EXTERNAL, ADC_TRIGGER_PROCESSOR, ADC_TRIGGER_PWM0, ADC_TRIGGER_PWM1, ADC_TRIGGER_PWM2, ADC_TRIGGER_PWM3, ADC_TRIGGER_PWM_MOD0, ADC_TRIGGER_PWM_MOD1, ADC_TRIGGER_TIMER, ASSERT, and HWREG.
Referenced by adc_open().
 {
     //
     // Check the arugments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     ASSERT(((ui32Trigger & 0xF) == ADC_TRIGGER_PROCESSOR) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_COMP0) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_COMP1) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_COMP2) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_EXTERNAL) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_TIMER) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_PWM0) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_PWM1) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_PWM2) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_PWM3) ||
            ((ui32Trigger & 0xF) == ADC_TRIGGER_ALWAYS) ||
            ((ui32Trigger & 0x30) == ADC_TRIGGER_PWM_MOD0) ||
            ((ui32Trigger & 0x30) == ADC_TRIGGER_PWM_MOD1));
     ASSERT(ui32Priority < 4);
     //
     // Compute the shift for the bits that control this sample sequence.
     //
     ui32SequenceNum *= 4;
     //
     // Set the trigger event for this sample sequence.
     //
     HWREG(ui32Base + ADC_O_EMUX) = ((HWREG(ui32Base + ADC_O_EMUX) &
                                      ~(0xf << ui32SequenceNum)) |
                                     ((ui32Trigger & 0xf) << ui32SequenceNum));
     //
     // Set the priority for this sample sequence.
     //
     HWREG(ui32Base + ADC_O_SSPRI) = ((HWREG(ui32Base + ADC_O_SSPRI) &
                                       ~(0xf << ui32SequenceNum)) |
                                      ((ui32Priority & 0x3) <<
                                       ui32SequenceNum));
     //
     // Set the source PWM module for this sequence's PWM triggers.
     //
     ui32SequenceNum *= 2;
     HWREG(ui32Base + ADC_O_TSSEL) = ((HWREG(ui32Base + ADC_O_TSSEL) &
                                       ~(0x30 << ui32SequenceNum)) |
                                      ((ui32Trigger & 0x30) <<
                                       ui32SequenceNum));
 }
int32_t ADCSequenceDataGet (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t * pui32Buffer)
Gets the captured data for a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
pui32Buffer is the address where the data is stored.
This function copies data from the specified sample sequencer output FIFO to a memory resident buffer. The number of samples available in the hardware FIFO are copied into the buffer, which is assumed to be large enough to hold that many samples. This function only returns the samples that are presently available, which may not be the entire sample sequence if it is in the process of being executed.
Returns
Returns the number of samples copied to the buffer.
Definition at line 824 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_SEQ, ADC_SEQ_STEP, ADC_SSFIFO, ADC_SSFSTAT, ADC_SSFSTAT0_EMPTY, ASSERT, and HWREG.
Referenced by ADC0Seq0_Handler(), and do_adc_func().
 {
     uint32_t ui32Count;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Get the offset of the sequence to be read.
     //
     ui32Base += ADC_SEQ + (ADC_SEQ_STEP * ui32SequenceNum);
     //
     // Read samples from the FIFO until it is empty.
     //
     ui32Count = 0;
     while(!(HWREG(ui32Base + ADC_SSFSTAT) & ADC_SSFSTAT0_EMPTY) &&
           (ui32Count < 8))
     {
         //
         // Read the FIFO and copy it to the destination.
         //
         *pui32Buffer++ = HWREG(ui32Base + ADC_SSFIFO);
         //
         // Increment the count of samples read.
         //
         ui32Count++;
     }
     //
     // Return the number of samples read.
     //
     return(ui32Count);
 }
void ADCSequenceDisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Disables a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
Prevents the specified sample sequence from being captured when its trigger is detected. A sample sequence must be disabled before it is configured.
Returns
None.
Definition at line 419 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ACTSS, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Disable the specified sequences.
     //
     HWREG(ui32Base + ADC_O_ACTSS) &= ~(1 << ui32SequenceNum);
 }
void ADCSequenceDMADisable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Disables DMA for sample sequencers.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
Prevents the specified sample sequencer from generating DMA requests.
Returns
None.
Definition at line 1799 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ACTSS, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Disable the DMA on the specified sequencer.
     //
     HWREG(ui32Base + ADC_O_ACTSS) &= ~(0x100 << ui32SequenceNum);
 }
void ADCSequenceDMAEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Enables DMA for sample sequencers.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
Allows DMA requests to be generated based on the FIFO level of the sample sequencer.
Returns
None.
Definition at line 1772 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ACTSS, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Enable the DMA on the specified sequencer.
     //
     HWREG(ui32Base + ADC_O_ACTSS) |= 0x100 << ui32SequenceNum;
 }
void ADCSequenceEnable (uint32_t ui32Base, uint32_t ui32SequenceNum)
Enables a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
Allows the specified sample sequence to be captured when its trigger is detected. A sample sequence must be configured before it is enabled.
Returns
None.
Definition at line 391 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_ACTSS, ASSERT, and HWREG.
Referenced by adc_init(), and adc_open().
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Enable the specified sequence.
     //
     HWREG(ui32Base + ADC_O_ACTSS) |= 1 << ui32SequenceNum;
 }
int32_t ADCSequenceOverflow (uint32_t ui32Base, uint32_t ui32SequenceNum)
Determines if a sample sequence overflow occurred.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function determines if a sample sequence overflow has occurred. Overflow happens if the captured samples are not read from the FIFO before the next trigger occurs.
Returns
Returns zero if there was not an overflow, and non-zero if there was.
Definition at line 704 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_OSTAT, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Determine if there was an overflow on this sequence.
     //
     return(HWREG(ui32Base + ADC_O_OSTAT) & (1 << ui32SequenceNum));
 }
void ADCSequenceOverflowClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
Clears the overflow condition on a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function clears an overflow condition on one of the sample sequences. The overflow condition must be cleared in order to detect a subsequent overflow condition (it otherwise causes no harm).
Returns
None.
Definition at line 733 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_OSTAT, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Clear the overflow condition for this sequence.
     //
     HWREG(ui32Base + ADC_O_OSTAT) = 1 << ui32SequenceNum;
 }
void ADCSequenceStepConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Step, uint32_t ui32Config)
Configure a step of the sample sequencer.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
ui32Step is the step to be configured.
ui32Config is the configuration of this step; must be a logical OR of ADC_CTL_TS, ADC_CTL_IE, ADC_CTL_END, ADC_CTL_D, one of the input channel selects (ADC_CTL_CH0 through ADC_CTL_CH23), and one of the digital comparator selects (ADC_CTL_CMP0 through ADC_CTL_CMP7).
This function configures the ADC for one step of a sample sequence. The ADC can be configured for single-ended or differential operation (the ADC_CTL_D bit selects differential operation when set), the channel to be sampled can be chosen (the ADC_CTL_CH0 through ADC_CTL_CH23 values), and the internal temperature sensor can be selected (the ADC_CTL_TS bit). Additionally, this step can be defined as the last in the sequence (the ADC_CTL_END bit) and it can be configured to cause an interrupt when the step is complete (the ADC_CTL_IE bit). If the digital comparators are present on the device, this step may also be configured to send the ADC sample to the selected comparator using ADC_CTL_CMP0 through ADC_CTL_CMP7. The configuration is used by the ADC at the appropriate time when the trigger for this sequence occurs.
Note
If the Digital Comparator is present and enabled using the ADC_CTL_CMP0 through ADC_CTL_CMP7 selects, the ADC sample is NOT written into the ADC sequence data FIFO.
The ui32Step parameter determines the order in which the samples are captured by the ADC when the trigger occurs. It can range from zero to seven for the first sample sequencer, from zero to three for the second and third sample sequencer, and can only be zero for the fourth sample sequencer.
Differential mode only works with adjacent channel pairs (for example, 0 and 1). The channel select must be the number of the channel pair to sample (for example, ADC_CTL_CH0 for 0 and 1, or ADC_CTL_CH1 for 2 and 3) or undefined results are returned by the ADC. Additionally, if differential mode is selected when the temperature sensor is being sampled, undefined results are returned by the ADC.
It is the responsibility of the caller to ensure that a valid configuration is specified; this function does not check the validity of the specified configuration.
Returns
None.
Definition at line 605 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_SEQ, ADC_SEQ_STEP, ADC_SSCTL, ADC_SSDC, ADC_SSEMUX, ADC_SSMUX, ADC_SSOP, ADC_SSTSH, ASSERT, and HWREG.
Referenced by adc_init(), and adc_open().
 {
     uint32_t ui32Temp;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     ASSERT(((ui32SequenceNum == 0) && (ui32Step < 8)) ||
            ((ui32SequenceNum == 1) && (ui32Step < 4)) ||
            ((ui32SequenceNum == 2) && (ui32Step < 4)) ||
            ((ui32SequenceNum == 3) && (ui32Step < 1)));
     //
     // Get the offset of the sequence to be configured.
     //
     ui32Base += ADC_SEQ + (ADC_SEQ_STEP * ui32SequenceNum);
     //
     // Compute the shift for the bits that control this step.
     //
     ui32Step *= 4;
     //
     // Set the analog mux value for this step.
     //
     HWREG(ui32Base + ADC_SSMUX) = ((HWREG(ui32Base + ADC_SSMUX) &
                                     ~(0x0000000f << ui32Step)) |
                                    ((ui32Config & 0x0f) << ui32Step));
     //
     // Set the upper bits of the analog mux value for this step.
     //
     HWREG(ui32Base + ADC_SSEMUX) = ((HWREG(ui32Base + ADC_SSEMUX) &
                                      ~(0x0000000f << ui32Step)) |
                                     (((ui32Config & 0xf00) >> 8) << ui32Step));
     //
     // Set the control value for this step.
     //
     HWREG(ui32Base + ADC_SSCTL) = ((HWREG(ui32Base + ADC_SSCTL) &
                                     ~(0x0000000f << ui32Step)) |
                                    (((ui32Config & 0xf0) >> 4) << ui32Step));
     //
     // Set the sample and hold time for this step.  This is not available on
     // all devices, however on devices that do not support this feature these
     // reserved bits are ignored on write access.
     //
     HWREG(ui32Base + ADC_SSTSH) = ((HWREG(ui32Base + ADC_SSTSH) &
                                     ~(0x0000000f << ui32Step)) |
                                 (((ui32Config & 0xf00000) >> 20) << ui32Step));
     //
     // Enable digital comparator if specified in the ui32Config bit-fields.
     //
     if(ui32Config & 0x000F0000)
     {
         //
         // Program the comparator for the specified step.
         //
         ui32Temp = HWREG(ui32Base + ADC_SSDC);
         ui32Temp &= ~(0xF << ui32Step);
         ui32Temp |= (((ui32Config & 0x00070000) >> 16) << ui32Step);
         HWREG(ui32Base + ADC_SSDC) = ui32Temp;
         //
         // Enable the comparator.
         //
         HWREG(ui32Base + ADC_SSOP) |= (1 << ui32Step);
     }
     //
     // Disable digital comparator if not specified.
     //
     else
     {
         HWREG(ui32Base + ADC_SSOP) &= ~(1 << ui32Step);
     }
 }
int32_t ADCSequenceUnderflow (uint32_t ui32Base, uint32_t ui32SequenceNum)
Determines if a sample sequence underflow occurred.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function determines if a sample sequence underflow has occurred. Underflow happens if too many samples are read from the FIFO.
Returns
Returns zero if there was not an underflow, and non-zero if there was.
Definition at line 762 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_USTAT, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Determine if there was an underflow on this sequence.
     //
     return(HWREG(ui32Base + ADC_O_USTAT) & (1 << ui32SequenceNum));
 }
void ADCSequenceUnderflowClear (uint32_t ui32Base, uint32_t ui32SequenceNum)
Clears the underflow condition on a sample sequence.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
This function clears an underflow condition on one of the sample sequencers. The underflow condition must be cleared in order to detect a subsequent underflow condition (it otherwise causes no harm).
Returns
None.
Definition at line 791 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_O_USTAT, ASSERT, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 4);
     //
     // Clear the underflow condition for this sequence.
     //
     HWREG(ui32Base + ADC_O_USTAT) = 1 << ui32SequenceNum;
 }
void ADCSoftwareOversampleConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Factor)
Configures the software oversampling factor of the ADC.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
ui32Factor is the number of samples to be averaged.
This function configures the software oversampling for the ADC, which can be used to provide better resolution on the sampled data. Oversampling is accomplished by averaging multiple samples from the same analog input. Three different oversampling rates are supported; 2x, 4x, and 8x.
Oversampling is only supported on the sample sequencers that are more than one sample in depth (that is, the fourth sample sequencer is not supported). Oversampling by 2x (for example) divides the depth of the sample sequencer by two; so 2x oversampling on the first sample sequencer can only provide four samples per trigger. This also means that 8x oversampling is only available on the first sample sequencer.
Returns
None.
Definition at line 923 of file adc.c.
References ADC0_BASE, ADC1_BASE, ASSERT, and g_pui8OversampleFactor.
 {
     uint32_t ui32Value;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 3);
     ASSERT(((ui32Factor == 2) || (ui32Factor == 4) || (ui32Factor == 8)) &&
            ((ui32SequenceNum == 0) || (ui32Factor != 8)));
     //
     // Convert the oversampling factor to a shift factor.
     //
     for(ui32Value = 0, ui32Factor >>= 1; ui32Factor;
         ui32Value++, ui32Factor >>= 1)
     {
     }
     //
     // Save the shift factor.
     //
     g_pui8OversampleFactor[ui32SequenceNum] = ui32Value;
 }
void ADCSoftwareOversampleDataGet (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t * pui32Buffer, uint32_t ui32Count)
Gets the captured data for a sample sequence using software oversampling.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
pui32Buffer is the address where the data is stored.
ui32Count is the number of samples to be read.
This function copies data from the specified sample sequence output FIFO to a memory resident buffer with software oversampling applied. The requested number of samples are copied into the data buffer; if there are not enough samples in the hardware FIFO to satisfy this many oversampled data items, then incorrect results are returned. It is the caller's responsibility to read only the samples that are available and wait until enough data is available, for example as a result of receiving an interrupt.
Returns
None.
Definition at line 1053 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_SEQ, ADC_SEQ_STEP, ADC_SSFIFO, ASSERT, g_pui8OversampleFactor, and HWREG.
 {
     uint32_t ui32Idx, ui32Accum;
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 3);
     ASSERT(((ui32SequenceNum == 0) &&
             (ui32Count < (8 >> g_pui8OversampleFactor[ui32SequenceNum]))) ||
            (ui32Count < (4 >> g_pui8OversampleFactor[ui32SequenceNum])));
     //
     // Get the offset of the sequence to be read.
     //
     ui32Base += ADC_SEQ + (ADC_SEQ_STEP * ui32SequenceNum);
     //
     // Read the samples from the FIFO until it is empty.
     //
     while(ui32Count--)
     {
         //
         // Compute the sum of the samples.
         //
         ui32Accum = 0;
         for(ui32Idx = 1 << g_pui8OversampleFactor[ui32SequenceNum]; ui32Idx;
             ui32Idx--)
         {
             //
             // Read the FIFO and add it to the accumulator.
             //
             ui32Accum += HWREG(ui32Base + ADC_SSFIFO);
         }
         //
         // Write the averaged sample to the output buffer.
         //
         *pui32Buffer++ = ui32Accum >> g_pui8OversampleFactor[ui32SequenceNum];
     }
 }
void ADCSoftwareOversampleStepConfigure (uint32_t ui32Base, uint32_t ui32SequenceNum, uint32_t ui32Step, uint32_t ui32Config)
Configures a step of the software oversampled sequencer.
Parameters
ui32Base is the base address of the ADC module.
ui32SequenceNum is the sample sequence number.
ui32Step is the step to be configured.
ui32Config is the configuration of this step.
This function configures a step of the sample sequencer when using the software oversampling feature. The number of steps available depends on the oversampling factor set by ADCSoftwareOversampleConfigure(). The value of ui32Config is the same as defined for ADCSequenceStepConfigure().
Returns
None.
Definition at line 968 of file adc.c.
References ADC0_BASE, ADC1_BASE, ADC_SEQ, ADC_SEQ_STEP, ADC_SSCTL, ADC_SSCTL0_END0, ADC_SSCTL0_IE0, ADC_SSEMUX, ADC_SSMUX, ASSERT, g_pui8OversampleFactor, and HWREG.
 {
     //
     // Check the arguments.
     //
     ASSERT((ui32Base == ADC0_BASE) || (ui32Base == ADC1_BASE));
     ASSERT(ui32SequenceNum < 3);
     ASSERT(((ui32SequenceNum == 0) &&
             (ui32Step < (8 >> g_pui8OversampleFactor[ui32SequenceNum]))) ||
            (ui32Step < (4 >> g_pui8OversampleFactor[ui32SequenceNum])));
     //
     // Get the offset of the sequence to be configured.
     //
     ui32Base += ADC_SEQ + (ADC_SEQ_STEP * ui32SequenceNum);
     //
     // Compute the shift for the bits that control this step.
     //
     ui32Step *= 4 << g_pui8OversampleFactor[ui32SequenceNum];
     //
     // Loop through the hardware steps that make up this step of the software
     // oversampled sequence.
     //
     for(ui32SequenceNum = 1 << g_pui8OversampleFactor[ui32SequenceNum];
         ui32SequenceNum; ui32SequenceNum--)
     {
         //
         // Set the analog mux value for this step.
         //
         HWREG(ui32Base + ADC_SSMUX) = ((HWREG(ui32Base + ADC_SSMUX) &
                                         ~(0x0000000f << ui32Step)) |
                                        ((ui32Config & 0x0f) << ui32Step));
         //
         // Set the upper bits of the analog mux value for this step.
         //
         HWREG(ui32Base + ADC_SSEMUX) = ((HWREG(ui32Base + ADC_SSEMUX) &
                                          ~(0x0000000f << ui32Step)) |
                                         (((ui32Config & 0xf00) >> 8) <<
                                          ui32Step));
         //
         // Set the control value for this step.
         //
         HWREG(ui32Base + ADC_SSCTL) = ((HWREG(ui32Base + ADC_SSCTL) &
                                         ~(0x0000000f << ui32Step)) |
                                        (((ui32Config & 0xf0) >> 4) <<
                                         ui32Step));
         if(ui32SequenceNum != 1)
         {
             HWREG(ui32Base + ADC_SSCTL) &= ~((ADC_SSCTL0_IE0 |
                                               ADC_SSCTL0_END0) << ui32Step);
         }
         //
         // Go to the next hardware step.
         //
         ui32Step += 4;
     }
 }
Variable Documentation
uint8_t g_pui8OversampleFactor[3] static
Definition at line 81 of file adc.c.
Referenced by ADCSoftwareOversampleConfigure(), ADCSoftwareOversampleDataGet(), and ADCSoftwareOversampleStepConfigure().