EE445M RTOS: lib/libhw/hardware.h File Reference
hardware.h File Reference
#include <stdbool.h>
#include "libnotify/notify.h"
Data Structures
struct _isr_subscription
struct hw_channel
struct hw_driver
struct hw_uart_metadata
struct hw_timer_metadata
union hw_metadata
Macros
#define HW_DRIVER_MAX_CHANNELS 8
#define HW_DRIVER_MAX_SUBSCRIPTIONS 8
Typedefs
typedef uint8_t hw_iterator
typedef long raw_hw_channel
typedef struct _isr_subscription _isr_subscription
typedef struct hw_channel hw_channel
typedef struct hw_driver hw_driver
typedef struct hw_uart_metadata hw_uart_metadata
typedef struct hw_timer_metadata hw_timer_metadata
Enumerations
enum HW_DEVICES {
HW_UART, HW_LCD, HW_TIMER, HW_ADC,
HW_SSI
}
Functions
void hw_driver_init (HW_DEVICES)
void hw_channel_init (HW_DEVICES, raw_hw_channel, hw_metadata)
bool hw_connect (HW_DEVICES, raw_hw_channel, const void *)
bool hw_disconnect (HW_DEVICES, raw_hw_channel, const void *)
bool hw_connect_single_shot (HW_DEVICES, raw_hw_channel, const void *)
hw_iterator _hw_first_available_subscription (hw_channel *)
raw_hw_channel _hw_channel_to_index (raw_hw_channel, HW_DEVICES)
hw_driver * hw_driver_singleton (HW_DEVICES hw_group)
hw_channel * _hw_get_channel (HW_DEVICES, raw_hw_channel)
void hw_notify (HW_DEVICES hw_group, raw_hw_channel channel, hw_notification notification)
Macro Definition Documentation
#define HW_DRIVER_MAX_CHANNELS 8
Maximum number of channels supported by each hardware peripheral
Definition at line 41 of file hardware.h.
#define HW_DRIVER_MAX_SUBSCRIPTIONS 8
Maximum number of subscribed threads each hardware driver is responsible for responding to
Definition at line 45 of file hardware.h.
Referenced by _hw_first_available_subscription(), hw_channel_init(), hw_disconnect(), and hw_notify().
Typedef Documentation
typedef struct _isr_subscription _isr_subscription
Each peripheral channel needs to be able to notify subscribers about incoming hardware events
typedef struct hw_channel hw_channel
A hardware driver manages multiple peripheral channels
typedef struct hw_driver hw_driver
Top level container for hardware driver data
typedef uint8_t hw_iterator
An iterator ensured to be of an optimized size according to the relevant #defines below it.
Definition at line 37 of file hardware.h.
typedef struct hw_timer_metadata hw_timer_metadata
Timer properties
typedef struct hw_uart_metadata hw_uart_metadata
typedef long raw_hw_channel
Used to represent #defines memory-mapped addresses before they are converted into hw_driver channel indices by libhw
Definition at line 49 of file hardware.h.
Enumeration Type Documentation
enum HW_DEVICES
Represents each of the hardware groups supported by libhw
Enumerator
HW_UART
HW_LCD
HW_TIMER
HW_ADC
HW_SSI
Definition at line 74 of file hardware.h.
               {
     HW_UART,
     HW_LCD,
     HW_TIMER,
     HW_ADC,
     HW_SSI,
 } HW_DEVICES;
Function Documentation
raw_hw_channel _hw_channel_to_index (raw_hw_channel , HW_DEVICES)
For internal use only. Convert a memory-mapped address (raw_hw_channel) into an index for hw_driver's internal data structures.
Parameters
hw_group The hardware group in question
channel The specified channel of
Returns
Internal index of channel's first open subscription bucket
Definition at line 149 of file hardware.c.
References ADC0_BASE, ADC1_BASE, HW_ADC, HW_LCD, HW_SSI, HW_TIMER, HW_UART, postpone_death(), SSI0_BASE, SSI1_BASE, SSI2_BASE, SSI3_BASE, TIMER0_BASE, TIMER1_BASE, TIMER2_BASE, TIMER3_BASE, TIMER4_BASE, UART0_BASE, UART1_BASE, UART2_BASE, UART3_BASE, UART4_BASE, UART5_BASE, UART6_BASE, and UART7_BASE.
Referenced by _hw_get_channel().
{
     /* TODO: is masking with an offset faster? Might take up less space */
     switch(hw_group){
     case HW_UART:
     switch(channel) {
     case UART0_BASE: return 0;
     case UART1_BASE: return 1;
     case UART2_BASE: return 2;
     case UART3_BASE: return 3;
     case UART4_BASE: return 4;
     case UART5_BASE: return 5;
     case UART6_BASE: return 6;
     case UART7_BASE: return 7;
     }
     break;
     case HW_LCD:   /* TODO: handle  */
     case HW_TIMER:
     switch(channel) {
     case TIMER0_BASE: return 0;
     case TIMER1_BASE: return 1;
     case TIMER2_BASE: return 2;
     case TIMER3_BASE: return 3;
     case TIMER4_BASE: return 4;
     }
     case HW_ADC:   /* TODO: handle channels having channels  */
     /* spitball'd idea - rename our 'channel' to 'base' (matching
      * hw_memmap.h) */
     switch(channel) {
     case ADC0_BASE: return 0;
     case ADC1_BASE: return 1;
     }
     case HW_SSI:
     switch(channel) {
     case SSI0_BASE: return 0;
     case SSI1_BASE: return 1;
     case SSI2_BASE: return 2;
     case SSI3_BASE: return 3;
     }
     default: postpone_death();
     }
     /* TODO: ensure software doesn't try to access nonexistent hardware
      * (mind the board model this is currently running on. current idea:
      * compile flags limiting the furthest indices) */
 }
hw_iterator _hw_first_available_subscription (hw_channel *)
For internal use only. This function returns the index of the first _isr_subscription in 's internal data structures.
Parameters
channel The channel to query for an open subscription slot
Returns
The index of the first available subscription bucket of
Definition at line 235 of file hardware.c.
References HW_DRIVER_MAX_SUBSCRIPTIONS, hw_channel::isr_subscriptions, postpone_death(), and _isr_subscription::valid.
Referenced by hw_connect(), and hw_connect_single_shot().
{
     hw_iterator i = 0;
     while(i<HW_DRIVER_MAX_SUBSCRIPTIONS &&
       channel->isr_subscriptions[i].valid) {
     ++i;
     }
     if(channel->isr_subscriptions[i].valid) {
     /* There are no empty slots for a new subscriber */
     /* TODO: determine how serious this is.  */
     /* plan a: threat level midnight (TLM) */
     postpone_death();
     /* plan b: business as usual */
     return false;
     }
     return i;
 }
hw_channel* _hw_get_channel (HW_DEVICES , raw_hw_channel)
For internal use only. Take care of the conversion between a memory-mapped (raw) hw address and the index of said peripheral channel in the memory banks of libhw's device-specific data structures.
Parameters
hw_group The hardware group in question
raw_hw_channel The specific channel of
Returns
Index of 'channel in 's data structures
Definition at line 228 of file hardware.c.
References _hw_channel_to_index(), hw_driver::channels, and hw_driver_singleton().
Referenced by hw_channel_init(), hw_connect(), hw_connect_single_shot(), hw_disconnect(), and hw_notify().
{
     long channel_index = _hw_channel_to_index(raw_channel, hw_group);
     return &(hw_driver_singleton(hw_group)->channels[channel_index]);
 }
void hw_channel_init (HW_DEVICES , raw_hw_channel , hw_metadata)
This function is responsible for enabling a specific channel on the specified hardware device. Internal libhw datastructures will also be reset.
Parameters
hw_group The hardware group in question
raw_channel The memory-mapped address of the device channel to initialize
metadata Information about how to initialize the device
Definition at line 71 of file hardware.c.
References _hw_get_channel(), HW_ADC, HW_DRIVER_MAX_SUBSCRIPTIONS, HW_LCD, HW_SSI, HW_TIMER, HW_UART, hw_channel::isr_subscriptions, postpone_death(), hw_metadata::timer, timer_add_periodic_interrupt(), hw_timer_metadata::TIMER_FREQUENCY, uart_init(), uart_set_active_channel(), and _isr_subscription::valid.
Referenced by main().
{
     hw_iterator i;
     hw_channel* channel = _hw_get_channel(hw_group, raw_channel);
     for(i=0; i<HW_DRIVER_MAX_SUBSCRIPTIONS; ++i) {
     channel->isr_subscriptions[i].valid = false;
     }
     switch(hw_group) {
     case HW_UART:
     uart_set_active_channel(raw_channel);
     uart_init();
     break;
     case HW_LCD:   /* TODO: handle  */
     case HW_TIMER:
         timer_add_periodic_interrupt(metadata.timer.TIMER_FREQUENCY,
                      raw_channel);
         break;
     case HW_ADC:   /* TODO: handle  */
     case HW_SSI:   /* TODO: handle  */
     default: postpone_death();
     }
 }
bool hw_connect (HW_DEVICES , raw_hw_channel , const void *)
Subscribe to a hardware interrupt. This is also called connecting a signal (the isr to be notified) to a slot (the hw-triggered driver isr).
Parameters
hw_group The hardware group in question
raw_channel 's channel (memory-mapped address)
isr The pseudo-isr to be notified by the hardware driver
Definition at line 98 of file hardware.c.
References _hw_first_available_subscription(), _hw_get_channel(), hw_channel::isr_subscriptions, _isr_subscription::single_shot_subscription, _isr_subscription::slot, and _isr_subscription::valid.
Referenced by shell_spawn().
{
     hw_iterator i = 0;
     hw_channel* channel = _hw_get_channel(hw_group, raw_channel);
     i = _hw_first_available_subscription(channel);
     channel->isr_subscriptions[i].valid = true;
     channel->isr_subscriptions[i].single_shot_subscription = false;
     channel->isr_subscriptions[i].slot = isr;
     return true;
 }
bool hw_connect_single_shot (HW_DEVICES , raw_hw_channel , const void *)
Subscribe to a one-time notification from a hardware interrupt. This is analagous to connecting to a hardware signal and disconnecting from said signal in the slot that is called. Note however that the hardware driver will do the disconnecting for you.
Parameters
hw_group The hardware group in question
raw_channel 's channel (memory-mapped address)
isr The pseudo-isr to be not notified anymore by the hardware driver
Note
When the hardware driver fires off a signal to a single-shot slot, the hardware driver will disconnect said slot from future notifications. In other words, the developer doesn't need to disconnect an isr manually if the one-shot slot is called.
To disconnect from a one-shot timer, simply use .
Definition at line 112 of file hardware.c.
References _hw_first_available_subscription(), _hw_get_channel(), hw_channel::isr_subscriptions, _isr_subscription::single_shot_subscription, _isr_subscription::slot, and _isr_subscription::valid.
{
     hw_iterator i;
     hw_channel* channel = _hw_get_channel(hw_group, raw_channel);
     i = _hw_first_available_subscription(channel);
     channel->isr_subscriptions[i].valid = true;
     channel->isr_subscriptions[i].single_shot_subscription = true;
     channel->isr_subscriptions[i].slot = isr;
     return true;
 }
bool hw_disconnect (HW_DEVICES , raw_hw_channel , const void *)
Unsubscribe from a hardware interrupt. This is also called disconnecting a signal (the isr in question) from a slot (the hw-triggered driver isr).
Parameters
hw_group The hardware group in question
raw_channel 's channel (memory-mapped address)
isr The pseudo-isr to be not notified anymore by the hardware driver
Definition at line 131 of file hardware.c.
References _hw_get_channel(), HW_DRIVER_MAX_SUBSCRIPTIONS, hw_channel::isr_subscriptions, NULL, _isr_subscription::single_shot_subscription, _isr_subscription::slot, and _isr_subscription::valid.
Referenced by shell_kill(), and timer_remove_periodic_thread().
{
     hw_iterator i;
     hw_channel* channel = _hw_get_channel(hw_group, raw_channel);
     while(i<HW_DRIVER_MAX_SUBSCRIPTIONS &&
       channel->isr_subscriptions[i].slot != isr) {
     ++i;
     }
     channel->isr_subscriptions[i].valid = false;
     channel->isr_subscriptions[i].single_shot_subscription = false;
     channel->isr_subscriptions[i].slot = NULL;
     return true;
 }
void hw_driver_init (HW_DEVICES)
This function is responsible for enabling the peripherals and internal data strutures used by the specified .
Parameters
hw_group The hardware group driver to initialize
Definition at line 48 of file hardware.c.
References HW_ADC, hw_driver_singleton(), HW_LCD, HW_SSI, HW_TIMER, HW_UART, postpone_death(), SYSCTL_PERIPH_GPIOA, SYSCTL_PERIPH_UART0, and SysCtlPeripheralEnable().
Referenced by main().
{
     hw_iterator i;
     hw_channel channel;
     hw_driver* driver = hw_driver_singleton(hw_group);
     /* Enable the peripherals this driver is responsible for */
     switch(hw_group){
     case HW_UART:
     /* TODO: allow flexibility with channel */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
     SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
     break;
     case HW_LCD:   /* TODO: handle  */
     case HW_TIMER: /* TODO: handle  */
     case HW_ADC:   /* TODO: handle  */
     case HW_SSI:   /* TODO: handle  */
     default: postpone_death();
     }
 }
hw_driver* hw_driver_singleton (HW_DEVICES hw_group)
Return the one hw_driver per hardware device group in use by the TM4C.
Parameters
hw_group The hardware group to grab a pointer of
Returns
Pointer to the hw_driver data structure managing
Definition at line 195 of file hardware.c.
References HW_ADC, HW_ADC_DRIVER, HW_LCD, HW_LCD_DRIVER, HW_TIMER, HW_TIMER_DRIVER, HW_UART, HW_UART_DRIVER, NULL, and postpone_death().
Referenced by _hw_get_channel(), and hw_driver_init().
{
     switch(hw_group) {
     case HW_UART:  return &HW_UART_DRIVER;
     case HW_LCD:   return &HW_LCD_DRIVER;
     case HW_TIMER: return &HW_TIMER_DRIVER;
     case HW_ADC:   return &HW_ADC_DRIVER;
     default:       postpone_death();
     }
     return NULL;
 }
void hw_notify (HW_DEVICES hw_group, raw_hw_channel channel, hw_notification notification)
Notify threads subscribed to about an incoming hardware event.
Parameters
hw_group The hardwawre group that received the incoming hardware event
channel The channel of that received the incoming hardware event
notifications The notification (prepared by NVIC-invoked ISR) containing information regarding the recently-occurring hardware interrupt event
Definition at line 208 of file hardware.c.
References _hw_get_channel(), HW_DRIVER_MAX_SUBSCRIPTIONS, hw_channel::isr_subscriptions, _isr_subscription::single_shot_subscription, _isr_subscription::slot, and _isr_subscription::valid.
Referenced by Timer0A_Handler(), Timer1A_Handler(), Timer2A_Handler(), and UART0_Handler().
{
     hw_iterator i=0;
     hw_channel* channel = _hw_get_channel(hw_group, raw_channel);
     for(i=0; i<HW_DRIVER_MAX_SUBSCRIPTIONS; ++i) {
     if (channel->isr_subscriptions[i].valid) {
         /* TODO: schedule a task to enable quick return from this ISR */
         channel->isr_subscriptions[i].slot(notification);
         if (channel->isr_subscriptions[i].single_shot_subscription) {
         /* Cease fire! cease fire! */
         channel->isr_subscriptions[i].single_shot_subscription = false;
         }
     }
     }
 }