EE445M RTOS: lib/libhw/hardware.c File Reference
hardware.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_types.h"
#include "driverlib/debug.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/rom.h"
#include "libut/utlist.h"
#include "libhw/hardware.h"
#include "libbuffer/buffer.h"
#include "driverlib/uart.h"
#include "driverlib/timer.h"
#include "libuart/uart.h"
#include "libtimer/timer.h"
#include "libbutton/button.h"
Functions
void hw_init_daemon ()
void hw_driver_init (HW_TYPE type, hw_metadata metadata)
void hw_channel_init (HW_TYPE type, hw_metadata metadata)
void _hw_subscribe (HW_TYPE type, hw_metadata metadata, void(*isr)(notification note), bool single_shot)
void hw_unsubscribe (HW_TYPE type, hw_metadata metadata, void(*isr)(notification note))
void hw_notify (HW_TYPE type, hw_metadata metadata, notification note)
void hw_daemon (void)
void hw_notify_uart (hw_metadata uart_metadata)
hw_channel * _hw_get_channel (HW_TYPE type, hw_metadata metadata)
hw_driver * hw_driver_singleton (HW_TYPE type)
void GPIOPortF_Handler (void)
void UART0_Handler (void)
void TIMER0A_Handler (void)
void TIMER1A_Handler (void)
void TIMER2A_Handler (void)
void ADC0Seq0_Handler (void)
void ADC0Seq1_Handler (void)
void ADC0Seq2_Handler (void)
void ADC0Seq3_Handler (void)
Variables
static hw_driver HW_UART_DRIVER
static hw_driver HW_TIMER_DRIVER
static hw_driver HW_BUTTON_DRIVER
static uint8_t UART0_RX_BUFFER [BUFFER_MAX_LENGTH]
static uint8_t UART0_RX_BUFFER_SIZE = 0
static uint8_t UART0_TX_BUFFER [BUFFER_MAX_LENGTH]
static uint8_t UART0_TX_BUFFER_SIZE = 0
uint32_t ADC0_SEQ0_SAMPLES [4]
uint32_t ADC0_SEQ1_SAMPLES [4]
uint32_t ADC0_SEQ2_SAMPLES [4]
uint32_t ADC0_SEQ3_SAMPLES [4]
semaphore_t HW_ADC_SEQ2_SEM
uint32_t jitter_begin
uint32_t jitter_end
Function Documentation
hw_channel* _hw_get_channel (HW_TYPE , hw_metadata) inline
For internal use only. Take care of the conversion between a memory-mapped (raw) hw address and the index of said peripheral channel in the memory banks of libhw's device-specific data structures.
Parameters
hw_group The hardware group in question
raw_hw_channel The specific channel of
Returns
Index of 'channel in 's data structures
Definition at line 203 of file hardware.c.
References hw_timer_metadata::base, hw_button_metadata::base, hw_metadata::button, hw_uart_metadata::channel, hw_driver::channels, GPIO_PORTE_BASE, HW_BUTTON, hw_driver_singleton(), HW_TIMER, HW_UART, postpone_death, hw_metadata::timer, TIMER0_BASE, hw_metadata::uart, and UART0_BASE.
Referenced by _hw_subscribe(), hw_channel_init(), hw_notify(), and hw_unsubscribe().
{
     memory_address_t idx;
     switch(type){
         /* optimize: divide should be a shift */
     case HW_UART:   idx = (metadata.uart.channel - UART0_BASE)     / 0x1000; break;
     case HW_TIMER:  idx = (metadata.timer.base   - TIMER0_BASE)    / 0x1000; break;
     case HW_BUTTON: idx = (metadata.button.base  - GPIO_PORTE_BASE)/ 0x1000; break;
         /* Note: libhw won't allow for the use of ports higher than
          * GPIO_PORTE without modification of the above indexing
          * algorithm */
     default: postpone_death();
     }
     return &(hw_driver_singleton(type)->channels[idx]);
 }
void _hw_subscribe (HW_TYPE , hw_metadata , void(*)(notification note) isr, bool)
Subscribe to a hardware interrupt. This is also called connecting a signal (the isr to be notified) to a slot (the hw-triggered driver isr).
Parameters
The hardware type in question
Metadata about the device
The pseudo-isr to be notified by the hardware driver
Definition at line 121 of file hardware.c.
References _hw_get_channel(), CDL_DELETE, CDL_PREPEND, hw_channel::free_slots, hw_channel::full_slots, _isr_subscription::single_shot_subscription, and _isr_subscription::slot.
Referenced by schedule_aperiodic().
{
     hw_iterator i;
     hw_channel* channel = _hw_get_channel(type, metadata);
     _isr_subscription* new_subscrip = channel->free_slots;
     CDL_DELETE(channel->free_slots, new_subscrip);
     CDL_PREPEND(channel->full_slots, new_subscrip);
     new_subscrip->single_shot_subscription = single_shot;
     new_subscrip->slot = isr;
 }
void ADC0Seq0_Handler (void)
Definition at line 378 of file hardware.c.
References ADC0_BASE, ADC0_SEQ3_SAMPLES, ADCIntClear(), and ADCSequenceDataGet().
Referenced by __attribute__().
{
     ADCIntClear(ADC0_BASE, 0);
     ADCSequenceDataGet(ADC0_BASE, 3, ADC0_SEQ3_SAMPLES);
     /* TODO: Conform to Notify */
 }
void ADC0Seq1_Handler (void)
Definition at line 385 of file hardware.c.
References ADC0_BASE, ADC0_SEQ3_SAMPLES, ADCIntClear(), and ADCSequenceDataGet().
Referenced by __attribute__().
{
     ADCIntClear(ADC0_BASE, 1);
     ADCSequenceDataGet(ADC0_BASE, 3, ADC0_SEQ3_SAMPLES);
     /* TODO: Conform to Notify */
 }
void ADC0Seq2_Handler (void)
Definition at line 392 of file hardware.c.
References ADC0_BASE, ADC0_SEQ2_SAMPLES, ADCIntClear(), ADCSequenceDataGet(), HW_ADC_SEQ2_SEM, HWREG, jitter_end, NVIC_ST_CURRENT, and sem_post.
Referenced by __attribute__().
{
     ADCIntClear(ADC0_BASE, 2);
     jitter_end = HWREG(NVIC_ST_CURRENT);
     ADCSequenceDataGet(ADC0_BASE, 2, ADC0_SEQ2_SAMPLES);
     /* GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1) ^ GPIO_PIN_1); */
     sem_post(HW_ADC_SEQ2_SEM);
     /* TODO: Conform to Notify */
 }
void ADC0Seq3_Handler (void)
Definition at line 402 of file hardware.c.
References ADC0_BASE, ADC0_SEQ3_SAMPLES, ADCIntClear(), and ADCSequenceDataGet().
Referenced by __attribute__().
{
     ADCIntClear(ADC0_BASE, 3);
     ADCSequenceDataGet(ADC0_BASE, 3, ADC0_SEQ3_SAMPLES);
     /* GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1) ^ GPIO_PIN_1); */
     /* TODO: Conform to Notify */
 }
void GPIOPortF_Handler (void)
GPIO PortF (includes on-board buttons) isr responsible for notifying all subscriptions with information describing the interrupt.
Definition at line 238 of file hardware.c.
References button_metadata_init, BUTTONS_BOTH, GPIO_PORTF_BASE, GPIOIntClear(), GPIOPinRead(), HW_BUTTON, hw_notify(), notification_init, and NULL.
Referenced by __attribute__().
{
     GPIOIntClear(GPIO_PORTF_BASE, BUTTONS_BOTH);
     notification_init(int, GPIOPinRead(GPIO_PORTF_BASE, BUTTONS_BOTH));
     button_metadata_init(GPIO_PORTF_BASE, BUTTONS_BOTH, NULL);
     hw_notify(HW_BUTTON, button_metadata, note);
 }
void hw_channel_init (HW_TYPE , hw_metadata)
This function is responsible for enabling a specific channel on the specified hardware device. Internal libhw datastructures will also be reset.
Parameters
hw_group The hardware group in question
raw_channel The memory-mapped address of the device channel to initialize
metadata Information about how to initialize the device
Definition at line 94 of file hardware.c.
References _hw_get_channel(), button_set_interrupt(), CDL_PREPEND, hw_channel::free_slots, hw_channel::full_slots, HW_BUTTON, HW_DRIVER_MAX_SUBSCRIPTIONS, HW_TIMER, HW_UART, hw_channel::isr_subscriptions, NULL, postpone_death, timer_add_interrupt(), and uart_init().
Referenced by adc_interrupt_init(), button_debounce_start(), and main().
{
     hw_iterator i;
     hw_channel* channel = _hw_get_channel(type, metadata);
     channel->full_slots = NULL;
     for(i=0; i<HW_DRIVER_MAX_SUBSCRIPTIONS; ++i) {
         CDL_PREPEND(channel->free_slots, &channel->isr_subscriptions[i]);
     }
     switch(type) {
     case HW_UART:
         uart_init(metadata);
         break;
     case HW_TIMER:
         timer_add_interrupt(metadata);
         break;
     case HW_BUTTON:
         /* TODO: parametrize */
         button_set_interrupt(metadata);
         break;
     default: postpone_death();
     }
 }
void hw_daemon (void)
Definition at line 172 of file hardware.c.
References hw_notify_uart(), HW_SEM_UART0, INT_UART0, os_surrender_context, sem_guard, sem_take, UART0_BASE, UART_DEFAULT_BAUD_RATE, and uart_metadata_init.
Referenced by hw_init_daemon(), and main().
                      {
     while (1) {
         /* mind ordering of sem_checks */
         /* fixme: one thread for each hardware device, so individual
          * priorities can be assigned to the threads (which will
          * handle simultaneous interrupts according to priority
          * scheduler's interpretation of priority) */
         sem_guard(HW_SEM_UART0) {
             sem_take(HW_SEM_UART0);
             /* todo: schedule */
             uart_metadata_init(UART_DEFAULT_BAUD_RATE, UART0_BASE, INT_UART0);
             hw_notify_uart(uart_metadata);
         }
         os_surrender_context();
     }
 }
void hw_driver_init (HW_TYPE , hw_metadata)
This function is responsible for enabling the peripherals and internal data strutures used by the specified .
Parameters
hw_group The hardware group driver to initialize
Definition at line 62 of file hardware.c.
References hw_timer_metadata::base, button_init(), hw_uart_metadata::channel, HW_BUTTON, HW_TIMER, HW_UART, postpone_death, SYSCTL_PERIPH_GPIOA, SYSCTL_PERIPH_GPIOF, SYSCTL_PERIPH_TIMER0, SYSCTL_PERIPH_UART0, SysCtlPeripheralEnable(), hw_metadata::timer, TIMER0_BASE, hw_metadata::uart, and UART0_BASE.
Referenced by main().
{
     switch(type) {
     case HW_UART:
         SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0 +
                                (metadata.uart.channel - UART0_BASE) / 0x1000);
         /* todo: parametrize - are they all on A? */
         SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
         break;
     case HW_TIMER:
         SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0 +
                                (metadata.timer.base - TIMER0_BASE) / 0x1000);
         break;
     case HW_BUTTON:
         /* TODO: parametrize to allow other buttons to be driven */
         SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
         /* #need4speed: Buttons on the board are only used for input,
          * we know how they're going to be used. Break the libhw
          * convention and initialize these buttons so this code never
          * has to be run again */
         button_init(metadata);
         break;
     default: postpone_death();
     }
 }
hw_driver* hw_driver_singleton (HW_TYPE) inline
Return the one hw_driver per hardware device group in use by the TM4C.
Parameters
The hardware type to grab a pointer of
Returns
Pointer to the hw_driver data structure managing
Definition at line 220 of file hardware.c.
References HW_BUTTON, HW_BUTTON_DRIVER, HW_TIMER, HW_TIMER_DRIVER, HW_UART, HW_UART_DRIVER, NULL, and postpone_death.
Referenced by _hw_get_channel().
{
     switch(type) {
     case HW_UART:   return &HW_UART_DRIVER;
     case HW_TIMER:  return &HW_TIMER_DRIVER;
     case HW_BUTTON: return &HW_BUTTON_DRIVER;
     default:        postpone_death();
     }
     return NULL;
 }
void hw_init_daemon ()
Initialize libhw's internal data structures
Definition at line 54 of file hardware.c.
References hw_daemon(), and os_add_thread().
                       {
     os_add_thread(hw_daemon);
 }
void hw_notify (HW_TYPE , hw_metadata , notification)
Notify threads subscribed to about an incoming hardware event.
Parameters
hw_group The hardwawre group that received the incoming hardware event
channel The channel of that received the incoming hardware event
notifications The notification (prepared by NVIC-invoked ISR) containing information regarding the recently-occurring hardware interrupt event
Definition at line 149 of file hardware.c.
References _hw_get_channel(), CDL_DELETE, CDL_PREPEND, hw_channel::free_slots, hw_channel::full_slots, _isr_subscription::next, NULL, _isr_subscription::single_shot_subscription, and _isr_subscription::slot.
Referenced by GPIOPortF_Handler(), hw_notify_uart(), s_Handler(), sA_Handler(), TIMER0A_Handler(), TIMER1A_Handler(), and TIMER2A_Handler().
{
     hw_iterator i=0;
     hw_channel* channel = _hw_get_channel(type, metadata);
     _isr_subscription* subscrip = channel->full_slots;
     _isr_subscription* new_subscrip = NULL;
     /* TODO: make this a doubly linked list, not circular */
     /* consider similar changes to os lib also */
     while(subscrip && subscrip != new_subscrip) {
         subscrip->slot(note);
         new_subscrip = subscrip->next;
         if (subscrip->single_shot_subscription) {
             /* Cease fire! cease fire! */
             subscrip->single_shot_subscription = false;
             CDL_DELETE(channel->full_slots, subscrip);
             CDL_PREPEND(channel->free_slots, subscrip);
         }
         subscrip = new_subscrip;
     }
 }
void hw_notify_uart (hw_metadata uart_metadata)
Iterate over all chars in the respective uart's RX_FIFO and notify all subscribed tasks.
Parameters
UART metadata
Definition at line 189 of file hardware.c.
References notification::_char, buffer_dec, buffer_empty, buffer_last, hw_notify(), HW_UART, and UART0_RX_BUFFER.
Referenced by hw_daemon().
{
     notification note;
     /* get-it-working: assume the dev knows which buffer to use */
     uint8_t* buffer = UART0_RX_BUFFER;
     while(!buffer_empty(UART0_RX_BUFFER)) {
         note._char = buffer_last(UART0_RX_BUFFER);
         buffer_dec(UART0_RX_BUFFER);
         hw_notify(HW_UART, uart_metadata, note);
     }
 }
void hw_unsubscribe (HW_TYPE , hw_metadata , void(*)(notification note) isr)
Unsubscribe from a hardware interrupt. This is also called disconnecting a signal (the isr in question) from a slot (the hw-triggered driver isr).
Parameters
The hardware type in question
Metadata about the device
The pseudo-isr to be notified by the hardware driver
Definition at line 137 of file hardware.c.
References _hw_get_channel(), CDL_DELETE, CDL_PREPEND, hw_channel::free_slots, and hw_channel::full_slots.
Referenced by shell_kill().
{
     hw_channel* channel = _hw_get_channel(type, metadata);
     _isr_subscription* remove = channel->full_slots;
     while(remove->slot != isr) {++remove;}
     CDL_DELETE(channel->full_slots, remove);
     CDL_PREPEND(channel->free_slots, remove);
 }
void TIMER0A_Handler (void)
TIMER0A isr responsible for notifying all subscriptions with information describing the interrupt.
This isr was generated automatically by bin/lisp/rtos-interrupt-generator.el
Definition at line 341 of file hardware.c.
References hw_notify(), HW_TIMER, notification_init, NULL, TIMER0_BASE, timer_metadata_init, TIMER_TIMA_TIMEOUT, and TimerIntClear().
{
   TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
   notification_init(int, 1);
   timer_metadata_init(TIMER0_BASE, NULL, NULL, NULL);
   hw_notify(HW_TIMER, timer_metadata, note);
 }
void TIMER1A_Handler (void)
TIMER1A isr responsible for notifying all subscriptions with information describing the interrupt.
This isr was generated automatically by bin/lisp/rtos-interrupt-generator.el
Definition at line 355 of file hardware.c.
References hw_notify(), HW_TIMER, HWREG, jitter_begin, notification_init, NULL, NVIC_ST_CURRENT, TIMER1_BASE, timer_metadata_init, TIMER_TIMA_TIMEOUT, and TimerIntClear().
Referenced by __attribute__().
{
   TimerIntClear(TIMER1_BASE, TIMER_TIMA_TIMEOUT);
   jitter_begin = HWREG(NVIC_ST_CURRENT);
   notification_init(int, 1);
   timer_metadata_init(TIMER1_BASE, NULL, NULL, NULL);
   hw_notify(HW_TIMER, timer_metadata, note);
 }
void TIMER2A_Handler (void)
TIMER2A isr responsible for notifying all subscriptions with information describing the interrupt.
This isr was generated automatically by bin/lisp/rtos-interrupt-generator.el
Definition at line 370 of file hardware.c.
References hw_notify(), HW_TIMER, notification_init, NULL, TIMER2_BASE, timer_metadata_init, TIMER_TIMA_TIMEOUT, and TimerIntClear().
Referenced by __attribute__().
{
   TimerIntClear(TIMER2_BASE, TIMER_TIMA_TIMEOUT);
   notification_init(int, 1);
   timer_metadata_init(TIMER2_BASE, NULL, NULL, NULL);
   hw_notify(HW_TIMER, timer_metadata, note);
 }
void UART0_Handler (void)
UART0 isr responsible for notifying all subscriptions with information describing the interrupt.
Definition at line 254 of file hardware.c.
References buffer_add, buffer_dec, buffer_empty, buffer_full, HW_SEM_UART0, sem_post, UART0_BASE, UART0_RX_BUFFER, UART_INT_RT, UART_INT_RX, UART_INT_TX, UART_LAST_WAS_CR, UARTCharGetNonBlocking(), UARTCharPut(), UARTCharsAvail(), UARTIntClear(), and UARTIntStatus().
Referenced by __attribute__().
{
     bool post;
     uint8_t recv;
     /* Get and clear the current interrupt sources */
     uint32_t interrupts = UARTIntStatus(UART0_BASE, true);
     UARTIntClear(UART0_BASE, interrupts);
     /* Are we being interrupted because the TX FIFO has space available? */
     if(interrupts & UART_INT_TX) {
         /* Move as many bytes as we can into the transmit FIFO */
         /* TODO:  */
         /* uart_prime_transmit(UART0_BASE); */
     }
     /* Are we being interrupted due to a received character? */
     if(interrupts & (UART_INT_RX | UART_INT_RT)) {
         /* Get all available chars from the UART */
         while(UARTCharsAvail(UART0_BASE)) {
             recv = (unsigned char) (UARTCharGetNonBlocking(UART0_BASE) & 0xFF);
             /* optional: check for '@echo_off */
             /* Handle backspace by erasing the last character in the
              * buffer */
             switch(recv) {
             case 127:
             case '\b':
                 /* If there are any chars to delete, delete the last text */
                 if(!buffer_empty(UART0_RX_BUFFER)) {
                     /* Erase previous characters on the user's terminal */
                     /* UARTCharPut(UART0_BASE, '\b'); */
                     /* UARTCharPut(UART0_BASE, ' '); */
                     /* UARTCharPut(UART0_BASE, '\b'); */
                     /* Decrement the number of chars in the buffer */
                     buffer_dec(UART0_RX_BUFFER);
                     /* Skip ahead to next buffered char */
                     continue;
                 }
                 /* if it is empty, somebody is watching so pass along
                  * the backspace */
                 break;
             case '\r':
             case '\n':
                 if(recv == '\r') {
                     UART_LAST_WAS_CR = true;
                 }
                 else if (UART_LAST_WAS_CR) {
                     UART_LAST_WAS_CR = false;
                     /* Don't react twice to a single newline */
                     continue;
                 }
             case 0x1b:
                 /* Regardless of the newline received, our convention
                  * is to mark end-of-lines in a buffer with the CR
                  * character. */
                 recv = '\r';
                 /* Echo the received character to the newline */
                 UARTCharPut(UART0_BASE, '\n');
                 break;
             default: break;
             }
             post = !buffer_full(UART0_RX_BUFFER);
             /* If there is room in the RX FIFO, store the char there,
              * else dump it. optional: a circular buffer might keep
              * more up-to-date data, considering this is a RTOS */
             /* this could be cleaned up with error-catching in the buffer library */
             if(post) {
                 buffer_add(UART0_RX_BUFFER, recv);
                 sem_post(HW_SEM_UART0);
             }
         }
     }
 }
Variable Documentation
uint32_t ADC0_SEQ0_SAMPLES[4]
Definition at line 44 of file hardware.c.
uint32_t ADC0_SEQ1_SAMPLES[4]
Definition at line 45 of file hardware.c.
uint32_t ADC0_SEQ2_SAMPLES[4]
Definition at line 46 of file hardware.c.
Referenced by ADC0Seq2_Handler(), display_adc_data_for_checkout(), and main().
uint32_t ADC0_SEQ3_SAMPLES[4]
Definition at line 47 of file hardware.c.
Referenced by ADC0Seq0_Handler(), ADC0Seq1_Handler(), and ADC0Seq3_Handler().
semaphore_t HW_ADC_SEQ2_SEM
Definition at line 49 of file hardware.c.
Referenced by ADC0Seq2_Handler(), display_adc_data_for_checkout(), and led_blink_green().
hw_driver HW_BUTTON_DRIVER static
Definition at line 36 of file hardware.c.
Referenced by hw_driver_singleton().
hw_driver HW_TIMER_DRIVER static
Definition at line 35 of file hardware.c.
Referenced by hw_driver_singleton().
hw_driver HW_UART_DRIVER static
Definition at line 34 of file hardware.c.
Referenced by hw_driver_singleton().
uint32_t jitter_begin
Definition at line 51 of file hardware.c.
Referenced by TIMER1A_Handler().
uint32_t jitter_end
Definition at line 52 of file hardware.c.
Referenced by ADC0Seq2_Handler().
uint8_t UART0_RX_BUFFER[BUFFER_MAX_LENGTH] static
Definition at line 38 of file hardware.c.
Referenced by hw_notify_uart(), and UART0_Handler().
uint8_t UART0_RX_BUFFER_SIZE = 0 static
Definition at line 39 of file hardware.c.
uint8_t UART0_TX_BUFFER[BUFFER_MAX_LENGTH] static
Definition at line 41 of file hardware.c.
uint8_t UART0_TX_BUFFER_SIZE = 0 static
Definition at line 42 of file hardware.c.