EE445M RTOS: lib/libheart/heartbeat.h File Reference
heartbeat.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/timer.h"
#include "driverlib/rom.h"
Macros
#define HEART_RED GPIO_PIN_1
#define HEART_BLUE GPIO_PIN_2
#define HEART_GREEN GPIO_PIN_3
#define THORACIC_CAVITY GPIO_PORTF_BASE
#define heart_wrap(x)
Functions
void heart_init ()
Initialize for visible transformation.
int32_t heart_status ()
Return the status of .
void heart_off ()
Turn off.
void heart_on ()
Turn on.
void heart_toggle ()
Toggle once.
void heart_beat ()
Toggle twice.
Macro Definition Documentation
#define HEART_BLUE GPIO_PIN_2
Definition at line 31 of file heartbeat.h.
Referenced by heart_beat(), heart_init(), heart_off(), heart_on(), heart_status(), and heart_toggle().
#define HEART_GREEN GPIO_PIN_3
Definition at line 32 of file heartbeat.h.
#define HEART_RED GPIO_PIN_1
The on-board LED colloquially referred to as the 'heart.' Does every computer have one?
Definition at line 30 of file heartbeat.h.
#define heart_wrap (x)
Value:
heart_beat();     \
    x                 \
    heart_toggle();   \
Surround the execution of a code block with two hooks.
pre_hook: heart_beat();
post_hook: heart_toggle();
Definition at line 132 of file heartbeat.h.
#define THORACIC_CAVITY GPIO_PORTF_BASE
The GPIO base where the may be found. Otherwise knows as a subdivision of the ventral body cavity which houses the heart.
Definition at line 37 of file heartbeat.h.
Referenced by heart_beat(), heart_init(), heart_off(), heart_on(), heart_status(), and heart_toggle().
Function Documentation
void heart_beat () inline
Toggle twice.
end_state = starting_state
Returns
void
Definition at line 120 of file heartbeat.h.
References GPIOPinWrite(), HEART_BLUE, heart_status(), and THORACIC_CAVITY.
                   {
 #if !(defined(PROFILING_DISABLE))
     GPIOPinWrite(THORACIC_CAVITY, HEART_BLUE, heart_status() ^ HEART_BLUE);
     GPIOPinWrite(THORACIC_CAVITY, HEART_BLUE, heart_status() ^ HEART_BLUE);
 #endif
 }
void heart_init () inline
Initialize for visible transformation.
Returns
void
Definition at line 49 of file heartbeat.h.
References GPIOPinTypeGPIOOutput(), HEART_BLUE, SYSCTL_PERIPH_GPIOF, SysCtlPeripheralEnable(), and THORACIC_CAVITY.
Referenced by main().
                   {
 #if !(defined(PROFILING_DISABLE))
     /* Enable the GPIO port that is used for the on-board LED. */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
     /* Enable the GPIO pins for the LED (PF2). */
     GPIOPinTypeGPIOOutput(THORACIC_CAVITY, HEART_BLUE);
 #endif
 }
void heart_off () inline
Turn off.
Returns
void
Definition at line 79 of file heartbeat.h.
References GPIOPinWrite(), HEART_BLUE, and THORACIC_CAVITY.
                  {
 #if !(defined(PROFILING_DISABLE))
     GPIOPinWrite(THORACIC_CAVITY, HEART_BLUE, 0);
 #endif
 }
void heart_on () inline
Turn on.
Returns
void
Definition at line 92 of file heartbeat.h.
References GPIOPinWrite(), HEART_BLUE, and THORACIC_CAVITY.
                 {
 #if !(defined(PROFILING_DISABLE))
     GPIOPinWrite(THORACIC_CAVITY, HEART_BLUE, 1);
 #endif
 }
int32_t heart_status () inline
Return the status of .
Returns
The current status of .
Definition at line 66 of file heartbeat.h.
References GPIOPinRead(), HEART_BLUE, and THORACIC_CAVITY.
Referenced by heart_beat(), and heart_toggle().
{
 #if !(defined(PROFILING_DISABLE))
     GPIOPinRead(THORACIC_CAVITY, HEART_BLUE);
 #endif
 }
void heart_toggle () inline
Toggle once.
end_state = ~starting_state
Returns
void
Definition at line 106 of file heartbeat.h.
References GPIOPinWrite(), HEART_BLUE, heart_status(), and THORACIC_CAVITY.
Referenced by Task1().
                     {
 #if !(defined(PROFILING_DISABLE))
     GPIOPinWrite(THORACIC_CAVITY, HEART_BLUE, heart_status() ^ HEART_BLUE);
 #endif
 }