EE445M RTOS: lib/libsystick/systick.h File Reference
systick.h File Reference
#include "libstd/nexus.h"
Functions
static always void systick_init (frequency_t frequency)
Function Documentation
static always void systick_init (frequency_t frequency) inline static
Provide a human-readable way to initialize the SysTick.
Definition at line 15 of file systick.h.
References SysCtlClockGet(), SysTickEnable(), SysTickIntEnable(), and SysTickPeriodSet().
{
     SysTickPeriodSet(SysCtlClockGet() / frequency);
     SysTickEnable();
     SysTickIntEnable();
 }