EE445M RTOS: lib/libuart/uart.c File Reference
uart.c File Reference
#include "uart.h"
#include "inc/hw_memmap.h"
#include "inc/hw_ints.h"
#include <stdint.h>
#include "driverlib/pin_map.h"
#include "driverlib/gpio.h"
#include "driverlib/uart.h"
Macros
#define NDEBUG
Functions
uint32_t ustrlen (const char *s)
void uart_set_active_channel (const long channel)
void uart_clear_active_channel ()
bool uart_has_active_channel ()
void uart_init ()
void uart_init_ (const long channel)
void uart_send_char (const char text)
void uart_send_char_ (const long channel, const char text)
void uart_send_string (const char *text)
void uart_send_string_ (const long channel, const char *text)
char uart_get_char ()
Read a char from the active uart channel.
char uart_get_char_ (const long channel)
Read a char from the specified uart channel.
char * uart_get_string (const long string_length)
Read a char array from the active uart channel.
char * uart_get_string_ (const long channel, const long string_length)
Read a char array from the active uart channel.
Variables
static char UART_BUFFER [128]
long uart_active_channel = -1
Macro Definition Documentation
#define NDEBUG
Definition at line 13 of file uart.c.
Function Documentation
void uart_clear_active_channel ()
Modally clear the active uart channel.
Returns
void
Definition at line 38 of file uart.c.
References uart_active_channel, and UART_UNUSED.
{
     uart_active_channel = UART_UNUSED;
 }
char uart_get_char ()
Read a char from the active uart channel.
Read a char from the active uart channel.
Read a char from the active uart channel.
Returns
char read from uart
Definition at line 99 of file uart.c.
References uart_active_channel, and uart_get_char_().
Referenced by UART0_Handler().
                      {
     return uart_get_char_(uart_active_channel);
 }
char uart_get_char_ (const long channel)
Read a char from the specified uart channel.
Read a char from the specified uart channel.
Read a char from the specified uart channel.
Parameters
channel The uart channel to read.
Returns
char read from uart
Definition at line 105 of file uart.c.
References UART0_BASE, UARTCharGetNonBlocking(), UARTIntClear(), and UARTIntStatus().
Referenced by uart_get_char().
{
     uint32_t ui32Status;
     /* Get the interrrupt status. */
     ui32Status = UARTIntStatus(UART0_BASE, true);
     /* Clear the asserted interrupts. */
     UARTIntClear(UART0_BASE, ui32Status);
     char ret = UARTCharGetNonBlocking(UART0_BASE);
 #ifndef NDEBUG
     printf("%s got char: %c", ret);
 #endif
     return ret;
 }
char* uart_get_string (const long string_length)
Read a char array from the active uart channel.
Read a char array from the active uart channel.
Read a char array from the active uart channel.
Parameters
string_length The maximum number of characters to read.
Returns
char array read from uart
Definition at line 124 of file uart.c.
References uart_active_channel, and uart_get_string_().
{
     return uart_get_string_(uart_active_channel, string_length);
 }
char* uart_get_string_ (const long channel, const long string_length)
Read a char array from the active uart channel.
Read a char array from the specified uart channel.
Read a char array from the active uart channel.
Parameters
channel The uart channel to read.
string_length The maximum number of characters to read.
Returns
char array read from uart
Definition at line 130 of file uart.c.
References UART0_BASE, UART_BUFFER, UARTCharGetNonBlocking(), UARTCharsAvail(), UARTIntClear(), and UARTIntStatus().
Referenced by uart_get_string().
{
     /* char* buffer; */
     uint32_t ui32Status;
     long remaining_chars = string_length;
     /* \buffer is a null-terminated string */
     /* buffer = malloc(string_length*sizeof(char) + 1); */
     UART_BUFFER[string_length] = 0;
     /* Get the interrrupt status. */
     ui32Status = UARTIntStatus(UART0_BASE, true);
     /* Clear the asserted interrupts. */
     UARTIntClear(UART0_BASE, ui32Status);
     while(UARTCharsAvail(UART0_BASE) && remaining_chars > 0) {
         UART_BUFFER[remaining_chars - string_length] = UARTCharGetNonBlocking(channel);
         remaining_chars--;
     }
 #ifndef NDEBUG
     printf("%s Got string: %s\n", __FUNCTION__, UART_BUFFER);
 #endif
     return UART_BUFFER;
 }
bool uart_has_active_channel ()
Test whether or not an active uart channel exists.
Returns
boolean indicating uart active channel is modally set.
Definition at line 43 of file uart.c.
References uart_active_channel, and UART_UNUSED.
{
     return uart_active_channel == UART_UNUSED;
 }
void uart_init ()
Initialize the active uart channel.
Returns
void
Definition at line 48 of file uart.c.
References uart_active_channel, and uart_init_().
Referenced by hw_channel_init(), and main().
                  {
     uart_init_(uart_active_channel);
 }
void uart_init_ (const long channel)
Initialize the specified uart channel.
Parameters
channel The uart channel to initialize.
Returns
void
Definition at line 54 of file uart.c.
References GPIO_PIN_0, GPIO_PIN_1, GPIO_PORTA_BASE, GPIOPinConfigure(), GPIOPinTypeUART(), INT_UART0, IntEnable(), SysCtlClockGet(), UART0_BASE, UART_CONFIG_PAR_NONE, UART_CONFIG_STOP_ONE, UART_CONFIG_WLEN_8, UART_INT_RT, UART_INT_RX, UARTConfigSetExpClk(), and UARTIntEnable().
Referenced by uart_init().
{
     GPIOPinConfigure(GPIO_PA0_U0RX);
     GPIOPinConfigure(GPIO_PA1_U0TX);
     GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);
     UARTConfigSetExpClk(UART0_BASE, SysCtlClockGet(), 115200,
                         (UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE |
                          UART_CONFIG_PAR_NONE));
     /* Enable the UART interrupt. */
     IntEnable(INT_UART0);
     UARTIntEnable(UART0_BASE, UART_INT_RX | UART_INT_RT);
 #ifndef NDEBUG
     /* TODO: uncomment when uart0_base has been updated with channel */
     printf("%s channel %d initialized\n", __FUNCTION__, channel);
 #endif
 }
void uart_send_char (const char text)
Send a char array over the active uart channel.
Parameters
text The null-terminated array of chars to send via uart.
Returns
void
Definition at line 73 of file uart.c.
References uart_active_channel, and uart_send_char_().
Referenced by shell_uart0_handler(), and UART0_Handler().
{
     uart_send_char_(uart_active_channel, text);
 }
void uart_send_char_ (const long channel, const char text)
Send a char array over the specified uart channel.
Parameters
channel The uart channel to send over.
text The null-terminated array of chars to send via uart.
Returns
void
Definition at line 79 of file uart.c.
References UART0_BASE, and UARTCharPut().
Referenced by uart_send_char().
{
     UARTCharPut(UART0_BASE, text);
 }
void uart_send_string (const char * text)
Send a char array over the active uart channel.
Parameters
text The null-terminated array of chars to send via uart.
Returns
void
Definition at line 84 of file uart.c.
References uart_active_channel, and uart_send_string_().
Referenced by doctor(), main(), shell_print_ps1(), and shell_uart0_handler().
{
     uart_send_string_(uart_active_channel, text);
 }
void uart_send_string_ (const long channel, const char * text)
Send a char array over the specified uart channel.
Parameters
channel The uart channel to send over.
text The null-terminated array of chars to send via uart.
Returns
void
Definition at line 89 of file uart.c.
References UARTCharPut(), and ustrlen().
Referenced by uart_send_string().
{
     uint32_t cnt = ustrlen(text);
     char* ptr = (char*)text;
     while(cnt--) {
         UARTCharPut(channel, *(ptr++));
     }
 }
void uart_set_active_channel (const long channel)
Modally set the active uart channel.
Returns
void
Definition at line 33 of file uart.c.
References uart_active_channel.
Referenced by hw_channel_init(), and main().
{
     uart_active_channel = channel;
 }
uint32_t ustrlen (const char * s)
Definition at line 27 of file uart.c.
Referenced by shell_set_ps1(), and uart_send_string_().
{
     uint32_t len = 0;
     while(s[len]) { ++len; }
     return(len);
 }
Variable Documentation
long uart_active_channel = -1
Definition at line 25 of file uart.c.
Referenced by uart_clear_active_channel(), uart_get_char(), uart_get_string(), uart_has_active_channel(), uart_init(), uart_send_char(), uart_send_string(), and uart_set_active_channel().
char UART_BUFFER[128] static
Definition at line 19 of file uart.c.
Referenced by uart_get_string_().