EE445M RTOS: lib/libadc/adc.h File Reference
adc.h File Reference
#include "libtimer/timer.h"
#include <stdbool.h>
#include <stdint.h>
Functions
void adc_init (void)
bool encode_adc_channel (uint32_t channel, uint32_t *encoded_channel)
uint32_t adc_collect (uint32_t channel, uint32_t frequency, unsigned long buffer[], uint32_t timer_peripheral)
void do_adc_func ()
uint32_t adc_open (uint32_t channel)
Function Documentation
uint32_t adc_collect (uint32_t channel, uint32_t frequency, unsigned long buffer[], uint32_t timer_peripheral)
Collect ADC data into the specified buffer at a specified interval
Parameters
channel the channel from which to sample
frequency the frequency in Hz of the sampling process
buffer a pointer to the buffer to populate
timer_peripheral the timer to use for this process
Definition at line 114 of file adc.c.
References adc_sample_buffer, and encode_adc_channel().
Referenced by main().
{
     uint32_t encoded_channel;
     if (encode_adc_channel(channel, &encoded_channel)) {
         adc_sample_buffer[channel] = (int32_t)buffer;
         /* low priority */
         /* timer_add_periodic_thread(do_adc_func, frequency, timer_peripheral); */
         return 1;
     }
     return 0;
 }
void adc_init (void)
Initialize the ADC device on the board
Returns
void
Definition at line 25 of file adc.c.
References ADC0_BASE, adc_active_scoreboard, ADC_CTL_CH2, ADC_CTL_END, ADC_CTL_IE, ADC_REF_EXT_3V, ADCReferenceSet(), ADCSequenceEnable(), ADCSequenceStepConfigure(), GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTE_AHB_BASE, GPIOPinTypeADC(), NUM_ADC_CHANNELS, SYSCTL_PERIPH_ADC0, SYSCTL_PERIPH_GPIOE, SysCtlGPIOAHBEnable(), SysCtlPeripheralEnable(), and SysCtlPeripheralReset().
Referenced by main().
                     {
     /* int32_t ui32Chan; */
     uint8_t i;
     /* Enable the GPIOs and the ADC used by this example. */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
     SysCtlGPIOAHBEnable(SYSCTL_PERIPH_GPIOE);
     SysCtlPeripheralEnable(SYSCTL_PERIPH_ADC0);
     SysCtlPeripheralReset(SYSCTL_PERIPH_ADC0);
     /* Select the external reference for greatest accuracy. */
     ADCReferenceSet(ADC0_BASE, ADC_REF_EXT_3V);
     /* Configure the pins which are used as analog inputs. */
     GPIOPinTypeADC(GPIO_PORTE_AHB_BASE, GPIO_PIN_3 | GPIO_PIN_2 | GPIO_PIN_1);
     /* Configure the sequencer for 3 steps. */
     for(i = 0; i < 2; ++i) {
         /* Configure the sequence step */
         ADCSequenceStepConfigure(ADC0_BASE, 0, i, i);
     }
     ADCSequenceStepConfigure(ADC0_BASE, 0, 2, ADC_CTL_CH2 | ADC_CTL_IE |
                              ADC_CTL_END);
     /* Enable the sequence but do not start it yet. */
     ADCSequenceEnable(ADC0_BASE, 0);
     for (i=0; i<NUM_ADC_CHANNELS; ++i) {
         adc_active_scoreboard[i] = false;
     }
 }
uint32_t adc_open (uint32_t channel)
KLUDGE: Opens the specified channel on ADC0
Parameters
channel the channel on ADC0 to open
Returns
void
Definition at line 58 of file adc.c.
References ADC0_BASE, ADC_CTL_END, ADC_CTL_IE, ADC_TRIGGER_PROCESSOR, ADCIntClear(), ADCSequenceConfigure(), ADCSequenceEnable(), ADCSequenceStepConfigure(), and encode_adc_channel().
Referenced by main().
{
     uint32_t encoded_channel;
     if (encode_adc_channel(channel, &encoded_channel)) {
         ADCSequenceConfigure(ADC0_BASE, 3, ADC_TRIGGER_PROCESSOR, 0);
         ADCSequenceStepConfigure(ADC0_BASE, 3, 0, encoded_channel | ADC_CTL_IE | ADC_CTL_END);
         ADCSequenceEnable(ADC0_BASE, 3);
         ADCIntClear(ADC0_BASE, 3);
         return 1;
     }
     return 0;
 }
void do_adc_func ()
The function the periodic timer calls to actually populate the ADC data. It operates on the array given in the adc_collect method
Returns
void
Definition at line 129 of file adc.c.
References ADC0_BASE, adc_sample_buffer, ADCIntClear(), ADCIntStatus(), ADCProcessorTrigger(), ADCSequenceDataGet(), GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinRead(), and GPIOPinWrite().
                    {
     uint32_t status = ADCIntStatus(ADC0_BASE, 0, false);
     if (status != 0) {
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2) ^ GPIO_PIN_2);
         /* Clear the ADC interrupt. */
         ADCIntClear(ADC0_BASE, 0);
         /* Read the data and trigger a new sample request. */
         /* ADCSequenceDataGet(ADC0_BASE, 0, &adc_channel_buffer[0]); */
         ADCSequenceDataGet(ADC0_BASE, 0, &adc_sample_buffer[0]);
         ADCProcessorTrigger(ADC0_BASE, 0);
         /* TODO: Update our report of the data somehow (whatever
            means we define are necessary). For now the data
            resides in adc_data_buffer ready for copying and
            interpretation. */
     }
 }
bool encode_adc_channel (uint32_t channel, uint32_t * encoded_channel)
Encode the ADC channel bit mask from the integer ADC channel number
Parameters
channel the integer channel to encode into the bit mask
encoded_channel the encoded channel's bit mask
Returns
whether the decoding was successful or not
Definition at line 70 of file adc.c.
References ADC_CTL_CH0, ADC_CTL_CH1, ADC_CTL_CH10, ADC_CTL_CH11, ADC_CTL_CH2, ADC_CTL_CH3, ADC_CTL_CH4, ADC_CTL_CH5, ADC_CTL_CH6, ADC_CTL_CH7, ADC_CTL_CH8, and ADC_CTL_CH9.
Referenced by adc_collect(), and adc_open().
{
     switch (channel) {
     case 0:
         *encoded_channel = ADC_CTL_CH0;
         break;
     case 1:
         *encoded_channel = ADC_CTL_CH1;
         break;
     case 2:
         *encoded_channel = ADC_CTL_CH2;
         break;
     case 3:
         *encoded_channel = ADC_CTL_CH3;
         break;
     case 4:
         *encoded_channel = ADC_CTL_CH4;
         break;
     case 5:
         *encoded_channel = ADC_CTL_CH5;
         break;
     case 6:
         *encoded_channel = ADC_CTL_CH6;
         break;
     case 7:
         *encoded_channel = ADC_CTL_CH7;
         break;
     case 8:
         *encoded_channel = ADC_CTL_CH8;
         break;
     case 9:
         *encoded_channel = ADC_CTL_CH9;
         break;
     case 10:
         *encoded_channel = ADC_CTL_CH10;
         break;
     case 11:
         *encoded_channel = ADC_CTL_CH11;
         break;
     default:
         return false;
     }
     return true;
 }