EE 445M: lib/libuart/uart.h File Reference
lib/libuart/uart.h File Reference
#include <stdbool.h>
Defines
#define UART_UNUSED -1
UART standard library.
Functions
void uart_set_active_channel (const long channel)
void uart_clear_active_channel ()
bool uart_has_active_channel ()
void uart_init ()
void uart_init_ (const long channel)
void uart_send_char (const char text)
void uart_send_char_ (const long channel, const char text)
void uart_send_string (const char *text)
void uart_send_string_ (const long channel, const char *text)
char uart_get_char ()
Read a char from the active uart channel.
char uart_get_char_ (const long channel)
Read a char from the specified uart channel.
char * uart_get_string (const long string_length)
Read a char array from the active uart channel.
char * uart_get_string_ (const long channel, const long string_length)
Read a char array from the active uart channel.
Define Documentation
#define UART_UNUSED -1
UART standard library.
UART initialization, transmission, reception.
Author:
Hershal Bhave
Eric Crosson
Version:
0.1
Date:
2015
Precondition:
None
Bug:
No scoreboard to detect UART collisions yet
Warning:
Do not bother a UART who is busy slaving for another user.
Copyright:
GNU Public License.
Definition at line 17 of file uart.h.
Referenced by uart_clear_active_channel(), and uart_has_active_channel().
Function Documentation
void uart_clear_active_channel ()
Modally clear the active uart channel.
Returns:
void
Definition at line 28 of file uart.c.
References uart_active_channel, and UART_UNUSED.
{
  uart_active_channel = UART_UNUSED;
}
char uart_get_char ()
Read a char from the active uart channel.
Read a char from the active uart channel.
Read a char from the active uart channel.
Returns:
char read from uart
Definition at line 85 of file uart.c.
References uart_active_channel, and uart_get_char_().
Referenced by UART0_Handler().
                     {
  return uart_get_char_(uart_active_channel);
}
char uart_get_char_ (const long channel)
Read a char from the specified uart channel.
Read a char from the specified uart channel.
Read a char from the specified uart channel.
Parameters:
channel The uart channel to read.
Returns:
char read from uart
Definition at line 91 of file uart.c.
References UART0_BASE, and UARTCharGetNonBlocking().
Referenced by uart_get_char(), and uart_get_string_().
{
  return UARTCharGetNonBlocking(UART0_BASE);
}
char* uart_get_string (const long string_length)
Read a char array from the active uart channel.
Read a char array from the active uart channel.
Read a char array from the active uart channel.
Parameters:
string_length The maximum number of characters to read.
Returns:
char array read from uart
Definition at line 96 of file uart.c.
References uart_active_channel, and uart_get_string_().
{
  return uart_get_string_(uart_active_channel, string_length);
}
char* uart_get_string_ (const long channel, const long string_length)
Read a char array from the active uart channel.
Read a char array from the specified uart channel.
Read a char array from the active uart channel.
Parameters:
channel The uart channel to read.
string_length The maximum number of characters to read.
Returns:
char array read from uart
Definition at line 102 of file uart.c.
References UART0_BASE, uart_get_char_(), UARTCharsAvail(), UARTIntClear(), and UARTIntStatus().
Referenced by uart_get_string().
{
  char* read;
  uint32_t ui32Status;
  long remaining_chars = string_length;
  /* \buffer is a null-terminated string */
  char* buffer = mem_malloc(string_length*sizeof(char));
  buffer[string_length] = 0;
  /* Get the interrrupt status. */
  ui32Status = UARTIntStatus(UART0_BASE, true);
  /* Clear the asserted interrupts. */
  UARTIntClear(UART0_BASE, ui32Status);
  while(UARTCharsAvail(UART0_BASE) && remaining_chars > 0) {
    buffer[remaining_chars - string_length] = uart_get_char_(channel);
    remaining_chars--;
  }
  return buffer;
}
bool uart_has_active_channel ()
Test whether or not an active uart channel exists.
Returns:
boolean indicating uart active channel is modally set.
Definition at line 33 of file uart.c.
References uart_active_channel, and UART_UNUSED.
{
  return uart_active_channel == UART_UNUSED;
}
void uart_init ()
Initialize the active uart channel.
Returns:
void
Definition at line 38 of file uart.c.
References uart_active_channel, and uart_init_().
Referenced by main().
                 {
  uart_init_(uart_active_channel);
}
void uart_init_ (const long channel)
Initialize the specified uart channel.
Parameters:
channel The uart channel to initialize.
Returns:
void
Definition at line 44 of file uart.c.
References GPIO_PIN_0, GPIO_PIN_1, GPIO_PORTA_BASE, GPIOPinConfigure(), GPIOPinTypeUART(), INT_UART0, IntEnable(), SysCtlClockGet(), UART0_BASE, UART_CONFIG_PAR_NONE, UART_CONFIG_STOP_ONE, UART_CONFIG_WLEN_8, UART_INT_RT, UART_INT_RX, UARTConfigSetExpClk(), and UARTIntEnable().
Referenced by uart_init().
{
  GPIOPinConfigure(GPIO_PA0_U0RX);
  GPIOPinConfigure(GPIO_PA1_U0TX);
  GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);
  UARTConfigSetExpClk(UART0_BASE, SysCtlClockGet(), 115200,
              (UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE |
               UART_CONFIG_PAR_NONE));
  /* Enable the UART interrupt. */
  IntEnable(INT_UART0);
  UARTIntEnable(UART0_BASE, UART_INT_RX | UART_INT_RT);
}
void uart_send_char (const char text)
Send a char array over the active uart channel.
Parameters:
text The null-terminated array of chars to send via uart.
Returns:
void
Definition at line 59 of file uart.c.
References uart_active_channel, and uart_send_char_().
Referenced by UART0_Handler().
{
  uart_send_char_(uart_active_channel, text);
}
void uart_send_char_ (const long channel, const char text)
Send a char array over the specified uart channel.
Parameters:
channel The uart channel to send over.
text The null-terminated array of chars to send via uart.
Returns:
void
Definition at line 65 of file uart.c.
References UART0_BASE, and UARTCharPutNonBlocking().
Referenced by uart_send_char().
{
  UARTCharPutNonBlocking(UART0_BASE, text);
}
void uart_send_string (const char * text)
Send a char array over the active uart channel.
Parameters:
text The null-terminated array of chars to send via uart.
Returns:
void
Definition at line 70 of file uart.c.
References uart_active_channel, and uart_send_string_().
{
  uart_send_string_(uart_active_channel, text);
}
void uart_send_string_ (const long channel, const char * text)
Send a char array over the specified uart channel.
Parameters:
channel The uart channel to send over.
text The null-terminated array of chars to send via uart.
Returns:
void
Definition at line 75 of file uart.c.
References UARTCharPutNonBlocking(), and ustrlen().
Referenced by uart_send_string().
{
  uint32_t cnt = ustrlen(text);
  char* ptr = (char*)text;
  while(cnt--) {
    UARTCharPutNonBlocking(channel, *(ptr++));
  }
}
void uart_set_active_channel (const long channel)
Modally set the active uart channel.
Returns:
void
Definition at line 23 of file uart.c.
References uart_active_channel.
Referenced by main().
{
  uart_active_channel = channel;
}