EE445M RTOS: lib/libtimer/timer.c File Reference
timer.c File Reference
#include "timer.h"
#include "libhw/hardware.h"
#include "libnotify/notify.h"
#include "inc/hw_memmap.h"
#include "inc/hw_ints.h"
#include <stdlib.h>
#include "driverlib/pin_map.h"
#include "driverlib/timer.h"
#include "driverlib/sysctl.h"
Functions
bool timer_add_periodic_interrupt (uint32_t frequency, uint32_t timer_peripheral)
bool timer_remove_periodic_thread (const void *task, uint32_t timer_peripheral)
Function Documentation
bool timer_add_periodic_interrupt (uint32_t frequency, uint32_t timer_peripheral)
Definition at line 16 of file timer.c.
References INT_TIMER0A, INT_TIMER1A, INT_TIMER2A, IntEnable(), SYSCTL_PERIPH_TIMER0, SYSCTL_PERIPH_TIMER1, SYSCTL_PERIPH_TIMER2, SysCtlClockGet(), SysCtlPeripheralEnable(), TIMER0_BASE, TIMER1_BASE, TIMER2_BASE, TIMER_A, TIMER_CFG_PERIODIC, TIMER_TIMA_TIMEOUT, TimerConfigure(), TimerEnable(), TimerIntEnable(), and TimerLoadSet().
Referenced by hw_channel_init().
{
     uint32_t timer_base, timer_periph, timer_int;
     /* can give it a raw timer address (TIMERx_BASE) or an int with
        the timer number (0, 1, 2) for convenience */
     switch (timer_peripheral) {
     case TIMER0_BASE:
         timer_base = TIMER0_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER0;
         timer_int = INT_TIMER0A;
         break;
     case TIMER1_BASE:
         timer_base = TIMER1_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER1;
         timer_int = INT_TIMER1A;
         break;
     case TIMER2_BASE:
         timer_base = TIMER2_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER2;
         timer_int = INT_TIMER2A;
         break;
     default:
         /* you broke the world */
         return false;
     }
     SysCtlPeripheralEnable(timer_periph);
     TimerConfigure(timer_base, TIMER_CFG_PERIODIC);
     TimerLoadSet(timer_base, TIMER_A, SysCtlClockGet() / frequency);
     TimerIntEnable(timer_base, TIMER_TIMA_TIMEOUT);
     /* TODO: Fill in priority */
     IntEnable(timer_int, 0);
     TimerEnable(timer_base, TIMER_A);
     /* Success */
     return true;
 }
bool timer_remove_periodic_thread (const void * task, uint32_t timer_peripheral)
Definition at line 58 of file timer.c.
References hw_disconnect(), and HW_TIMER.
{
     hw_disconnect(HW_TIMER, timer_peripheral, task);
 }