EE445M RTOS: lib/libtimer/timer.h File Reference
timer.h File Reference
#include <stdint.h>
#include <stdbool.h>
Macros
#define Hz
Schedule a task (function) to be invoked periodically.
Functions
bool timer_add_periodic_interrupt (uint32_t frequency, uint32_t timer_peripheral)
Macro Definition Documentation
#define Hz
Schedule a task (function) to be invoked periodically.
Parameters
task A pointer to the function to execute every milliseconds
period_in_ms Number of milliseconds to wait before invoking repeatedly
priority The value to be specified in the NVIC for this thread (task)
timer_peripheral The timer device (peripheral) to use for scheduling
Returns
TODO
Note
Note that this function name was chosen by the class administrators. This name has been the source of some confusion; namely the fact that the function name refers to a thread and the function argument refers to a task. This function actually takes a task (a function pointer, not a fully-fledged thread) and invokes said function on the designated schedule. No true threads exist in this context.
Definition at line 24 of file timer.h.
Referenced by main().
Function Documentation
bool timer_add_periodic_interrupt (uint32_t frequency, uint32_t timer_peripheral)
Definition at line 16 of file timer.c.
References INT_TIMER0A, INT_TIMER1A, INT_TIMER2A, IntEnable(), SYSCTL_PERIPH_TIMER0, SYSCTL_PERIPH_TIMER1, SYSCTL_PERIPH_TIMER2, SysCtlClockGet(), SysCtlPeripheralEnable(), TIMER0_BASE, TIMER1_BASE, TIMER2_BASE, TIMER_A, TIMER_CFG_PERIODIC, TIMER_TIMA_TIMEOUT, TimerConfigure(), TimerEnable(), TimerIntEnable(), and TimerLoadSet().
Referenced by hw_channel_init().
{
     uint32_t timer_base, timer_periph, timer_int;
     /* can give it a raw timer address (TIMERx_BASE) or an int with
        the timer number (0, 1, 2) for convenience */
     switch (timer_peripheral) {
     case TIMER0_BASE:
         timer_base = TIMER0_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER0;
         timer_int = INT_TIMER0A;
         break;
     case TIMER1_BASE:
         timer_base = TIMER1_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER1;
         timer_int = INT_TIMER1A;
         break;
     case TIMER2_BASE:
         timer_base = TIMER2_BASE;
         timer_periph = SYSCTL_PERIPH_TIMER2;
         timer_int = INT_TIMER2A;
         break;
     default:
         /* you broke the world */
         return false;
     }
     SysCtlPeripheralEnable(timer_periph);
     TimerConfigure(timer_base, TIMER_CFG_PERIODIC);
     TimerLoadSet(timer_base, TIMER_A, SysCtlClockGet() / frequency);
     TimerIntEnable(timer_base, TIMER_TIMA_TIMEOUT);
     /* TODO: Fill in priority */
     IntEnable(timer_int, 0);
     TimerEnable(timer_base, TIMER_A);
     /* Success */
     return true;
 }