var modules =
[
    [ "Example_list", "group__example__list.html", null ],
    [ "Adc_api", "group__adc__api.html", "group__adc__api" ],
    [ "Aes_api", "group__aes__api.html", "group__aes__api" ],
    [ "Can_api", "group__can__api.html", "group__can__api" ],
    [ "Comp_api", "group__comp__api.html", "group__comp__api" ],
    [ "Crc_api", "group__crc__api.html", "group__crc__api" ],
    [ "Des_api", "group__des__api.html", "group__des__api" ],
    [ "Eeprom_api", "group__eeprom__api.html", "group__eeprom__api" ],
    [ "Emac_api", "group__emac__api.html", "group__emac__api" ],
    [ "Epi_api", "group__epi__api.html", "group__epi__api" ],
    [ "Flash_api", "group__flash__api.html", "group__flash__api" ],
    [ "Fpu_api", "group__fpu__api.html", "group__fpu__api" ],
    [ "Gpio_api", "group__gpio__api.html", "group__gpio__api" ],
    [ "Hibernate_api", "group__hibernate__api.html", "group__hibernate__api" ],
    [ "I2c_api", "group__i2c__api.html", "group__i2c__api" ],
    [ "Interrupt_api", "group__interrupt__api.html", "group__interrupt__api" ],
    [ "Lcd_api", "group__lcd__api.html", "group__lcd__api" ],
    [ "Mpu_api", "group__mpu__api.html", "group__mpu__api" ],
    [ "Pwm_api", "group__pwm__api.html", "group__pwm__api" ],
    [ "Qei_api", "group__qei__api.html", "group__qei__api" ],
    [ "Shamd5_api", "group__shamd5__api.html", "group__shamd5__api" ],
    [ "Ssi_api", "group__ssi__api.html", "group__ssi__api" ],
    [ "Sw_crc_api", "group__sw__crc__api.html", "group__sw__crc__api" ],
    [ "Sysctl_api", "group__sysctl__api.html", "group__sysctl__api" ],
    [ "Sysexc_api", "group__sysexc__api.html", "group__sysexc__api" ],
    [ "Systick_api", "group__systick__api.html", "group__systick__api" ],
    [ "Timer_api", "group__timer__api.html", "group__timer__api" ],
    [ "Uart_api", "group__uart__api.html", "group__uart__api" ],
    [ "Udma_api", "group__udma__api.html", "group__udma__api" ],
    [ "Usb_api", "group__usb__api.html", "group__usb__api" ],
    [ "Usb_dma", "group__usb__dma.html", "group__usb__dma" ],
    [ "Usb_ulpi", "group__usb__ulpi.html", "group__usb__ulpi" ],
    [ "Usb_lpm", "group__usb__lpm.html", "group__usb__lpm" ],
    [ "Watchdog_api", "group__watchdog__api.html", "group__watchdog__api" ],
    [ "Font faces and transformations.", "group___font.html", "group___font" ],
    [ "Framebuffer manipulation framework", "group___framebuffer.html", "group___framebuffer" ],
    [ "Graphical manipulation framework", "group___graphics.html", null ],
    [ "Hardware drivers", "group___drivers.html", null ],
    [ "Geometric modeling", "group___geometry.html", "group___geometry" ],
    [ "Notices and notifications", "group___notifications.html", null ],
    [ "Operating system routines", "group___o_s.html", null ],
    [ "System-interaction calls", "group___system.html", null ],
    [ "Command line interpreter", "group___shell.html", null ],
    [ "Global variables and typedefs", "group___globals.html", null ],
    [ "C structures for hash tables, linked lists, strings, and arrays", "group___u_t_hash.html", null ],
    [ "Cmdline_api", "group__cmdline__api.html", "group__cmdline__api" ],
    [ "Cpu_usage_api", "group__cpu__usage__api.html", "group__cpu__usage__api" ],
    [ "Flash_pb_api", "group__flash__pb__api.html", "group__flash__pb__api" ],
    [ "Isqrt_api", "group__isqrt__api.html", "group__isqrt__api" ],
    [ "Random_api", "group__random__api.html", "group__random__api" ],
    [ "Scheduler_api", "group__scheduler__api.html", "group__scheduler__api" ],
    [ "Sine_api", "group__sine__api.html", "group__sine__api" ],
    [ "Softssi_api", "group__softssi__api.html", "group__softssi__api" ],
    [ "Softuart_api", "group__softuart__api.html", "group__softuart__api" ],
    [ "Spi_flash_api", "group__spi__flash__api.html", "group__spi__flash__api" ],
    [ "Uartstdio_api", "group__uartstdio__api.html", "group__uartstdio__api" ],
    [ "Ustdlib_api", "group__ustdlib__api.html", "group__ustdlib__api" ]
];