var modules =
[
    [ "Example_list", "group__example__list.html", null ],
    [ "Adc_api", "group__adc__api.html", null ],
    [ "Aes_api", "group__aes__api.html", null ],
    [ "Can_api", "group__can__api.html", null ],
    [ "Comp_api", "group__comp__api.html", null ],
    [ "Crc_api", "group__crc__api.html", null ],
    [ "Des_api", "group__des__api.html", null ],
    [ "Eeprom_api", "group__eeprom__api.html", null ],
    [ "Emac_api", "group__emac__api.html", null ],
    [ "Epi_api", "group__epi__api.html", null ],
    [ "Flash_api", "group__flash__api.html", null ],
    [ "Fpu_api", "group__fpu__api.html", null ],
    [ "Gpio_api", "group__gpio__api.html", null ],
    [ "Hibernate_api", "group__hibernate__api.html", null ],
    [ "I2c_api", "group__i2c__api.html", null ],
    [ "Interrupt_api", "group__interrupt__api.html", null ],
    [ "Lcd_api", "group__lcd__api.html", null ],
    [ "Mpu_api", "group__mpu__api.html", null ],
    [ "Pwm_api", "group__pwm__api.html", null ],
    [ "Qei_api", "group__qei__api.html", null ],
    [ "Shamd5_api", "group__shamd5__api.html", null ],
    [ "Ssi_api", "group__ssi__api.html", null ],
    [ "Sw_crc_api", "group__sw__crc__api.html", null ],
    [ "Sysctl_api", "group__sysctl__api.html", null ],
    [ "Sysexc_api", "group__sysexc__api.html", null ],
    [ "Systick_api", "group__systick__api.html", null ],
    [ "Timer_api", "group__timer__api.html", null ],
    [ "Uart_api", "group__uart__api.html", null ],
    [ "Udma_api", "group__udma__api.html", null ],
    [ "Usb_api", "group__usb__api.html", null ],
    [ "Usb_dma", "group__usb__dma.html", null ],
    [ "Usb_ulpi", "group__usb__ulpi.html", null ],
    [ "Usb_lpm", "group__usb__lpm.html", null ],
    [ "Watchdog_api", "group__watchdog__api.html", null ],
    [ "Cmdline_api", "group__cmdline__api.html", null ],
    [ "Cpu_usage_api", "group__cpu__usage__api.html", null ],
    [ "Flash_pb_api", "group__flash__pb__api.html", null ],
    [ "Isqrt_api", "group__isqrt__api.html", null ],
    [ "Random_api", "group__random__api.html", null ],
    [ "Scheduler_api", "group__scheduler__api.html", null ],
    [ "Sine_api", "group__sine__api.html", null ],
    [ "Softssi_api", "group__softssi__api.html", null ],
    [ "Softuart_api", "group__softuart__api.html", null ],
    [ "Spi_flash_api", "group__spi__flash__api.html", null ],
    [ "Uartstdio_api", "group__uartstdio__api.html", null ],
    [ "Ustdlib_api", "group__ustdlib__api.html", null ],
    [ "OpenOCD invocation wrapper", "./bin/html/group__OpenOCD.html", null ],
    [ "Development environment setup", "./bin/html/group__Environment.html", null ]
];