EE445M RTOS: lib/libstd/nexus.c File Reference
nexus.c File Reference
#include "nexus.h"
Functions
void * memset (void *b, int c, int len)
void * memcpy (void *str1, const void *str2, long n)
int strcmp (const char *s1, const char *s2)
int ustrncmp (const char *s1, const char *s2, uint32_t n)
void ustrcpy (char *dest, const char *source)
Function Documentation
void* memcpy (void * , const void * , long)
A duplicate of the c standard memcpy function.
Definition at line 19 of file nexus.c.
Referenced by shell_set_ps1().
{
     long i = 0;
     uint8_t *dest8 = (uint8_t*)str1;
     uint8_t *source8 = (uint8_t*)str2;
     for (i=0; i<n; ++i) {
         dest8[i] = source8[i];
     }
 }
void* memset (void * , int , int)
A duplicate of the c standard memset function.
Definition at line 4 of file nexus.c.
Referenced by shell_clear_shell_buffer(), SoftUARTInit(), and system_register_command().
{
     int i;
     unsigned char *p = b;
     i = 0;
     while(len > 0) {
     *p = c;
     ++p;
     --len;
     }
     return b;
 }
int strcmp (const char * , const char *)
A duplicate of the c standard strcmp function.
Definition at line 29 of file nexus.c.
References ustrncmp().
Referenced by _system_command_from_name(), and CmdLineProcess().
{
     return(ustrncmp(s1, s2, (uint32_t)-1));
 }
void ustrcpy (char * , const char *)
A duplicate of the c standard strcpy function.
Definition at line 63 of file nexus.c.
Referenced by system_register_command().
{
     uint32_t i = 0;
     while (1) {
     dest[i] = source[i];
     if (dest[i++] == '\0') { break; }
     }
 }
int ustrncmp (const char * , const char * , uint32_t)
A duplicate of the c standard strncmp function.
Definition at line 34 of file nexus.c.
Referenced by strcmp().
{
     /* Loop while there are more characters. */
     while(n) {
         /* If we reached a NULL in both strings, they must be equal so
      * we end the comparison and return 0 */
         if(!*s1 && !*s2) {
             return(0);
         }
         /* Compare the two characters and, if different, return the
      * relevant return code. */
         if(*s2 < *s1) {
             return(1);
         }
         if(*s1 < *s2) {
             return(-1);
         }
         /* Move on to the next character. */
         s1++;
         s2++;
         n--;
     }
     /* If we fall out, the strings must be equal for at least the
      * first n characters so return 0 to indicate this. */
     return 0;
 }