EE445M Real Time Operating Systems: lib/libgraphics2d/shape.h File Reference
lib/libgraphics2d/shape.h File Reference
#include <stdlib.h>
#include "g2d_defines.h"
Data Structures
struct point
struct shape
struct circle
Defines
#define SHDuplicatePoint(p) SHCreatePoint(p->x, p->y, p->shade);
#define SHDestroyPoint(p) free(p);
Typedefs
typedef struct point point
typedef struct shape shape
typedef struct circle circle
Functions
point * SHCreatePoint (ushort x, ushort y, shade_t shade)
void FBPrintPointToConsole (point *p)
shape * SHCreateShape (ushort numPoints,...)
shape * SHDuplicateShape (shape *s)
void SHDestroyShape (shape *sh)
circle * SHCreateCircle (ushort radius, point *center)
shape * SHCreateTriangle (point *p0, point *p1, point *p2)
shape * SHCreateQuad (point *top_left_corner, uchar width, uchar height)
Define Documentation
#define SHDestroyPoint (p) free(p);
Definition at line 43 of file shape.h.
Referenced by _FBDrawLine(), _FBDrawString(), FBDrawAnonLine(), FBDrawFullscreenGraph(), FBEraseAnonLine(), FBEraseFullscreenGraph(), FBEraseFullscreenGraphData(), and FBEraseString().
#define SHDuplicatePoint (p) SHCreatePoint(p->x, p->y, p->shade);
Definition at line 40 of file shape.h.
Referenced by _FBDrawLine(), _FBDrawString(), CHCreateClockHand(), CHDuplicateClockHand(), and FBEraseString().
Typedef Documentation
typedef struct circle circle
typedef struct point point
typedef struct shape shape
Function Documentation
void FBPrintPointToConsole (point * p)
Definition at line 529 of file framebuffer.c.
References point::shade, point::x, and point::y.
{
#ifdef __GNUC__
  printf("(%d,%d):%d\n", p->x, p->y, p->shade);
#endif
}
circle* SHCreateCircle (ushort radius, point * center)
Definition at line 105 of file shape.c.
References circle::center, and circle::radius.
Referenced by demonstrateClock().
{
    circle* c = (circle*) calloc(1, sizeof(circle));
    c->center = center;
    c->radius = radius;
    return c;
}
point* SHCreatePoint (ushort x, ushort y, shade_t shade)
Definition at line 22 of file shape.c.
References point::shade, point::x, and point::y.
Referenced by _FBDrawGraphBounds(), _FBDrawGraphData(), demonstrateClock(), demonstrateDrawShapes(), demonstrateDrawString(), FBDrawFullscreenGraph(), FBEraseFullscreenGraph(), FBEraseFullscreenGraphData(), and SHCreateQuad().
{
    point* p = malloc(sizeof(point));
    p->x = x;
    p->y = y;
    p->shade = shade;
    return p;
}
shape* SHCreateQuad (point * top_left_corner, uchar width, uchar height)
Definition at line 48 of file shape.c.
References point::shade, SHCreatePoint(), SHCreateShape(), point::x, and point::y.
Referenced by demonstrateDrawShapes().
{
    ushort x = top_left_corner->x;
    ushort y = top_left_corner->y;
    shade_t shade = top_left_corner->shade;
    return SHCreateShape(4,
             top_left_corner,
             SHCreatePoint(x+width, y,        shade),
             SHCreatePoint(x+width, y+height, shade),
             SHCreatePoint(x,       y+height, shade));
}
shape* SHCreateShape (ushort numPoints, ...)
Definition at line 66 of file shape.c.
References shape::numPoints, and shape::points.
Referenced by CHToShape(), SHCreateQuad(), and SHCreateTriangle().
{
  unsigned char i;
  shape* sh = (shape*) calloc(1, sizeof(shape));
  point** pts = (point**) calloc(numPoints, sizeof(point*));
  va_list args;
  va_start(args, numPoints);
  for(i=0; i < numPoints; ++i) {
    pts[i] = va_arg(args, point*);
  }
  va_end(args);         /* clean up the list */
  sh->numPoints = numPoints;
  sh->points = pts;
  return sh;
}
shape* SHCreateTriangle (point * p0, point * p1, point * p2)
Definition at line 37 of file shape.c.
References SHCreateShape().
Referenced by demonstrateDrawShapes().
{
  return SHCreateShape(3, p0, p1, p2);
}
void SHDestroyShape (shape * sh)
Definition at line 89 of file shape.c.
References shape::numPoints, and shape::points.
{
  ushort i;
  for(i=0; i<sh->numPoints; ++i) {
    free(sh->points[i]);
  }
  free(sh->points);
}
shape* SHDuplicateShape (shape * s)
Definition at line 130 of file shape.c.
References shape::numPoints, and shape::points.
Referenced by CHDuplicateClockHand().
{
    ushort i;
    shape* dup = (shape*) calloc(1, sizeof(shape));
    dup->numPoints = s->numPoints;
    dup->points = (point**) calloc(dup->numPoints, sizeof(point*));
    for(i=0; i < dup->numPoints; ++i) {
    dup->points[i] = s->points[i];
    }
    return dup;
}