EE445M RTOS: lib/libshell/shell.c File Reference
shell.c File Reference
#include "shell.h"
#include "libhw/hardware.h"
#include "inc/hw_memmap.h"
#include "inc/hw_ints.h"
#include <stdint.h>
#include <stdbool.h>
#include "driverlib/pin_map.h"
#include "driverlib/timer.h"
#include "driverlib/sysctl.h"
#include "driverlib/gpio.h"
Functions
void shell_spawn ()
char * shell_represent ()
void shell_kill ()
void shell_uart0_handler (char recv)
void shell_set_ps1 (char *new_ps1)
void shell_clear_shell_buffer ()
void shell_print_ps1 ()
exit_status_t shell_execute_command ()
Variables
static unsigned short SHELL_BUFFER_POSITION
static char SHELL_BUFFER [64]
static char * SHELL_PS1 [4]
static char * SHELL_DEFAULT_PS1 = "\n> "
Function Documentation
void shell_clear_shell_buffer ()
Clear and reset
Definition at line 80 of file shell.c.
References memset(), SHELL_BUFFER, and SHELL_BUFFER_POSITION.
Referenced by shell_spawn(), and shell_uart0_handler().
{
     memset(SHELL_BUFFER, 0, sizeof(SHELL_BUFFER));
     SHELL_BUFFER_POSITION = 0;
 }
exit_status_t shell_execute_command ()
Execute the command contained in .
Bug:
This function does not allow the passing of arguments
Definition at line 91 of file shell.c.
References NULL, SHELL_BUFFER, and system_exec().
Referenced by shell_uart0_handler().
{
     const char** arguments = NULL;
     return system_exec(SHELL_BUFFER, arguments);
 }
void shell_kill ()
Kill the current shell process. This involves disconnecting from the hardware driver but not clearing internal data structures. The behavior of killing a non-spawned shell is undetermined.
Bug:
The behavior of killing a non-spawned shell is undetermined.
Definition at line 41 of file shell.c.
References hw_disconnect(), HW_UART, shell_uart0_handler(), and UART0_BASE.
                   {
     hw_disconnect(HW_UART, UART0_BASE, shell_uart0_handler);
 }
void shell_print_ps1 ()
Print the PS1.
Bug:
Ambiguity on which uart channel is used for terminal communication.
Note
This just displays to stdout, not a uart channel, which can be picked up by a display entity driver or whatever they're going to be called.
Definition at line 86 of file shell.c.
References SHELL_PS1, and uart_send_string().
Referenced by shell_spawn(), and shell_uart0_handler().
{
     uart_send_string(SHELL_PS1);
 }
char* shell_represent ()
Display the current state of the shell process. The behavior of representing a non-spawned shell is undetermined.
Bug:
This is not the sole method of displaying this process - it should be.
The behavior of representing a non-spawned shell is undetermined.
Definition at line 35 of file shell.c.
References SHELL_BUFFER.
{
     /* TODO: improve */
     return SHELL_BUFFER;
 }
void shell_set_ps1 (char * new_ps1)
Definition at line 74 of file shell.c.
References memcpy(), SHELL_PS1, and ustrlen().
Referenced by shell_spawn().
{
     /* TODO: ensure this copies a null terminator */
     memcpy(SHELL_PS1, new_ps1, ustrlen(new_ps1));
 }
void shell_spawn ()
Spawn a shell. Enable necessary peripherals, initialize internal data structures.
Bug:
No scoreboard prevents multiple shells from spawning - better trust the init'ing dev
Definition at line 23 of file shell.c.
References hw_connect(), HW_UART, shell_clear_shell_buffer(), SHELL_DEFAULT_PS1, shell_print_ps1(), shell_set_ps1(), shell_uart0_handler(), and UART0_BASE.
Referenced by main().
                    {
     /* TODO: have this handled by hw_connect (look at the scoreboard,
      * see what HAS been used (don't need to initialize), what IS
      * being used (blocked)) */
     /* SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0); */
     hw_connect(HW_UART, UART0_BASE, shell_uart0_handler);
     shell_set_ps1(SHELL_DEFAULT_PS1);
     shell_clear_shell_buffer();
     shell_print_ps1();
 }
void shell_uart0_handler (char)
Pseudo-ISR used to handle incoming chars from a user over UART.
Bug:
Ambiguity on which uart channel is used for terminal communication.
Definition at line 46 of file shell.c.
References SC_BACKSPACE, SC_CR, SHELL_BUFFER, SHELL_BUFFER_LENGTH, SHELL_BUFFER_POSITION, shell_clear_shell_buffer(), shell_execute_command(), shell_print_ps1(), uart_send_char(), and uart_send_string().
Referenced by shell_kill(), and shell_spawn().
{
     switch(recv) {
     case SC_CR:
         {   /* TODO: schedule */
         shell_execute_command();
         shell_clear_shell_buffer();
         uart_send_string("\r\n");
         /* TODO: why doesn't PS1 print twice? */
         shell_print_ps1();
         }
     break;
     case SC_BACKSPACE:
     SHELL_BUFFER[SHELL_BUFFER_POSITION--] = (char) 0;
     /* TODO: represent at all, with shell_represent */
     break;
     default:
     if (SHELL_BUFFER_LENGTH > SHELL_BUFFER_POSITION) {
         SHELL_BUFFER[SHELL_BUFFER_POSITION++] = recv;
         /* Echo char to terminal for user */
         uart_send_char(recv);
     }
     break;
     }
 }
Variable Documentation
char SHELL_BUFFER[64] static
Definition at line 18 of file shell.c.
Referenced by shell_clear_shell_buffer(), shell_execute_command(), shell_represent(), and shell_uart0_handler().
unsigned short SHELL_BUFFER_POSITION static
Definition at line 17 of file shell.c.
Referenced by shell_clear_shell_buffer(), and shell_uart0_handler().
char* SHELL_DEFAULT_PS1 = "\n> " static
Definition at line 21 of file shell.c.
Referenced by shell_spawn().
char* SHELL_PS1[4] static
Definition at line 20 of file shell.c.
Referenced by shell_print_ps1(), and shell_set_ps1().