EE445M RTOS: lib/libos/system.c File Reference
system.c File Reference
#include "system.h"
#include <stdbool.h>
#include <stdlib.h>
#include "libut/utlist.h"
#include "libstd/nexus.h"
Functions
void system_init ()
bool system_register_command (const char *command_name, int(*command)())
bool system_deregister_command (const char *command_name)
system_command * _system_command_from_name (const char *command_name)
exit_status_t system_exec (const char *command, const char **arguments)
Variables
static system_command SYSTEM_COMMANDS [16]
system_command * registered_commands = NULL
system_command * unregistered_commands = NULL
Function Documentation
system_command* _system_command_from_name (const char * command_name)
For internal use only. This function returns a pointer to the registered to the command name .
Definition at line 56 of file system.c.
References strcmp(), and SYSTEM_MAX_COMMANDS.
Referenced by system_deregister_command(), and system_exec().
{
     system_iterator i=0;
     while(i<SYSTEM_MAX_COMMANDS &&
           0 != strcmp(SYSTEM_COMMANDS[i].name, command_name)) {
         ++i;
     }
     return &SYSTEM_COMMANDS[i];
 }
bool system_deregister_command (const char *)
Remove a command from the index of executable system commands.
Returns
True if command was successfully deregistered.
Definition at line 43 of file system.c.
References _system_command_from_name(), CDL_DELETE, CDL_PREPEND, and system_command::valid.
{
     /* Grab the structure of the command to deregister and invaldiate
      * the metadata. Move it from the registered to the unregistered
      * pile. */
     system_command* command = _system_command_from_name(command_name);
     command->valid = false;
     CDL_DELETE(registered_commands, command);
     CDL_PREPEND(unregistered_commands, command);
     return true;
 }
exit_status_t system_exec (const char * , const char **)
Execute a system command.
Returns
The exit code of the executed command.
Bug:
Currently argument passing is not supported.
Definition at line 67 of file system.c.
References _system_command_from_name(), system_command::command, postpone_death(), and system_command::valid.
Referenced by shell_execute_command().
{
     system_command* sys_command = _system_command_from_name(command);
     if (sys_command->valid) {
     return sys_command->command(/*arguments*/);
     } else {
     /* TODO: determine what to do here */
     postpone_death();       /* plan a */
     return EXIT_FAILURE;    /* plan b */
     }
 }
void system_init ()
Initialize internal data structures.
Note
Ensure this method is called before any commands are registered.
Definition at line 17 of file system.c.
References CDL_PREPEND, and SYSTEM_MAX_COMMANDS.
Referenced by main().
                    {
     system_iterator i;
     /* All commands begin in the unregistered state */
     for(i=0; i<SYSTEM_MAX_COMMANDS; ++i) {
     CDL_PREPEND(unregistered_commands, &SYSTEM_COMMANDS[i]);
     }
 }
bool system_register_command (const char * , int(*)())
Register a command for later execution.
Returns
True if command was successfully registered.
Definition at line 27 of file system.c.
References CDL_DELETE, CDL_PREPEND, system_command::command, memset(), system_command::name, SYSTEM_MAX_COMMANDS, unregistered_commands, ustrcpy(), and system_command::valid.
Referenced by main().
{
     /* Grab the first free command, move it from the unregisted to the
      * registered pile, and populate it with this function's
      * arguments */
     system_command* sys_command = unregistered_commands;
     CDL_DELETE(unregistered_commands, unregistered_commands);
     CDL_PREPEND(registered_commands, sys_command);
     sys_command->valid = true;
     memset(sys_command->name, 0, SYSTEM_MAX_COMMANDS);
     ustrcpy(sys_command->name, command_name);
     sys_command->command = command;
     return true;
 }
Variable Documentation
system_command* registered_commands = NULL
Circular doubly-linked list containing all registered commands.
Definition at line 13 of file system.c.
system_command SYSTEM_COMMANDS[16] static
Statically allocated space for all system commands to reside.
Definition at line 11 of file system.c.
system_command* unregistered_commands = NULL
Circular doubly-linked list containing all unregistered commands.
Definition at line 15 of file system.c.
Referenced by system_register_command().