EE445M RTOS: board-progs/test-timer/startup_gcc.c File Reference
startup_gcc.c File Reference
#include <stdint.h>
#include <inc/hw_nvic.h>
#include <inc/hw_types.h>
Functions
void Reset_Handler (void)
static void NMI_Handler (void)
static void HardFault_Handler (void)
static void MemManage_Handler (void)
static void BusFault_Handler (void)
static void UsageFault_Handler (void)
static void SVC_Handler (void)
static void DebugMon_Handler (void)
static void PendSV_Handler (void)
static void SysTick_Handler (void)
void __attribute__ ((weak))
static void Default_Handler (void)
Variables
uint32_t _etext
uint32_t _data
uint32_t _edata
uint32_t _bss
uint32_t _ebss
Function Documentation
void __attribute__ ((weak))
Definition at line 50 of file startup_gcc.c.
References _bss, _data, _ebss, _edata, _etext, ADC0Seq0_Handler(), BusFault_Handler(), DebugMon_Handler(), HardFault_Handler(), MemManage_Handler(), NMI_Handler(), PendSV_Handler(), Reset_Handler(), SVC_Handler(), SysTick_Handler(), Timer0A_Handler(), Timer1A_Handler(), Timer2A_Handler(), UART0_Handler(), and UsageFault_Handler().
 {
     (void (*)(void))((uint32_t)pui32Stack + sizeof(pui32Stack)),
                                             // The initial stack pointer
     Reset_Handler,                              // The reset handler
     NMI_Handler,                                // The NMI handler
     HardFault_Handler,                          // The hard fault handler
     MemManage_Handler,                          // The MPU fault handler
     BusFault_Handler,                           // The bus fault handler
     UsageFault_Handler,                         // The usage fault handler
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     SVC_Handler,                                // SVCall handler
     DebugMon_Handler,                           // Debug monitor handler
     0,                                          // Reserved
     PendSV_Handler,                             // The PendSV handler
     SysTick_Handler,                            // The SysTick handler
     GPIOPortA_Handler,                          // GPIO Port A
     GPIOPortB_Handler,                          // GPIO Port B
     GPIOPortC_Handler,                          // GPIO Port C
     GPIOPortD_Handler,                          // GPIO Port D
     GPIOPortE_Handler,                          // GPIO Port E
     UART0_Handler,                              // UART0 Rx and Tx
     UART1_Handler,                              // UART1 Rx and Tx
     SSI0_Handler,                               // SSI0 Rx and Tx
     I2C0_Handler,                               // I2C0 Master and Slave
     PWM0Fault_Handler,                          // PWM Fault
     PWM0Generator0_Handler,                     // PWM Generator 0
     PWM0Generator1_Handler,                     // PWM Generator 1
     PWM0Generator2_Handler,                     // PWM Generator 2
     Quadrature0_Handler,                        // Quadrature Encoder 0
     ADC0Seq0_Handler,                           // ADC Sequence 0
     ADC0Seq1_Handler,                           // ADC Sequence 1
     ADC0Seq2_Handler,                           // ADC Sequence 2
     ADC0Seq3_Handler,                           // ADC Sequence 3
     WDT_Handler,                                // Watchdog timer
     Timer0A_Handler,                            // Timer 0 subtimer A
     Timer0B_Handler,                            // Timer 0 subtimer B
     Timer1A_Handler,                            // Timer 1 subtimer A
     Timer1B_Handler,                            // Timer 1 subtimer B
     Timer2A_Handler,                            // Timer 2 subtimer A
     Timer2B_Handler,                            // Timer 2 subtimer B
     Comp0_Handler,                              // Analog Comparator 0
     Comp1_Handler,                              // Analog Comparator 1
     Comp2_Handler,                              // Analog Comparator 2
     SysCtl_Handler,                             // System Control (PLL, OSC, BO)
     FlashCtl_Handler,                           // FLASH Control
     GPIOPortF_Handler,                          // GPIO Port F
     GPIOPortG_Handler,                          // GPIO Port G
     GPIOPortH_Handler,                          // GPIO Port H
     UART2_Handler,                              // UART2 Rx and Tx
     SSI1_Handler,                               // SSI1 Rx and Tx
     Timer3A_Handler,                            // Timer 3 subtimer A
     Timer3B_Handler,                            // Timer 3 subtimer B
     I2C1_Handler,                               // I2C1 Master and Slave
     Quadrature1_Handler,                        // Quadrature Encoder 1
     CAN0_Handler,                               // CAN0
     CAN1_Handler,                               // CAN1
     CAN2_Handler,                               // CAN2
     0,                                          // Reserved
     Hibernate_Handler,                          // Hibernate
     USB0_Handler,                               // USB0
     PWM0Generator3_Handler,                     // PWM Generator 3
     uDMA_Handler,                               // uDMA Software Transfer
     uDMA_Error,                                 // uDMA Error
     ADC1Seq0_Handler,                           // ADC1 Sequence 0
     ADC1Seq1_Handler,                           // ADC1 Sequence 1
     ADC1Seq2_Handler,                           // ADC1 Sequence 2
     ADC1Seq3_Handler,                           // ADC1 Sequence 3
     0,                                          // Reserved
     0,                                          // Reserved
     GPIOPortJ_Handler,                          // GPIO Port J
     GPIOPortK_Handler,                          // GPIO Port K
     GPIOPortL_Handler,                          // GPIO Port L
     SSI2_Handler,                               // SSI2 Rx and Tx
     SSI3_Handler,                               // SSI3 Rx and Tx
     UART3_Handler,                              // UART3 Rx and Tx
     UART4_Handler,                              // UART4 Rx and Tx
     UART5_Handler,                              // UART5 Rx and Tx
     UART6_Handler,                              // UART6 Rx and Tx
     UART7_Handler,                              // UART7 Rx and Tx
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     I2C2_Handler,                               // I2C2 Master and Slave
     I2C3_Handler,                               // I2C3 Master and Slave
     Timer4A_Handler,                            // Timer 4 subtimer A
     Timer4B_Handler,                            // Timer 4 subtimer B
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     0,                                          // Reserved
     Timer5A_Handler,                            // Timer 5 subtimer A
     Timer5B_Handler,                            // Timer 5 subtimer B
     WideTimer0A_Handler,                        // Wide Timer 0 subtimer A
     WideTimer0B_Handler,                        // Wide Timer 0 subtimer B
     WideTimer1A_Handler,                        // Wide Timer 1 subtimer A
     WideTimer1B_Handler,                        // Wide Timer 1 subtimer B
     WideTimer2A_Handler,                        // Wide Timer 2 subtimer A
     WideTimer2B_Handler,                        // Wide Timer 2 subtimer B
     WideTimer3A_Handler,                        // Wide Timer 3 subtimer A
     WideTimer3B_Handler,                        // Wide Timer 3 subtimer B
     WideTimer4A_Handler,                        // Wide Timer 4 subtimer A
     WideTimer4B_Handler,                        // Wide Timer 4 subtimer B
     WideTimer5A_Handler,                        // Wide Timer 5 subtimer A
     WideTimer5B_Handler,                        // Wide Timer 5 subtimer B
     FPU_Handler,                                // FPU
     0,                                          // Reserved
     0,                                          // Reserved
     I2C4_Handler       ,                        // I2C4 Master and Slave
     I2C5_Handler       ,                        // I2C5 Master and Slave
     GPIOPortM_Handler  ,                        // GPIO Port M
     GPIOPortN_Handler  ,                        // GPIO Port N
     Quadrature2_Handler,                        // Quadrature Encoder 2
     0,                                          // Reserved
     0,                                          // Reserved
     GPIOPortP_Handler     ,                     // GPIO Port P (Summary or P0)
     GPIOPortP1_Handler    ,                     // GPIO Port P1
     GPIOPortP2_Handler    ,                     // GPIO Port P2
     GPIOPortP3_Handler    ,                     // GPIO Port P3
     GPIOPortP4_Handler    ,                     // GPIO Port P4
     GPIOPortP5_Handler    ,                     // GPIO Port P5
     GPIOPortP6_Handler    ,                     // GPIO Port P6
     GPIOPortP7_Handler    ,                     // GPIO Port P7
     GPIOPortQ_Handler     ,                     // GPIO Port Q (Summary or Q0)
     GPIOPortQ1_Handler    ,                     // GPIO Port Q1
     GPIOPortQ2_Handler    ,                     // GPIO Port Q2
     GPIOPortQ3_Handler    ,                     // GPIO Port Q3
     GPIOPortQ4_Handler    ,                     // GPIO Port Q4
     GPIOPortQ5_Handler    ,                     // GPIO Port Q5
     GPIOPortQ6_Handler    ,                     // GPIO Port Q6
     GPIOPortQ7_Handler    ,                     // GPIO Port Q7
     GPIOPortR_Handler     ,                     // GPIO Port R
     GPIOPortS_Handler     ,                     // GPIO Port S
     PWM1Generator0_Handler,                     // PWM 1 Generator 0
     PWM1Generator1_Handler,                     // PWM 1 Generator 1
     PWM1Generator2_Handler,                     // PWM 1 Generator 2
     PWM1Generator3_Handler,                     // PWM 1 Generator 3
     PWM1Fault_Handler                           // PWM 1 Fault
 };
static void BusFault_Handler (void) static
Definition at line 465 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void DebugMon_Handler (void) static
Definition at line 498 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void Default_Handler (void) static
Definition at line 646 of file startup_gcc.c.
{
 //  while (1) {}
 }
static void HardFault_Handler (void) static
Definition at line 443 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void MemManage_Handler (void) static
Definition at line 454 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void NMI_Handler (void) static
Definition at line 425 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void PendSV_Handler (void) static
Definition at line 509 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
void Reset_Handler (void)
Definition at line 371 of file startup_gcc.c.
References _edata, _etext, and main().
 {
     uint32_t *pui32Src, *pui32Dest;
     //
     // Copy the data segment initializers from flash to SRAM.
     //
     pui32Src = &_etext;
     for(pui32Dest = &_data; pui32Dest < &_edata; )
     {
         *pui32Dest++ = *pui32Src++;
     }
     //
     // Zero fill the bss segment.
     //
     __asm("    ldr     r0, =_bss\n"
           "    ldr     r1, =_ebss\n"
           "    mov     r2, #0\n"
           "    .thumb_func\n"
           "zero_loop:\n"
           "        cmp     r0, r1\n"
           "        it      lt\n"
           "        strlt   r2, [r0], #4\n"
           "        blt     zero_loop");
     //
     // Enable the floating-point unit.  This must be done here to handle the
     // case where main() uses floating-point and the function prologue saves
     // floating-point registers (which will fault if floating-point is not
     // enabled).  Any configuration of the floating-point unit using DriverLib
     // APIs must be done here prior to the floating-point unit being enabled.
     //
     // Note that this does not use DriverLib since it might not be included in
     // this project.
     //
 //    HWREG(NVIC_CPAC) = ((HWREG(NVIC_CPAC) &
 //                         ~(NVIC_CPAC_CP10_M | NVIC_CPAC_CP11_M)) |
 //                        NVIC_CPAC_CP10_FULL | NVIC_CPAC_CP11_FULL);
 //
     //
     // Call the application's entry point.
     //
     main();
 }
static void SVC_Handler (void) static
Definition at line 487 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void SysTick_Handler (void) static
Definition at line 520 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
static void UsageFault_Handler (void) static
Definition at line 476 of file startup_gcc.c.
Referenced by __attribute__().
 {
     //
     // Enter an infinite loop.
     //
     while(1)
     {
     }
 }
Variable Documentation
uint32_t _bss
uint32_t _data
uint32_t _ebss
uint32_t _edata
uint32_t _etext