EE445M RTOS: board-progs/test-display/test-display.c File Reference
test-display.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/rom.h"
#include <sys/stat.h>
#include "libdisplay/ST7735.h"
#include "libstd/nexus.h"
Functions
int main (void)
Function Documentation
int main (void)
Accept input on UART 0, and parrot input back out to UART 0.
Returns
Exit status
Definition at line 32 of file test-display.c.
References FPUEnable(), GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinTypeGPIOOutput(), INITR_REDTAB, IntMasterEnable(), postpone_death, ST7735_DrawFastHLine(), ST7735_InitR(), ST7735_OutString(), ST7735_OutString2(), ST7735_YELLOW, SYSCTL_OSC_MAIN, SYSCTL_PERIPH_GPIOF, SYSCTL_PERIPH_TIMER0, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), and SysCtlPeripheralEnable().
                {
     int j;
     FPUEnable();
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     /* Enable the GPIO port that is used for the on-board LED. */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
     /* Enable the timer for display driver timings */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
     /* Enable the GPIO pins for the LED (PF2). */
     GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
     /* Enable processor interrupts. */
     IntMasterEnable();
     ST7735_InitR(INITR_REDTAB);
     ST7735_OutString("test on screen 0\n");
     ST7735_OutString("test on screen 0\n");
     ST7735_DrawFastHLine(0, 70, 128, ST7735_YELLOW);
     ST7735_OutString2("test on screen 1\n");
     ST7735_OutString2("test on screen 1\n");
     postpone_death();
 }