EE445M RTOS: board-progs/test-adc/test-adc.c File Reference
test-adc.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/adc.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/rom.h"
#include "libadc/adc.h"
#include "libstd/nexus.h"
#include "libheart/heartbeat.h"
Macros
#define HEARTBEAT_MODAL
Functions
void led_blink_red ()
void led_blink_green ()
void led_blink_blue ()
int main (void)
Variables
semaphore_t HW_ADC_SEQ2_SEM
uint32_t ADC0_SEQ2_SAMPLES [4]
uint32_t * adc_data_buffer
uint32_t red_work = 0
uint32_t blue_work = 0
uint32_t green_work = 0
Macro Definition Documentation
#define HEARTBEAT_MODAL
Definition at line 24 of file test-adc.c.
Function Documentation
void led_blink_blue ()
Definition at line 56 of file test-adc.c.
References blue_work, GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and os_surrender_context.
Referenced by main().
                       {
     while (1) {
         ++blue_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,
                      GPIO_PIN_2 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2));
         os_surrender_context();
     }
 }
void led_blink_green ()
Definition at line 44 of file test-adc.c.
References GPIO_PIN_3, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), green_work, HW_ADC_SEQ2_SEM, os_surrender_context, sem_guard, and sem_take.
Referenced by main().
{
     while (1) {
         sem_guard(HW_ADC_SEQ2_SEM) {
             sem_take(HW_ADC_SEQ2_SEM);
             ++green_work;
             GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3,
                          GPIO_PIN_3 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_3));
             os_surrender_context();
         }
     }
 }
void led_blink_red ()
Definition at line 35 of file test-adc.c.
References GPIO_PIN_1, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), os_surrender_context, and red_work.
Referenced by main().
                      {
     while (1) {
         ++red_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,
                      GPIO_PIN_1 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1));
         os_surrender_context();
     }
 }
int main (void)
Definition at line 65 of file test-adc.c.
References hw_metadata::adc, ADC0_BASE, ADC0_SEQ2_SAMPLES, adc_channel_init(), ADC_CTL_CH0, ADC_CTL_END, ADC_CTL_IE, adc_data_buffer, adc_init(), adc_interrupt_init(), ADC_TRIGGER_TIMER, hw_timer_metadata::base, hw_adc_metadata::base, hw_adc_metadata::channel, hw_adc_metadata::channel_configuration, DL_SOFT, hw_timer_metadata::frequency, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTF_BASE, heart_init(), Hz, INT_TIMER1A, hw_timer_metadata::interrupt, IntMasterDisable(), IntMasterEnable(), led_blink_blue(), led_blink_green(), led_blink_red(), os_launch(), os_threading_init(), hw_timer_metadata::periodic, hw_adc_metadata::sample_sequence, schedule(), SYSCTL_OSC_MAIN, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), adc_trigger_metadata::timer, TIMER1_BASE, TIMER_CFG_PERIODIC, hw_adc_metadata::trigger_metadata, and hw_adc_metadata::trigger_source.
                {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     /* Enable processor interrupts. */
     IntMasterDisable();
     heart_init();
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_1);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_2);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_3);
     /* Activate the ADC on PE1, 2, and 3 (AIN0-2). */
     /* start adc init */
     hw_metadata metadata;
     metadata.adc.base = ADC0_BASE;
     metadata.adc.trigger_source = ADC_TRIGGER_TIMER;
     metadata.adc.sample_sequence = 2;
     metadata.adc.channel = 0;
     metadata.adc.channel_configuration =
         ADC_CTL_CH0 | ADC_CTL_IE | ADC_CTL_END;
     metadata.adc.trigger_metadata.timer.base = TIMER1_BASE;
     metadata.adc.trigger_metadata.timer.frequency = 2 Hz;
     metadata.adc.trigger_metadata.timer.interrupt = INT_TIMER1A;
     metadata.adc.trigger_metadata.timer.periodic = TIMER_CFG_PERIODIC;
     adc_init(metadata);
     adc_channel_init(metadata);
     adc_interrupt_init(metadata);
     adc_data_buffer = ADC0_SEQ2_SAMPLES;
     /* end adc init */
     os_threading_init();
     schedule(led_blink_red, 100 Hz, DL_SOFT);
     schedule(led_blink_blue, 100 Hz, DL_SOFT);
     schedule(led_blink_green, 100 Hz, DL_SOFT);
     IntMasterEnable();
     os_launch();
     while (1) {
     }
 }
Variable Documentation
uint32_t ADC0_SEQ2_SAMPLES[4]
Definition at line 46 of file hardware.c.
Referenced by main().
uint32_t* adc_data_buffer
Definition at line 30 of file test-adc.c.
Referenced by main().
uint32_t blue_work = 0
Definition at line 32 of file test-adc.c.
Referenced by led_blink_blue().
uint32_t green_work = 0
Definition at line 33 of file test-adc.c.
Referenced by led_blink_green().
semaphore_t HW_ADC_SEQ2_SEM
Definition at line 49 of file hardware.c.
Referenced by led_blink_green().
uint32_t red_work = 0
Definition at line 31 of file test-adc.c.
Referenced by led_blink_red().