EE445M RTOS: board-progs/autonomous-racer/test-countdown/test-countdown.cpp File Reference
test-countdown.cpp File Reference
#include "../common/adcpp.hpp"
#include "../common/blinker.hpp"
#include "../common/uartpp.hpp"
#include "../common/shellpp.hpp"
#include "../common/semaphorepp.hpp"
#include "../common/motorpp.hpp"
#include "../common/drivepp.hpp"
#include "../common/canpp.hpp"
#include "../common/ctlsysctl.hpp"
#include "../common/switchpp.hpp"
#include "libos/os.h"
#include "libschedule/schedule.h"
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include "inc/hw_memmap.h"
#include "driverlib/adc.h"
#include "driverlib/sysctl.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/uart.h"
Macros
#define UART0_RX_BUFFER_SIZE 8
Functions
void timer_updater ()
int main (void)
void Timer2A_Handler ()
void Timer1A_Handler ()
void __cxa_pure_virtual ()
Variables
timer countdown_timer
timer blink_timer
blinker blink
uart uart0
static semaphore UART0_RX_SEM
static buffer< char, 8 > UART0_RX_BUFFER
Macro Definition Documentation
#define UART0_RX_BUFFER_SIZE 8
Definition at line 36 of file test-countdown.cpp.
Function Documentation
void __cxa_pure_virtual ()
Definition at line 82 of file test-countdown.cpp.
 { while (1) {} }
int main (void)
Definition at line 51 of file test-countdown.cpp.
References ctlsys::set_clock(), timer_updater(), and UART0_RX_SEM.
                {
     ctlsys::set_clock();
     IntMasterDisable();
     blink = blinker(GPIO_PORTF_BASE, GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);
     UART0_RX_BUFFER = buffer<char, UART0_RX_BUFFER_SIZE>(&UART0_RX_SEM);
     uart0 = uart(UART0_BASE, INT_UART0);
     countdown_timer = timer(2, TIMER_BOTH, TIMER_CFG_ONE_SHOT,
                             SysCtlClockGet()*180, TIMER_TIMA_TIMEOUT, true);
     blink_timer = timer(1, TIMER_A, TIMER_CFG_PERIODIC,
                             SysCtlClockGet()/2, TIMER_TIMA_TIMEOUT, true);
     os_threading_init();
     schedule(timer_updater, 200);
     os_launch();
 }
void Timer1A_Handler ()
Definition at line 77 of file test-countdown.cpp.
References timer::ack(), PIN_GREEN, and blinker::toggle().
{
     blink_timer.ack();
     blink.toggle(PIN_GREEN);
 }
void Timer2A_Handler ()
Definition at line 72 of file test-countdown.cpp.
References timer::ack(), PIN_RED, and blinker::toggle().
{
     countdown_timer.ack();
     blink.toggle(PIN_RED);
 }
void timer_updater ()
Definition at line 40 of file test-countdown.cpp.
References uart::printf().
Referenced by main().
                      {
     uint32_t timer_data;
     while(1) {
         /* todo: populate these uint32_t's with sensor data */
         timer_data = TimerValueGet(TIMER2_BASE, TIMER_A);
         uart0.printf("timer: %u\n", timer_data);
         os_surrender_context();
     }
 }
Variable Documentation
blinker blink
Definition at line 33 of file test-countdown.cpp.
timer blink_timer
Definition at line 32 of file test-countdown.cpp.
timer countdown_timer
Definition at line 31 of file test-countdown.cpp.
uart uart0
Definition at line 34 of file test-countdown.cpp.
buffer<char, 8 > UART0_RX_BUFFER static
Definition at line 38 of file test-countdown.cpp.
semaphore UART0_RX_SEM static
Definition at line 37 of file test-countdown.cpp.
Referenced by main().