EE445M RTOS: board-progs/test-button/test-button.c File Reference
test-button.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_gpio.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "driverlib/rom.h"
#include "libos/os.h"
#include "libbutton/button.h"
#include "libhw/hardware.h"
Functions
void update_pid (notification button_bitmask)
int main ()
Variables
uint32_t button_left_pressed = 0
uint32_t button_right_pressed = 0
Function Documentation
int main (void)
Definition at line 43 of file test-button.c.
References button_metadata_init, BUTTONS_BOTH, GPIO_BOTH_EDGES, GPIO_PORTF_BASE, HW_BUTTON, hw_init, hw_subscribe, IntMasterDisable(), IntMasterEnable(), postpone_death, SYSCTL_OSC_MAIN, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), and update_pid().
            {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     IntMasterDisable();
     button_metadata_init(GPIO_PORTF_BASE, BUTTONS_BOTH, GPIO_BOTH_EDGES);
     hw_init(HW_BUTTON, button_metadata);
     hw_subscribe(HW_BUTTON, button_metadata, update_pid);
     IntMasterEnable();
     postpone_death();
 }
void update_pid (notification button_bitmask)
Definition at line 32 of file test-button.c.
References notification::_int, BUTTON_LEFT, button_left_pressed, BUTTON_RIGHT, and button_right_pressed.
Referenced by main().
{
     /* What was that technique we learned in 460n to avoid a bunch of
      branches? cond && action*/
     if (button_bitmask._int & BUTTON_LEFT) {
         button_left_pressed++;
     }
     if (button_bitmask._int & BUTTON_RIGHT) {
         button_right_pressed++;
     }
 }
Variable Documentation
uint32_t button_left_pressed = 0
Definition at line 29 of file test-button.c.
Referenced by update_pid().
uint32_t button_right_pressed = 0
Definition at line 30 of file test-button.c.
Referenced by update_pid().