EE445M RTOS: board-progs/test-uart/test-uart.c File Reference
test-uart.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "libuart/uart.h"
#include "libhw/hardware.h"
#include "libheart/heartbeat.h"
Macros
#define HEARTBEAT_MODAL
Functions
void led_blink_red ()
void led_blink_green ()
void led_blink_blue ()
void uart_handler (notification note)
int main (void)
Variables
uint32_t red_work = 0
uint32_t blue_work = 0
uint32_t green_work = 0
Macro Definition Documentation
#define HEARTBEAT_MODAL
Definition at line 22 of file test-uart.c.
Function Documentation
void led_blink_blue ()
Definition at line 47 of file test-uart.c.
References blue_work, GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and os_surrender_context.
Referenced by main().
                       {
     while (1) {
         ++blue_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,
                      GPIO_PIN_2 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2));
         os_surrender_context();
     }
 }
void led_blink_green ()
Definition at line 38 of file test-uart.c.
References GPIO_PIN_3, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and green_work.
Referenced by uart_handler().
{
     /* while (1) { */
         ++green_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3,
                      GPIO_PIN_3 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_3));
         /* os_surrender_context(); */
     /* } */
 }
void led_blink_red ()
Definition at line 29 of file test-uart.c.
References GPIO_PIN_1, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), os_surrender_context, and red_work.
Referenced by main().
                      {
     while (1) {
         ++red_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,
                      GPIO_PIN_1 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1));
         os_surrender_context();
     }
 }
int main (void)
Accept input on UART 0, and parrot input back out to UART 0.
Returns
Exit status
Definition at line 70 of file test-uart.c.
References DL_SOFT, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTF_BASE, heart_init(), hw_daemon(), hw_init_and_subscribe, HW_UART, Hz, INT_UART0, IntMasterDisable(), IntMasterEnable(), led_blink_blue(), led_blink_red(), os_launch(), os_threading_init(), postpone_death, schedule(), SYSCTL_OSC_MAIN, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), UART0_BASE, UART_DEFAULT_BAUD_RATE, uart_handler(), uart_metadata_init, and uart_send_string().
                {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     IntMasterDisable();
     heart_init();
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_1);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_2);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_3);
     uart_metadata_init(UART_DEFAULT_BAUD_RATE, UART0_BASE, INT_UART0);
     hw_init_and_subscribe(HW_UART, uart_metadata, uart_handler);
     os_threading_init();
     schedule(led_blink_red, 100 Hz, DL_SOFT);
     schedule(led_blink_blue, 100 Hz, DL_SOFT);
     schedule(hw_daemon, 100 Hz, DL_SOFT);
     /* Prompt for text to be entered. */
     uart_send_string("Enter text:");
     IntMasterEnable();
     os_launch();
     postpone_death();
 }
void uart_handler (notification note)
Read the next character from the UART and write it back to the UART.
Returns
void
Definition at line 59 of file test-uart.c.
References notification::_char, led_blink_green(), and uart_send_char().
Referenced by main().
{
     char recv = note._char;
     uart_send_char(recv);
     led_blink_green();
 }
Variable Documentation
uint32_t blue_work = 0
Definition at line 26 of file test-uart.c.
Referenced by led_blink_blue().
uint32_t green_work = 0
Definition at line 27 of file test-uart.c.
Referenced by led_blink_green().
uint32_t red_work = 0
Definition at line 25 of file test-uart.c.
Referenced by led_blink_red().