EE445M RTOS: board-progs/test-shell/test-shell.c File Reference
test-shell.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/rom.h"
#include "libshell/shell.h"
#include "libnotify/notify.h"
#include "libhw/hardware.h"
#include "libuart/uart.h"
#include "libstd/nexus.h"
#include "libos/system.h"
#include "libos/os.h"
#include <sys/stat.h>
#include "libheart/heartbeat.h"
Macros
#define HEARTBEAT_MODAL
Functions
void led_blink_red ()
void led_blink_green ()
void led_blink_blue ()
int doctor ()
int witch ()
int main (void)
Variables
uint32_t red_work = 0
uint32_t blue_work = 0
uint32_t green_work = 0
Macro Definition Documentation
#define HEARTBEAT_MODAL
Definition at line 34 of file test-shell.c.
Function Documentation
int doctor ()
Definition at line 68 of file test-shell.c.
References UART0_BASE, and UARTCharPut().
Referenced by main().
              {
     /* uart_set_active_channel(UART0_BASE); */
     UARTCharPut(UART0_BASE, 'd');
     /* uart_send_string("Well what did you expect would happen? You're dreaming!\n"); */
     return EXIT_SUCCESS;
 }
void led_blink_blue ()
Definition at line 59 of file test-shell.c.
References blue_work, GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and os_surrender_context.
Referenced by main().
                       {
     while (1) {
         ++blue_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,
                      GPIO_PIN_2 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2));
         os_surrender_context();
     }
 }
void led_blink_green ()
Definition at line 50 of file test-shell.c.
References GPIO_PIN_3, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and green_work.
{
     /* while (1) { */
         ++green_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3,
                      GPIO_PIN_3 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_3));
         /* os_surrender_context(); */
     /* } */
 }
void led_blink_red ()
Definition at line 41 of file test-shell.c.
References GPIO_PIN_1, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), os_surrender_context, and red_work.
Referenced by main().
                      {
     while (1) {
         ++red_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,
                      GPIO_PIN_1 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1));
         os_surrender_context();
     }
 }
int main (void)
Definition at line 83 of file test-shell.c.
References DL_SOFT, doctor(), GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTF_BASE, heart_init(), hw_daemon(), hw_init, HW_UART, Hz, INT_UART0, IntMasterDisable(), IntMasterEnable(), led_blink_blue(), led_blink_red(), os_launch(), os_threading_init(), postpone_death, schedule(), shell_spawn(), SYSCTL_OSC_MAIN, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), system_init(), system_register_command(), UART0_BASE, UART_DEFAULT_BAUD_RATE, uart_metadata_init, and witch().
                {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     IntMasterDisable();
     heart_init();
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_1);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_2);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_3);
     os_threading_init();
     schedule(hw_daemon, 100 Hz, DL_SOFT);
     schedule(led_blink_red, 100 Hz, DL_SOFT);
     schedule(led_blink_blue, 100 Hz, DL_SOFT);
     system_init();
     system_register_command((const char*) "doctor", doctor);
     system_register_command((const char*) "witch", witch);
     /* Initialize hardware devices */
     uart_metadata_init(UART_DEFAULT_BAUD_RATE, UART0_BASE, INT_UART0);
     hw_init(HW_UART, uart_metadata);
     /* Initialize the shell and the system it interacts with */
     shell_spawn();
     IntMasterEnable();
     os_launch();
     postpone_death();
 }
int witch ()
Definition at line 76 of file test-shell.c.
References uart_send_string().
Referenced by main().
             {
     /* uart_set_active_channel(UART0_BASE); */
     uart_send_string("no help here\n");
     return EXIT_SUCCESS;
 }
Variable Documentation
uint32_t blue_work = 0
Definition at line 38 of file test-shell.c.
Referenced by led_blink_blue().
uint32_t green_work = 0
Definition at line 39 of file test-shell.c.
Referenced by led_blink_green().
uint32_t red_work = 0
Definition at line 37 of file test-shell.c.
Referenced by led_blink_red().