EE445M RTOS: board-progs/autonomous-racer/test-ping/test-ping.cpp File Reference
test-ping.cpp File Reference
#include "../common/adcpp.hpp"
#include "../common/blinker.hpp"
#include "../common/uartpp.hpp"
#include "../common/shellpp.hpp"
#include "../common/semaphorepp.hpp"
#include "../common/motorpp.hpp"
#include "../common/drivepp.hpp"
#include "../common/canpp.hpp"
#include "../common/ctlsysctl.hpp"
#include "../common/switchpp.hpp"
#include "../common/pingpp.hpp"
#include "libos/os.h"
#include "libschedule/schedule.h"
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include "inc/hw_memmap.h"
#include "driverlib/adc.h"
#include "driverlib/sysctl.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/uart.h"
Macros
#define UART0_RX_BUFFER_SIZE 8
Functions
void ping_handler ()
int main (void)
void Timer1A_Handler ()
void GPIOPortD_Handler ()
void __cxa_pure_virtual ()
Variables
blinker blink
uart uart0
ping ping0
semaphore * ping0_sem
static semaphore UART0_RX_SEM
static buffer< char, 8 > UART0_RX_BUFFER
Macro Definition Documentation
#define UART0_RX_BUFFER_SIZE 8
Definition at line 37 of file test-ping.cpp.
Function Documentation
void __cxa_pure_virtual ()
Definition at line 79 of file test-ping.cpp.
 { while (1) {} }
void GPIOPortD_Handler ()
Definition at line 75 of file test-ping.cpp.
References ping::handle_gpio().
{
     ping0.handle_gpio();
 }
int main (void)
Definition at line 54 of file test-ping.cpp.
References ping::get_sem(), ping_handler(), ctlsys::set_clock(), and UART0_RX_SEM.
                {
     ctlsys::set_clock();
     IntMasterDisable();
     UART0_RX_BUFFER = buffer<char, UART0_RX_BUFFER_SIZE>(&UART0_RX_SEM);
     uart0 = uart(UART0_BASE, INT_UART0);
     blink = blinker(GPIO_PORTF_BASE, GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);
     ping0 = ping(GPIO_PORTD_BASE, GPIO_PIN_3, 1, TIMER_A);
     ping0_sem = ping0.get_sem();
     os_threading_init();
     schedule(ping_handler, 200);
     os_launch();
 }
void ping_handler ()
Definition at line 41 of file test-ping.cpp.
References ping::average(), semaphore::guard(), uart::printf(), ping::sample(), and ping::start().
Referenced by main().
                     {
     ping0.start();
     while(1){
         if (ping0_sem->guard()) {
             ping0.sample();
             uart0.printf("ping: %u\n", ping0.average());
         }
         os_surrender_context();
     }
 }
void Timer1A_Handler ()
Definition at line 71 of file test-ping.cpp.
References ping::handle_timer().
{
     ping0.handle_timer();
 }
Variable Documentation
blinker blink
Definition at line 32 of file test-ping.cpp.
ping ping0
Definition at line 34 of file test-ping.cpp.
semaphore* ping0_sem
Definition at line 35 of file test-ping.cpp.
uart uart0
Definition at line 33 of file test-ping.cpp.
buffer<char, 8 > UART0_RX_BUFFER static
Definition at line 39 of file test-ping.cpp.
semaphore UART0_RX_SEM static
Definition at line 38 of file test-ping.cpp.
Referenced by main().