EE445M RTOS: board-progs/test-timer/test-timer.c File Reference
test-timer.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/fpu.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/rom.h"
#include "libtimer/timer.h"
#include "libheart/heartbeat.h"
#include "libhw/hardware.h"
#include <sys/stat.h>
Functions
void blink_onboard_led (void)
Blink the onboard LED three times to show activity.
int main (void)
Function Documentation
void blink_onboard_led (void)
Blink the onboard LED three times to show activity.
Definition at line 31 of file test-timer.c.
References heart_beat(), and heart_toggle().
{
     heart_beat();
     heart_toggle();
 }
int main (void)
Accept input on UART 0, and parrot input back out to UART 0.
Returns
Exit status
Definition at line 39 of file test-timer.c.
References FPUEnable(), GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinTypeGPIOOutput(), hw_channel_init(), hw_driver_init(), HW_TIMER, Hz, IntMasterEnable(), SYSCTL_OSC_MAIN, SYSCTL_PERIPH_GPIOF, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), SysCtlPeripheralEnable(), hw_metadata::timer, TIMER0_BASE, and hw_timer_metadata::TIMER_FREQUENCY.
                {
     FPUEnable();
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     /* Enable the GPIO port that is used for the on-board LED. */
     SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
     /* Enable the GPIO pins for the LED (PF2). */
     GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
     /* Enable processor interrupts. */
     IntMasterEnable();
     hw_driver_init(HW_TIMER);
     hw_metadata timer_metadata;
     timer_metadata.timer.TIMER_FREQUENCY = 1 Hz;
     hw_channel_init(HW_TIMER, TIMER0_BASE, timer_metadata);
     /* Postpone death */
     while (1) {
     }
 }