EE445M RTOS: board-progs/test-edf/test-edf.c File Reference
test-edf.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "libbutton/button.h"
#include "libtimer/timer.h"
#include "libschedule/schedule.h"
#include "libos/os.h"
#include "libheart/heartbeat.h"
Macros
#define HEARTBEAT_MODAL
#define SCHEDLUE_PRIORITY
#define SCHEDULER_MAX_THREADS 16
#define HEART_RED GPIO_PIN_1
#define HEART_BLUE GPIO_PIN_2
#define HEART_GREEN GPIO_PIN_3
Functions
void button_debounce_end (notification button_notification)
void button_debounce_start (notification button_notification)
void postpone_suicide ()
void led_blink_red ()
void led_blink_blue ()
void main (void)
Variables
volatile uint32_t button_left_pressed
volatile uint32_t button_right_pressed
volatile uint32_t button_debounced_mailbox
volatile uint32_t button_debounced_wtf
volatile semaphore_t button_debounced_new_data
volatile uint32_t red_work = 0
volatile uint32_t blue_work = 0
Macro Definition Documentation
#define HEART_BLUE GPIO_PIN_2
Definition at line 34 of file test-edf.c.
#define HEART_GREEN GPIO_PIN_3
Definition at line 35 of file test-edf.c.
#define HEART_RED GPIO_PIN_1
Definition at line 33 of file test-edf.c.
#define HEARTBEAT_MODAL
Definition at line 23 of file test-edf.c.
#define SCHEDLUE_PRIORITY
Definition at line 24 of file test-edf.c.
#define SCHEDULER_MAX_THREADS 16
Definition at line 25 of file test-edf.c.
Function Documentation
void button_debounce_end (notification button_notification)
Definition at line 48 of file test-edf.c.
References button_debounced_mailbox, button_debounced_new_data, BUTTONS_BOTH, GPIO_PORTF_BASE, GPIOPinRead(), and sem_post.
Referenced by button_debounce_start(), and main().
{
     button_debounced_mailbox = GPIOPinRead(GPIO_PORTF_BASE, BUTTONS_BOTH);
     sem_post(button_debounced_new_data);
 }
void button_debounce_start (notification button_notification)
Definition at line 55 of file test-edf.c.
References button_debounce_end(), button_debounced_wtf, BUTTONS_BOTH, GPIO_PORTF_BASE, GPIOPinRead(), hw_channel_init(), hw_subscribe_single_shot, HW_TIMER, Hz, INT_TIMER0A, TIMER0_BASE, TIMER_CFG_ONE_SHOT, and timer_metadata_init.
{
     button_debounced_wtf = GPIOPinRead(GPIO_PORTF_BASE, BUTTONS_BOTH);
     timer_metadata_init(TIMER0_BASE, 100 Hz, INT_TIMER0A, TIMER_CFG_ONE_SHOT);
     hw_channel_init(HW_TIMER, timer_metadata);
     hw_subscribe_single_shot(HW_TIMER, timer_metadata,
                              button_debounce_end);
 }
void led_blink_blue ()
Definition at line 93 of file test-edf.c.
References blue_work, GPIO_PIN_2, GPIO_PORTF_BASE, GPIOPinRead(), and GPIOPinWrite().
Referenced by main().
                       {
     while (1) {
         ++blue_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2,
                      GPIO_PIN_2 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2));
         /* os_surrender_context(); */
     }
 }
void led_blink_red ()
Definition at line 84 of file test-edf.c.
References GPIO_PIN_1, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), and red_work.
Referenced by main().
                      {
     while (1) {
         ++red_work;
         GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1,
                      GPIO_PIN_1 ^ GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_1));
         /* os_surrender_context(); */
     }
 }
void main (void)
Definition at line 102 of file test-edf.c.
References button_debounce_end(), button_metadata_init, BUTTONS_BOTH, DL_SOFT, GPIO_BOTH_EDGES, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTF_BASE, heart_init(), HW_BUTTON, hw_driver_init(), hw_init, hw_subscribe, HW_TIMER, Hz, INT_TIMER0A, IntMasterDisable(), IntMasterEnable(), led_blink_blue(), led_blink_red(), os_launch(), os_threading_init(), pidwork_init(), postpone_death, postpone_suicide(), schedule(), SYSCTL_OSC_MAIN, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockSet(), TIMER0_BASE, TIMER_CFG_ONE_SHOT, and timer_metadata_init.
                 {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                    SYSCTL_XTAL_16MHZ);
     IntMasterDisable();
     heart_init();
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_1);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_2);
     heart_init_(GPIO_PORTF_BASE, GPIO_PIN_3);
     /* begin timer init */
     timer_metadata_init(TIMER0_BASE, 10 Hz, INT_TIMER0A, TIMER_CFG_ONE_SHOT);
     hw_driver_init(HW_TIMER, timer_metadata);
     /* end timer init */
     /* button init */
     button_metadata_init(GPIO_PORTF_BASE, BUTTONS_BOTH, GPIO_BOTH_EDGES);
     hw_init(HW_BUTTON, button_metadata);
     hw_subscribe(HW_BUTTON, button_metadata, button_debounce_end);
     pidwork_init();
     os_threading_init();
     schedule(led_blink_red, 10 Hz, DL_SOFT);
     /* schedule(led_blink_green, 10 Hz, DL_SOFT); */
     schedule(led_blink_blue, 100 Hz, DL_SOFT);
     schedule(postpone_suicide, 100 Hz, DL_SOFT);
     /* next test: different frequencies,pools */
     IntMasterEnable();
     os_launch();
     postpone_death();
 }
void postpone_suicide ()
Definition at line 64 of file test-edf.c.
References button_debounced_mailbox, button_debounced_new_data, BUTTON_LEFT, button_left_pressed, BUTTON_RIGHT, button_right_pressed, GPIO_PIN_2, GPIO_PIN_3, GPIO_PORTF_BASE, GPIOPinRead(), GPIOPinWrite(), sem_guard, and sem_take.
Referenced by main().
{
     while (1) {
         sem_guard(button_debounced_new_data) {
             sem_take(button_debounced_new_data);
             if (~button_debounced_mailbox & BUTTON_LEFT) {
                 GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2 ^
                              GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_2));
                 ++button_left_pressed;
             }
             if (~button_debounced_mailbox & BUTTON_RIGHT) {
                 GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, GPIO_PIN_3 ^
                              GPIOPinRead(GPIO_PORTF_BASE, GPIO_PIN_3));
                 ++button_right_pressed;
             }
         }
         /* os_surrender_context(); */
     }
 }
Variable Documentation
volatile uint32_t blue_work = 0
Definition at line 46 of file test-edf.c.
Referenced by led_blink_blue().
volatile uint32_t button_debounced_mailbox
Definition at line 40 of file test-edf.c.
Referenced by button_debounce_end(), and postpone_suicide().
volatile semaphore_t button_debounced_new_data
Definition at line 43 of file test-edf.c.
Referenced by button_debounce_end(), and postpone_suicide().
volatile uint32_t button_debounced_wtf
Definition at line 41 of file test-edf.c.
Referenced by button_debounce_start().
volatile uint32_t button_left_pressed
Definition at line 37 of file test-edf.c.
Referenced by postpone_suicide().
volatile uint32_t button_right_pressed
Definition at line 38 of file test-edf.c.
Referenced by postpone_suicide().
volatile uint32_t red_work = 0
Definition at line 45 of file test-edf.c.
Referenced by led_blink_red().