EE445M RTOS: board-progs/test-semaphore/test-semaphore.c File Reference
test-semaphore.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "driverlib/debug.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "driverlib/rom.h"
#include "libos/os.h"
#include "libheart/heartbeat.h"
#include "libos/semaphore.h"
#include "libtimer/timer.h"
#include "libsystick/systick.h"
Macros
#define HEARTBEAT_MODAL
Functions
void timer_task ()
void Task1 ()
void Task2 ()
void TIMER0A_Handler (void)
void main (void)
Variables
uint32_t PIDWork = 0
semaphore_t semaphore
uint32_t interrupt_counter
Macro Definition Documentation
#define HEARTBEAT_MODAL
Definition at line 24 of file test-semaphore.c.
Function Documentation
void main (void)
Definition at line 77 of file test-semaphore.c.
References heart_init(), Hz, INT_TIMER0A, IntEnable(), IntMasterDisable(), IntMasterEnable(), os_add_thread(), os_launch(), OS_SYSTEM_POOL, os_threading_init(), postpone_death, sem_init, semaphore, SYSCTL_OSC_MAIN, SYSCTL_PERIPH_TIMER0, SYSCTL_SYSDIV_1, SYSCTL_USE_OSC, SYSCTL_XTAL_16MHZ, SysCtlClockGet(), SysCtlClockSet(), SysCtlPeripheralEnable(), Task1(), Task2(), TIMER0_BASE, TIMER_A, TIMER_CFG_PERIODIC, timer_metadata_init, TIMER_TIMA_TIMEOUT, TimerConfigure(), TimerEnable(), TimerIntEnable(), and TimerLoadSet().
                 {
     SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
            SYSCTL_XTAL_16MHZ);
     IntMasterDisable();
     heart_init();
     sem_init(semaphore);
     timer_metadata_init(TIMER0_BASE, 1 Hz, INT_TIMER0A, TIMER_CFG_PERIODIC);
     SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
     TimerConfigure(timer_metadata.timer.base, timer_metadata.timer.periodic);
     TimerLoadSet(timer_metadata.timer.base, TIMER_A, SysCtlClockGet() / timer_metadata.timer.frequency);
     TimerIntEnable(timer_metadata.timer.base, TIMER_TIMA_TIMEOUT);
     IntEnable(timer_metadata.timer.interrupt);
     TimerEnable(timer_metadata.timer.base, TIMER_A);
     os_threading_init(100 Hz);
     os_add_thread(Task1, OS_SYSTEM_POOL);
     os_add_thread(Task2, OS_SYSTEM_POOL);
     IntMasterEnable();
     os_launch();
     postpone_death();
 }
void Task1 ()
Definition at line 40 of file test-semaphore.c.
References FAULT_PENDSV, heart_toggle(), IntPendSet(), semaphore, and semaphore_blocked.
Referenced by main().
              {
     /* Consider: if I can trigger pendsv from an atomic block, will
      * the atomic block be restarted when the context resumes? */
     while(1) {
     /* defun: sem_wait */
     --semaphore;
     while (semaphore_blocked(semaphore)) {
         /* defun: os_surrender_context */
         /* TODO: examine in the context of this not switching to
          * Task2 but instead running the loop endlessly */
         IntPendSet(FAULT_PENDSV);
         /* end_defun */
     }
     /* end_defun */
     heart_toggle();
     }
 }
void Task2 ()
Definition at line 59 of file test-semaphore.c.
References PIDWork.
Referenced by main().
              {
     while(1) {
     ++PIDWork;
     }
 }
void TIMER0A_Handler (void)
Definition at line 66 of file test-semaphore.c.
References interrupt_counter, sem_signal, semaphore, TIMER0_BASE, TIMER_TIMA_TIMEOUT, and TimerIntClear().
{
     TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
     /* the task */
     sem_signal(semaphore);
     /* we should see Task1 blink the heartbeat */
     ++interrupt_counter;
 }
void timer_task ()
Definition at line 35 of file test-semaphore.c.
References sem_post, semaphore, TIMER0_BASE, TIMER_TIMA_TIMEOUT, and TimerIntClear().
                   {
     TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
     sem_post(semaphore);
 }
Variable Documentation
uint32_t interrupt_counter
Definition at line 33 of file test-semaphore.c.
Referenced by TIMER0A_Handler().
uint32_t PIDWork = 0
Definition at line 31 of file test-semaphore.c.
Referenced by Task2().
semaphore_t semaphore
Definition at line 32 of file test-semaphore.c.
Referenced by main(), Task1(), TIMER0A_Handler(), and timer_task().