EE445M Real Time Operating Systems: lib/libtime/timekit.h File Reference
lib/libtime/timekit.h File Reference
Data Structures
struct clocktime
Defines
#define TK_MAX_PRINTBUFFER_LEN 20
#define TK_PRINT_MODE_HOURS_MINUTES 0
#define TK_PRINT_MODE_HOURS_MINUTES_SECONDS 1
#define TK_PRINT_MODE_HOURS_MINUTES_SECONDS_MS 2
#define TK_TIME_VALID 0
#define TK_TIME_INVALID_HOURS 1
#define TK_TIME_INVALID_MINUTES 2
#define TK_TIME_INVALID_SECONDS 3
#define TK_TIME_INVALID_MS 4
#define TK_NUM_HOURS 24
#define TK_NUM_MINUTES 60
#define TK_NUM_SECONDS 60
#define TK_NUM_MS 1000
Typedefs
typedef struct clocktime clocktime
Functions
clocktime * TKCreateTimeHandle (char mode)
clocktime * TKDuplicateTimeHandle (clocktime *th)
void TKDestroy (clocktime *tm)
char * TKToString (clocktime *tm)
void TKIncrementHours (clocktime *tm, short hours)
void TKIncrementMinutes (clocktime *tm, short minutes)
void TKIncrementSeconds (clocktime *tm, short seconds)
void TKIncrementMS (clocktime *tm, short ms)
short TKValidateTime (clocktime *tm)
void TKCleanupTime (clocktime *tm)
Define Documentation
#define TK_MAX_PRINTBUFFER_LEN 20
Definition at line 13 of file timekit.h.
#define TK_NUM_HOURS 24
Definition at line 25 of file timekit.h.
Referenced by TKIncrementHours(), and TKValidateTime().
#define TK_NUM_MINUTES 60
Definition at line 26 of file timekit.h.
Referenced by TKIncrementMinutes(), and TKValidateTime().
#define TK_NUM_MS 1000
Definition at line 28 of file timekit.h.
Referenced by TKIncrementMS(), and TKValidateTime().
#define TK_NUM_SECONDS 60
Definition at line 27 of file timekit.h.
Referenced by TKIncrementSeconds(), and TKValidateTime().
#define TK_PRINT_MODE_HOURS_MINUTES 0
Definition at line 15 of file timekit.h.
Referenced by TKToString().
#define TK_PRINT_MODE_HOURS_MINUTES_SECONDS 1
Definition at line 16 of file timekit.h.
Referenced by TKToString().
#define TK_PRINT_MODE_HOURS_MINUTES_SECONDS_MS 2
Definition at line 17 of file timekit.h.
Referenced by demonstrateClock(), main(), and TKToString().
#define TK_TIME_INVALID_HOURS 1
Definition at line 20 of file timekit.h.
Referenced by TKCleanupTime(), and TKValidateTime().
#define TK_TIME_INVALID_MINUTES 2
Definition at line 21 of file timekit.h.
Referenced by TKCleanupTime(), and TKValidateTime().
#define TK_TIME_INVALID_MS 4
Definition at line 23 of file timekit.h.
Referenced by TKCleanupTime(), and TKValidateTime().
#define TK_TIME_INVALID_SECONDS 3
Definition at line 22 of file timekit.h.
Referenced by TKCleanupTime(), and TKValidateTime().
#define TK_TIME_VALID 0
Definition at line 19 of file timekit.h.
Referenced by main(), TKCleanupTime(), and TKValidateTime().
Typedef Documentation
typedef struct clocktime clocktime
Function Documentation
void TKCleanupTime (clocktime * tm)
Definition at line 147 of file timekit.c.
References clocktime::hours, clocktime::minutes, clocktime::ms, clocktime::seconds, TK_TIME_INVALID_HOURS, TK_TIME_INVALID_MINUTES, TK_TIME_INVALID_MS, TK_TIME_INVALID_SECONDS, TK_TIME_VALID, and TKValidateTime().
{
  short error = TKValidateTime(tm);
  switch(error) {
  case TK_TIME_VALID:
      break;
  case TK_TIME_INVALID_HOURS:
    tm->hours = 0;
    break;
  case TK_TIME_INVALID_MINUTES:
    tm->minutes = 0;
    break;
  case TK_TIME_INVALID_SECONDS:
    tm->seconds = 0;
    break;
  case  TK_TIME_INVALID_MS:
    tm->ms = 0;
    break;
  default:
    break;
  }
}
clocktime* TKCreateTimeHandle (char mode)
Definition at line 14 of file timekit.c.
References clocktime::hours, clocktime::minutes, clocktime::mode, clocktime::ms, and clocktime::seconds.
Referenced by demonstrateClock().
{
  clocktime* t = (clocktime*)malloc(sizeof(clocktime));
  t->hours = 0;
  t->minutes = 0;
  t->seconds = 0;
  t->ms = 0;
  t->mode = mode;
  return t;
}
void TKDestroy (clocktime * tm)
Definition at line 24 of file timekit.c.
Referenced by demonstrateClock().
{
  free(tm);
}
clocktime* TKDuplicateTimeHandle (clocktime * th)
Definition at line 170 of file timekit.c.
References clocktime::hours, clocktime::minutes, clocktime::mode, clocktime::ms, and clocktime::seconds.
{
  clocktime* handle = (clocktime*)malloc(sizeof(clocktime));
  handle->hours = th->hours;
  handle->minutes = th->minutes;
  handle->seconds = th->seconds;
  handle->ms = th->ms;
  handle->mode = th->mode;
  /* Don't copy the printbuffer! */
  return handle;
}
void TKIncrementHours (clocktime * tm, short hours)
Definition at line 55 of file timekit.c.
References clocktime::hours, and TK_NUM_HOURS.
Referenced by demonstrateClock(), main(), and TKIncrementMinutes().
{
  short tmpHours = tm->hours + hours;
    while ((1U * tmpHours) >= TK_NUM_HOURS) {
        tmpHours %= TK_NUM_HOURS;
    }
  tm->hours = tmpHours;
}
void TKIncrementMinutes (clocktime * tm, short minutes)
Definition at line 69 of file timekit.c.
References clocktime::minutes, TK_NUM_MINUTES, and TKIncrementHours().
Referenced by demonstrateClock(), main(), and TKIncrementSeconds().
{
  short tmpMinutes = tm->minutes + minutes;
  if(minutes > 0) {
    while (tmpMinutes >= TK_NUM_MINUTES) {
      tmpMinutes -= TK_NUM_MINUTES;
      TKIncrementHours(tm, 1);
    }
  } else {
    while (tmpMinutes < 0) {
      tmpMinutes += TK_NUM_MINUTES;
      TKIncrementHours(tm, -1);
    }
  }
  tm->minutes = tmpMinutes;
}
void TKIncrementMS (clocktime * tm, short ms)
Definition at line 109 of file timekit.c.
References clocktime::ms, TK_NUM_MS, and TKIncrementSeconds().
Referenced by main(), and pseudointerrupt().
{
  short tmpMs = tm->ms + ms;
  if(ms > 0) {
    while (tmpMs >= TK_NUM_MS) {
      tmpMs -= TK_NUM_MS;
      TKIncrementSeconds(tm, 1);
    }
  } else {
    while (tmpMs < 0) {
      tmpMs += TK_NUM_MS;
      TKIncrementSeconds(tm, -1);
    }
  }
  tm->ms = tmpMs;
}
void TKIncrementSeconds (clocktime * tm, short seconds)
Definition at line 89 of file timekit.c.
References clocktime::seconds, TK_NUM_SECONDS, and TKIncrementMinutes().
Referenced by main(), and TKIncrementMS().
{
  short tmpSeconds = tm->seconds + seconds;
  if(seconds > 0) {
  while (tmpSeconds >= TK_NUM_SECONDS) {
    tmpSeconds -= TK_NUM_SECONDS;
    TKIncrementMinutes(tm, 1);
  }
  } else {
    while (tmpSeconds < 0) {
      tmpSeconds += TK_NUM_SECONDS;
      TKIncrementMinutes(tm, -1);
  }
}
  tm->seconds = tmpSeconds;
}
char* TKToString (clocktime * tm)
Definition at line 31 of file timekit.c.
References clocktime::hours, clocktime::minutes, clocktime::mode, clocktime::ms, clocktime::printBuffer, clocktime::seconds, TK_PRINT_MODE_HOURS_MINUTES, TK_PRINT_MODE_HOURS_MINUTES_SECONDS, and TK_PRINT_MODE_HOURS_MINUTES_SECONDS_MS.
Referenced by main().
{
  switch(tm->mode) {
  case TK_PRINT_MODE_HOURS_MINUTES:
    sprintf(tm->printBuffer, "%0.2d:%0.2d", tm->hours, tm->minutes);
    break;
  case TK_PRINT_MODE_HOURS_MINUTES_SECONDS:
    sprintf(tm->printBuffer, "%0.2d:%0.2d:%0.2d",
        tm->hours, tm->minutes, tm->seconds);
    break;
  case TK_PRINT_MODE_HOURS_MINUTES_SECONDS_MS:
    sprintf(tm->printBuffer, "%0.2d:%0.2d:%0.2d:%0.3d",
        tm->hours, tm->minutes, tm->seconds, tm->ms);
    break;
  default:
    printf("ERROR OCCURRED IN toString!!");
    break;
  }
  return tm->printBuffer;
}
short TKValidateTime (clocktime * tm)
Definition at line 131 of file timekit.c.
References clocktime::hours, clocktime::minutes, clocktime::mode, clocktime::ms, clocktime::seconds, TK_NUM_HOURS, TK_NUM_MINUTES, TK_NUM_MS, TK_NUM_SECONDS, TK_TIME_INVALID_HOURS, TK_TIME_INVALID_MINUTES, TK_TIME_INVALID_MS, TK_TIME_INVALID_SECONDS, and TK_TIME_VALID.
Referenced by main(), and TKCleanupTime().
{
  if(tm->hours > TK_NUM_HOURS) {
    return TK_TIME_INVALID_HOURS;
  } else if(tm->minutes > TK_NUM_MINUTES) {
    return TK_TIME_INVALID_MINUTES;
  } else if((tm->mode > 0) && (tm->seconds > TK_NUM_SECONDS)) {
    return TK_TIME_INVALID_SECONDS;
  } else if((tm->mode > 1) && (tm->ms > TK_NUM_MS)) {
    return TK_TIME_INVALID_MS;
  }
  return TK_TIME_VALID;
}