EE445M RTOS: lib/libut/utstring.h File Reference
utstring.h File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
Data Structures
struct UT_string
Macros
#define UTSTRING_VERSION 1.9.9
#define _UNUSED_
#define oom() exit(-1)
#define utstring_reserve(s, amt)
#define utstring_init(s)
#define utstring_done(s)
#define utstring_free(s)
#define utstring_new(s)
#define utstring_renew(s)
#define utstring_clear(s)
#define utstring_bincpy(s, b, l)
#define utstring_concat(dst, src)
#define utstring_len(s) ((unsigned)((s)->i))
#define utstring_body(s) ((s)->d)
Functions
static void utstring_printf_va (UT_string *s, const char *fmt, va_list ap)
static void utstring_printf (UT_string *s, const char *fmt,...)
static void _utstring_BuildTable (const char *P_Needle, size_t P_NeedleLen, long *P_KMP_Table)
static void _utstring_BuildTableR (const char *P_Needle, size_t P_NeedleLen, long *P_KMP_Table)
static long _utstring_find (const char *P_Haystack, size_t P_HaystackLen, const char *P_Needle, size_t P_NeedleLen, long *P_KMP_Table)
static long _utstring_findR (const char *P_Haystack, size_t P_HaystackLen, const char *P_Needle, size_t P_NeedleLen, long *P_KMP_Table)
static long utstring_find (UT_string *s, long P_StartPosition, const char *P_Needle, size_t P_NeedleLen)
static long utstring_findR (UT_string *s, long P_StartPosition, const char *P_Needle, size_t P_NeedleLen)
Macro Definition Documentation
#define _UNUSED_
Definition at line 34 of file utstring.h.
#define oom () exit(-1)
Definition at line 41 of file utstring.h.
#define utstring_bincpy (s, b, l)
Value:
do {                                                       \
  utstring_reserve((s),(l)+1);                               \
  if (l) memcpy(&(s)->d[(s)->i], b, l);                    \
  (s)->i += l;                                               \
  (s)->d[(s)->i]='\0';                                         \
} while(0)
Definition at line 99 of file utstring.h.
#define utstring_body (s) ((s)->d)
Definition at line 117 of file utstring.h.
#define utstring_clear (s)
Value:
do {                                                       \
  (s)->i = 0;                                              \
  (s)->d[0] = '\0';                                        \
} while(0)
Definition at line 93 of file utstring.h.
#define utstring_concat (dst, src)
Value:
do {                                                             \
  utstring_reserve((dst),((src)->i)+1);                          \
  if ((src)->i) memcpy(&(dst)->d[(dst)->i], (src)->d, (src)->i); \
  (dst)->i += (src)->i;                                          \
  (dst)->d[(dst)->i]='\0';                                       \
} while(0)
Definition at line 107 of file utstring.h.
#define utstring_done (s)
Value:
do {                                                       \
  if ((s)->d != NULL) free((s)->d);                        \
  (s)->n = 0;                                              \
} while(0)
Definition at line 65 of file utstring.h.
#define utstring_free (s)
Value:
do {                                                       \
  utstring_done(s);                                        \
  free(s);                                                 \
} while(0)
Definition at line 71 of file utstring.h.
#define utstring_init (s)
Value:
do {                                                       \
  (s)->n = 0; (s)->i = 0; (s)->d = NULL;                   \
  utstring_reserve(s,100);                                 \
  (s)->d[0] = '\0'; \
} while(0)
Definition at line 58 of file utstring.h.
#define utstring_len (s) ((unsigned)((s)->i))
Definition at line 115 of file utstring.h.
#define utstring_new (s)
Value:
do {                                                       \
   s = (UT_string*)calloc(sizeof(UT_string),1);            \
   if (!s) oom();                                          \
   utstring_init(s);                                       \
} while(0)
Definition at line 77 of file utstring.h.
#define utstring_renew (s)
Value:
do {                                                       \
   if (s) {                                                \
     utstring_clear(s);                                    \
   } else {                                                \
     utstring_new(s);                                      \
   }                                                       \
} while(0)
Definition at line 84 of file utstring.h.
#define utstring_reserve (s, amt)
Value:
do {                                                       \
  if (((s)->n - (s)->i) < (size_t)(amt)) {                 \
     (s)->d = (char*)realloc((s)->d, (s)->n + amt);        \
     if ((s)->d == NULL) oom();                            \
     (s)->n += amt;                                        \
  }                                                        \
} while(0)
Definition at line 49 of file utstring.h.
Referenced by utstring_printf_va().
#define UTSTRING_VERSION 1.9.9
Definition at line 29 of file utstring.h.
Function Documentation
static void _utstring_BuildTable (const char * P_Needle, size_t P_NeedleLen, long * P_KMP_Table) static
Definition at line 157 of file utstring.h.
Referenced by utstring_find().
 {
     long i, j;
     i = 0;
     j = i - 1;
     P_KMP_Table[i] = j;
     while (i < (long) P_NeedleLen)
     {
         while ( (j > -1) && (P_Needle[i] != P_Needle[j]) )
         {
            j = P_KMP_Table[j];
         }
         i++;
         j++;
         if (i < (long) P_NeedleLen)
         {
             if (P_Needle[i] == P_Needle[j])
             {
                 P_KMP_Table[i] = P_KMP_Table[j];
             }
             else
             {
                 P_KMP_Table[i] = j;
             }
         }
         else
         {
             P_KMP_Table[i] = j;
         }
     }
     return;
 }
static void _utstring_BuildTableR (const char * P_Needle, size_t P_NeedleLen, long * P_KMP_Table) static
Definition at line 197 of file utstring.h.
Referenced by utstring_findR().
 {
     long i, j;
     i = P_NeedleLen - 1;
     j = i + 1;
     P_KMP_Table[i + 1] = j;
     while (i >= 0)
     {
         while ( (j < (long) P_NeedleLen) && (P_Needle[i] != P_Needle[j]) )
         {
            j = P_KMP_Table[j + 1];
         }
         i--;
         j--;
         if (i >= 0)
         {
             if (P_Needle[i] == P_Needle[j])
             {
                 P_KMP_Table[i + 1] = P_KMP_Table[j + 1];
             }
             else
             {
                 P_KMP_Table[i + 1] = j;
             }
         }
         else
         {
             P_KMP_Table[i + 1] = j;
         }
     }
     return;
 }
static long _utstring_find (const char * P_Haystack, size_t P_HaystackLen, const char * P_Needle, size_t P_NeedleLen, long * P_KMP_Table) static
Definition at line 237 of file utstring.h.
Referenced by utstring_find().
 {
     long i, j;
     long V_FindPosition = -1;
     /* Search from left to right. */
     i = j = 0;
     while ( (j < (int)P_HaystackLen) && (((P_HaystackLen - j) + i) >= P_NeedleLen) )
     {
         while ( (i > -1) && (P_Needle[i] != P_Haystack[j]) )
         {
             i = P_KMP_Table[i];
         }
         i++;
         j++;
         if (i >= (int)P_NeedleLen)
         {
             /* Found. */
             V_FindPosition = j - i;
             break;
         }
     }
     return V_FindPosition;
 }
static long _utstring_findR (const char * P_Haystack, size_t P_HaystackLen, const char * P_Needle, size_t P_NeedleLen, long * P_KMP_Table) static
Definition at line 270 of file utstring.h.
Referenced by utstring_findR().
 {
     long i, j;
     long V_FindPosition = -1;
     /* Search from right to left. */
     j = (P_HaystackLen - 1);
     i = (P_NeedleLen - 1);
     while ( (j >= 0) && (j >= i) )
     {
         while ( (i < (int)P_NeedleLen) && (P_Needle[i] != P_Haystack[j]) )
         {
             i = P_KMP_Table[i + 1];
         }
         i--;
         j--;
         if (i < 0)
         {
             /* Found. */
             V_FindPosition = j + 1;
             break;
         }
     }
     return V_FindPosition;
 }
static long utstring_find (UT_string * s, long P_StartPosition, const char * P_Needle, size_t P_NeedleLen) static
Definition at line 304 of file utstring.h.
References _utstring_BuildTable(), _utstring_find(), UT_string::d, UT_string::i, and NULL.
 {
     long V_StartPosition;
     long V_HaystackLen;
     long *V_KMP_Table;
     long V_FindPosition = -1;
     if (P_StartPosition < 0)
     {
         V_StartPosition = s->i + P_StartPosition;
     }
     else
     {
         V_StartPosition = P_StartPosition;
     }
     V_HaystackLen = s->i - V_StartPosition;
     if ( (V_HaystackLen >= (long) P_NeedleLen) && (P_NeedleLen > 0) )
     {
         V_KMP_Table = (long *)malloc(sizeof(long) * (P_NeedleLen + 1));
         if (V_KMP_Table != NULL)
         {
             _utstring_BuildTable(P_Needle, P_NeedleLen, V_KMP_Table);
             V_FindPosition = _utstring_find(s->d + V_StartPosition,
                                             V_HaystackLen,
                                             P_Needle,
                                             P_NeedleLen,
                                             V_KMP_Table);
             if (V_FindPosition >= 0)
             {
                 V_FindPosition += V_StartPosition;
             }
             free(V_KMP_Table);
         }
     }
     return V_FindPosition;
 }
static long utstring_findR (UT_string * s, long P_StartPosition, const char * P_Needle, size_t P_NeedleLen) static
Definition at line 350 of file utstring.h.
References _utstring_BuildTableR(), _utstring_findR(), UT_string::d, UT_string::i, and NULL.
 {
     long V_StartPosition;
     long V_HaystackLen;
     long *V_KMP_Table;
     long V_FindPosition = -1;
     if (P_StartPosition < 0)
     {
         V_StartPosition = s->i + P_StartPosition;
     }
     else
     {
         V_StartPosition = P_StartPosition;
     }
     V_HaystackLen = V_StartPosition + 1;
     if ( (V_HaystackLen >= (long) P_NeedleLen) && (P_NeedleLen > 0) )
     {
         V_KMP_Table = (long *)malloc(sizeof(long) * (P_NeedleLen + 1));
         if (V_KMP_Table != NULL)
         {
             _utstring_BuildTableR(P_Needle, P_NeedleLen, V_KMP_Table);
             V_FindPosition = _utstring_findR(s->d,
                                              V_HaystackLen,
                                              P_Needle,
                                              P_NeedleLen,
                                              V_KMP_Table);
             free(V_KMP_Table);
         }
     }
     return V_FindPosition;
 }
static void utstring_printf (UT_string * s, const char * fmt, ...) static
Definition at line 146 of file utstring.h.
References utstring_printf_va().
{
    va_list ap;
    va_start(ap,fmt);
    utstring_printf_va(s,fmt,ap);
    va_end(ap);
 }
static void utstring_printf_va (UT_string * s, const char * fmt, va_list ap) static
Definition at line 119 of file utstring.h.
References UT_string::d, UT_string::i, UT_string::n, and utstring_reserve.
Referenced by utstring_printf().
{
    int n;
    va_list cp;
    while (1) {
 #ifdef _WIN32
       cp = ap;
 #else
       va_copy(cp, ap);
 #endif
       n = vsnprintf (&s->d[s->i], s->n-s->i, fmt, cp);
       va_end(cp);
       if ((n > -1) && ((size_t) n < (s->n-s->i))) {
         s->i += n;
         return;
       }
       /* Else try again with more space. */
       if (n > -1) utstring_reserve(s,n+1); /* exact */
       else utstring_reserve(s,(s->n)*2);   /* 2x */
    }
 }